Add Server-side configuration for mTLS
mendersoftware/mender-docs pull request #1163
Opened 2020-09-07 05:00 UTC by tranchitella

Signed-off-by: Fabio Tranchitella <fabio.tranchitella@northern.tech>

2020-09-07 08:20 UTC, kacf requested changes

2020-09-07 08:20 UTC, kacf commented on 08.Server-integration/03.Client-certificates/docs.md
> +The field `commonName` is device specific, and needs to be changed for every device. Fill the rest of the fields with information about your organization, locality, and contact information.
Maybe a native English speaker can comment on this: I have learned that when listing things, the final "and" should not have a comma, only the elements before that should have a comma between them. Do you know if it applies to English?

@drewmoseley, @michaelatmender

2020-09-07 08:20 UTC, kacf commented on 08.Server-integration/03.Client-certificates/docs.md
> +## Set up the mTLS edge proxy to authenticated devices using mTLS
"Set up the mTLS edge proxy to **authenticate** devices using mTLS"

2020-09-07 08:20 UTC, kacf commented on 08.Server-integration/03.Client-certificates/docs.md
> +The mTLS ambassador acts as an edge proxy running in front of your Mender server. The Mender client running on the devices connects to it, providing its client TLS certificate and establishing a mutu
"...it provides the same API end-points **as** the upstream Mender server."

2020-09-07 08:20 UTC, kacf commented on 08.Server-integration/03.Client-certificates/docs.md
> +The mTLS ambassador is distributed as a Docker image and can be run on a Linux host, using docker-compose or on Kubernetes.
Perhaps we should say "can be run on a Docker host", since theoretically you could run it both on Windows and on Mac.

2020-09-07 08:20 UTC, kacf commented on 08.Server-integration/03.Client-certificates/docs.md
> +* `server.crt`, a regular HTTPS server certificate the ambassador can use to terminate the TLS connections
Same here: Is "authenticate" better than "terminate"?

2020-09-07 08:20 UTC, kacf commented on 08.Server-integration/03.Client-certificates/docs.md
> +* `ca.crt`, the Certification Authority's certificate used to sign the server and client certificates.
This certificate is only mentioned here. Where does it come from? And where is it used?

2020-09-07 08:20 UTC, kacf commented on 08.Server-integration/03.Client-certificates/docs.md
> +  -e MTLS_MENDER_BACKEND=https://hosted.mender.io \
Unrelated to this PR, but we really should think of some token based authentication in the future...

2020-09-07 08:20 UTC, kacf commented on 08.Server-integration/03.Client-certificates/docs.md
> +  registry.mender.io/mendersoftware/mtls-ambassador:master
How do we release the mtls-ambassador? It is not currently part of our release-tool. Should we include it like the rest of the components, or should we release it separately? Might deserve some face to face discussion.

2020-09-07 08:22 UTC, tranchitella commented on 08.Server-integration/03.Client-certificates/docs.md
> +Now that we have both a CA certificate, and a certificate request for the server, we need to sign the latter with the former. This produces a signed certificate the edge proxy will use to terminate t
I still think terminate is the right technical word:
https://en.wikipedia.org/wiki/TLS_termination_proxy

2020-09-07 08:23 UTC, tranchitella commented on 08.Server-integration/03.Client-certificates/docs.md
> +The field `commonName` is device specific, and needs to be changed for every device. Fill the rest of the fields with information about your organization, locality, and contact information.
My grammarly app told me to add the comma, don't know.

2020-09-07 08:25 UTC, tranchitella commented on 08.Server-integration/03.Client-certificates/docs.md
> +  registry.mender.io/mendersoftware/mtls-ambassador:master
Ack, it's in the todo list.

2020-09-07 08:25 UTC, tranchitella commented on 08.Server-integration/03.Client-certificates/docs.md
> +  -e MTLS_MENDER_BACKEND=https://hosted.mender.io \
Ack, it's in the to-do list.

2020-09-07 08:26 UTC, tranchitella commented on 08.Server-integration/03.Client-certificates/docs.md
> +  registry.mender.io/mendersoftware/mtls-ambassador:master
Good question, today we do not release it at all. It is an enterprise, custom component. Suggestions?

2020-09-07 08:27 UTC, tranchitella commented on 08.Server-integration/03.Client-certificates/docs.md
> +* `server.crt`, a regular HTTPS server certificate the ambassador can use to terminate the TLS connections
See comment above.

2020-09-07 08:48 UTC, mirzak commented
I missed the first round of review for this page but I have a couple of high level remarks on structure for introduction of this feature:

1. We need to update https://docs.mender.io/overview/device-authentication to include the mTLS option. Note here it should be described as a "reference" on a high level and not a tutorial how to implement it.

2. We are introducing new client configuration options, at a minimum we should document it [here](https://docs.mender.io/client-installation/configuration-file/configuration-options)

3. Shouldn't the mTLS ambassador be an option of the Mender Enterprise on-premise setup, https://docs.mender.io/2.4/administration/production-installation#enterprise ?

4. How do I enable mTLS ambassador if I am on https://hosted.mender.io? This should be mentioned somewhere, probably on https://docs.mender.io/overview/device-authentication

5. This tutorial details on how to setup an PKI, I think it should be **very clear** that this is for evaluation purposes only. Managing an PKI is a complex thing and there are many pitfalls that we do not take care of in this tutorial. There are far better resources for this then what what we can provide, we should instead link to them, e.g https://pki-tutorial.readthedocs.io/en/latest/. In the end this feature falls under the "Advanced" category imo, mainly for user that already have an PKI in place.

6. I would consider to put this section in https://docs.mender.io/server-integration instead.

2020-09-07 09:18 UTC, michaelatmender commented on 08.Server-integration/03.Client-certificates/docs.md
> +The field `commonName` is device specific, and needs to be changed for every device. Fill the rest of the fields with information about your organization, locality, and contact information.
Aha, the Oxford comma question! It's optional; while some people don't like to use it, it can often make a sentence clearer. In this case it doesn't matter much, but it's perfectly fine.

2020-09-07 09:18 UTC, kacf commented on 08.Server-integration/03.Client-certificates/docs.md
> +  registry.mender.io/mendersoftware/mtls-ambassador:master
We have to release it since it's part of the product and will be part of our public facing documentation. I have talked to @lluiscampos and this was missed in the release process. You can leave this part as is, but in the `AUTOVERSION` tag above, you need to switch from `ignore` to `mtls-ambassador`. It will probably fail until the support has been added to the release tool, but @lluiscampos is working on that.

2020-09-07 09:25 UTC, kacf commented on 08.Server-integration/03.Client-certificates/docs.md
> +The field `commonName` is device specific, and needs to be changed for every device. Fill the rest of the fields with information about your organization, locality, and contact information.
Ok, if it's optional, it's fine as is. I guess my suggestion is more of a general guide, not an absolute rule.

2020-09-07 10:04 UTC, tranchitella commented on 08.Server-integration/03.Client-certificates/docs.md
> +The field `commonName` is device specific, and needs to be changed for every device. Fill the rest of the fields with information about your organization, locality, and contact information.
Ok, let me remove it then.

2020-09-07 10:06 UTC, tranchitella commented on 08.Server-integration/03.Client-certificates/docs.md
> +  registry.mender.io/mendersoftware/mtls-ambassador:master
Done

2020-09-07 10:34 UTC, tranchitella commented on 08.Server-integration/03.Client-certificates/docs.md
> +* `ca.crt`, the Certification Authority's certificate used to sign the server and client certificates.
you are right, I've updated the docs to also describe the CA cert and volume-mount it.

2020-09-07 11:22 UTC, kacf commented
I agree with most of @mirzak's comments, good catches! However, I think they are quite out of scope for what the task originally instructed, so I will create new tasks for 1, 2 and 4. Maybe 3, 5, and 6 can be done straight. See below for some additional comments, also.

>     3. Shouldn't the mTLS ambassador be an option of the Mender Enterprise on-premise setup, https://docs.mender.io/2.4/administration/production-installation#enterprise ?

It can be a link, but I think that adding it is an option is too advanced. This is a pretty high end feature.

>     4. How do I enable mTLS ambassador if I am on https://hosted.mender.io? This should be mentioned somewhere, probably on https://docs.mender.io/overview/device-authentication

I don't know. Do people have to contact us directly? @tranchitella?

>     5. This tutorial details on how to setup an PKI, I think it should be **very clear** that this is for evaluation purposes only. Managing an PKI is a complex thing and there are many pitfalls that we do not take care of in this tutorial. There are far better resources for this then what what we can provide, we should instead link to them, e.g https://pki-tutorial.readthedocs.io/en/latest/. In the end this feature falls under the "Advanced" category imo, mainly for user that already have an PKI in place.

Perhaps you could add this as a note in the PR, @tranchitella?

>     6. I would consider to put this section in https://docs.mender.io/server-integration instead.

It is already inside https://docs.mender.io/server-integration ...?

2020-09-07 11:25 UTC, tranchitella commented
> > 1. How do I enable mTLS ambassador if I am on https://hosted.mender.io? This should be mentioned somewhere, probably on https://docs.mender.io/overview/device-authentication
> I don't know. Do people have to contact us directly? @tranchitella?

Technically speaking, you can self-host the mTLS ambassador in your own infrastructure and point it to https://hosted.mender.io over the Internet. We can also host the ambassador for our customers, if they ask so. In any case, setting it up is a manual process as you have to provide the certs.

> > 1. This tutorial details on how to setup an PKI, I think it should be **very clear** that this is for evaluation purposes only. Managing an PKI is a complex thing and there are many pitfalls that we do not take care of in this tutorial. There are far better resources for this then what what we can provide, we should instead link to them, e.g https://pki-tutorial.readthedocs.io/en/latest/. In the end this feature falls under the "Advanced" category imo, mainly for user that already have an PKI in place.
> 
> Perhaps you could add this as a note in the PR, @tranchitella?

Sure, pushing it now.

2020-09-07 11:45 UTC, kacf commented
> Technically speaking, you can self-host the mTLS ambassador in your own infrastructure and point it to https://hosted.mender.io over the Internet. We can also host the ambassador for our customers, if they ask so. In any case, setting it up is a manual process as you have to provide the certs.

Ok, maybe you can write that in a "documentation friendly" way? They can point to Hosted Mender, or if they want us to host it, just tell them they need to contact us for assistance.

2020-09-07 11:49 UTC, mirzak commented
> I agree with most of @mirzak's comments, good catches! However, I think they are quite out of scope for what the task originally instructed, so I will create new tasks for 1, 2 and 4

Thanks.

> Shouldn't the mTLS ambassador be an option of the Mender Enterprise on-premise setup, https://docs.mender.io/2.4/administration/production-installation#enterprise ?
It can be a link, but I think that adding it is an option is too advanced. This is a pretty high end feature.

A link makes sense, as long as it "fits in".

A follow up questions:

1. Will the mTLS ambassador have a compose file mendersoftware/integration?
2. Relates to above. In an on-premise Mender Enterprise setting, would the mTLS ambassador be deployed on the same server as the Mender backend? Or does it have to be deployed desperately? I can image there being an conflict on port 443?

> > Technically speaking, you can self-host the mTLS ambassador in your own infrastructure and point it to https://hosted.mender.io over the Internet. We can also host the ambassador for our customers, if they ask so. In any case, setting it up is a manual process as you have to provide the certs.

> Ok, maybe you can write that in a "documentation friendly" way? They can point to Hosted Mender, or if they want us to host it, just tell them they need to contact us for assistance.

Yeah. I would maybe flip it around.

"If you are using Hosted Mender contact us for assistance, or if you would like you can host and point to https://hosted.mender.io <link to instructions>...."

2020-09-08 03:43 UTC, tranchitella commented
> Yeah. I would maybe flip it around.
> 
> "If you are using Hosted Mender contact us for assistance, or if you would like you can host and point to https://hosted.mender.io , link to instructions..."

```If you are using Hosted Mender, you can host the mTLS ambassador in your infrastructure and point it to the upstream server `https://hosted.mender.io`.
In case you need assistance or use a hosted mTLS ambassador, contact us describing your use case.
```

2020-09-08 10:47 UTC, kacf approved these changes

2020-09-08 10:49 UTC, kacf commented
Thanks for fixing! I suppose we could merge this to master now, since all the items in the task are fixed.

2020-09-08 11:09 UTC, kacf commented
> Will the mTLS ambassador have a compose file mendersoftware/integration?

No. It requires a lot of extra steps to run it, and it's currently used as an "outside the box" solution when compared to the rest. It could make sense to put it integration, if there's interest, but I think it's alright as it is for the first version. We can improve later if there are requests for this.

2020-09-08 11:10 UTC, kacf commented
For doc followups, I have created:
* https://tracker.mender.io/browse/MEN-3926
* https://tracker.mender.io/browse/MEN-3927
* https://tracker.mender.io/browse/MEN-3928

2020-09-08 11:10 UTC, merged