Include extra OpenSSL error messages in the trouble shooting section
mendersoftware/mender-docs pull request #1166
Opened 2020-09-08 15:05 UTC by merlin-northern

ChangeLog:none
Signed-off-by: Peter Grzybowski <peter@northern.tech>

2020-09-08 15:06 UTC, merlin-northern commented
@kacf this is the one we discussed back in early August, now I think it should be in, as we are with OpenSSL full time.

2020-09-08 15:24 UTC, merlin-northern commented
@lluiscampos this is something that would be nice to have somewhere around the release. it is not urgent, but we should mention the new errors that can appear which are related to the port to OpenSSL and the security level.

2020-09-09 06:45 UTC, kacf requested changes
Good to have this covered!

2020-09-09 06:45 UTC, kacf commented on 201.Troubleshoot/03.Mender-Client/docs.md
> +the OpenSSL code cant verify the server identity. You have to either use
`s/cant/can't/`

2020-09-09 06:45 UTC, kacf commented on 201.Troubleshoot/03.Mender-Client/docs.md
> +a valid certificate or include the certificate in the local trust store.
I'm not really clear on why a zero depth certificate is not a valid certificate. Can you explain a bit more why it isn't valid, and what needs to change for it to become valid?

2020-09-09 06:45 UTC, kacf commented on 201.Troubleshoot/03.Mender-Client/docs.md
> +With the Mender Client ported to OpenSSL it is possible that you see this error
Suggestion: "Starting with Mender client 2.4.0, the client uses OpenSSL and it is possible..."

2020-09-09 08:41 UTC, lluiscampos requested changes
Thanks. I will bring this to 2.5.x release branch

2020-09-09 08:41 UTC, lluiscampos commented on 201.Troubleshoot/03.Mender-Client/docs.md
> +The security level of `2` is the default one on many installations nowadays.
```suggestion
The security level `2` is the default one on many installations nowadays.
```
or
```suggestion
A security level of `2` is the default one on many installations nowadays.
```

2020-09-09 13:21 UTC, merlin-northern commented on 201.Troubleshoot/03.Mender-Client/docs.md
> +the OpenSSL code cant verify the server identity. You have to either use
fixed.

2020-09-09 13:22 UTC, merlin-northern commented on 201.Troubleshoot/03.Mender-Client/docs.md
> +a valid certificate or include the certificate in the local trust store.
neither am I. my wife tells me that when I try to explain something no one understands.
fixed. is it better now?

2020-09-09 13:22 UTC, merlin-northern commented on 201.Troubleshoot/03.Mender-Client/docs.md
> +With the Mender Client ported to OpenSSL it is possible that you see this error
sure.

2020-09-09 13:23 UTC, merlin-northern commented on 201.Troubleshoot/03.Mender-Client/docs.md
> +The security level of `2` is the default one on many installations nowadays.
chose second one.

2020-09-10 08:39 UTC, kacf commented on 201.Troubleshoot/03.Mender-Client/docs.md
> +a valid certificate or include the certificate in the local trust store.
Yes, that's better, thanks!

2020-09-10 08:39 UTC, kacf approved these changes

2020-09-10 09:07 UTC, lluiscampos approved these changes

2020-09-16 12:46 UTC, merged