[RFC] Adapt integration checklist to GRUB as well
mendersoftware/mender-docs pull request #1176
Opened 2020-09-16 18:19 UTC by drewmoseley

Signed-off-by: Drew Moseley <drew.moseley@northern.tech>

# External Contributor Checklist

🚨 Please review the [guidelines for contributing](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md) to this repository.

- [ ] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.

### Description

This is the basic set of changes needed so that the integration checklist also applies to GRUB. Basically, instead of relying on stopping at the U-Boot prompt and printing the environment, we do it solely from the shell prompt and verifying that bootcount is updated properly.  If updates in either direction are incorrect this will be detected by the bootcount variable.

Obviously this should get moved in the folder hierarchy but for now I just want to get the content reviewed.

2020-09-25 08:21 UTC, lluiscampos requested changes
I found one typo, the rest looks good.

One general question, though. As this is now both U-Boot and GRUB, this integration checklist does not belong to `02.Board-integration/02.Bootloader-support/02.U-Boot/02.Integration-checklist` but maybe `02.Board-integration/02.Bootloader-support/02.Integration-checklist`?

2020-09-25 08:21 UTC, lluiscampos commented on 05.System-updates-Yocto-Project/02.Board-integration/02.Bootloader-support/02.U-Boot/02.Integration-checklist/docs.md
> +   pidof mender
This should be `pidof mender-client`

2020-09-25 08:21 UTC, lluiscampos commented on 05.System-updates-Yocto-Project/02.Board-integration/02.Bootloader-support/02.U-Boot/02.Integration-checklist/docs.md
> +    This value should be returned as 1.  This step verifies that the bootloader and the bootloader environment tools can properly communicate and agree on the format of the bootloader environment.
```suggestion
    This value should be returned as 1. This step verifies that the bootloader and the bootloader environment tools can properly communicate and agree on the format of the bootloader environment.
```

2020-09-25 08:41 UTC, kacf reviewed
Nice changes, @drewmoseley!

Ironically, if we do [MEN-3978](https://tracker.mender.io/browse/MEN-3978) we may have to split this up again to avoid making the instructions too complicated. But we can cross that bridge when we get there.

Should this file be moved though? It is currently indexed under the U-Boot chapter.

2020-09-25 13:28 UTC, drewmoseley commented
Yes, it should obviously be moved. I wanted to review the changes here first as it makes it more evident what specifically has changed.  I'll move it and update this PR and remove the RFC tag.

2020-09-25 15:20 UTC, drewmoseley commented on 05.System-updates-Yocto-Project/02.Board-integration/02.Bootloader-support/02.U-Boot/02.Integration-checklist/docs.md
> +   pidof mender
Are you sure? I know the service is named mender-client but I didn't think the executable was renamed.

2020-09-25 15:25 UTC, drewmoseley commented
@mirzak is the "Client Installation" chapter a good place for this?

2020-09-28 06:23 UTC, mirzak commented
As the instructions are Yocto specific, I would put it in,

```
05.System-updates-Yocto-Project/02.Board-integration/02.Bootloader-support/03-Integration-checklist/
```

2020-09-28 13:26 UTC, drewmoseley commented
Hmm.  I wonder if we should make it more generic then.  But does it get too complicated that way?

2020-09-29 07:58 UTC, lluiscampos commented on 05.System-updates-Yocto-Project/02.Board-integration/02.Bootloader-support/02.U-Boot/02.Integration-checklist/docs.md
> +   pidof mender
Yes, you are completely right... I got confused.

2020-09-29 08:29 UTC, mirzak commented
I guess the steps 1-3 are Yocto specific, the rest should be fairly generic.

Would this be equivalent:

```
# Remove kernel from rootfs A, this should result in a failure in case of the integration is trying to load the kernel from the wrong partition
rm /boot/uImage

fw_setenv mender_boot_part 3
fw_setenv mender_boot_part_hex 3
reboot
```

This is so that we can get rid of keeping track of timestamps of Linux kernel.

2020-09-29 13:27 UTC, drewmoseley commented
Yeah I think that could work.  Let me write it up.

2020-09-29 14:17 UTC, drewmoseley commented
@michaelatmender @lluiscampos @kacf please take another look.  I added a commit to remove the Yocto-specifics.

2020-10-14 17:36 UTC, drewmoseley commented
@mirzak ping

2020-10-15 06:47 UTC, kacf requested changes
Sorry, this one slipped.

2020-10-15 06:47 UTC, kacf commented on 03.Client-installation/07.Integration-checklist/docs.md
> +2. Verify that the two commands `fw_printenv` and `fw_setenv` are in the path and are executable. Calling them with no arguments will should give a variable listing and an error about missing variabl
"...~will~ should..."

2020-10-15 06:47 UTC, kacf commented on 03.Client-installation/07.Integration-checklist/docs.md
> +    mv /boot/uImage.testing-backup /boot/uImage
I think you forgot `/mnt` in the paths here.

2020-10-15 06:47 UTC, kacf commented on 03.Client-installation/07.Integration-checklist/docs.md
> +    mv /boot/uImage.testing-backup /boot/uImage
Here as well.

2020-10-15 06:47 UTC, kacf commented on 03.Client-installation/07.Integration-checklist/docs.md
> +    mount /dev/ubi0_1 /mnt
Shouldn't this be `ubi0_0` if it's the first partition?

2020-10-15 06:47 UTC, kacf commented on 03.Client-installation/07.Integration-checklist/docs.md
> +   mv /boot/uImage /boot/uImage.testing-backup
Nice, a bit more straightforward than the original!

2020-10-15 13:19 UTC, drewmoseley commented
@kacf thanks for the review. I pushed a new commit with your recommendations.

2020-10-19 06:18 UTC, kacf approved these changes
Looks good! @lluiscampos: You good with this too?

I'm not sure about the passive voice checker which is failing now. Are these actually new words, or is it triggering on pre-existing content?

2020-10-19 06:38 UTC, mirzak commented
The passive voice checker is enabled for the "Client installation" section, and since the integration checklist was moved there the script will run on the "new" content. 

Needs to be fixed up.

2020-10-19 18:04 UTC, mirzak approved these changes

2020-10-20 11:38 UTC, lluiscampos approved these changes
LGTM!

Sorry for lagging in the final review.

2020-10-22 08:23 UTC, kacf approved these changes
One small typo below. You can just go ahead and merge afterwards. Looks good!

2020-10-22 08:23 UTC, kacf commented on 03.Client-installation/07.Integration-checklist/docs.md
> +12. Reboot, but pull the power plug before the system has had time to finish booting. The Mender will service will auto-commit the update, which will defeat the purpose of this test. It ss important
"It ss"

2020-10-22 16:58 UTC, drewmoseley commented on 03.Client-installation/07.Integration-checklist/docs.md
> +12. Reboot, but pull the power plug before the system has had time to finish booting. The Mender will service will auto-commit the update, which will defeat the purpose of this test. It ss important
Fixed.

2020-10-22 17:07 UTC, merged