CI for checking latest version in hosted branch
mendersoftware/mender-docs pull request #1189
Opened 2020-09-22 13:19 UTC by 0lmi

https://tracker.mender.io/browse/QA-215

Signed-off-by: Oleksandr Miliukov <28045858+0lmi@users.noreply.github.com>

# External Contributor Checklist

🚨 Please review the [guidelines for contributing](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md) to this repository.

- [*] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.

### Description

Please describe your pull request.

Thank you!

2020-09-23 08:31 UTC, lluiscampos requested changes
This looks very good! I hope there was good learning wrt these tools ;)

See my comments below for suggested improvements.

2020-09-23 08:31 UTC, lluiscampos commented on .gitlab-ci.yml
> +    # exists with non zero status if not staged for commit files exist
```suggestion
    # exits with non zero status if not staged for commit files exist
```

2020-09-23 08:31 UTC, lluiscampos commented on .gitlab-ci.yml
> +    - ./autoversion.py --update --mender-convert-version $MENDER_CONVERT_VERSION --mender-convert-client-version $MENDER_CLIENT_VERSION --mender-binary-delta-version $MENDER_BINARY_DELTA_VERSION --in
I bit more readable with a multi-line call:
```suggestion
    - ./autoversion.py --update --mender-convert-version $MENDER_CONVERT_VERSION
      --mender-convert-client-version $MENDER_CLIENT_VERSION
      --mender-binary-delta-version $MENDER_BINARY_DELTA_VERSION
      --integration-dir $INTEGRATION_REPO_DIR
      --integration-version $INTEGRATION_VERSION
```

2020-09-23 08:31 UTC, lluiscampos commented on .gitlab-ci.yml
> +    - git diff-index --quiet HEAD
I didn't know that this command would exit with error, thanks :+1: 

But I think before this we should also call `git diff HEAD`, so that on a failure we can see here in the CI log exactly which files and versions are incorrect.

```suggestion
    - git diff HEAD
    - git diff-index --quiet HEAD
```

2020-09-23 08:35 UTC, lluiscampos commented on .gitlab-ci.yml
> +    - export MENDER_BINARY_DELTA_VERSION=$(cd $MENDER_BINARY_DELTA_DIR ; git describe --tags $(git rev-list --tags --max-count=1))
(this was the most important comment and got lost when I submitted my review :thinking: )

Listing tags with `git rev-list --tags --max-count=1` is not good enough, as it will also catch beta tags (i.e. `1.2.3b1`), release candidates (i.e. `1.2.3-build4`) or even saas tags (i.e. `saas-v2020...`).

So we shall filter out to only get final tags. I suggest the following command:
```
git tag | egrep -e '^[0-9]+\.[0-9]+\.[0-9]+$' | sort -V -r | head -n1
```

2020-09-23 10:01 UTC, 0lmi commented on .gitlab-ci.yml
> +    - git diff-index --quiet HEAD
@lluiscampos for this purpose I added `git status`, but can add even more debug information with `git diff HEAD`

2020-09-23 10:08 UTC, 0lmi commented on .gitlab-ci.yml
> +    - export MENDER_BINARY_DELTA_VERSION=$(cd $MENDER_BINARY_DELTA_DIR ; git describe --tags $(git rev-list --tags --max-count=1))
Thanks 👍

2020-09-24 07:41 UTC, lluiscampos approved these changes
Good work.

Please follow-up with the mender-docs team to get this merged into hosted branch too.

2020-09-24 11:26 UTC, merged