MEN-3489, MEN-3499: add section about software versioning
mendersoftware/mender-docs pull request #1197
Opened 2020-10-04 13:02 UTC by tranchitella

2020-10-05 08:10 UTC, kacf requested changes
Well written!

2020-10-05 08:10 UTC, kacf commented on 06.Artifact-creation/09.Software-versioning/docs.md
> +```
I think that we will also need to cover `clears_artifact_provides` here. These definitely belong to advanced usage, but they are an important part of the feature set. I suggest a new sub page with an introduction marking this as an advanced section, and then a few example use cases. Some of the use cases I can think of:

* Alternative rootfs-image update methods, based on Update Module:
  ```bash
    mender-artifact write module-image -T custom-root-image --software-filesystem rootfs-image --no-default-clears-provides --clears-provides 'rootfs-image.*'
    ```
* Updating other partitions:
  ```bash
  mender-artifact write module-image -T part2-image --software-filesystem part2-image --no-default-clears-provides --clears-provides 'part2-image.*'
  ```
* Proxy updates:
  * You have multiple connected devices that you can update both fully and partially. In this scenario, for the full updates to report correctly, they need to be created like this:
    ```bash
    mender-artifact write module-image -T full-proxy-update --software-filesystem device1-fs --no-default-clears-provides --clears-provides 'device1-fs.*'
    ```

2020-10-05 10:59 UTC, tranchitella commented on 06.Artifact-creation/09.Software-versioning/docs.md
> +For these reasons, the Mender Artifact tool supports several options to customize the current software version's reporting, both for full system updates and Update modules.
Ack

2020-10-05 11:00 UTC, tranchitella commented on 06.Artifact-creation/09.Software-versioning/docs.md
> +It is possible to customize this behaviour overriding the base key (`rootfs-image`) with a custom one using the `--software-filesystem` flag of `mender-artifact`. It is also possible to set a specifi
Ack

2020-10-05 11:03 UTC, tranchitella commented on 06.Artifact-creation/09.Software-versioning/docs.md
> +To override the software name in the versioning key, use the `--software-name" flag as follows:
Ack

2020-10-05 11:24 UTC, tranchitella commented on 06.Artifact-creation/09.Software-versioning/docs.md
> +```
done

2020-10-06 07:13 UTC, kacf requested changes
Also very well written! All my comments are minor things, the next one will be "the one", I think!

2020-10-06 07:13 UTC, kacf commented on 06.Artifact-creation/09.Software-versioning/docs.md
> +For these reasons, the Mender Artifact tool supports several options to customize the current software version's reporting, both for full system updates and Update modules.
You changed the header, but you didn't change it here.

2020-10-06 07:13 UTC, kacf commented on 06.Artifact-creation/09.Software-versioning/docs.md
> +Each pattern can contain multiple placeholders, each of them expressed using asterisks (`*`), which match a sequence of zero or more characters. For example, the pattern `rootfs-image.*` matches `roo
"...but not `datafs-image.checksum` **nor** `rootfs-image`."

2020-10-06 07:13 UTC, kacf commented on 06.Artifact-creation/09.Software-versioning/docs.md
> +* `--delete-clears-provides`: removes the specified pattern from the *Clear provides*
This is for `mender-artifact modify` only, and doesn't work in `write` mode. I think it's ok not to describe this one, and let people discover it when they use `modify`.

2020-10-06 07:13 UTC, kacf commented on 06.Artifact-creation/09.Software-versioning/docs.md
> +For example, to provide an alternative rootfs-image update method based on Update Module, you would need an artifact that clears the `rootfs-image.version` and `rootfs-image.checksum` *Provides* keys
Minor: "to provide an alternative rootfs-image update method based on **an** Update Module"

2020-10-06 07:13 UTC, kacf commented on 06.Artifact-creation/09.Software-versioning/docs.md
> +For example, to provide an alternative rootfs-image update method based on Update Module, you would need an artifact that clears the `rootfs-image.version` and `rootfs-image.checksum` *Provides* keys
Our style guide says that "artifact" should be capitalized "Artifact" in all places where it makes sense. This should probably be changed throughout.

2020-10-06 07:41 UTC, tranchitella commented
@kacf ready for another round, don't be shy if you find something else, I'm okay with multiple rounds of the review! :)

2020-10-06 08:09 UTC, kacf commented
@tranchitella: Uhm, did you actually push? Nothing changed AFAICS.

2020-10-06 08:10 UTC, tranchitella commented
@kacf sorry, push failed because of network issues here and I did not notice it

2020-10-06 08:36 UTC, kacf approved these changes
:+1:

2020-10-06 08:38 UTC, merged

2020-10-06 10:57 UTC, lluiscampos reviewed
Indeed, very well written. Personally, I understood quite well the feature now (from the user point of view).

Some comments below, but as arrived very late to the party just follow-up if you have the capacity.

2020-10-06 10:57 UTC, lluiscampos commented on 06.Artifact-creation/09.Software-versioning/docs.md
> +The command above will generate the following versioning ekey/value pair:
Typo: `key/value`

2020-10-06 10:57 UTC, lluiscampos commented on 06.Artifact-creation/09.Software-versioning/docs.md
> +For example, to provide an alternative rootfs-image update method based on an Update Module, you would need an Artifact that clears the `rootfs-image.version` and `rootfs-image.checksum` *Provides* k
Inconsistency: `Update module` here or `Update Module` elsewhere.

2020-10-06 11:41 UTC, tranchitella commented
@lluiscampos follow-up PR: https://github.com/mendersoftware/mender-docs/pull/1201