Feature partial updates
mendersoftware/mender-docs pull request #1205
Opened 2020-10-08 12:53 UTC by kacf

This should not be merged until https://tracker.mender.io/browse/MEN-3490 is being merged, but I'd like some early feedback.

2020-10-08 12:54 UTC, kacf commented
@estenberg, @michaelatmender, @drewmoseley, @mirzak: This has been reviewed on the feature branch as technically correct, but it would be good to get some outsiders' and native English speakers' eyes on this. I have a feeling it still suffers from "too-close-to-development" syndrome.

2020-10-08 14:01 UTC, drewmoseley requested changes

2020-10-08 14:01 UTC, drewmoseley commented on 06.Artifact-creation/09.Software-versioning/docs.md
> +```
Should we explicitly make this example against the /data partition? That seems the most likely use case.

2020-10-08 14:01 UTC, drewmoseley commented on 06.Artifact-creation/09.Software-versioning/docs.md
> +To support advanced software reporting needs, the Mender Artifact tool also supports the so-named *Clear provides* payload field, a list of patterns that remove the *Provides* entries matching them.
Remove "so-named"

2020-10-08 14:01 UTC, drewmoseley commented on 06.Artifact-creation/09.Software-versioning/docs.md
> +To support advanced software reporting needs, the Mender Artifact tool also supports the so-named *Clear provides* payload field, a list of patterns that remove the *Provides* entries matching them.
payload field, which contains a list of patterns to be removed from the *Provides* entries on the device.

2020-10-09 17:41 UTC, estenberg commented on 06.Artifact-creation/09.Software-versioning/docs.md
> +```
Agree, would at least add a sentence about this.

2020-10-09 17:41 UTC, estenberg commented on 06.Artifact-creation/09.Software-versioning/docs.md
> +rootfs-image.version=1.0.0
Can we add the command that outputs this (show-provides), so the users learn how to see it?

2020-10-09 17:44 UTC, estenberg commented on 06.Artifact-creation/09.Software-versioning/docs.md
> +The software versioning is stored in the Mender Artifacts as *Provides*, and is automatically reported by the Mender Client as inventory data. See below for further details on how to override the def
Yes, we could just say it's part of the meta-data included in the Artifact. Then link to Overview/Artifact, where Provides could be defined.

2020-10-09 17:51 UTC, estenberg commented on 06.Artifact-creation/09.Software-versioning/docs.md
> +## Introduction
I get a little bit lost in details when reading further down (e.g. the Update Module part), and not quite sure where the versions "end up".

I think a simple diagram at the top would be very helpful to get an overview first before going into the details.

As an example it could be a rootfs system update and File Update module usage (e.g. python application), each with different, but realistic versions. Then show one of the Artifacts and how this is stored on the device (both are stored there), which (Provides) is overwritten by the Artifact being installed.

We have some related diagrams that could be used for inspiration:
* https://mender.io/how-it-works (under Extensibility of update types)
* https://docs.mender.io/overview/artifact#the-mender-artifact-file-format

2020-10-09 17:52 UTC, estenberg commented on 06.Artifact-creation/09.Software-versioning/docs.md
> +```
Here too I would include the command (show-provides)

2020-10-09 17:53 UTC, estenberg commented on 06.Artifact-creation/09.Software-versioning/docs.md
> +For these reasons, the Mender Artifact tool supports several options to customize the current software version's reporting, both for full system updates and application updates via Update Modules.
We consistently refer to these as "utility", not "tool" I believe. See e.g. https://docs.mender.io/downloads#mender-artifact

2020-10-15 08:11 UTC, kacf commented
@estenberg, @drewmoseley: I posted an update in https://github.com/mendersoftware/mender-docs/pull/1215. See if you like that better!

2020-11-09 12:55 UTC, merged