MEN-4021: Remove passive voice from the Client-installation section.
mendersoftware/mender-docs pull request #1206
Opened 2020-10-08 13:13 UTC by oleorhagen

2020-10-08 13:55 UTC, drewmoseley requested changes

2020-10-08 13:55 UTC, drewmoseley commented on 03.Client-installation/06.Configuration-file/01.Polling-intervals/docs.md
> +Higher frequency (i.e. the lower the configuration value), the more response the
The  Mender client is more responsive with higher frequency intervals.

2020-10-08 13:55 UTC, drewmoseley commented on 03.Client-installation/06.Configuration-file/50.Configuration-options/docs.md
> +When set enables:
When set, the Mender client verifies the following:
* All Artifact installs are signed. If a signature is not provided, then the update is rejected.
* Update signatures are verified using the provided public key.

2020-10-08 13:55 UTC, drewmoseley commented on 03.Client-installation/06.Configuration-file/50.Configuration-options/docs.md
> +to run, before it is considered hanging and killed. The process will first be
considered hung and killed.

2020-10-08 13:55 UTC, drewmoseley commented on 03.Client-installation/06.Configuration-file/50.Configuration-options/docs.md
> +sent a SIGTERM signal, and one minute later, if it has not exited, SIGKILL. The
if it has not exited, a SIGKILL signal will be sent.

2020-10-09 08:12 UTC, oleorhagen commented
Thank you @drewmoseley

2020-10-09 09:18 UTC, merged