Server-installation/Upgrading: add information about upgrading MongoDB
mendersoftware/mender-docs pull request #1208
Opened 2020-10-12 11:52 UTC by kjaskiewiczz

2020-10-12 14:21 UTC, mirzak commented on 07.Server-installation/07.Upgrading/docs.md
> +
I, who know very little about MongoDB, have a very hard time following the linked instructions and how to translate them to a Mender server environment.

2020-10-12 14:34 UTC, tranchitella requested changes
I believe we have to provide a bit of guidance regarding the upgrade of MongoDB. At minimum, we should tell the user to manually bump the image tag of mongodb to the next version, start it using docker-compose, enter the container and upgrade the compatibility version using the admin command. This has to be repeated for each major version until it reaches MongoDB 4.4.

Can you please add commands and explanations on how to perform these upgrades?

2020-10-12 14:57 UTC, kjaskiewiczz commented
@tranchitella @mirzak I'll provide a more detailed description

2020-10-12 16:08 UTC, kjaskiewiczz commented
@tranchitella @mirzak I've updated the docs; it still needs some polishing so please wait with the review, but it would be great if you could just take a look and say if I wasn't too verbose

2020-10-13 03:38 UTC, tranchitella commented on 07.Server-installation/07.Upgrading/docs.md
> +docker exec -it menderproduction_mender-mongo_1 mongo ir --eval "db.adminCommand( { getParameter: 1, featureCompatibilityVersion: 1 } )"
What is the `ir` in the command line?

2020-10-13 07:50 UTC, mirzak commented
> @tranchitella @mirzak I've updated the docs; it still needs some polishing so please wait with the review, but it would be great if you could just take a look and say if I wasn't too verbose

The approach looks good to me.

2020-10-13 07:51 UTC, kjaskiewiczz commented on 07.Server-installation/07.Upgrading/docs.md
> +docker exec -it menderproduction_mender-mongo_1 mongo ir --eval "db.adminCommand( { getParameter: 1, featureCompatibilityVersion: 1 } )"
name of the database on which I was experimenting with features incompatible across different versions of MongoDB;
I've already removed it; thanks for pointing this out; I was copy/pasting from the wrong terminal;

2020-10-13 10:19 UTC, tranchitella approved these changes
Great, well done!

2020-10-13 11:10 UTC, mirzak approved these changes
Looks good. I guess this needs to be cherry-picked to 2.5.x branch?

2020-10-13 15:37 UTC, kjaskiewiczz commented
@mirzak yes, this should be in the 2.5.x for sure.
I was wondering if this change should be in the master branch?
If master is development then what upgrade really means? Upgrading from last stable to development? If that's the case then the last stable is 2.5 and the section about upgrading MongoDB shouldn't be there.

2020-10-13 18:30 UTC, estenberg approved these changes

2020-10-13 18:30 UTC, estenberg commented on 07.Server-installation/07.Upgrading/docs.md
> +## Upgrading MongoDB
Would rephrase to "Upgrade to MongoDB 4.4"

This is section is version-specific but merged to master, so we'll need to remove it in a while (maybe a year or so from now, or when we do the next major DB upgrade).

2020-10-14 06:55 UTC, mirzak commented
> @mirzak yes, this should be in the 2.5.x for sure.
> I was wondering if this change should be in the master branch?

I think I would also question if this really should be in master at all. Makes most sense if goes directly to 2.5.x.

2020-10-15 08:42 UTC, kjaskiewiczz commented
@mirzak @estenberg change has been merged to 2.5.x and now I need a final decision if I should merge to master
in my opinion, we don't need it in master branch

2020-10-15 16:37 UTC, mirzak commented
As this is not applicable in master, I would say that we close this one without merge

2020-10-15 18:19 UTC, estenberg commented
:+1: makes sense to me as well, it should be a temporary version-specific problem only.

2020-10-15 20:40 UTC, closed without merging