MEN-3924 Allow to load private key from the Security conf section
mendersoftware/mender-docs pull request #1209
Opened 2020-10-12 16:33 UTC by merlin-northern

ChangeLog:none
Signed-off-by: Peter Grzybowski <peter@northern.tech>

2020-10-13 06:35 UTC, kacf approved these changes
Looks good, consider my comments below as suggestions.

2020-10-13 06:35 UTC, kacf commented on 03.Client-installation/06.Configuration-file/50.Configuration-options/docs.md
> +and `SSLEngine` which you can use for signing of authentication requests.
Small grammar tweak, I would use this punctuation: ``...basic security options, `PKIPrivateKey` and `SSLEngine`, which you...`` (note the two new commas and removed colon).

2020-10-13 06:35 UTC, kacf commented on 03.Client-installation/06.Configuration-file/50.Configuration-options/docs.md
> +the former takes precedence over for signing.
Actually it means that the key specified here won't be used, or have I misunderstood? If so, you can just say "...takes precedence ~over for signing~.".

2020-10-13 06:35 UTC, kacf commented on 03.Client-installation/06.Configuration-file/50.Configuration-options/docs.md
> +A path to the file in pem format holding the private key, or  a PKCS#11 URI.
Nitpick: double space.

2020-10-13 06:35 UTC, kacf commented on 03.Client-installation/06.Configuration-file/50.Configuration-options/docs.md
> +The SSLEngine to use.
For this one, and PKCS#11, is there anything you can link to? Even Wikipedia might be better than nothing.

2020-10-13 06:41 UTC, kacf requested changes

2020-10-13 06:41 UTC, kacf commented on 03.Client-installation/06.Configuration-file/50.Configuration-options/docs.md
> +the former takes precedence over for signing.
Actually, reading your [mender PR](https://github.com/mendersoftware/mender/pull/617), I realize that this is wrong. You're stating the opposite, it is the latter which takes precedence.

2020-10-13 07:37 UTC, merlin-northern commented on 03.Client-installation/06.Configuration-file/50.Configuration-options/docs.md
> +the former takes precedence over for signing.
wow, you are right.

2020-10-13 08:06 UTC, merlin-northern commented on 03.Client-installation/06.Configuration-file/50.Configuration-options/docs.md
> +The SSLEngine to use.
of course, I even linked that in the HttpsClient subsection.

2020-10-13 08:13 UTC, merlin-northern commented on 03.Client-installation/06.Configuration-file/50.Configuration-options/docs.md
> +the former takes precedence over for signing.
the HttpsClient.Key will not be used for signing if the Security.PKIPrivateKey is given. but HttpsClient.Key will still be used in the SSL handshake.

2020-10-13 08:13 UTC, merlin-northern commented on 03.Client-installation/06.Configuration-file/50.Configuration-options/docs.md
> +the former takes precedence over for signing.
so I am keeping "over for signing", ok?

2020-10-13 11:07 UTC, mirzak commented on 03.Client-installation/06.Configuration-file/50.Configuration-options/docs.md
> +##### PKIPrivateKey
What is the purpose of having `PKI` prefix here?

2020-10-13 11:43 UTC, merlin-northern commented on 03.Client-installation/06.Configuration-file/50.Configuration-options/docs.md
> +##### PKIPrivateKey
I wanted some prefix to point out that it is used in signing and in case we will introduce some other keys in that section -- I am not that bound to it -- do you think it would look better without it? if you really have a strong opinion here, then I will have to change client patch as well.

2020-10-13 12:04 UTC, mirzak commented on 03.Client-installation/06.Configuration-file/50.Configuration-options/docs.md
> +##### PKIPrivateKey
I find it confusing,

From my understanding, PKI relates to certificates and this key will normally be used when you **do not** have an PKI (certificates)

`AuthPrivateKey` might be a better description if you want to have some kind of prefix?

2020-10-13 14:12 UTC, merlin-northern commented on 03.Client-installation/06.Configuration-file/50.Configuration-options/docs.md
> +##### PKIPrivateKey
all right. so AuthPrivateKey it is.

2020-10-14 06:11 UTC, kacf requested changes

2020-10-14 06:11 UTC, kacf commented on 03.Client-installation/06.Configuration-file/50.Configuration-options/docs.md
> +the former takes precedence over for signing.
The logic is correct now, but I would still delete "~over for signing~" because the grammar is a bit off. I think just saying "...the former takes precedence." is enough.

2020-10-14 06:11 UTC, kacf commented on 03.Client-installation/06.Configuration-file/50.Configuration-options/docs.md
> +The [SSLEngine](https://www.openssl.org/docs/man1.1.1/man1/engine.html) to use.
:+1:

2020-10-14 08:07 UTC, mirzak approved these changes

2020-10-14 08:17 UTC, kacf approved these changes

2020-10-14 09:12 UTC, merged

2020-10-14 09:15 UTC, merlin-northern commented
this one was actaully https://tracker.mender.io/browse/MEN-3957