Mcl 2.3.1 client
mendersoftware/mender-docs pull request #1227
Opened 2020-11-04 13:14 UTC by oleorhagen

Cherry pick `mender-client-version` option to `autoversion`, and bump `Mender-client` version to `2.3.1`

2020-11-05 10:26 UTC, lluiscampos requested changes
Looks good otherwise

2020-11-05 10:26 UTC, lluiscampos commented on 04.Artifacts/10.Yocto-project/01.Building/docs.md
> +git clone -b dunfell git://github.com/mendersoftware/meta-mender
We cannot update the yocto branch.

2020-11-05 10:28 UTC, lluiscampos commented
Nitpick: Could you please rename this PR to something more human-readable? (what does `Mcl` stands for?)

2020-11-05 10:32 UTC, oleorhagen commented on 04.Artifacts/10.Yocto-project/01.Building/docs.md
> +git clone -b dunfell git://github.com/mendersoftware/meta-mender
Hmm, why not?

2020-11-05 10:33 UTC, oleorhagen commented on 04.Artifacts/10.Yocto-project/01.Building/docs.md
> +git clone -b dunfell git://github.com/mendersoftware/meta-mender
Release ran on dunfell

2020-11-05 12:09 UTC, lluiscampos commented on 04.Artifacts/10.Yocto-project/01.Building/docs.md
> +git clone -b dunfell git://github.com/mendersoftware/meta-mender
You are right, we should update it then.

2020-11-05 12:09 UTC, lluiscampos approved these changes

2020-11-06 11:40 UTC, lluiscampos approved these changes

2020-11-06 12:22 UTC, merged