Changelog and change-statistics for the new releases
mendersoftware/mender-docs pull request #1228
Opened 2020-11-05 13:37 UTC by oleorhagen

That is:

* Mender-client 2.4.1
* Mender-client 2.3.1
* Mender-convert 2.2.1

2020-11-05 13:37 UTC, oleorhagen commented
I hope this is what you had in mind :)

2020-11-06 08:43 UTC, lluiscampos requested changes
Looking good.

Two details that need amending and a question for @kacf.

2020-11-06 08:43 UTC, lluiscampos commented on 202.Release-information/01.Release-notes-changelog/docs.md
> +
Here, and in all of them, we are missing a `### Changelogs` header
```suggestion

### Changelogs
```

2020-11-06 08:43 UTC, lluiscampos commented on 202.Release-information/01.Release-notes-changelog/docs.md
> +_Released 10.03.2020_
Here, and in all the rest, the month is wrong: it should be `11`.

2020-11-06 08:43 UTC, lluiscampos commented on 202.Release-information/01.Release-notes-changelog/docs.md
> +## mender 2.3.1
@kacf These are technically correct, we use `Mender` for the whole release, `mender` for the client. However I fear that it can easily miss lead readers. As this is the first time we are doing client only release, what do you think about a header like:
```suggestion
## mender (client only) 2.3.1
```
Or similar?

2020-11-06 08:43 UTC, lluiscampos commented on 202.Release-information/01.Release-notes-changelog/docs.md
> +| Ole Petter Orhagen | 3 (3.1%) |
(low priority, independent of the PR)

There is a known bug in `gitdm` tool: it should say `3 (100%)`, right? It has puzzled me for more than a year... maybe you are curious enough to find it?

2020-11-06 08:45 UTC, oleorhagen commented on 202.Release-information/01.Release-notes-changelog/docs.md
> +## mender 2.3.1
True. or `Mender client` ?

2020-11-06 08:49 UTC, kacf commented on 202.Release-information/01.Release-notes-changelog/docs.md
> +## mender 2.3.1
Mender client sounds good to me.

2020-11-06 08:51 UTC, kacf commented on 202.Release-information/01.Release-notes-changelog/docs.md
> +| Ole Petter Orhagen | 3 (3.1%) |
No, I think this is correct. It only counts removals above a certain threshold, otherwise all commits would be eligible. But the actual amount of lines removed is much higher.

2020-11-06 08:53 UTC, kacf approved these changes
@lluiscampos already has an outstanding change request, so I'm approving "the rest of it".

2020-11-06 09:07 UTC, lluiscampos commented on 202.Release-information/01.Release-notes-changelog/docs.md
> +| Ole Petter Orhagen | 3 (3.1%) |
All right. Thanks for clarifying.

2020-11-06 09:16 UTC, lluiscampos requested changes

2020-11-06 09:16 UTC, lluiscampos commented on 202.Release-information/01.Release-notes-changelog/docs.md
> +New changes in the Mender client since 2.4.0:
Sorry for the confusion. Here (and same for 2.3.1) we should use `mender`, which the the technical name (repo name) of the component.
```suggestion
#### mender (2.4.1)

New changes in mender since 2.4.0:
```

I only meant to modify the title or main header of the release.

2020-11-06 09:17 UTC, oleorhagen commented on 202.Release-information/01.Release-notes-changelog/docs.md
> +New changes in the Mender client since 2.4.0:
No worries. Fixing

2020-11-06 09:21 UTC, lluiscampos approved these changes

2020-11-06 09:38 UTC, merged