Device support section
mendersoftware/mender-docs pull request #1232
Opened 2020-11-06 23:26 UTC by estenberg

# External Contributor Checklist

🚨 Please review the [guidelines for contributing](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md) to this repository.

- [ ] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.

### Description

Please describe your pull request.

Thank you!

2020-11-07 00:14 UTC, estenberg commented
Argh I broke lots of links. Will fix.

2020-11-16 14:46 UTC, drewmoseley requested changes

2020-11-16 14:46 UTC, drewmoseley commented on 02.Overview/02.Device-Support/docs.md
> +to meet your exact needs. A board integion generally consists of the following.
A board integration

2020-11-16 15:04 UTC, mirzak approved these changes
Looks good (once Drews comment is handled :))

2020-11-16 21:58 UTC, estenberg commented on 02.Overview/02.Device-Support/docs.md
> +to meet your exact needs. A board integion generally consists of the following.
Thanks, fixed.

2020-11-16 22:33 UTC, merged