MEN-4095: Add documentation for installing remote terminal add-on
mendersoftware/mender-docs pull request #1241
Opened 2020-11-24 13:33 UTC by alfrunes

2020-11-25 09:32 UTC, merlin-northern commented
> FYI: I spaced out the directory tree in the `03.Client-Installation` to allow inserting sections in between the existing one. References to `../70.Mender-shell-configuration` are provisional and will be coordinated once @merlin-northern finishes this section.

roger that!
mine is ready for review, I will rebase on top of yours, once this one is merged.

2020-11-25 09:33 UTC, merlin-northern commented
@alfrunes do not forget to check all the links and fix them, they all use paths with numbers, so probably all references to 03.Client-installation are broken.

2020-11-25 09:33 UTC, merlin-northern commented
> @alfrunes do not forget to check all the links and fix them, they all use paths with numbers, so probably all references to 03.Client-installation are broken.

the link checker that is online should help you with that.

2020-11-25 09:37 UTC, merlin-northern commented on 09.Downloads/docs.md
> +client, allowing remote terminal sessions using the Mender API.
suggested change: "Mender API" -> "Mender _UI_" since currently we do not have any API around remote terminal feature.

2020-11-25 09:42 UTC, merlin-northern commented on 09.Downloads/docs.md
> +client, allowing remote terminal sessions using the Mender API.
maybe even "from the Mender UI" wold sound better.

2020-11-25 09:52 UTC, merlin-northern requested changes
looks good, some nitpicks and suggestions, a couple of changes requested.

2020-11-25 09:52 UTC, merlin-northern commented on 03.Client-installation/60.Installing-Mender-Shell/docs.md
> +to downloading the packages.
suggested change "to downloading" -> "to _download_"
or
"for links to downloading the packages." -> "for the links to _the packages_"

2020-11-25 09:52 UTC, merlin-northern commented on 03.Client-installation/60.Installing-Mender-Shell/docs.md
> +page](../../09.Downloads/docs.md#Remote-terminal).
suggested change "page" -> "_section_"

2020-11-25 09:52 UTC, merlin-northern commented on 03.Client-installation/60.Installing-Mender-Shell/docs.md
> +configuration targeting the Hosted Mender service. Read the [configuration
sggested change "Read the" -> "_Please refer to the_"

2020-11-25 09:52 UTC, merlin-northern commented on 03.Client-installation/60.Installing-Mender-Shell/docs.md
> +!!! If you are hosting your own Mender server on premises you must reconfigure
suggested comma insert: "premises you must" -> "premises _,_ you must"

2020-11-25 10:05 UTC, lluiscampos requested changes
@alfrunes @merlin-northern  I think we have a problem with the package download, see my comments below and let's discuss it in person if necessary.

2020-11-25 10:05 UTC, lluiscampos commented on 03.Client-installation/60.Installing-Mender-Shell/docs.md
> +```
This URL will not be available for `mender-shell` releases, as we will only release them through our APT repository. The `wget` method is only for legacy `mender-client` package.

Generally speaking: I would not give specific instructions there on how to install it, just refer to one centralized point (Downloads page).

2020-11-25 10:05 UTC, lluiscampos commented on 03.Client-installation/60.Installing-Mender-Shell/docs.md
> +](https://github.com/mendersoftware/mender-shell/tree/master#building-from-source)
These instructions are empty

2020-11-25 10:05 UTC, lluiscampos commented on 09.Downloads/docs.md
> +
We cannot add this. The package will only be available via APT repository. If we need to support direct downloads, we need to rethink the APT epic as a whole.

2020-11-25 19:06 UTC, drewmoseley approved these changes

2020-11-26 08:43 UTC, merlin-northern commented on 09.Downloads/docs.md
> +
we have to think of something, since we assumed that user will be able to download mender-shell deb package. otherwise I do not have a clear idea how to install it. I thought we do the same as with the client: [instructions](https://docs.mender.io/client-installation/install-with-debian-package) and [the deb](https://downloads.mender.io/2.4.1/dist-packages/debian/armhf/mender-client_2.4.1-1_armhf.deb)?

2020-11-26 12:54 UTC, lluiscampos commented on 09.Downloads/docs.md
> +
@merlin-northern We discussed it yesterday with @alfrunes, and I even got confirmation from Eystein; we will install the deb package via APT repository, not direct download.

2020-11-26 13:54 UTC, merlin-northern commented on 09.Downloads/docs.md
> +
o great thanks.

2020-11-26 16:12 UTC, alfrunes commented
@lluiscampos I'm kind of lost about what to do with this task. To me it seems like this section ("Installing Remote Terminal Extension") is superfluous once we have the entire install path described in the "Downloads" chapter. What do you think?

2020-11-27 09:07 UTC, lluiscampos commented
> @lluiscampos I'm kind of lost about what to do with this task. To me it seems like this section ("Installing Remote Terminal Extension") is superfluous once we have the entire install path described in the "Downloads" chapter. Maybe we should simply have a small introduction about installing `mender-shell` in the section about configuring `mender-shell` and reference the instructions in Downloads. What do you think?

@alfrunes Yes, I completely agree, I pointed it out a bit earlier (https://github.com/mendersoftware/mender-docs/pull/1241#discussion_r530248394).

2020-11-27 09:50 UTC, alfrunes commented
After discussions on Slack, I'm closing this in favor of #1246 and #1242.

2020-11-27 09:50 UTC, closed without merging