MEN-4093 Remote terminal overview and configuration options.
mendersoftware/mender-docs pull request #1242
Opened 2020-11-25 11:15 UTC by merlin-northern

ChangeLog:none
Signed-off-by: Peter Grzybowski <peter@northern.tech>

2020-11-25 19:05 UTC, drewmoseley requested changes

2020-11-25 19:05 UTC, drewmoseley commented on 02.Overview/14.Remote.Terminal/docs.md
> +imposes two configurable restrictions: on the total number of shells, and the number
I would break these restrictions into a bulleted list.

2020-11-25 19:05 UTC, drewmoseley commented on 02.Overview/14.Remote.Terminal/docs.md
> +In order to counter act that, mender-shell supports automatic termination
In order to protect against this scenario, mender-shell support....

2020-11-25 19:05 UTC, drewmoseley commented on 02.Overview/14.Remote.Terminal/docs.md
> +it from the regular SSH interactive session just by working with the shell.
I think this paragraph can be removed.

2020-11-25 19:05 UTC, drewmoseley commented on 02.Overview/14.Remote.Terminal/docs.md
> +Remote terminal session consists of a spawned shell (as a subprocess of
A remote terminal session....

2020-11-25 19:05 UTC, drewmoseley commented on 02.Overview/14.Remote.Terminal/docs.md
> +mender-shell) a unique string called a session id, and a system username
subprocess of the mender-shell process)...

2020-11-25 19:05 UTC, drewmoseley commented on 02.Overview/14.Remote.Terminal/docs.md
> +that is running the shell command. The main purpose of mender-shell
Remove "that is running the shell command"
The main responsibility of the mender-shell executable...

2020-11-25 19:05 UTC, drewmoseley commented on 02.Overview/14.Remote.Terminal/docs.md
> +* For a detailed configuration options please refer to
a detailed list of configuration options

2020-11-25 19:05 UTC, drewmoseley commented on 02.Overview/14.Remote.Terminal/docs.md
> +[mender-shell configuration section](../../03.Client-installation/06.Configuration-file/02.Mender-shell/docs.md).
the mender-shell configuration section.

2020-11-25 19:05 UTC, drewmoseley commented on 03.Client-installation/06.Mender-shell-configuration-file/50.Mender-shell-configuration-options/docs.md
> +Allows you to provide terminal settings.
Example needed here

2020-11-25 19:05 UTC, drewmoseley commented on 03.Client-installation/06.Mender-shell-configuration-file/50.Mender-shell-configuration-options/docs.md
> +User sessions settings.
Example needed here

2020-11-25 19:05 UTC, drewmoseley commented on 03.Client-installation/06.Mender-shell-configuration-file/50.Mender-shell-configuration-options/docs.md
> +It controls whether to stop sessions. If set to `false` mender-shell will
Determines whether stopped sessions will be automatically expired and removed.

2020-11-26 09:43 UTC, merlin-northern commented on 02.Overview/01.Introduction/docs.md
> +remote terminal session to any device under Mender control.
currently this is the only and the first add-on. And it is not very generic at the moment. I want to mention it here, since it is an important architectural change and a new significant feature. This was my attempt, if you have any suggestions into which direction this should be changed, I am all ears.

2020-11-26 12:56 UTC, mirzak commented
Have not yet looked close enough on content but more interested on architecture of the docs, and here @estenberg should have a say.

I am not super convinced that we should add this to `Overview` and `Client installation` sections. Instead I am wondering if we should have a separate "Add-on" top level category or something similar to keep it isolated from the rest and over time we might merge this more, but our current docs focused on OTA, and just adding non-related blocks to existing section I find confusing.

BTW, I have the site rendered here, http://13.53.78.221:8080/development/overview

2020-11-27 08:10 UTC, merlin-northern commented on 02.Overview/01.Introduction/docs.md
> +remote terminal session to any device under Mender control.
fixed the best I could.

2020-11-27 08:10 UTC, merlin-northern commented on 02.Overview/01.Introduction/docs.md
> +One example being [mender-shell](https://github.com/mendersoftware/mender-shell)
fixed.

2020-11-27 08:19 UTC, merlin-northern commented on 02.Overview/01.Introduction/docs.md
> +see it from the device perspective.
sure.

2020-11-27 08:19 UTC, merlin-northern commented on 02.Overview/01.Introduction/docs.md
> +Please refer to
fixed.

2020-11-27 08:20 UTC, merlin-northern commented on 02.Overview/14.Remote.Terminal/docs.md
> +get a live terminal where you can freely type commands, as the below
dropped.

2020-11-27 08:21 UTC, merlin-northern commented on 02.Overview/14.Remote.Terminal/docs.md
> +shell, or terminal. Below picture shows a simplified architecture
fixed.

2020-11-27 08:28 UTC, merlin-northern commented on 02.Overview/14.Remote.Terminal/docs.md
> +to enjoy interactive sessions from the Mender UI to your devices. Additionally,
ok.

2020-11-27 08:29 UTC, merlin-northern commented on 02.Overview/14.Remote.Terminal/docs.md
> +in this picture you can take advantage of the Role Based Access Control
right.

2020-11-27 08:32 UTC, merlin-northern commented on 02.Overview/14.Remote.Terminal/docs.md
> +you to specify which system user to run the shell process as.
rephrased to escape the passive:
```
 The mender-shell supports simultaneous shells from different Mender users.
 On the device, you run the shell as a system user which you can set
 in the configuration.
```

2020-11-27 08:33 UTC, merlin-northern commented on 02.Overview/14.Remote.Terminal/docs.md
> +imposes two configurable restrictions: on the total number of shells, and the number
right. done.

2020-11-27 08:35 UTC, merlin-northern commented on 02.Overview/14.Remote.Terminal/docs.md
> +In order to counter act that, mender-shell supports automatic termination
fixed.

2020-11-27 08:35 UTC, merlin-northern commented on 02.Overview/14.Remote.Terminal/docs.md
> +it from the regular SSH interactive session just by working with the shell.
removed.

2020-11-27 08:36 UTC, merlin-northern commented on 02.Overview/14.Remote.Terminal/docs.md
> +Remote terminal session consists of a spawned shell (as a subprocess of
right. (I meant the Remote terminal as a proper name of the feature). fixed.

2020-11-27 08:38 UTC, merlin-northern commented on 02.Overview/14.Remote.Terminal/docs.md
> +mender-shell) a unique string called a session id, and a system username
fixed.

2020-11-27 08:38 UTC, merlin-northern commented on 02.Overview/14.Remote.Terminal/docs.md
> +that is running the shell command. The main purpose of mender-shell
fixed.

2020-11-27 08:38 UTC, merlin-northern commented on 02.Overview/14.Remote.Terminal/docs.md
> +* For a detailed configuration options please refer to
fixed.

2020-11-27 08:39 UTC, merlin-northern commented on 02.Overview/14.Remote.Terminal/docs.md
> +[mender-shell configuration section](../../03.Client-installation/06.Configuration-file/02.Mender-shell/docs.md).
fixed

2020-11-27 08:40 UTC, merlin-northern commented on 03.Client-installation/06.Mender-shell-configuration-file/50.Mender-shell-configuration-options/docs.md
> +Allows you to provide terminal settings.
added.

2020-11-27 08:41 UTC, merlin-northern commented on 03.Client-installation/06.Mender-shell-configuration-file/50.Mender-shell-configuration-options/docs.md
> +User sessions settings.
it is there: below :)

2020-11-27 08:42 UTC, merlin-northern commented on 03.Client-installation/06.Mender-shell-configuration-file/50.Mender-shell-configuration-options/docs.md
> +It controls whether to stop sessions. If set to `false` mender-shell will
fixed.

2020-11-27 08:43 UTC, merlin-northern commented
> Have not yet looked close enough on content but more interested on architecture of the docs, and here @estenberg should have a say.
> 
> I am not super convinced that we should add this to `Overview` and `Client installation` sections. Instead I am wondering if we should have a separate "Add-on" top level category or something similar to keep it isolated from the rest and over time we might merge this more, but our current docs focused on OTA, and just adding non-related blocks to existing section I find confusing.

I did that on purpose: to hint that we are changing.
 
> BTW, I have the site rendered here, http://13.53.78.221:8080/development/overview

thanks.

2020-11-27 08:45 UTC, merlin-northern commented
@estenberg @mirzak @drewmoseley see also: https://github.com/mendersoftware/mender-docs/pull/1241 (related, and the discussion there)

2020-11-27 17:32 UTC, drewmoseley commented on 03.Client-installation/06.Mender-shell-configuration-file/50.Mender-shell-configuration-options/docs.md
> +User sessions settings.
Oh, I didn't notice the header levels here indicating that the below were sub-fields

2020-11-30 18:14 UTC, drewmoseley approved these changes
LGTM

2020-12-02 08:13 UTC, mirzak commented
Can this be rebased on top of https://github.com/mendersoftware/mender-docs/tree/feature-deviceconnect, so that we get everything related in one place?

2020-12-02 12:10 UTC, kjaskiewiczz commented
shouldn't a target of this PR be the feature-deviceconnect branch?

2020-12-02 20:07 UTC, merlin-northern commented
> shouldn't a target of this PR be the feature-deviceconnect branch?

sure, but I think the branch was no existent at the time.

2020-12-02 20:08 UTC, merlin-northern commented
> Can this be rebased on top of https://github.com/mendersoftware/mender-docs/tree/feature-deviceconnect, so that we get everything related in one place?

sure.

2020-12-02 20:12 UTC, merlin-northern commented
> Can this be rebased on top of https://github.com/mendersoftware/mender-docs/tree/feature-deviceconnect, so that we get everything related in one place?

it was supposed to be the base, thats why I had taken it early.

2020-12-04 23:44 UTC, estenberg commented
Thanks @merlin-northern !
I think this content is great! I do have a few high-level comments (sorry!):

* Creating a new top-level Chapter called "Add on" is a good idea I think. Basically you just need to move the Overview/Remote terminal and the Client installation/Mender shell as subsections of it. The main reason is that this feature will be part of "Troubleshoot" so there will be more of these features going forward (file up/download, etc.). It should be clear they can be disabled/removed, and there will be a commercial add-on offering around this too - and it would be nice if the marketing were aligned with the docs structure.

* Taxonomy is a bit mixed, I checked with Farshad and "Remote terminal" should be what we use. Now it's a mix of Remote terminal, remote access, shell.

I will provide some comments in the PR as well.

2020-12-04 23:53 UTC, estenberg requested changes

2020-12-04 23:53 UTC, estenberg commented on 02.Overview/01.Introduction/docs.md
> +It also supports an add-on mechanism, which currently has one implementation
Would rephrase slightly to, "It also supports an add-on features, enabling support for related device management features like Remote terminal."

2020-12-04 23:53 UTC, estenberg commented on 02.Overview/01.Introduction/docs.md
> +## The architecture of a Mender add-on
This is good, would leave it here.

2020-12-04 23:53 UTC, estenberg commented on 02.Overview/14.Remote.Terminal/docs.md
> +## Remote access
Remove this heading - doesn't add much?

2020-12-04 23:53 UTC, estenberg commented on 02.Overview/14.Remote.Terminal/docs.md
> +With Mender, you can start an interactive shell to any accepted
interactive shell -> terminal session?
accepted -> connected?

2020-12-04 23:53 UTC, estenberg commented on 02.Overview/14.Remote.Terminal/docs.md
> +[mender-shell](https://github.com/mendersoftware/mender-shell)
This (link to github) is a bit raw? Perhaps link to the other section about it in the docs instead?

2020-12-04 23:53 UTC, estenberg commented on 02.Overview/14.Remote.Terminal/docs.md
> +[mender-shell](https://github.com/mendersoftware/mender-shell)
Maybe there is no better place to link currently? I would expect some kind of setup instructions here though?

2020-12-04 23:53 UTC, estenberg commented on 02.Overview/14.Remote.Terminal/docs.md
> +## mender-shell vs SSH
"No relation to SSH"?

2020-12-04 23:53 UTC, estenberg commented on 02.Overview/14.Remote.Terminal/docs.md
> +The coupling between mender-shell and the rest of Mender is not tight.
Perhaps rephrase "There is loose coupling between Mender and add-ons like mender-shell."

2020-12-04 23:53 UTC, estenberg commented on 02.Overview/14.Remote.Terminal/docs.md
> +## mender-shell and the rest of the Mender ecosystem
"Loose coupling to Mender" ?

2020-12-04 23:53 UTC, estenberg commented on 02.Overview/14.Remote.Terminal/docs.md
> +## mender-shell and the user model
"Support for multiple users"?

2020-12-10 09:20 UTC, merlin-northern commented on 02.Overview/01.Introduction/docs.md
> +It also supports an add-on mechanism, which currently has one implementation
right.

2020-12-10 09:25 UTC, merlin-northern commented on 02.Overview/14.Remote.Terminal/docs.md
> +## Remote access
sure.

2020-12-10 09:25 UTC, merlin-northern commented on 02.Overview/14.Remote.Terminal/docs.md
> +With Mender, you can start an interactive shell to any accepted
sure. both sound better. I put "accepted" because technically it is most correct: you cant run a remote terminal to a device that you have not accepted.

2020-12-10 09:28 UTC, merlin-northern commented on 02.Overview/14.Remote.Terminal/docs.md
> +[mender-shell](https://github.com/mendersoftware/mender-shell)
got me with both comments. at the time of writing there was nothing. so I tried to link to anything. fixed to link to donwloads.

2020-12-10 09:32 UTC, merlin-northern commented on 02.Overview/14.Remote.Terminal/docs.md
> +## mender-shell vs SSH
sure

2020-12-10 09:37 UTC, merlin-northern commented on 02.Overview/14.Remote.Terminal/docs.md
> +The coupling between mender-shell and the rest of Mender is not tight.
I exactly had in mind "loose" but somehow I decided otherwise. fixed.

2020-12-10 09:38 UTC, merlin-northern commented on 02.Overview/14.Remote.Terminal/docs.md
> +## mender-shell and the rest of the Mender ecosystem
sure.

2020-12-10 09:38 UTC, merlin-northern commented on 02.Overview/14.Remote.Terminal/docs.md
> +## mender-shell and the user model
sure.

2020-12-11 21:35 UTC, estenberg approved these changes
Overall very nice, I have some nitpicks to improve the security section in particular but it can be improved later too.

2020-12-11 21:35 UTC, estenberg commented on 03.Add-ons/chapter.md
> +Mender supports extensions in a form of standalone binaries running
"extensions" -> "add-ons"

2020-12-11 21:35 UTC, estenberg commented on 03.Add-ons/chapter.md
> +on a device along side the Mender client. We call them _add-ons_. They
Can remove "We call them _add-ons_. "

2020-12-11 21:35 UTC, estenberg commented on 03.Add-ons/chapter.md
> +Mender supports extensions in a form of standalone binaries running
Can emphasise "add-ons"

2020-12-11 21:35 UTC, estenberg commented on 03.Add-ons/01.Remote-Terminal/40.Security/docs.md
> +The name of the feature is [Remote Terminal](../10.Overview/docs.md).
This is implicit, can remove this sentence.

2020-12-11 21:35 UTC, estenberg commented on 03.Add-ons/01.Remote-Terminal/40.Security/docs.md
> +The mender-shell uses [Encrypted WebSocket connections](https://tools.ietf.org/html/rfc6455#section-11.1.2) to communicate with the server.
mender-shell -> "Remote terminal"

2020-12-11 21:35 UTC, estenberg commented on 03.Add-ons/01.Remote-Terminal/40.Security/docs.md
> +Remote Terminal does not opens or listens on any port and the device initiates the connection.
"opens" -> "open"

2020-12-11 21:35 UTC, estenberg commented on 03.Add-ons/01.Remote-Terminal/40.Security/docs.md
> +Remote Terminal does not opens or listens on any port and the device initiates the connection.
"listens" -> "listen"

2020-12-11 21:35 UTC, estenberg commented on 03.Add-ons/01.Remote-Terminal/40.Security/docs.md
> +Remote Terminal does not opens or listens on any port and the device initiates the connection.
Recommending "Remote Terminal does not open nor listen on any port: the device initiates the connection to the server."

2020-12-11 21:35 UTC, estenberg commented on 03.Add-ons/01.Remote-Terminal/40.Security/docs.md
> +## Remote Terminal
Would mention audit logs at the end.

Also would consider having subsections here to improve structure.

E.g.

"Local device user"

"Role Based Access Control"

"No open ports"

"Audit logs"

Finally, need to tag that some of these features are only available if they are using Mender Enterprise (RBAC, Audit logs).

2020-12-11 21:51 UTC, merlin-northern commented
> Overall very nice, I have some nitpicks to improve the security section in particular but it can be improved later too.

great! it is not only not mine, but belongs to KJ, but also already reviewed ;-) I will correct according to your comments of course.

2020-12-14 14:41 UTC, merlin-northern commented on 03.Add-ons/chapter.md
> +Mender supports extensions in a form of standalone binaries running
right.

2020-12-14 14:41 UTC, merlin-northern commented on 03.Add-ons/chapter.md
> +on a device along side the Mender client. We call them _add-ons_. They
right.

2020-12-14 14:42 UTC, merlin-northern commented on 03.Add-ons/01.Remote-Terminal/40.Security/docs.md
> +The name of the feature is [Remote Terminal](../10.Overview/docs.md).
removed.

2020-12-14 14:42 UTC, merlin-northern commented on 03.Add-ons/01.Remote-Terminal/40.Security/docs.md
> +The mender-shell uses [Encrypted WebSocket connections](https://tools.ietf.org/html/rfc6455#section-11.1.2) to communicate with the server.
fixed.

2020-12-14 14:42 UTC, merlin-northern commented on 03.Add-ons/01.Remote-Terminal/40.Security/docs.md
> +Remote Terminal does not opens or listens on any port and the device initiates the connection.
recommendation taken.

2020-12-14 14:42 UTC, merlin-northern commented on 03.Add-ons/01.Remote-Terminal/40.Security/docs.md
> +## Remote Terminal
added subsections, noted about enterprise features, and corrected.

2020-12-14 17:18 UTC, estenberg approved these changes

2020-12-14 17:22 UTC, merged

2020-12-14 17:23 UTC, merlin-northern commented
thanks so much @estenberg