MEN-4136: Update download package with options to use apt repository
mendersoftware/mender-docs pull request #1246
Opened 2020-11-26 12:16 UTC by alfrunes

Adds two more installation paths:
 - Using the convenience script (https://get.mender.io)
 - Setting up our APT repository and installing from there.

(requires mendersoftware/mender-docs-site#297 to render properly)

2020-11-26 16:57 UTC, lluiscampos requested changes
Thanks @alfrunes, looks quite good. A bunch of comments below.

2020-11-26 16:57 UTC, lluiscampos commented on 09.Downloads/docs.md
> +* Set up Mender's apt repository and using the [package
I think we should capitalize `APT`

2020-11-26 16:57 UTC, lluiscampos commented on 09.Downloads/docs.md
> +](https://get.mender.io) that non-interactively install the Mender client
installs

2020-11-26 16:57 UTC, lluiscampos commented on 09.Downloads/docs.md
> +  examine the script before executing them.
executing it.

2020-11-26 16:57 UTC, lluiscampos commented on 09.Downloads/docs.md
> +* The Mender GPG public key and apt repository will be silently added to your
APT

2020-11-26 16:57 UTC, lluiscampos commented on 09.Downloads/docs.md
> +* The Mender GPG public key and apt repository will be silently added to your
And I wouldn't say "silently". I mean, is a script with standard verbosity. We could make it more verbose if necessary.

2020-11-26 16:57 UTC, lluiscampos commented on 09.Downloads/docs.md
> +* The script install several dependencies with the package manager without
The script will install

2020-11-26 16:57 UTC, lluiscampos commented on 09.Downloads/docs.md
> +* The script install several dependencies with the package manager without
Maybe: "The script will install necessary Mender dependencies..."

2020-11-26 16:57 UTC, lluiscampos commented on 09.Downloads/docs.md
> +  trusted apt keychain and sources list respectively.
APT

2020-11-26 16:57 UTC, lluiscampos commented on 09.Downloads/docs.md
> +installation methods.
In my personal opinion, this is redundant: we already have given other options and we have already warn extensively. I would just remove it

2020-11-26 16:57 UTC, lluiscampos commented on 09.Downloads/docs.md
> +sudo sh get-mender.sh
Okey, so no `curl -fLsS https://get.mender.io -o get-mender.sh | sudo bash` ? ;)

I envisioned a one-liner, but I think you are right in being as explicit as possible about the security risks.

2020-11-26 16:57 UTC, lluiscampos commented on 09.Downloads/docs.md
> +which can cause issues when upgrading packages using apt.
I think you are right but I consider this a bug or weakness in the script. We can follow-up separately to make the script idempotent, do you agree?

2020-11-26 16:57 UTC, lluiscampos commented on 09.Downloads/docs.md
> +  trusted apt keychain and sources list respectively.
(more below, but I'll stop commenting on these now)

2020-11-26 16:57 UTC, lluiscampos commented on 09.Downloads/docs.md
> +   [/ui-tabs]
This looks nice, but we are missing a note being explicit about choosing the correct architecture. Maybe "Add the Mender repository to your sources list. Chose the architecture matching your device."

An alternative could have been having it in a single script using `dpkg --print-architecture` instead of three different tabs.

2020-11-26 17:23 UTC, alfrunes commented on 09.Downloads/docs.md
> +sudo sh get-mender.sh
Yeah, I think it's better to just be honest and explicit about good security practices.

2020-11-26 17:28 UTC, alfrunes commented on 09.Downloads/docs.md
> +which can cause issues when upgrading packages using apt.
I think this is a trade-off. If we make the script more involved it's also making it harder for users to inspect it. I don't see it as a critical issue that users can't run this twice. In any case, I think we should encourage users to use `apt upgrade` from this point on somehow.

2020-11-26 18:03 UTC, alfrunes commented on 09.Downloads/docs.md
> +* The Mender GPG public key and apt repository will be silently added to your
I changed "silently" to "... without asking for confirmation".

2020-11-26 18:07 UTC, alfrunes commented
@lluiscampos I've addressed most of the comment and added a paragraph explaining the `mender-shell` dependency in the Express installation. I'll also add the rest of the "Remote terminal client" sub-section tomorrow. I'll hold off the next review request until this is done.

2020-11-27 09:10 UTC, lluiscampos approved these changes
Looks good to me!

The broken link I guess it because we need #1241 

Also, let's discuss the requirement or not of a feature branch in Slack `mender-docs-team` before merging this.

2020-11-27 09:10 UTC, lluiscampos commented on 09.Downloads/docs.md
> +multiple additions of the Mender Debian repository to the APT sources list,
I would omit Debian, to avoid confusion with upstream repo

```suggestion
multiple additions of the Mender repository to the APT sources list,
```

2020-11-27 09:10 UTC, lluiscampos commented on 09.Downloads/docs.md
> +The remote terminal client is only available from the Mender Debian repository.
Same suggestion here

```suggestion
The remote terminal client is only available from the Mender repository.
```

2020-11-27 09:54 UTC, alfrunes commented on 09.Downloads/docs.md
> +multiple additions of the Mender Debian repository to the APT sources list,
I'm ok with that if it does not lead to confusion with "GitHub repository".

2020-11-27 10:31 UTC, mchalski commented on 09.Downloads/docs.md
> +which can cause issues when upgrading packages using apt.
I'll make it idempotent, as discussed in https://github.com/mendersoftware/mender-dist-packages/pull/46

2020-11-27 11:59 UTC, lluiscampos commented on 09.Downloads/docs.md
> +multiple additions of the Mender Debian repository to the APT sources list,
Good point. "Mender APT repository", maybe? Does someone else have an opinion?

2020-11-30 18:13 UTC, drewmoseley requested changes
Looks good except for one minor change.  Definitely don't need to re-review for that fix alone.

2020-11-30 18:13 UTC, drewmoseley commented on 09.Downloads/docs.md
> +!! Always examine scripts downloaded over the Internet before running it
before running them locally.

2020-12-01 08:58 UTC, merlin-northern commented on 09.Downloads/docs.md
> +2. Add the official Mender GPG to your trusted `apt` keychain:
suggested change "official Mender GPG to" -> "official Mender GPG _key_ to"

2020-12-01 08:58 UTC, merlin-northern commented on 09.Downloads/docs.md
> +curl -fLsS https://get.mender.io -o get-mender.sh
```
#curl -fLsS https://get.mender.io -o get-mender.sh
curl: (6) Could not resolve host: get.mender.io
```

2020-12-01 08:58 UTC, merlin-northern commented on 09.Downloads/docs.md
> +After installing the Mender client with [get.mender.io](https://get.mender.io),
suggested change: 
either
"installing the Mender client with [get.mender.io]..." -> "installing the Mender client _from_ [get.mender.io](https://get.mender.io)"
or
"installing the Mender client with [get.mender.io]..." -> "installing the Mender client _with_ get-mender.sh "

2020-12-01 08:58 UTC, merlin-northern commented on 09.Downloads/docs.md
> +the `mender-client` package is managed by the package manager. To upgrade the
managed by a manager, and also passive. maybe somehow reword this? "you can upgrade mender-client in a standard way with the package manager:"

2020-12-01 08:58 UTC, merlin-northern commented on 09.Downloads/docs.md
> +the Mender client from the repository.
Second sentence is redundant. I would suggest some rewording of this paragraph:
"If you choose to install the Mender client with the `apt-get` command you need to first configure the APT repository."
just a suggestion, I somehow do not like how this reads.

2020-12-01 08:58 UTC, merlin-northern commented on 09.Downloads/docs.md
> +The Debian package (`.deb`) is also provided for users wanting to install the
passive. suggested change: "We also provide the Debian package .."

2020-12-01 09:17 UTC, merlin-northern commented on 09.Downloads/docs.md
> +* Download our DEB package and [install it manually](#install-from-package).
this is the one and only place where we use "`DEB`" string, in the rest of this section we refer to the package as "Debian package" with occasional ".deb".

2020-12-01 09:21 UTC, merlin-northern commented on 09.Downloads/docs.md
> +* Download our DEB package and [install it manually](#install-from-package).
Technically speaking, you are listing here three "different ways" to install. First one "Express installation" is a way to install. second and third "Set up Mender's APT" and "Download our DEB" could be rephrased to better fit here. e.g.: "Download our DEB" -> "Install from a .deb file", "Set up Mender's APT" -> "Install from the APT repository"

2020-12-01 09:25 UTC, alfrunes commented on 09.Downloads/docs.md
> +curl -fLsS https://get.mender.io -o get-mender.sh
This URL depends on [MEN-4150](https://tracker.mender.io/browse/MEN-4150) and [MEN-4152](https://tracker.mender.io/browse/MEN-4152) - hence, the feature branch.

2020-12-01 10:23 UTC, merlin-northern commented on 09.Downloads/docs.md
> +* The script require `root` privileges to run. Therefore, be careful to
suggested change: "The script require " -> "The script _requires_ "

2020-12-01 10:24 UTC, merlin-northern commented on 09.Downloads/docs.md
> +using this method should be aware of:
suggested change "be aware of:" -> "be aware of _the following_:" or something in the lines of "aware that:"

2020-12-01 10:25 UTC, merlin-northern commented on 09.Downloads/docs.md
> +  examine the script before executing it.
suggested change: "examine the script before executing it." -> "examine it before executing."

2020-12-01 10:41 UTC, merlin-northern commented on 09.Downloads/docs.md
> +airtight systems with limited access to the Internet, for example when running
somehow this does not read well.
suggested change: "access to the Internet, for example when running" -> "access to the Internet, _or_ when running"

2020-12-01 10:41 UTC, merlin-northern commented on 09.Downloads/docs.md
> +Mender in [standalone
suggested change: "Mender in [standalone" -> "Mender in _the_ [standalone"

2020-12-01 10:43 UTC, merlin-northern commented on 09.Downloads/docs.md
> +more information about the remote terminal plugin.
suggested change: drop: " about the remote terminal plugin"

2020-12-01 11:19 UTC, merlin-northern commented on 09.Downloads/docs.md
> +## Remote terminal client
suggested: let's not use "remote terminal client" every where we use mender-shell or add-on, so maybe change to "Remote terminal add-on"?

2020-12-01 11:21 UTC, merlin-northern commented on 09.Downloads/docs.md
> +accessing the device terminal using the Mender API. See the [configuration page
we do not provide any API for remote terminal.
suggested change: "using the Mender API" -> "using the Mender _UI_"

2020-12-01 11:25 UTC, merlin-northern commented on 09.Downloads/docs.md
> +`mender-shell` installed by default.
this does not read very well.
suggested change:
"The mender-shell add-on requires the Mender client in order to provide remote terminals to accepted devices from the Mender UI. Please also note, that if you used [the express installation method](#express-installation), you will already have
`mender-shell` installed by default."

2020-12-01 11:31 UTC, merlin-northern commented on 09.Downloads/docs.md
> +After the final step, install `mender-shell` using the package manager:
suggested change:
"The mender-shell add-on is only available from the Mender APT repository. Once you perform [the steps to configure the APT repository](#install-using-the-apt-repository), you can go with the installation in a normal way, by running:"

2020-12-01 11:32 UTC, merlin-northern reviewed
left some comments.

2020-12-01 13:47 UTC, merlin-northern approved these changes
I trust you -- did not revisit all.

2020-12-01 14:52 UTC, alfrunes commented
I'm merging this into the feature branch. We may revisit once we merge the other docs tickets for `mender-shell`.

2020-12-01 14:52 UTC, merged