05.System-updates-Yocto-Project/05.Customize-Mender/: mender-shell
mendersoftware/mender-docs pull request #1249
Opened 2020-12-01 10:08 UTC by mchalski

changelog: none

Signed-off-by: Marcin Chalczynski <m.chalczynski@gmail.com>

# External Contributor Checklist

🚨 Please review the [guidelines for contributing](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md) to this repository.

- [ ] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.

### Description

Please describe your pull request.

Thank you!

2020-12-01 10:19 UTC, merlin-northern reviewed
I will leave the yocto related things for the experts to review.

2020-12-01 10:19 UTC, merlin-northern commented on 05.System-updates-Yocto-Project/05.Customize-Mender/docs.md
> +Mender-shell is not enabled by default, unless you are building with the demo layer.
passive. suggested change: "Mender-shell is not enabled by default" -> "_We do not enable mender-shell_ by default". and I reallt have no idea wether we use Mender-shell or mender-shell and shall we treat it as a command, in that case "the mender-shell" or the name of the addon, in that case we can drop the article.

2020-12-01 10:36 UTC, mchalski commented on 05.System-updates-Yocto-Project/05.Customize-Mender/docs.md
> +Mender-shell is not enabled by default, unless you are building with the demo layer.
fixed

2020-12-01 14:58 UTC, lluiscampos requested changes
The PR should target the feature branch. See also some comments below.

The CI error is due to the broken link, which I think should be fix if we target feature branch.

2020-12-01 14:58 UTC, lluiscampos commented on 05.System-updates-Yocto-Project/05.Customize-Mender/docs.md
> +## Addons
```suggestion
## Add-ons 
```

@merlin-northern right?

2020-12-01 14:58 UTC, lluiscampos commented on 05.System-updates-Yocto-Project/05.Customize-Mender/docs.md
> +To enable Mender-shell you can add it either via your own `.bbappend` recipe file`,
```suggestion
To enable Mender-shell you can add it either via your own `.bbappend` recipe file,
```

2020-12-01 14:58 UTC, lluiscampos commented on 05.System-updates-Yocto-Project/05.Customize-Mender/docs.md
> +    install -m 644 ${WORKDIR}/mender-shell.conf ${datadir}/mender/mender-shell.conf
I think this should be `600` like in [the Makefile](https://github.com/mendersoftware/mender-shell/blob/master/Makefile#L59).

2020-12-09 18:15 UTC, merlin-northern commented on 05.System-updates-Yocto-Project/05.Customize-Mender/docs.md
> +## Addons
yes, right!

2020-12-14 18:01 UTC, merlin-northern commented on 05.System-updates-Yocto-Project/05.Customize-Mender/docs.md
> +    install -m 644 ${WORKDIR}/mender-shell.conf ${datadir}/mender/mender-shell.conf
corrected here https://github.com/mchalski/mender-docs/pull/1

2020-12-14 18:01 UTC, merlin-northern commented on 05.System-updates-Yocto-Project/05.Customize-Mender/docs.md
> +To enable Mender-shell you can add it either via your own `.bbappend` recipe file`,
corrected here https://github.com/mchalski/mender-docs/pull/1

2020-12-14 18:01 UTC, merlin-northern commented on 05.System-updates-Yocto-Project/05.Customize-Mender/docs.md
> +## Addons
corrected here https://github.com/mchalski/mender-docs/pull/1

2020-12-14 18:44 UTC, merlin-northern commented
needs a rebase on top of current feature branch, or we can merge it, the link is present, and I will be merging feature branch very soon any way.

2020-12-14 18:56 UTC, mchalski commented
first off, thank you @merlin-northern for taking over this after discussions on doc structure.
I rebased on top of fresh `feature-deviceconnect` just now.

2020-12-15 08:24 UTC, lluiscampos approved these changes

2020-12-15 08:24 UTC, merged