Step 8 should use mmcblk0p2 instead of mmcblk2 #1370
mendersoftware/mender-docs pull request #1371
Opened 2021-03-15 06:48 UTC by lerv22

root@raspberrypi4:# mount /dev/mmcblk2 /mnt
mount: /mnt: special device /dev/mmcblk2 does not exist.
root@raspberrypi4:# mount /dev/mmcblk0p2 /mnt
[ 498.514342] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null)
[ 498.522653] ext4 filesystem being mounted at /mnt supports timestamps until 2038 (0x7fffffff)

Signed-off-by: Luis Ramirez <lerv22@gmail.com>

# External Contributor Checklist

🚨 Please review the [guidelines for contributing](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md) to this repository.

- [ ] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.

### Description

There was an error while following the tutorial. My fix allows me to continue

Thank you!

2021-03-15 08:56 UTC, lluiscampos approved these changes
I _think_ this is correct. @kacf can you double-check?

2021-03-15 10:17 UTC, kacf requested changes
Yes, this is correct, but please target this PR to the `master` branch. All the other branches are receiving their updates from there.

2021-03-15 16:08 UTC, lerv22 commented
The differences between hosted and master are so many that I can not just merge them and I don't want to remove anything that is important. Can you check it?

2021-03-16 08:19 UTC, kacf approved these changes

2021-03-16 10:17 UTC, merged

2021-03-16 10:18 UTC, kacf commented
I force pushed to remove the extraneous commits, and merged. Thanks!