WIP: document configure add-on
mendersoftware/mender-docs pull request #1372
Opened 2021-03-15 23:41 UTC by kjaskiewiczz

2021-03-15 23:45 UTC, kjaskiewiczz commented
I know it's still WIP, but I wasn't sure what should be documented here;
@estenberg it would be great if you could take a brief look and possibly left some comment so I could adjust the docs;

2021-03-16 14:54 UTC, merlin-northern commented on 01.Get-started/chapter.md
> +foo Quickly try the most common use cases of Mender.
foo you say? ;-)

2021-03-16 19:17 UTC, estenberg requested changes
Added a few cosmetic comments.

Though I think we'll need a bit more here:

Architecture / how it works end-to-end
The screenshots and diagram provide a very high-level architecture & UI. But what do I do from here? How does it all tie together? Would at least have a header "How it works" and include the flow from when settings are typed in to the UI until they are applied & reported back to the backend.

Here is one diagram from planning: https://docs.google.com/presentation/d/1a7hQQDSxRJzMDWqjktFpMWrJ610MMruthwTpLx2IlFk/edit#slide=id.g6f2c5369fe_0_8
Here is another that includes the file paths (which I think is important); https://docs.google.com/presentation/d/1reuk8qu7aSsQf_IOzbYFa_JoLpWMwGDbCTQ98g4Y_6A/edit#slide=id.g9b313eab1b_0_228

Would take these as a starting point and create a diagram for how this all fits together, e.g. take the first diagram and add the file paths from the second, perhaps with a UI screenshot as well.

* Installation
How to install it is needed, similar to: https://docs.mender.io/add-ons/remote-terminal/installation. Even if the only thing needed is the Update Module, just write that in a new document and point to the Update Module on Mender Hub.

2021-03-16 19:17 UTC, estenberg commented on 09.Add-ons/02.Configure/docs.md
> +
Add a header about the commercial package, align with what @merlin-northern asked about for Troubleshoot add-ons.

E.g. "!! Configure is part of a commercial add-on package. See the [Mender features page](https://mender.io/plans/features?target=_blank) for an overview of all Mender plans and features."

2021-03-16 19:17 UTC, estenberg commented on 09.Add-ons/02.Configure/docs.md
> +The specialized update module is responsible for applying the configuration to the device.
Link to the Update Module on Mender Hub (https://tracker.mender.io/browse/MEN-4424)

2021-03-29 20:02 UTC, kjaskiewiczz commented on 09.Add-ons/02.Configure/docs.md
> +
I've added something; please take a look

2021-03-29 20:03 UTC, kjaskiewiczz commented on 09.Add-ons/02.Configure/docs.md
> +The specialized update module is responsible for applying the configuration to the device.
there is no info about this update module on the Mender Hub yet

2021-03-29 20:03 UTC, kjaskiewiczz commented on 01.Get-started/chapter.md
> +foo Quickly try the most common use cases of Mender.
fixed

2021-03-29 20:25 UTC, estenberg commented on 09.Add-ons/02.Configure/docs.md
> +
Text is fine, but try to style it the same as the other notes of this kind. E.g. take a look here, and steal the style (I think it's three exclamation marks): https://docs.mender.io/overview/delta-update

2021-03-30 07:51 UTC, kjaskiewiczz commented on 09.Add-ons/02.Configure/docs.md
> +
done

2021-03-30 21:12 UTC, estenberg commented
It's quite good now, thanks for the improvements.

One thing I think still needs to be fixed is this configure1.png diagram: https://github.com/mendersoftware/mender-docs/blob/77c048a91cdbb16612de8d7b6baebcc4aba2b708/09.Add-ons/02.Configure/configure1.png

It's not quite how it turned out. For example, there is no state script involved AFIK? Should we include the file paths too? 

Save to: /var/lib/mender-configure/device-config.json
Execute (modified by end user): /usr/lib/mender-configure/apply-device-config.d/*

2021-03-31 17:38 UTC, TheMeaningfulEngineer commented on 09.Add-ons/02.Configure/docs.md
> +The picture below shows the configuration update flow.
FWIW
Separating the description between the server and client.

```suggestion
The configuration is applied in a similar way the updates are applied.
`deviceconfig` is a microservice on the server responsible for "translating" a configuration change made in the UI into a deployment.
It then proceeds to trigger a deployment to the device using the same mechanism used in OTA, the `deployments` microservice. 

On the device side, a specialized update module is responsible for applying the configuration.
You can find more information about the configuration update module on [Mender Hub](https://hub.mender.io).
The picture below shows the configuration update flow.
```

2021-03-31 17:56 UTC, TheMeaningfulEngineer commented
@kjaskiewiczz 
How does the device provide the information to the `devicevonfig`. Is it pushing the updates at regular intervals or "real time"?

2021-04-01 09:24 UTC, kjaskiewiczz commented
@TheMeaningfulEngineer the device is reporting back the configuration using this endpoint - https://staging.docs.mender.io/api/development/#report-device-configuration

2021-04-01 09:29 UTC, kjaskiewiczz commented
> It's not quite how it turned out. For example, there is no state script involved AFIK? Should we include the file paths too?
@estenberg not sure if this should be a part of the overview; we are providing the detailed description of how the configure update module works in other place

2021-04-01 18:56 UTC, estenberg commented
>> It's not quite how it turned out. For example, there is no state script involved AFIK? Should we include the file paths too?

> @estenberg not sure if this should be a part of the overview; we are providing the detailed description of how the configure update module works in other place

I understand, but I think at least a diagram that shows the flow is very helpful here. I think the file paths are helpful to understand it, but if you think it's too detailed then we can live without them here then. We still need the diagram to correctly reflect how it is though (now there are some errors, as I pointed out).

2021-04-01 20:16 UTC, kjaskiewiczz commented
@estenberg  I've added paths to the diagram; please take a look

2021-04-02 17:11 UTC, estenberg approved these changes
Very good, thank you.

2021-04-02 17:37 UTC, merged