MEN-4515 File Transfer docs and refactoring around mender-connect and…
mendersoftware/mender-docs pull request #1390
Opened 2021-04-07 17:16 UTC by merlin-northern

… Remote Terminal

ChangeLog:none
Signed-off-by: Peter Grzybowski <peter@northern.tech>

2021-04-07 20:29 UTC, TheMeaningfulEngineer commented on 09.Add-ons/00.Overview/docs.md
> +| [Configure](../02.Configure/docs.md) | Lets you pass arbitrary configuration to your devices | Configure package |
```suggestion
| [Configure](../02.Configure/docs.md) | Lets you apply configuration to your devices through a uniform interface | Configure package |
```
No strong opinion on this. Pass felt a bit casual.

2021-04-07 20:34 UTC, TheMeaningfulEngineer commented on 09.Add-ons/00.Overview/docs.md
> +The Mender Connect is loosely tied to the Mender Client. The main information passed between
```suggestion
The Mender Connect is loosely coupled to the Mender Client. The main information passed between 
```

2021-04-07 20:46 UTC, TheMeaningfulEngineer commented on 09.Add-ons/00.Overview/docs.md
> +and portable.
I'll try to paraphrase this just so see if I got it correctly:

> `mender-client` is the service which keeps track if the device has been authorized on the server. Upon successful authorization `mender-client` gains possession of the authorization token needed to make API calls to the server. Through the DBus API which `mender-client` exposes, `mender-connect` gains access to the authorization token which it uses to establish a websocket connection to the server.

2021-04-07 21:06 UTC, TheMeaningfulEngineer commented on 09.Add-ons/00.Overview/docs.md
> +A path to the file in pem format holding the certificate.
Why does the client need a certificate?

2021-04-07 21:10 UTC, TheMeaningfulEngineer commented on 09.Add-ons/00.Overview/docs.md
> +The number of seconds to wait between consecutive reconnection attempts.
Reconnection attempts to establish a websocket with the server?

2021-04-07 21:14 UTC, TheMeaningfulEngineer commented on 09.Add-ons/01.Remote-Terminal/20.Installation/docs.md
> +to the below sections for the details:
Some "file transfer" mentions.
There seems to be a chapter on file transfer below?

2021-04-07 21:14 UTC, TheMeaningfulEngineer commented on 09.Add-ons/01.Remote-Terminal/20.Installation/docs.md
> +for the available configuration options.
Same as above. File transfer here?

2021-04-07 21:26 UTC, TheMeaningfulEngineer commented on 09.Add-ons/00.Overview/docs.md
> +    "User": "mender",
"User" isn't described as an option. 
I'm assuming this is the user you end up becoming when you "remote terminal" (remote termnal is used as a verb ;)) to the device?
And it will also be the owner of the files which get transferred to the device via the file transfer?

2021-04-07 21:59 UTC, estenberg requested changes
Thanks for doing this, it was really necessary to clean this up with 2.7!

I had a few comments, some of them applies to more places than I commented. In particular, I think we should refer to it as `mender-connect` (with backticks).

I also think "piece of software" is a bit too informal. Suggesting "software application", "application", "client" or something similar.

2021-04-07 21:59 UTC, estenberg commented on 02.Overview/01.Introduction/docs.md
> +Mender also supports powerful extensions in a form of so-called
Remove "so-called"

2021-04-07 21:59 UTC, estenberg commented on 02.Overview/01.Introduction/docs.md
> +Mender also supports powerful extensions in a form of so-called
Remove "so-called"

2021-04-07 21:59 UTC, estenberg commented on 02.Overview/01.Introduction/docs.md
> +[add-ons](../../09.Add-ons/00.Overview/docs.md) which bring
"which bring ... " -> "which enables features like Remote terminal, Port forward, and device configuration."

2021-04-07 21:59 UTC, estenberg commented on 02.Overview/15.Taxonomy/docs.md
> +* _Mender Connect_ - A user space application providing the add-ons
I would leave this out (not define it), it's not a 1-1 mapping to add-ons. It's also more of a tool than a taxonomy.

For example, Configure is an add-on package that doesn't use mender-connect at all. And later we'll have instant OTA updates due to mender-connect.

2021-04-07 21:59 UTC, estenberg commented on 09.Add-ons/00.Overview/docs.md
> +The add-ons are independent pieces of software, but they run under a common executable:
"pieces of software" -> "software applications"

2021-04-07 21:59 UTC, estenberg commented on 09.Add-ons/00.Overview/docs.md
> +The Mender Connect is loosely tied to the Mender Client. The main information passed between
coupled with

2021-04-07 21:59 UTC, estenberg commented on 09.Add-ons/00.Overview/docs.md
> +Please refer to the following sections for the Mender Connect installation:
Would refer to it as "mender-connect", I think.

2021-04-07 21:59 UTC, estenberg commented on 09.Add-ons/01.Remote-Terminal/20.Installation/docs.md
> +File Transfer is a mender-connect based add-on. This means that
Use backticks when referring to utilities, `mender-connect`

2021-04-07 21:59 UTC, estenberg commented on 09.Add-ons/chapter.md
> +Mender _add-ons_ are pieces of software running on a device and fully integrated
"software applications"

2021-04-08 05:33 UTC, merlin-northern commented on 09.Add-ons/chapter.md
> +Mender _add-ons_ are pieces of software running on a device and fully integrated
changed.

2021-04-08 05:33 UTC, merlin-northern commented on 09.Add-ons/01.Remote-Terminal/20.Installation/docs.md
> +File Transfer is a mender-connect based add-on. This means that
yes, fixed everywhere I could find.

2021-04-08 05:33 UTC, merlin-northern commented on 09.Add-ons/00.Overview/docs.md
> +Please refer to the following sections for the Mender Connect installation:
see above, let's talk about it. my reasons: we say "Mender Client", "Mender Server"

2021-04-08 05:33 UTC, merlin-northern commented on 09.Add-ons/00.Overview/docs.md
> +The add-ons are independent pieces of software, but they run under a common executable:
changed to applications to keep it short.

2021-04-08 05:33 UTC, merlin-northern commented on 02.Overview/15.Taxonomy/docs.md
> +* _Mender Connect_ - A user space application providing the add-ons
there is only one small problem. we refer to to it in many places, just as to Mender Client. let's discuss privately, will be faster.

2021-04-08 05:33 UTC, merlin-northern commented on 02.Overview/01.Introduction/docs.md
> +[add-ons](../../09.Add-ons/00.Overview/docs.md) which bring
changed.

2021-04-08 05:34 UTC, merlin-northern commented on 02.Overview/01.Introduction/docs.md
> +Mender also supports powerful extensions in a form of so-called
removed. (I now searched everywhere for 'so-called')

2021-04-08 05:34 UTC, merlin-northern commented on 02.Overview/01.Introduction/docs.md
> +Mender also supports powerful extensions in a form of so-called
removed.

2021-04-08 05:34 UTC, merlin-northern commented on 09.Add-ons/00.Overview/docs.md
> +    "User": "mender",
right:) this is Remote-Terminal specific, described in later sections. I removed that from there. good catch. File Transfer uses a bit different config.

2021-04-08 05:34 UTC, merlin-northern commented on 09.Add-ons/01.Remote-Terminal/20.Installation/docs.md
> +for the available configuration options.
yes copy-paste error. thanks. fixed.

2021-04-08 05:34 UTC, merlin-northern commented on 09.Add-ons/01.Remote-Terminal/20.Installation/docs.md
> +to the below sections for the details:
right! copy-paste error. fixed. thanks.

2021-04-08 05:34 UTC, merlin-northern commented on 09.Add-ons/00.Overview/docs.md
> +The number of seconds to wait between consecutive reconnection attempts.
yes. this was moved here unchanged.

2021-04-08 05:35 UTC, merlin-northern commented on 09.Add-ons/00.Overview/docs.md
> +A path to the file in pem format holding the certificate.
this is optional, and the same as in the client configuration. this was just moved here un changed.

2021-04-08 05:35 UTC, merlin-northern commented on 09.Add-ons/00.Overview/docs.md
> +and portable.
yes. the reason I wrote it like that is: DBus actually triggers events about auth status change.

2021-04-08 05:35 UTC, merlin-northern commented on 09.Add-ons/00.Overview/docs.md
> +The Mender Connect is loosely tied to the Mender Client. The main information passed between
changed.

2021-04-08 05:35 UTC, merlin-northern commented on 09.Add-ons/00.Overview/docs.md
> +| [Configure](../02.Configure/docs.md) | Lets you pass arbitrary configuration to your devices | Configure package |
sure. changed to apply and added at the end. (left arbitrary)

> Thanks for doing this, it was really necessary to clean this up with 2.7!
> 
> I had a few comments, some of them applies to more places than I commented. In particular, I think we should refer to it as `mender-connect` (with backticks).

I searched and replaced every mender-connect mention and thanged to `mender-connect`.

> 
> I also think "piece of software" is a bit too informal. Suggesting "software application", "application", "client" or something similar.

thanks for the review.

2021-04-08 05:36 UTC, merlin-northern commented on 09.Add-ons/00.Overview/docs.md
> +and portable.
thanks for the review.

2021-04-08 07:24 UTC, TheMeaningfulEngineer approved these changes
LGTM Thanks :)

2021-04-08 20:49 UTC, estenberg requested changes
Some small nitpicks, but overall I think it's good now and agree with your reasoning for calling it "Mender Connect".

2021-04-08 20:49 UTC, estenberg commented on 02.Overview/01.Introduction/docs.md
> +enable features like Remote Terminal, Port Forward, FIle Transfer,
FI -> Fi

2021-04-08 20:49 UTC, estenberg commented on 02.Overview/01.Introduction/docs.md
> +Mender supports add-ons via the Mender Connect daemon running on a device.
"mainly via" ?

2021-04-08 20:49 UTC, estenberg commented on 02.Overview/15.Taxonomy/docs.md
> +* _Add-on_ (also _Mender Add-on_)- A piece of software which extends Mender beyond
Not piece please :)

2021-04-08 20:49 UTC, estenberg commented on 02.Overview/15.Taxonomy/docs.md
> +* _Mender Connect_ - A user space application providing the add-ons
OK, it makes sense. We can leave it here.

2021-04-08 20:49 UTC, estenberg commented on 09.Add-ons/00.Overview/docs.md
> +The Mender Connect is loosely coupled with the Mender Client. The main information passed between
"The Mender Connect" -> "Mender Connect"

2021-04-08 20:49 UTC, estenberg commented on 09.Add-ons/00.Overview/docs.md
> +Please refer to the following sections for the Mender Connect installation:
Yes, makes sense. Let's keep "Mender Connect". :+1:

2021-04-09 05:40 UTC, merlin-northern commented on 09.Add-ons/00.Overview/docs.md
> +The Mender Connect is loosely coupled with the Mender Client. The main information passed between
fixed

2021-04-09 05:42 UTC, merlin-northern commented on 02.Overview/15.Taxonomy/docs.md
> +* _Add-on_ (also _Mender Add-on_)- A piece of software which extends Mender beyond
sorry for that. I now grepped for 'piece' everywhere. fixed to "An application".

2021-04-09 05:42 UTC, merlin-northern commented on 02.Overview/01.Introduction/docs.md
> +Mender supports add-ons via the Mender Connect daemon running on a device.
fixed.

2021-04-09 05:43 UTC, merlin-northern commented on 02.Overview/01.Introduction/docs.md
> +enable features like Remote Terminal, Port Forward, FIle Transfer,
right!

2021-04-09 16:54 UTC, estenberg approved these changes
Perfecto!

2021-04-09 17:10 UTC, merged