WIP: update docs to reflect actual state of the mender server
mendersoftware/mender-docs pull request #1391
Opened 2021-04-11 20:14 UTC by kjaskiewiczz

2021-04-12 09:34 UTC, mchalski reviewed
1 typo

2021-04-12 09:34 UTC, mchalski commented on 07.Server-installation/03.Production-installation/docs.md
> +Mender API Gateway as a proxy to the storge service, by runnig the floolwing command:
following

2021-04-12 09:37 UTC, kjaskiewiczz commented on 07.Server-installation/03.Production-installation/docs.md
> +Mender API Gateway as a proxy to the storge service, by runnig the floolwing command:
fixed

2021-04-12 13:24 UTC, lluiscampos requested changes
Thanks for tackling this!

See my comments below, I don't know what we should do with the list of services and the diagram. Maybe is best to remove it from integration repo and only maintain it here?

2021-04-12 13:24 UTC, lluiscampos commented on 07.Server-installation/01.Overview/docs.md
Missing in this list:
* Device Config
* Device Connect
* Workflows
* Create Artifact Worker
* NATS
* (something else?)

We have this information duplicated (and wrong) in integration repo: https://github.com/mendersoftware/integration#services

2021-04-12 13:24 UTC, lluiscampos commented on 07.Server-installation/01.Overview/docs.md
>          |
This is incomplete, see my previous comment

2021-04-12 13:24 UTC, lluiscampos commented on 07.Server-installation/03.Production-installation/docs.md
>  ```
The line above can be removed: `API_GATEWAY_DOMAIN_NAME="mender.example.com"  # NB! replace with your server's public domain name`

2021-04-12 14:43 UTC, kjaskiewiczz commented on 07.Server-installation/03.Production-installation/docs.md
>  ```
we still use API_GATEWAY_DOMAIN_NAME env in other places

2021-04-12 15:06 UTC, lluiscampos commented on 07.Server-installation/03.Production-installation/docs.md
>  ```
You are right. Sorry.

2021-04-12 16:38 UTC, kjaskiewiczz commented on 07.Server-installation/01.Overview/docs.md
>          |
right; for some reason I thought we are documenting here only user facing services, but that's not true

2021-04-12 17:24 UTC, kjaskiewiczz commented on 07.Server-installation/01.Overview/docs.md
once this PR will be merge I'll open one in integration where I'll point to the docs instead of copy/pasting the content

2021-04-12 17:24 UTC, kjaskiewiczz commented on 07.Server-installation/01.Overview/docs.md
I've updated the list

2021-04-12 17:25 UTC, kjaskiewiczz commented on 07.Server-installation/01.Overview/docs.md
>          |
fixed (at least I hope it's fixed)

2021-04-13 06:55 UTC, lluiscampos approved these changes
Looks good. Thank you

2021-04-13 08:32 UTC, kacf approved these changes
Very nice to have all the outdated output snippets replaced!

I have one possible improvement for you below, but it's good as is also.

2021-04-13 08:32 UTC, kacf commented on 07.Server-installation/03.Production-installation/docs.md
> +<!--AUTOMATION: execute=STORAGE_PROXY_DOMAIN_NAME="s3.docker.mender.io" -->
Aren't the ignored snippet and `AUTOMATION` steps identical now? If so, it's better to remove all the `AUTOMATION` tags, which causes the original snippet to be executed instead of being ignored. Then we are one step closer to doing what the steps actually say! :-)

2021-04-13 08:37 UTC, TheMeaningfulEngineer commented on 07.Server-installation/01.Overview/docs.md
> +        |                                            +-------------------------+
I have accidentally run `./demo up` while having the docs server running locally and this produced an error:

> ERROR: for integration_mender-api-gateway_1  Cannot start service mender-api-gateway: driver failed programming external connectivity on endpoint integration_mender-api-gateway_1 (e7f42c60a2840508b8c8ce0
> b96a1e8b4ce605d4532231fa36af01671c19655c2): Bind for 0.0.0.0:8080 failed: port is already allocated

 However looking at this picture there is nothing telling me that port 8080 will end up consumed.
 Any thoughts on this?

2021-04-13 08:45 UTC, TheMeaningfulEngineer commented on 07.Server-installation/03.Production-installation/docs.md
> +Mender API Gateway as a proxy to the storage service, by running the following command:
[Knowledge sharing]
What does this means practically?
That the mender client no longer has different endpoints for API calls and artifact downloads?
However minio/s3 can still be a separate server but it's just proxied through the API gateway now?

2021-04-13 08:46 UTC, TheMeaningfulEngineer commented on 201.Troubleshoot/04.Mender-Server/docs.md
> -## mender-api-gateway exits with code 132
This isn't relevant anymore as this was an nginx specific error?

2021-04-13 09:21 UTC, kjaskiewiczz commented on 201.Troubleshoot/04.Mender-Server/docs.md
> -## mender-api-gateway exits with code 132
yes

2021-04-13 09:23 UTC, kjaskiewiczz commented on 07.Server-installation/03.Production-installation/docs.md
> +Mender API Gateway as a proxy to the storage service, by running the following command:
This means API gateway serves artifacts too, but under different domain name.
Old setup:
mender.server.domain.com -> Mender API Gateway
storage.domain.name.com -> Storage Proxy
Current setup:
mender.server.domain.com -> API Gateway
storage.domain.name.com -> API Gateway (the same one)

2021-04-13 09:24 UTC, kjaskiewiczz commented on 07.Server-installation/01.Overview/docs.md
> +        |                                            +-------------------------+
this is the difference between demo and production; in the demo setup you have port 8080 exposed:
https://github.com/mendersoftware/integration/blob/2494211d43e70264e3bc5aaed5fffd1ad5e1484f/docker-compose.demo.yml#L21

2021-04-13 09:33 UTC, TheMeaningfulEngineer commented on 07.Server-installation/01.Overview/docs.md
> +        |                                            +-------------------------+
What for?
If the API proxy is the only endpoint now? (I'm accessing the demo server also via localhost:80/443)

2021-04-13 09:34 UTC, TheMeaningfulEngineer commented on 07.Server-installation/01.Overview/docs.md
> +        |                                            +-------------------------+
A wait. It's the API gateway status interface

2021-04-13 09:35 UTC, TheMeaningfulEngineer commented on 07.Server-installation/01.Overview/docs.md
> +        |                                            +-------------------------+
Don't have the docs anymore rendered to check. But could you mention that in the demo docs if it isn't (I seem to have missed it)

2021-04-13 09:39 UTC, kjaskiewiczz commented on 07.Server-installation/03.Production-installation/docs.md
> +<!--AUTOMATION: execute=STORAGE_PROXY_DOMAIN_NAME="s3.docker.mender.io" -->
done; since the review is ongoing I did the change in a separate commit; please take a look

2021-04-13 11:04 UTC, kjaskiewiczz commented on 07.Server-installation/01.Overview/docs.md
> +        |                                            +-------------------------+
I think we are not documenting the exported ports in the demo setup at all;
if we really need it could it be a follow-up task?

2021-04-13 11:19 UTC, TheMeaningfulEngineer commented on 07.Server-installation/01.Overview/docs.md
> +        |                                            +-------------------------+
Sure, no issues with that

2021-04-13 11:19 UTC, TheMeaningfulEngineer approved these changes

2021-04-13 11:29 UTC, merged