MEN-4476: Documentation for port forwardiing
mendersoftware/mender-docs pull request #1394
Opened 2021-04-13 12:03 UTC by alfrunes

Depends on  mendersoftware/mender-docs-site#312

2021-04-13 16:19 UTC, estenberg commented on 09.Add-ons/40.Port-Forward/docs.md
> +!!!!! <i class="fa fa-wrench"></i> [Mender troubleshoot](https://mender.io/plans/features?target=_blank) add on required.
I have not seen this i class tag before, is it intentional?

2021-04-13 16:20 UTC, estenberg commented on 09.Add-ons/40.Port-Forward/docs.md
> +The Mender troubleshoot add-on package includes the ability to forward TCP/UDP
Troubleshoot (capital T)

2021-04-13 16:21 UTC, estenberg commented on 09.Add-ons/40.Port-Forward/docs.md
> +traffic to a securely remote host on a device network utilizing the
"traffic securely to a remote device"

2021-04-13 16:21 UTC, estenberg commented on 09.Add-ons/40.Port-Forward/docs.md
> +<div class="notices tip"><p>
HTML tag?

2021-04-13 16:22 UTC, estenberg commented on 09.Add-ons/40.Port-Forward/docs.md
> +The `device-uuid` is obtained from the device list in the [Mender
'device-uuid' -> "Device ID"

2021-04-13 16:27 UTC, estenberg commented on 09.Add-ons/40.Port-Forward/docs.md
> +mender-cli port-forward 162f1b92-c0d5-4f5d-961d-30fd26932be6 tcp/8080:192.168.1.123:4443
Would split with variable for easy copy/paste, like in other places.

Also have the simplest and most common case (forward TCP to port on the device) first, followed by a more advanced case. E.g.

To forward port 8080 from your workstation to your device, obtain the Device ID from the Mender server and run the following:

DEVICE_ID=<COPY-FROM-DEVICES-UI>
mender-cli port-forward $DEVICE_ID 8080:4443

As a more advanced example, you can forward only local TCP traffic on 8080 via the device to a different remote destination service and port with the following:

DEVICE_ID=<COPY-FROM-DEVICES-UI>
mender-cli port-forward DEVICE_ID tcp/8080:192.168.1.123:4443

2021-04-13 16:29 UTC, estenberg commented on 09.Add-ons/40.Port-Forward/docs.md
> +# Requirements
Prerequisites, like for other tutorials (e.g. https://docs.mender.io/get-started/preparation/prepare-a-raspberry-pi-device)

2021-04-13 16:29 UTC, estenberg commented on 09.Add-ons/40.Port-Forward/docs.md
> +To enable port forwarding on your device, you will need to have both
Make it into a bullet list and add mender-cli, please see above link.

2021-04-13 16:30 UTC, estenberg commented on 09.Add-ons/40.Port-Forward/docs.md
> +<div class="notices tip"><p>
More below as well.

2021-04-13 16:30 UTC, estenberg commented on 09.Add-ons/90.Reference/docs.md
> +!!!!! <i class="fa fa-wrench"></i> [Mender troubleshoot](https://mender.io/plans/features?target=_blank) add on required.
HTML tag

2021-04-13 16:31 UTC, estenberg commented on 09.Add-ons/90.Reference/docs.md
> +!!!!! <i class="fa fa-wrench"></i> [Mender troubleshoot](https://mender.io/plans/features?target=_blank) add on required.
HTML tag

Troubleshoot (cap T), add-on *package*.

2021-04-13 16:31 UTC, estenberg commented on 09.Add-ons/90.Reference/docs.md
> +!!!!! <i class="fa fa-wrench"></i> [Mender troubleshoot](https://mender.io/plans/features?target=_blank) add on required.
HTML tag

Troubleshoot (cap T), add-on *package*.

2021-04-14 07:54 UTC, alfrunes commented on 09.Add-ons/40.Port-Forward/docs.md
> +!!!!! <i class="fa fa-wrench"></i> [Mender troubleshoot](https://mender.io/plans/features?target=_blank) add on required.
I tried putting my artistic hat on, creating an easily recognizable notice about add on requirements. The _italic_ HTML class simply puts a wrench icon at the beginning of the notice.
![image](https://user-images.githubusercontent.com/35835176/114674178-400f2b80-9d07-11eb-9ad2-a78b6fcb4960.png)

2021-04-14 11:28 UTC, alfrunes commented on 09.Add-ons/40.Port-Forward/docs.md
> +<div class="notices tip"><p>
Oops, I forgot to convert this to markdown.

2021-04-14 11:29 UTC, alfrunes commented on 09.Add-ons/40.Port-Forward/docs.md
> +mender-cli port-forward 162f1b92-c0d5-4f5d-961d-30fd26932be6 tcp/8080:192.168.1.123:4443
I created a new subsection with a range of examples (of increasing complexity) using `DEVICE_ID` env variable.

2021-04-14 15:04 UTC, TheMeaningfulEngineer commented on 09.Add-ons/40.Port-Forward/docs.md
> +channel already in use by Mender. Port forwarding allows you to troubleshoot
"already used by Mender" is somewhat ambiguous. Would `mender-connect` be better?

2021-04-14 21:03 UTC, estenberg commented on 09.Add-ons/40.Port-Forward/docs.md
> +* Install [mender-cli](../../09.Downloads/docs.md#mender-cli) on your machine.
"machine" -> "workstation"

That is what we call your laptop/local machine across the docs.

2021-04-14 21:03 UTC, estenberg commented on 09.Add-ons/40.Port-Forward/docs.md
> +# Prerequisites
Very nice now below! Easy to follow.

2021-04-14 21:04 UTC, estenberg commented on 09.Add-ons/40.Port-Forward/docs.md
> +Having the device setup, you can _port forward_ traffic from your local machine
workstation

2021-04-14 21:05 UTC, estenberg commented on 09.Add-ons/40.Port-Forward/docs.md
> +Having the device setup, you can _port forward_ traffic from your local machine
Not sure if it makes a difference, but italic is done with *dots* instead of _underline_ other places.

2021-04-14 21:06 UTC, estenberg commented on 09.Add-ons/40.Port-Forward/docs.md
> +! To use the `mender-cli port-forward` command you need to authenticate with the
"To use" -> "Before using"

2021-04-14 21:07 UTC, estenberg commented on 09.Add-ons/40.Port-Forward/docs.md
> +### Examples
Great!

2021-04-14 21:10 UTC, estenberg commented on 09.Add-ons/40.Port-Forward/docs.md
> +!!!!! <i class="fa fa-wrench"></i> [Mender troubleshoot](https://mender.io/plans/features?target=_blank) add on required.
It looks great but in order to not confuse users we need to make sure it's consistent. :)
Also, a wrench to me feels more like a "Setting", not a requirement/dependency?

I would consult with our VP of UX, @michaelatmender :)

2021-04-14 21:10 UTC, estenberg commented on 09.Add-ons/40.Port-Forward/docs.md
> +mender-cli port-forward 162f1b92-c0d5-4f5d-961d-30fd26932be6 tcp/8080:192.168.1.123:4443
...and it is very good! thank you.

2021-04-15 07:54 UTC, michaelatmender commented on 09.Add-ons/40.Port-Forward/docs.md
> +!!!!! <i class="fa fa-wrench"></i> [Mender troubleshoot](https://mender.io/plans/features?target=_blank) add on required.
I agree that it more suggests something like 'settings'. It works well without the icon - using the Mender brand colored 'notice' markdown is nice

2021-04-15 07:58 UTC, michaelatmender commented on 09.Add-ons/90.Reference/docs.md
> +!!!!! <i class="fa fa-wrench"></i> [Mender troubleshoot](https://mender.io/plans/features?target=_blank) add on required.
@estenberg I would actually suggest not to use 'package'. On the website we are just referring to add-ons (we found when writing website text things got messy with add-on _package_/_packages_/_features_ and other variations). Simplest to just call them **add-ons**.

2021-04-15 08:34 UTC, alfrunes commented on 09.Add-ons/40.Port-Forward/docs.md
> +channel already in use by Mender. Port forwarding allows you to troubleshoot
*changed to `mender-connect`*

2021-04-15 08:41 UTC, michaelatmender requested changes
Just a few adjustments to markdown and text formatting

2021-04-15 08:41 UTC, michaelatmender commented on 09.Add-ons/40.Port-Forward/docs.md
> +# Port forwarding
Watch the heading levels - # is H1, which is already used by the page title.
So this should be ##

2021-04-15 08:41 UTC, michaelatmender commented on 09.Add-ons/40.Port-Forward/docs.md
> +# Prerequisites
change # to  ##

2021-04-15 08:41 UTC, michaelatmender commented on 09.Add-ons/90.Reference/docs.md
> +# mender-connect
Change # to ##

2021-04-15 08:41 UTC, michaelatmender commented on 09.Add-ons/40.Port-Forward/docs.md
> +# Further reading
Change # to ##

2021-04-15 08:41 UTC, michaelatmender commented on 09.Add-ons/90.Reference/docs.md
> +!!!!! [Mender Troubleshoot](https://mender.io/plans/features?target=_blank) add on required.
"add on" should be "add-on" everywhere

2021-04-15 08:43 UTC, alfrunes commented on 09.Add-ons/40.Port-Forward/docs.md
> +!!!!! <i class="fa fa-wrench"></i> [Mender troubleshoot](https://mender.io/plans/features?target=_blank) add on required.
We should probably create some macros for stuff like this, but I didn't find a way to do this without involving [mender-docs-site](https://github.com/mendersoftware/mender-docs-site), so I resorted to copy-paste for now.

> Also, a wrench to me feels more like a "Setting", not a requirement/dependency?

Now that you mention it, it sounds more like a "Configure" icon to me. I removed the icon from this notice.

2021-04-15 08:58 UTC, michaelatmender approved these changes
Thanks!

2021-04-15 09:06 UTC, merlin-northern reviewed
I only took a look at `Reference: mender-connect` section, since so many people already reviewed.

2021-04-15 09:06 UTC, merlin-northern commented on 09.Add-ons/90.Reference/docs.md
> +{
`ClientProtocol` is missing, is that on purpose?

2021-04-15 09:08 UTC, alfrunes commented on 09.Add-ons/90.Reference/docs.md
> +{
I initially had it in, but I removed it as it's currently unused.

2021-04-15 20:36 UTC, estenberg commented on 09.Add-ons/90.Reference/docs.md
> +!!!!! <i class="fa fa-wrench"></i> [Mender troubleshoot](https://mender.io/plans/features?target=_blank) add on required.
OK! Just to be clear, I used Troubleshoot as an add on *package*, while Remote terminal is an *add on* inside it.

But we can call it "Troubleshoot add ons" as well, if that is what we used on the website? Consistency is the most important :)

2021-04-15 20:38 UTC, estenberg approved these changes
All good.

Just need to hear from @michaelatmender if we should *not* use "Troubleshoot add on package", rather "Troubleshoot add ons". :)

2021-04-16 07:31 UTC, michaelatmender commented on 09.Add-ons/90.Reference/docs.md
> +!!!!! <i class="fa fa-wrench"></i> [Mender troubleshoot](https://mender.io/plans/features?target=_blank) add on required.
@estenberg maybe we need a separate discussion to align around taxonomy?
I consider Remote Terminal a feature of the Troubleshoot add-on. I assume we have a few days now to decide, so maybe we can discuss and adjust docs+website before release?

2021-04-19 13:30 UTC, merged