Server-installation/Upgrading - info about moving to traefik and incompatible clients
mendersoftware/mender-docs pull request #1395
Opened 2021-04-13 14:02 UTC by kjaskiewiczz

2021-04-13 16:35 UTC, estenberg requested changes
Small tweaks.

2021-04-13 16:35 UTC, estenberg commented on 07.Server-installation/07.Upgrading/docs.md
> +In the Mender 2.7 there is no separate service acting as a Storage Proxy.
In Mender 2.7 (no the)

2021-04-13 16:35 UTC, estenberg commented on 07.Server-installation/07.Upgrading/docs.md
> +Instead, Mender 2.7 uses API Gateway based on traefik to serve both backend endpoints and artifacts downloads.
"uses an API Gateway"

2021-04-13 16:35 UTC, estenberg commented on 07.Server-installation/07.Upgrading/docs.md
> +In the Mender 2.7 there is no separate service acting as a Storage Proxy.
Perhaps call this out more explicitly? E.g.

**Upgrading to Mender 2.7 or newer:** If you are upgrading from Mender 2.6 or older to Mender 2.7 or newer please follow this section.

2021-04-14 09:16 UTC, kjaskiewiczz commented on 07.Server-installation/07.Upgrading/docs.md
> +Instead, Mender 2.7 uses API Gateway based on traefik to serve both backend endpoints and artifacts downloads.
fixed

2021-04-14 09:17 UTC, kjaskiewiczz commented on 07.Server-installation/07.Upgrading/docs.md
> +In the Mender 2.7 there is no separate service acting as a Storage Proxy.
rephrased; please take a look

2021-04-14 11:17 UTC, mchalski approved these changes

2021-04-14 21:12 UTC, estenberg requested changes
All good except one important detail. :)

2021-04-14 21:12 UTC, estenberg commented on 07.Server-installation/07.Upgrading/docs.md
> +# Upgrading from Mander 2.6 or older
Mander -> Mender

2021-04-15 09:19 UTC, closed without merging

2021-04-15 09:19 UTC, mchalski commented
superseded by https://github.com/mendersoftware/mender-docs/pull/1399

2021-04-15 09:20 UTC, mchalski commented on 07.Server-installation/07.Upgrading/docs.md
> +# Upgrading from Mander 2.6 or older
@estenberg I'm taking over for this final fix because KJ is off - please check it out at https://github.com/mendersoftware/mender-docs/pull/1399.
(I had to copy the PR to my own fork, closing this one then.)