Docs exec testing: pass as soon as containers run.
mendersoftware/mender-docs pull request #1407
Opened 2021-04-17 06:14 UTC by merlin-northern

ChangeLog:none
Signed-off-by: Peter Grzybowski <peter@northern.tech>

2021-04-19 07:25 UTC, lluiscampos requested changes
Great initiative, thank you!

One request: to please define the magic numbers at the beginning of the files for easier maintenance in the future. What do you think?

2021-04-19 07:25 UTC, lluiscampos commented on 07.Server-installation/03.Production-installation/docs.md
> +<!--AUTOMATION: execute=export EXPECTED_COUNT=14 -->
Once we are reworking the test... please let's move these magic numbers to explicit variables at the beginning of the file. Something like `EXPECTED_COUNT_ENTERPRISE` and `EXPECTED_COUNT_OPENSOURCE` will be much better. I suggest we do the same in `01.Upgrading-from-OS-to-Enterprise` file, even though there we would only use one of them (enterprise)

2021-04-19 07:25 UTC, lluiscampos commented on 07.Server-installation/03.Production-installation/docs.md
> +<!--AUTOMATION: execute=function CONTAINERS_COUNT_TEST() { local n; [ "${EXPECTED_COUNT}" == "" ] && return 1; for ((n=0;n<${MAX_INTERATIONS:-11};n++)); do count=$(docker container ls -f "status=runn
I don't think the variables here should have defaults as we should expect all to have been defined
```suggestion
<!--AUTOMATION: execute=function CONTAINERS_COUNT_TEST() { local n; [ "${EXPECTED_COUNT}" == "" ] && return 1; for ((n=0;n<${MAX_INTERATIONS};n++)); do count=$(docker container ls -f "status=running" --format 'table {{.Status}}\t{{.Names}}' | grep ^Up | grep -c menderproduction); [ ${count} -eq ${EXPECTED_COUNT} ] && break; sleep ${SLEEP_INTERVAL}; done; [ ${count} -eq ${EXPECTED_COUNT} ] || { echo "some containers are not 'Up'; ${count}/${EXPECTED_COUNT} running." && docker ps && ./run images && ./run logs && exit 1; }; } -->
```

I would also suggest (weak suggestion) to remove the `[ "${EXPECTED_COUNT}" == "" ] && return 1` check, what is the purpose of that?

2021-04-22 08:38 UTC, merlin-northern commented on 07.Server-installation/03.Production-installation/docs.md
> +<!--AUTOMATION: execute=function CONTAINERS_COUNT_TEST() { local n; [ "${EXPECTED_COUNT}" == "" ] && return 1; for ((n=0;n<${MAX_INTERATIONS:-11};n++)); do count=$(docker container ls -f "status=runn
fixed!

> I would also suggest (weak suggestion) to remove the [ "${EXPECTED_COUNT}" == "" ] && return 1 check, what is the purpose of that?

to fail the test if the count is not set? I can remove, no worries, it made sense to me to have it.

2021-04-22 08:38 UTC, merlin-northern commented on 07.Server-installation/03.Production-installation/docs.md
> +<!--AUTOMATION: execute=export EXPECTED_COUNT=14 -->
sure.
moved and renamed, also renamed the function name to indicate the ENT/OS test scenario.

2021-04-22 09:00 UTC, lluiscampos approved these changes

2021-04-26 07:25 UTC, merged