MEN-4557: Documentation for Update Control configuration options
mendersoftware/mender-docs pull request #1434
Opened 2021-04-21 08:25 UTC by alfrunes

2021-04-21 08:41 UTC, lluiscampos commented
Thinking out loud: should we put this into a feature branch for now? These days we expect small docs fixes here and there that we want to release to `hosted` branch, but documenting a not yet released feature like this PR will prevent us to do simple merges.

I know is a headache to maintain a feature branch in this repo, but we could at least keep it on a feature branch for one week or something.

2021-04-21 09:04 UTC, kacf requested changes
> Thinking out loud: should we put this into a feature branch for now?

Yes, please do. Most tickets have this in their criteria, but looks like I forgot it in this ticket. I have added it now.

2021-04-21 09:04 UTC, kacf commented on 03.Client-installation/06.Configuration-file/50.Configuration-options/docs.md
> +#### UpdateControlMapBootExpireTimeSeconds
Naming, see above.

2021-04-21 09:04 UTC, kacf commented on 03.Client-installation/06.Configuration-file/50.Configuration-options/docs.md
> +value provides an upper bound on the update control map [expire time](#UpdateControlMapExipreTimeSeconds) after
Same typo.

2021-04-22 05:54 UTC, kacf approved these changes
Is the sentence below a bit weird? Fix if you agree, if not then go ahead!

2021-04-22 05:54 UTC, kacf commented on 03.Client-installation/06.Configuration-file/50.Configuration-options/docs.md
> +the update control map to enter the expired state. _Defaults to
Isn't this sentence a bit weird? Maybe "...to refresh the update control map **before it enters** the expired state."

2021-04-22 17:31 UTC, merged