MEN-4256: Mender-convert no longer installs the client by default
mendersoftware/mender-docs pull request #1449
Opened 2021-05-03 08:51 UTC by oleorhagen

Changelog: None
Signed-off-by: Ole Petter <ole.orhagen@northern.tech>

2021-05-03 13:34 UTC, lluiscampos approved these changes

2021-05-03 13:36 UTC, lluiscampos requested changes
Missing: to add the new variable in https://docs.mender.io/system-updates-debian-family/variables#mender_client_version

2021-05-03 13:42 UTC, oleorhagen commented
> Missing: to add the new variable in https://docs.mender.io/system-updates-debian-family/variables#mender_client_version

Oh yes, good catch! I didn't know we documented these

2021-05-03 13:53 UTC, lluiscampos approved these changes
See comment below, though.

2021-05-03 13:53 UTC, lluiscampos commented on 04.System-updates-Debian-family/99.Variables/docs.md
> +> Value: y (default)
```suggestion
> Value: y(default)/n
```

See the syntax in, for example, `MENDER_ADDON_CONNECT_INSTALL`

2021-05-04 03:52 UTC, oleorhagen commented on 04.System-updates-Debian-family/99.Variables/docs.md
> +> Value: y (default)
This is a bit all over the place though:

```
#### `MENDER_DATA_PART_GROWFS`

> Values: y(default)/n

Enable/Disable automatically growing the filesystem to fill the physical storage device.
```

```
#### `MENDER_ADDON_CONFIGURE_INSTALL`

> Value: y/n(default)

Install the Mender Configure add-on.

```
```
#### `MENDER_BOOT_PART_SIZE_MB`

> Value: 40 (default)

The size of the boot partition.

``` (with air, like most of them have)

To be honest, it's the `ADDON` values standing out as the outliers

2021-05-04 09:48 UTC, lluiscampos commented on 04.System-updates-Debian-family/99.Variables/docs.md
> +> Value: y (default)
They all look good to me.

Criteria seems to be: we use `/` to describe legal values with no air, adding `(default)` on the default one, and we have air on the "any-string" kind of config.

2021-05-04 11:39 UTC, lluiscampos approved these changes

2021-05-06 15:12 UTC, merged