QA-251: Added AUTOMATION tests to Mutual TLS authentication snippets.
mendersoftware/mender-docs pull request #1451
Opened 2021-05-07 13:16 UTC by NilsOlavKJohansen

Changelog: Small changes to the snippets that are used in the Mutual TLS authentication.

Signed-off-by: Nils Olav Kvelvane Johansen <nils.olav@northern.tech>

# External Contributor Checklist

🚨 Please review the [guidelines for contributing](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md) to this repository.

- [ ] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.

### Description

Please describe your pull request.

Thank you!

2021-05-07 13:17 UTC, NilsOlavKJohansen commented
Two things i was wondering about

1. Should i add this line since the mtls is only for enterprise users? `<!-- AUTOMATION: execute=if [ "$TEST_ENTERPRISE" != 1 ]; then echo "TEST_ENTERPRISE must be set to 1!"; exit 1; fi -->`

2. At the moment, only the test checks if the snippet starts a mender mtls ambassadors. It does not test what is actually happening in the container. Should I add one or more tests to check that the mtls ambassador is working as expected?

2021-05-10 14:06 UTC, lluiscampos requested changes
Looking good overall, you figured it out.

See my comments below

2021-05-10 14:06 UTC, lluiscampos commented on 08.Server-integration/03.Mutual-TLS-authentication/docs.md
> +!!! for an overview of all Mender plans and features.
Changed by mistake?

2021-05-10 14:06 UTC, lluiscampos commented on 08.Server-integration/03.Mutual-TLS-authentication/docs.md
> +<!-- AUTOMATION: execute=function cleanup() { if [ `docker ps | grep mender | grep mtls | sed 's/ .*//'` ]; then docker stop `docker ps | grep mender | grep mtls | sed 's/ .*//'`; fi }  -->
If we know the name of the container, can't we just grep for that exact name? I think `grep mender | grep mtls` is less robust.

2021-05-10 14:06 UTC, lluiscampos commented on 08.Server-integration/03.Mutual-TLS-authentication/docs.md
> +<!-- AUTOMATION: execute=BACKEND=https://hosted.mender.io -->
This should be something like:
```suggestion
<!-- AUTOMATION: execute=USER=$HM_TESTS_USER -->
<!-- AUTOMATION: execute=PASSWORD=$HM_TESTS_PASSWORD -->
<!-- AUTOMATION: execute=BACKEND=https://hosted.mender.io -->
```

So that I then set the corresponding CI ENV variables with the secrets.

2021-05-10 14:06 UTC, lluiscampos commented on 08.Server-integration/03.Mutual-TLS-authentication/docs.md
> +<!--AUTOMATION: test=sleep 1 && test "$(docker ps | grep mender | grep mtls | grep up -c -i)" = 1  || ( echo "The mTLS ambassador container is not 'Up'" && exit 1 ); -->
Maybe we should add some retries to this in a for loop, in case it takes longer than 1 second. We have to avoid tests that are time sensitive.

2021-05-10 14:06 UTC, lluiscampos commented on 08.Server-integration/03.Mutual-TLS-authentication/docs.md
>  Then copy the modified file back into the disk image:
Changed my mistake?

2021-05-11 07:18 UTC, NilsOlavKJohansen commented on 08.Server-integration/03.Mutual-TLS-authentication/docs.md
> +<!--AUTOMATION: test=sleep 1 && test "$(docker ps | grep mender | grep mtls | grep up -c -i)" = 1  || ( echo "The mTLS ambassador container is not 'Up'" && exit 1 ); -->
Ah, I did not think of that! I give it a few retries.

2021-05-11 07:21 UTC, NilsOlavKJohansen commented on 08.Server-integration/03.Mutual-TLS-authentication/docs.md
>  Then copy the modified file back into the disk image:
Yea

2021-05-11 12:11 UTC, NilsOlavKJohansen commented on 08.Server-integration/03.Mutual-TLS-authentication/docs.md
> +<!-- AUTOMATION: execute=BACKEND=https://hosted.mender.io -->
:+1:

2021-06-28 12:13 UTC, lluiscampos commented
Re-submitted at https://github.com/mendersoftware/mender-docs/pull/1483

2021-06-28 12:13 UTC, closed without merging