MEN-4505: Add the `ShellArguments` mender-connect config docs
mendersoftware/mender-docs pull request #1472
Opened 2021-06-11 08:17 UTC by oleorhagen

Changelog: None
Signed-off-by: Ole Petter <ole.orhagen@northern.tech>

2021-06-15 07:22 UTC, merlin-northern commented on 09.Add-ons/90.Reference/docs.md
> +* `ShellArguments`: The command line arguments passed to the shell when spawned.
are they optional? (perhaps it is worth mentioning)

2021-06-15 07:22 UTC, merlin-northern approved these changes
one comment, looks good.

2021-06-15 07:27 UTC, merlin-northern commented on 09.Add-ons/90.Reference/docs.md
> +* `ShellArguments`: The command line arguments passed to the shell when spawned.
and one more thing: the code says "[Defaults to '--login'](https://github.com/mendersoftware/mender-connect/pull/33/files#diff-fe44f09c4d5977b5f5eaea29170b6a0748819c9d02271746a20d81a5f3efca17R135-R136)" we have to mention that in the docs.

2021-06-15 07:31 UTC, merlin-northern requested changes

2021-06-15 07:31 UTC, merlin-northern commented on 09.Add-ons/90.Reference/docs.md
> +  "ShellArguments": "--login",
wait, something I do not understand looking at the code it is an array, right?

2021-06-15 07:31 UTC, oleorhagen commented on 09.Add-ons/90.Reference/docs.md
> +  "ShellArguments": "--login",
Good eye!

2021-06-15 07:32 UTC, oleorhagen commented on 09.Add-ons/90.Reference/docs.md
> +* `ShellArguments`: The command line arguments passed to the shell when spawned.
I figured, since the others didn't mention the defaults, and the defaults are all listed above in the example configuration, it was not needed, but up to you. Which do you prefer?

2021-06-15 15:28 UTC, merlin-northern commented on 09.Add-ons/90.Reference/docs.md
> +* `ShellArguments`: The command line arguments passed to the shell when spawned.
I would prefer to state explicitly that there is a default value. I am not super adamant about it, but thats what I would prefer.

2021-06-16 06:21 UTC, oleorhagen commented on 09.Add-ons/90.Reference/docs.md
> +* `ShellArguments`: The command line arguments passed to the shell when spawned.
@merlin-northern fixed

2021-06-16 06:46 UTC, merlin-northern approved these changes
lgtm

2021-06-16 06:47 UTC, merged