MEN-4561: Customize the update process with Synchronized updates
mendersoftware/mender-docs pull request #1473
Opened 2021-06-14 04:29 UTC by tranchitella

2021-06-14 07:01 UTC, oleorhagen approved these changes
Nice, left some comments for thought, feel free to ignore if you disagree, most of them are suggestions/nits. Only a couple of points which needs attention.

2021-06-14 07:01 UTC, oleorhagen commented on 02.Overview/10.Customize-the-update-process/docs.md
> +be active by default unless overridden by a deployment's update control map with a higher priority.
Suggestion:
unless a deployment's update control map overrides it with a map with a higher priority.

2021-06-14 07:01 UTC, oleorhagen commented on 02.Overview/10.Customize-the-update-process/docs.md
> +For more information about the different update control map's settings, please refer to the
I think we could get away with:
the different update control map settings

2021-06-14 07:19 UTC, tranchitella commented on 02.Overview/10.Customize-the-update-process/docs.md
> +an update control map, which can control the update process considering **external conditions**,
It sounds good to me, to be honest.

2021-06-14 07:20 UTC, oleorhagen commented on 02.Overview/10.Customize-the-update-process/docs.md
> +an update control map, which can control the update process considering **external conditions**,
Then go with it :)

2021-06-14 07:29 UTC, kacf reviewed
Maybe @estenberg have some comments too, especially regarding my last comment.

2021-06-14 07:29 UTC, kacf commented on 02.Overview/10.Customize-the-update-process/docs.md
> +eventually including input from the user.
I think we might need a slightly softer introduction. I think that the sentence is difficult to understand if you don't know what an Update Control map is. How about starting with "*When creating a software deployment, it is possible to control the progress of the update. It's possible to tell the Mender client to wait at certain points in the deployment, and then either continue or roll back from that point at some later time. This is done by specifying an update control map, which can...*"

2021-06-14 07:29 UTC, kacf commented on 02.Overview/10.Customize-the-update-process/docs.md
> +machine and can optionally have the priority defined as a positive integer value. The default
I would omit the priority altogether. This is only important if you mix the backend and D-Bus approaches, at which point you're already very deep into this feature. So I think it's enough that this property is listed in the D-Bus API reference.

2021-06-14 07:29 UTC, kacf commented on 02.Overview/10.Customize-the-update-process/docs.md
> +## Synchronized updates
I think the two approaches for using update control, D-Bus and backend-based, have very different audiences, and we should not treat them in the same section. I would split this up, perhaps handle the server based variant first (since it is easier to grasp), and the D-Bus information under a new header. The fact that they are based on the same underlying mechanism is more of an implementation detail, and not normally how you would approach the subject, I think.

You may have to duplicate some things then, but I think that's alright.

2021-06-14 07:56 UTC, tranchitella commented on 02.Overview/10.Customize-the-update-process/docs.md
> +## Synchronized updates
@kacf two sections in the same page, right?

2021-06-14 08:46 UTC, kacf commented on 02.Overview/10.Customize-the-update-process/docs.md
> +## Synchronized updates
Long term I think it would be better to have a separate page, but I can't find a good place for it in our current structure. So yes, for now I think we can use the same page.

2021-06-14 09:41 UTC, tranchitella commented on 02.Overview/10.Customize-the-update-process/docs.md
> +## Synchronized updates
Done: https://github.com/mendersoftware/mender-docs/pull/1473/commits/d8692b195e61e9e5720aa31717af3ffa96fdb6ce

2021-06-14 12:07 UTC, lluiscampos commented on 02.Overview/10.Customize-the-update-process/docs.md
> +as failed by updating the update control map of the Mender client.
Should `Update Control Map` be capitalized or not? There is one iteration above with `Update Control Map` and others here and below with `update control map`.

2021-06-14 12:07 UTC, lluiscampos commented on 02.Overview/10.Customize-the-update-process/docs.md
> +be active by default unless a deployment's update control map overrides it.
This is not really trivial, as to do that you need an application in the device constantly refreshing the map into the Mender client.

While it is a valid use case, the phrasing here seems to be that you can set a default map like in a config file or somewhere *static* and let it be. It is not the case so I would either remove the paragraph or be more explicit.

2021-06-14 12:12 UTC, tranchitella commented on 02.Overview/10.Customize-the-update-process/docs.md
> +as failed by updating the update control map of the Mender client.
No idea, @oleorhagen asked to capitalize the first occurrence. What's our policy?

2021-06-14 12:13 UTC, tranchitella commented on 02.Overview/10.Customize-the-update-process/docs.md
> +be active by default unless a deployment's update control map overrides it.
@lluiscampos what do you mean with refreshing the map? should it be done every N seconds/minutes, or after each Mender client restart, or...?

2021-06-14 12:15 UTC, lluiscampos commented on 02.Overview/10.Customize-the-update-process/docs.md
> +be active by default unless a deployment's update control map overrides it.
Once you set a map via D-Bus you get an expire time (in seconds). The application needs to refresh it (or send a new one) before it expires, or the client will disregard this map whenever the next update arrives (or within an update in progress, for all that matters).

2021-06-14 12:25 UTC, tranchitella commented on 02.Overview/10.Customize-the-update-process/docs.md
> +be active by default unless a deployment's update control map overrides it.
Let's give it a try: https://github.com/mendersoftware/mender-docs/pull/1473/commits/3471ed4318bd302b1c7eae5ff205c2a65e474cb7

2021-06-14 12:25 UTC, tranchitella commented on 02.Overview/10.Customize-the-update-process/docs.md
> +as failed by updating the update control map of the Mender client.
Let's capitalize it everywhere: https://github.com/mendersoftware/mender-docs/pull/1473/commits/3471ed4318bd302b1c7eae5ff205c2a65e474cb7

2021-06-14 18:10 UTC, estenberg requested changes
A few minor tweaks to simplify. I suppose the "Use the Device-side API" is coming later.

2021-06-14 18:10 UTC, estenberg commented on 02.Overview/10.Customize-the-update-process/docs.md
> +When creating a software deployment, it is possible to control the update progress.
"..update progress from an external service by calling Mender APIs."

2021-06-14 18:10 UTC, estenberg commented on 02.Overview/10.Customize-the-update-process/docs.md
> +Update control maps can specify an action for some transitions between the Mender client's
I think it's too detailed for overivew. Would move to (to-be-written "Use the Device-side API" tutorial).

2021-06-14 18:10 UTC, estenberg commented on 02.Overview/10.Customize-the-update-process/docs.md
> +Once *paused*, the update process can either be *resumed* or *canceled* and the whole deployment marked
I think it's too detailed for overivew. Would move to (to-be-written "Use the Device-side API" tutorial).

2021-06-14 18:10 UTC, estenberg commented on 02.Overview/10.Customize-the-update-process/docs.md
> +Applications running in the device can also set a default Update Control Map in the Mender
I think it's too detailed for overivew. Would move to (to-be-written "Use the Device-side API" tutorial).

2021-06-14 18:10 UTC, estenberg commented on 02.Overview/10.Customize-the-update-process/docs.md
> +### Synchronized updates using the Server-side API
Would replace everything from here to the end with a simple next step (API reference is quite "rough"):

## Further reading
"For more information on getting started with synchronized updates attributes, see [Use the Device-side API][404 LINK for now], or take a look at the [Device-side APIs](../../201.Device-side-API) and [Server-side API](../../200.Server-side-API) reference directly."

2021-06-14 19:04 UTC, tranchitella commented on 02.Overview/10.Customize-the-update-process/docs.md
> +### Synchronized updates using the Server-side API
Something like this, maybe? https://github.com/mendersoftware/mender-docs/pull/1473/commits/1bdd4470137bf5096a5c25eb689acbe4d69bf4fa

2021-06-15 07:03 UTC, lluiscampos commented on 02.Overview/10.Customize-the-update-process/01.How-to-use-the-update-control-map/docs.md
> +client, which will be active by default unless a deployment's Update Control Map overrides it.
Good try, but I think we are not completely there yet.

A deployment Update Control Map cannot override a D-Bus set map. All maps need a UUID and are therefore unique. (For the deployment, the UUID of the map would be the same as the deployment ID). What can happen is that the deployment map has a higher priority, then both are taking into consideration starting by the high priority one and then the other, but I think that the effect is that it will get "merged" in the attributes that are not present in both.

@kacf what is the right thing to say here?

2021-06-15 16:16 UTC, tranchitella commented on 02.Overview/10.Customize-the-update-process/01.How-to-use-the-update-control-map/docs.md
> +client, which will be active by default unless a deployment's Update Control Map overrides it.
Trying my best: https://github.com/mendersoftware/mender-docs/pull/1473/commits/9858c653fc6281e85688c175c259137083a3f020

2021-06-15 21:30 UTC, estenberg requested changes
@tranchitella I think you achieved the task at hand if you remove "10.Customize-the-update-process/01.How-to-use-the-update-control-map/docs.md" (and the link to it).

This tutorial does not fit within Overview, which is supposed to be only what & why (use cases), not how (tutorials).

Also note that https://tracker.mender.io/browse/MEN-4630 will cover what you started here, this is why I suggest you simply drop it for now. :)

2021-06-16 03:29 UTC, tranchitella commented
> @tranchitella I think you achieved the task at hand if you remove "10.Customize-the-update-process/01.How-to-use-the-update-control-map/docs.md" (and the link to it).
> 
> This tutorial does not fit within Overview, which is supposed to be only what & why (use cases), not how (tutorials).
> 
> Also note that https://tracker.mender.io/browse/MEN-4630 will cover what you started here, this is why I suggest you simply drop it for now. :)

Done: https://github.com/mendersoftware/mender-docs/pull/1473/commits/6f355cfb58c67e588e15370504d083447893e3e0
I added the text I wrote to the ticket, in case it can be useful in the future.

2021-06-16 08:12 UTC, lluiscampos commented on 02.Overview/10.Customize-the-update-process/01.How-to-use-the-update-control-map/docs.md
> +client, which will be active by default unless a deployment's Update Control Map overrides it.
Looks good to me :+1: Thanks

2021-06-16 11:11 UTC, kacf requested changes

2021-06-16 11:11 UTC, kacf commented on 02.Overview/10.Customize-the-update-process/docs.md
> +update process considering **external conditions**, eventually including input from the user.
With the focus on high level information, I think we should just leave out API altogether and focus on usability from the UI, in which case this paragraph can be significantly simplified. This is my suggestion:

> When creating a software deployment, it is possible to control the update from the Mender UI by telling the Mender client to wait at specific points in the deployment. The deployment can then either be continued or rolled back from this point at some later time. See the screenshot below for an example of what is possible.

@estenberg, do you agree?

2021-06-16 11:11 UTC, kacf commented on 02.Overview/10.Customize-the-update-process/docs.md
> +update.
With the picture below, I think this paragraph is redundant and we can remove it.

2021-06-16 11:11 UTC, kacf commented on 02.Overview/10.Customize-the-update-process/docs.md
> +* User presses *Start update* on the device to process the software update.
This is not a valid use case anymore after the device-side of things was removed from this section. However, I think we should have at least two use cases, so what about:

> Synchronized reboot: Devices can download whenever they have the opportunity, but all devices need to reboot during the maintenance window, at the same time.

2021-06-16 13:21 UTC, tranchitella commented on 02.Overview/10.Customize-the-update-process/01.How-to-use-the-update-control-map/docs.md
> +client, which will be active by default unless a deployment's Update Control Map overrides it.
This sentence was removed, as requested by @estenberg

2021-06-16 13:25 UTC, tranchitella commented on 02.Overview/10.Customize-the-update-process/docs.md
> +update process considering **external conditions**, eventually including input from the user.
https://github.com/mendersoftware/mender-docs/pull/1473/commits/3c7290ca9c253d8d88023efa662d5432526c9a22

2021-06-16 20:01 UTC, estenberg commented on 02.Overview/10.Customize-the-update-process/docs.md
> +update process considering **external conditions**, eventually including input from the user.
@tranchitella not sure if you wanted all these comments when you started asking for reviews :)

But now it omits the device-side use-cases, which leaves out a large part of the value (only talking about the UI).
I think we should have the device-side use cases there without getting into the API details. Will add some comments.

2021-06-16 20:07 UTC, estenberg requested changes

2021-06-16 20:07 UTC, estenberg commented on 02.Overview/10.Customize-the-update-process/docs.md
> +
* User presses *Start update* on the device to process the software update as an update is ready.
* Device is in use, by default no updates are started. Once ready, the user can press *Enable updates* on the device.

2021-06-16 20:07 UTC, estenberg commented on 02.Overview/10.Customize-the-update-process/docs.md
> +the Mender UI by telling the Mender client to wait at specific points in the
"..the Mender UI or an application running locally on the device.."

2021-06-17 03:25 UTC, tranchitella commented
@estenberg @kacf this is now a loop: you asked to add the device-side API, then remove it, now asking to add it again. :)
What shall we do? The content is there, more or less, can you please you two find an agreement? Based on that, I can finalize the PR.

2021-06-17 18:24 UTC, estenberg commented
@tranchitella I don't think there is a loop/conflict and that @kacf and me are saying the same thing:

* Do not cover (server or device) API details / howtos under Overview/ (so you removed that part and posted it in the ticket that will deal with it: https://tracker.mender.io/browse/MEN-4630)
* Do cover use cases (both server and device), without going into how they are implemented.

Basically Overview/ is about what & why, while the more detailed sections (e.g. Client installation) is more about how. Overview/ is used so users can see what can be done, and motivate them to move to the tutorials later.

Did it make sense? @kacf ?

2021-06-18 04:04 UTC, tranchitella commented
@estenberg @kacf @lluiscampos @oleorhagen I addressed the last two comments from Eystein, and squashed the commits. Can I kindly ask you a final round of comments?

2021-06-18 07:21 UTC, kacf commented
Yes, it looks good now! Sorry about all the back and forth.

One question for @estenberg, though it is more for the future: Should we have a dedicated page for how to use Update Control from the Mender UI? If we do, I don't think we have a ticket for this.

It's also possible it's self explanatory enough that we don't need it, but I suspect users will feel more reassured if they know exactly what the buttons do.

2021-06-18 07:21 UTC, kacf approved these changes

2021-06-18 10:29 UTC, tranchitella commented
@estenberg your call, now. :)

2021-06-19 03:16 UTC, merged