MEN-4680: update the server installation section using the Helm chart
mendersoftware/mender-docs pull request #1497
Opened 2021-07-13 08:09 UTC by tranchitella

We consider the Helm charts the only production-grade installation for
the Mender Server. The legacy installation with docker-compose is still
available but we remove all the references to "production" there.

Changelog: title

Signed-off-by: Fabio Tranchitella <fabio.tranchitella@northern.tech>

2021-07-13 08:30 UTC, Nicarim commented on 07.Server-installation/04.Production-installation-with-kubernetes/01.Kubernetes/docs.md
> +```bash
It would be a good practice to not recommend piping directly internet output to bash - We can just break it up to three steps
1. Download script
2. Verify it with for ex. SHA checksum / manual inspection
3. Run it manually.

2021-07-13 08:30 UTC, Nicarim commented on 07.Server-installation/04.Production-installation-with-kubernetes/01.Kubernetes/docs.md
> +If you don't have a ready-to-use Kubernetes cluster you can install [K3S](https://k3s.io/),
Well, given it says its production installation don't we want to recommend production grade solutions like EKS instead? (not saying k3s is not production grade, but given you talk about EC2 instances or DO instances, they already offer managed k8s). Just a thought rather than suggestion. It depends on what do we expect from the potential reader on following this tutorial - whether they should use it as our **recommended** way of doing production ready deployment, or just an idea of how to do it.

2021-07-13 08:30 UTC, Nicarim commented on 07.Server-installation/04.Production-installation-with-kubernetes/02.MongoDB/docs.md
> +!!! On the Debian family of distributions you can install `pwgen` with `apt-get install pwgen`.
I'd also add RPM based snippet - if someone runs on EC2 there is high chance they use amazon linux 2

2021-07-13 08:30 UTC, Nicarim commented on 07.Server-installation/04.Production-installation-with-kubernetes/04.Minio/docs.md
> +If you don't have an available AWS S3 bucket, you can install Minio in your cluster
Maybe we could inverse that sentence
```
If you already have S3 bucket which you can use, you can skip this section
```

2021-07-13 08:30 UTC, Nicarim commented on 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
> +For example, to expose thee Mender Server with an Ingress, run:
typo `thee` although thee also sounds good :D

2021-07-13 11:19 UTC, tranchitella commented on 07.Server-installation/04.Production-installation-with-kubernetes/01.Kubernetes/docs.md
> +If you don't have a ready-to-use Kubernetes cluster you can install [K3S](https://k3s.io/),
This is tricky, because we do not want to hand-hold the user, but at the same time we need to provide some copy-and-paste snippets to go through the tutorial. From my point of view, k3s is enough to get "something up and running" on a virtual machine. Do you have other suggestions to provide a simple-and-easy-to-install path for Kubernetes in this context?

2021-07-13 11:22 UTC, Nicarim commented on 07.Server-installation/04.Production-installation-with-kubernetes/01.Kubernetes/docs.md
> +If you don't have a ready-to-use Kubernetes cluster you can install [K3S](https://k3s.io/),
I was thinking in terms of providing ready-made script for running it in the cloud (that would require to provide it for different clouds), but then again I think for now this is really enough and we can revisit it if there will be demand for that. 

We can just mention that k3s is used for presentation purpose and we don't see it as our preferred way to do it

2021-07-13 11:34 UTC, tranchitella commented on 07.Server-installation/04.Production-installation-with-kubernetes/01.Kubernetes/docs.md
> +```bash
the problem is that those files can change upstream, making our documentation outdated quickly.

2021-07-13 11:48 UTC, Nicarim commented on 07.Server-installation/04.Production-installation-with-kubernetes/01.Kubernetes/docs.md
> +```bash
Let's just add a note above that we recommend first inspecting the script and then running the command.

2021-07-13 14:21 UTC, alfrunes commented on 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
> +```
This seems a little out of place, considering that you've gone with Letsencrypt and cert-manager in the preceding sections; why not continue this practice here?

2021-07-13 14:21 UTC, alfrunes commented on 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
> +```bash
This snippet is using environment variables from the preceding sections, including the optional minio section.
I think this is worth mentioning as a notice.

2021-07-13 15:17 UTC, tranchitella commented on 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
> +```
left-over, sorry

2021-07-14 06:47 UTC, alfrunes approved these changes

2021-07-14 07:52 UTC, mchalski commented on 07.Server-installation/03.Installation-with-docker-compose/01.Upgrading/docs.md
> +Recall from the [production installation](../docs.md) tutorial that our
I think this should also be just `installation`

2021-07-14 08:24 UTC, mchalski commented on 301.Troubleshoot/04.Mender-Server/docs.md
> +From the [production installation](../../07.Server-installation/03.Installation-with-docker-compose/docs.md) tutorial, we can recall
still a `[production installation]` reference

2021-07-14 08:28 UTC, mchalski commented on 07.Server-installation/03.Installation-with-docker-compose/03.Backup-and-restore/docs.md
> +As described in the [production installation](../docs.md) chapter,
`production installation` -> just installation?

2021-07-14 08:30 UTC, mchalski commented on 301.Troubleshoot/04.Mender-Server/docs.md
> +only applies when the Mender server is [installed for production](../../07.Server-installation/03.Installation-with-docker-compose/docs.md).
docker compose install is still called `production` here.

2021-07-14 08:41 UTC, mchalski commented on 07.Server-installation/03.Installation-with-docker-compose/03.Backup-and-restore/docs.md
> +As described in the [production installation](../docs.md) chapter,
production installation again

2021-07-14 08:42 UTC, mchalski commented on 07.Server-installation/03.Installation-with-docker-compose/docs.md
> +title: Installation with Docker Compose
maybe add a comment here that it's a hardened, more production-ready instance of a demo setup, but the only official production setup is the k8s one?

2021-07-14 08:43 UTC, mchalski commented on 301.Troubleshoot/04.Mender-Server/docs.md
> +From the [production installation](../../07.Server-installation/03.Installation-with-docker-compose/docs.md) tutorial, we can recall
production installation again

2021-07-14 09:12 UTC, mchalski commented on 301.Troubleshoot/04.Mender-Server/docs.md
> +only applies when the Mender server is [installed for production](../../07.Server-installation/03.Installation-with-docker-compose/docs.md).
installed for production?

2021-07-14 09:36 UTC, mchalski reviewed
The only issue I have is - in many places we still call the compose installation `production installation`. I pointed them out in case you missed them. The better wording is simply the general `installation` or `docker-compose installation`, applied in many places already, and mostly simple to fix. 

I won't push it though, because we also have to call the 'old production' setup somehow... One awkward section based on it's distinction from 'demo' is 301.Troubleshoot/04.Mender-Server:

```
The first part applies to all installations, while the section below on Production installations
only applies when the Mender server is [installed for production](../../07.Server-installation/03.Installation-with-docker-compose/docs.md).
```

An alternate wording could be sth like:
```
This applies to all docker-compose setups, both the demo setup and the [docker-compose installation](../../07.Server-installation/03.Installation-with-docker-compose/docs.md)
```

I also advised to add an extra section in the docker compose installation doc saying that it's 'a more production ready demo', but the only official production is via k8s. This removes all doubt IMO even if we accidentally call docker-compose install 'production' again.

other than that great job on the core of the documentation regarding k8s @tranchitella . I have no remarks here, and really, you can consider this an approve if you don't want more fuss with the details I mentioned.

2021-07-14 11:20 UTC, kjaskiewiczz requested changes

2021-07-14 11:20 UTC, kjaskiewiczz commented on 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
> +helm upgrade --install mender mender/mender --version master -f mender-master.yml
I think `helm upgrade --install mender mender/mender --version master -f mender-master.yml` will not work;
it should be `helm upgrade --install mender mender --version master -f mender-master.yml`

2021-07-14 11:20 UTC, kjaskiewiczz commented on 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
> +helm upgrade --install mender mender/mender --version master -f mender-master.yml
same as above (mender/mender -> mender)

2021-07-14 11:22 UTC, tranchitella commented on 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
> +helm upgrade --install mender mender/mender --version master -f mender-master.yml
@kjaskiewiczz uhm, interesting, it works fine here. What's the issue you are facing with the command? Can you post the output? `mender/mender` means `mender` helm chart from the `mender` helm repository, which you created with `helm repo`. One note: I actually tested with `2.7.0` instead of `master`, but I used `master` everywhere to make the autoversion happy.

2021-07-14 12:09 UTC, tranchitella commented on 07.Server-installation/03.Installation-with-docker-compose/docs.md
> +title: Installation with Docker Compose
I added a warning, good idea.

2021-07-14 12:09 UTC, tranchitella commented
Thanks @mchalski , I applied all the changes you suggested.

2021-07-14 12:28 UTC, kjaskiewiczz commented on 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
> +helm upgrade --install mender mender/mender --version master -f mender-master.yml
the output: `Error: failed to download "mender/mender" at version "master" (hint: running `helm repo update` may help)`
it works fine with mender instead of mender/mender

2021-07-14 12:30 UTC, tranchitella commented on 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
> +helm upgrade --install mender mender/mender --version master -f mender-master.yml
oh, that's because the `master` version of the Helm chart doesn't exist (yet). If you enter `mender` only you are probably using a local version you have. If you replace `master` with `2.7.0` should work fine.

2021-07-14 12:44 UTC, kjaskiewiczz approved these changes

2021-07-14 13:18 UTC, tranchitella commented
I published the master version:

```
$ helm search repo mender --versions
NAME         	CHART VERSION	APP VERSION	DESCRIPTION
mender/mender	master       	master     	Mender is a robust and secure way to update all...
mender/mender	2.7.0        	2.7.0      	Mender is a robust and secure way to update all...
mender/mender	2.6.0        	2.6.0      	Mender is a robust and secure way to update all...
mender/mender	2.5.0        	2.5.0      	Mender is a robust and secure way to update all...
```

2021-07-15 08:05 UTC, mchalski approved these changes
approving, btw `legacy production installation` is the phrase I was looking for myself!

2021-07-15 08:19 UTC, kacf approved these changes
I didn't go in depth, since many people already have, but looks good from what I can see.

I assume this will go to 3.0.x as well? If so, just ping me and I can take care of it, since I need to rerun the version update, and I only have those changes locally at the moment.

2021-07-15 08:20 UTC, merged