MEN-4818 Monitoring add-on: initial docs
mendersoftware/mender-docs pull request #1508
Opened 2021-07-20 10:31 UTC by merlin-northern

ChangeLog:title
Signed-off-by: Peter Grzybowski <peter@northern.tech>

2021-07-20 10:33 UTC, merlin-northern commented
@estenberg I could really use an early review here. if the direction is correct I will continue along these lines.

2021-07-20 11:40 UTC, estenberg requested changes
Nothing wrong with the direction, just try to keep it as simple as possible for the initial tutorial.
Also remember we need similar subsections like Remote Terminal, (Installation, Configuration) -- the latter you may perhaps cover the more advanced topics (subsystems, etc.).

2021-07-20 11:40 UTC, estenberg commented on 02.Overview/01.Introduction/docs.md
> +and alert with the Monitoring add-on.
Monitoring -> Monitor

2021-07-20 11:40 UTC, estenberg commented on 09.Add-ons/00.Overview/docs.md
> +`mender-connect`. Every add-on, with [Configure](../02.Configure/docs.md)
Would reword this, there are too many exceptions. E.g. "The Troubleshoot add-on package requires `mender-connect`"

Also Monitoring -> Monitor

2021-07-20 11:40 UTC, estenberg commented on 09.Add-ons/00.Overview/docs.md
> +| [Monitoring](../50.Monitoring/docs.md) | Monitor your devices and get alerts | Monitoring |
Monitor

2021-07-20 11:40 UTC, estenberg commented on 09.Add-ons/50.Monitoring/docs.md
> +title: Monitoring
Monitor

2021-07-20 11:40 UTC, estenberg commented on 09.Add-ons/50.Monitoring/docs.md
> +!!!!! The Mender Monitoring add-on package is required.
Monitor

2021-07-20 11:40 UTC, estenberg commented on 09.Add-ons/50.Monitoring/docs.md
> +The Mender Monitoring add-on gives the power to
Monitor

2021-07-20 11:40 UTC, estenberg commented on 09.Add-ons/50.Monitoring/docs.md
> +You do not need `mender-connect`
Would skip this.

2021-07-20 11:40 UTC, estenberg commented on 09.Add-ons/50.Monitoring/docs.md
> +The `mender-monitor` supports _monitoring subsystems_ which perform
Remove The

2021-07-20 11:40 UTC, estenberg commented on 09.Add-ons/50.Monitoring/docs.md
> +It consists of two parts: the API to the backend that allows
Move this text to the next section, or remove it.

Add 1-2 sentences about what's the point of this Monitor add-on. Why should I use it? What's the use cases / user value?

2021-07-20 11:40 UTC, estenberg commented on 09.Add-ons/50.Monitoring/docs.md
> +## Running and configuring
This is good information, but maybe a bit too advanced to cover this early? Could be covered in a separate "Architecture" sub-page or further down in the document I think.

Maybe rewrite this one to two examples:
* How do I ensure the systemd service "mender-client" is running?
* How do I check for a pattern "input device disconnected" in the kernel journal log?

2021-07-20 13:26 UTC, merlin-northern commented on 09.Add-ons/50.Monitoring/docs.md
> +You do not need `mender-connect`
wow -- sorry some unfinished thougts:)

2021-07-22 08:55 UTC, merlin-northern commented on 09.Add-ons/50.Monitoring/docs.md
> +## Running and configuring
moved to Architecture section and added examples section. with mender-connect check (if mender-client is not running we can't alert we do not have the JWT) and `Started Session [^ ]+ of user root` pattern in /var/log/messages (I could not find the exact example with the device in my logs)

2021-07-22 08:55 UTC, merlin-northern commented on 09.Add-ons/50.Monitoring/docs.md
> +It consists of two parts: the API to the backend that allows
yes, that was the idea behind the unfinished sentence. let me fix it.

2021-07-22 08:55 UTC, merlin-northern commented on 09.Add-ons/50.Monitoring/docs.md
> +The `mender-monitor` supports _monitoring subsystems_ which perform
fixed.

2021-07-22 08:56 UTC, merlin-northern commented on 09.Add-ons/50.Monitoring/docs.md
> +The Mender Monitoring add-on gives the power to
fixed

2021-07-22 08:56 UTC, merlin-northern commented on 09.Add-ons/50.Monitoring/docs.md
> +title: Monitoring
fixed

2021-07-22 08:56 UTC, merlin-northern commented on 09.Add-ons/00.Overview/docs.md
> +| [Monitoring](../50.Monitoring/docs.md) | Monitor your devices and get alerts | Monitoring |
fixed

2021-07-22 08:56 UTC, merlin-northern commented on 09.Add-ons/00.Overview/docs.md
> +`mender-connect`. Every add-on, with [Configure](../02.Configure/docs.md)
reworded, also added a column  to the table below.

2021-07-22 08:56 UTC, merlin-northern commented on 02.Overview/01.Introduction/docs.md
> +and alert with the Monitoring add-on.
fixed.

2021-07-22 15:51 UTC, estenberg requested changes
Minor adjustments / nicpicks for readability. I think you've covered the meat here.

2021-07-22 15:51 UTC, estenberg commented on 09.Add-ons/50.Monitoring/docs.md
> +within your fleet of devices. It allows you to configure and receive
allows you to configure alerts to be sent when certain

2021-07-22 15:51 UTC, estenberg commented on 09.Add-ons/50.Monitoring/docs.md
> +The Mender Monitor add-on gives you an insight to what happens
gives you instant visibility into issues with your device fleet

2021-07-22 15:51 UTC, estenberg commented on 09.Add-ons/50.Monitoring/docs.md
> +systemd service being an out-of-the-box monitoring daemon.
daemon, that runs on the devices.

2021-07-22 15:51 UTC, estenberg commented on 09.Add-ons/50.Monitoring/docs.md
> +### Running and configuring
How about installation? Is it covered separately (would make sense)? if so, we need a link here to how to install it first.

2021-07-22 15:51 UTC, estenberg commented on 09.Add-ons/50.Monitoring/docs.md
> +solution for the world of the IoT.
To save bandwidth and support edge processing, Monitor is a fully distributed solution, meaning that no data is sent from the device to the server *unless* an alert is triggered. Compared to classic approaches of sending all the data about all the nodes to the server all the time, this leads to massive bandwidth savings and allows instant local processing.

2021-07-22 15:51 UTC, estenberg commented on 09.Add-ons/50.Monitoring/docs.md
> +## Alerting
Move this as first section, before Architecture?

2021-07-22 15:51 UTC, estenberg commented on 09.Add-ons/50.Monitoring/docs.md
> +all users that have access to a device receive an email notification.
have access to the given device on the Mender server

2021-07-22 15:51 UTC, estenberg commented on 09.Add-ons/50.Monitoring/docs.md
> +### Daemon config defaults
Nice and should be covered, but maybe better in a separate doc subsection?

2021-07-22 19:25 UTC, merlin-northern commented on 09.Add-ons/50.Monitoring/docs.md
> +### Running and configuring
I think we have to wait with that until we have a clear solution on how we distribute it. (the yocto external flow task)

2021-07-22 19:31 UTC, merlin-northern commented on 09.Add-ons/50.Monitoring/docs.md
> +within your fleet of devices. It allows you to configure and receive
fixed

2021-07-22 19:32 UTC, merlin-northern commented on 09.Add-ons/50.Monitoring/docs.md
> +The Mender Monitor add-on gives you an insight to what happens
fixed

2021-07-22 19:32 UTC, merlin-northern commented on 09.Add-ons/50.Monitoring/docs.md
> +systemd service being an out-of-the-box monitoring daemon.
fixed

2021-07-22 19:32 UTC, merlin-northern commented on 09.Add-ons/50.Monitoring/docs.md
> +solution for the world of the IoT.
added

2021-07-22 19:32 UTC, merlin-northern commented on 09.Add-ons/50.Monitoring/docs.md
> +## Alerting
moved

2021-07-22 19:32 UTC, merlin-northern commented on 09.Add-ons/50.Monitoring/docs.md
> +all users that have access to a device receive an email notification.
right.

2021-07-22 19:32 UTC, merlin-northern commented on 09.Add-ons/50.Monitoring/docs.md
> +### Daemon config defaults
right! moved.

2021-07-23 12:45 UTC, estenberg requested changes
A few more nitpicks. :)

2021-07-23 12:45 UTC, estenberg commented on 09.Add-ons/50.Monitoring/30.Daemon-config/docs.md
> +The daemon that the `mender-monitor` service runs has certain
The `mender-monitor` daemon has default configurations set in `config/config.sh`.

Or did I misunderstand, is there a difference between the service and the daemon?

2021-07-23 12:45 UTC, estenberg commented on 09.Add-ons/50.Monitoring/30.Daemon-config/docs.md
> +title: Monitoring configuration defaults
Configuration

Also call the directory "30.Configuration" I think.

Even if there are other components to configure except the daemon, I would still keep them in this same document.

2021-07-23 12:45 UTC, estenberg commented on 09.Add-ons/50.Monitoring/docs.md
> +To save bandwidth and support edge processing, Monitor is a fully
Would add newline, so it's a separate paragraph.

2021-07-23 12:45 UTC, estenberg commented on 09.Add-ons/50.Monitoring/docs.md
> +You can mute the email notifications in the settings.
in the Mender server settings.

2021-07-23 12:45 UTC, estenberg commented on 09.Add-ons/50.Monitoring/docs.md
> +Keep in mind to log-rotate that file as needed.
Can we do this? It sounds a bit risky to have an unbounded log file. Or is this normally how log files behave (e.g. how do we do it with the Mender client?).

2021-07-23 12:45 UTC, estenberg commented on 09.Add-ons/50.Monitoring/docs.md
> +as well as an _OK_ when it is back online. In order to get this
"back online" -> "back up"

2021-07-23 12:45 UTC, estenberg commented on 09.Add-ons/50.Monitoring/docs.md
> +Let's get the alerts when a `Started Session c244 of user root`-like log
To alert on root sessions to the device, we check for the pattern `Started Session c244 of user root` in `/var/log/syslog`.

2021-07-23 12:45 UTC, estenberg commented on 09.Add-ons/50.Monitoring/docs.md
> +is something we do not know a priori.
What is c244, a regex pattern? If so, add a short note about this.

E.g. is something we do not know a priori, so we use the PCRE pattern `c244` to match INSERT-HERE.

2021-07-23 13:28 UTC, merlin-northern commented on 09.Add-ons/50.Monitoring/30.Daemon-config/docs.md
> +The daemon that the `mender-monitor` service runs has certain
technicaly there is. fixed.

2021-07-23 13:28 UTC, merlin-northern commented on 09.Add-ons/50.Monitoring/30.Daemon-config/docs.md
> +title: Monitoring configuration defaults
fixed

2021-07-23 13:28 UTC, merlin-northern commented on 09.Add-ons/50.Monitoring/docs.md
> +To save bandwidth and support edge processing, Monitor is a fully
added

2021-07-23 13:28 UTC, merlin-northern commented on 09.Add-ons/50.Monitoring/docs.md
> +You can mute the email notifications in the settings.
fixed

2021-07-23 13:28 UTC, merlin-northern commented on 09.Add-ons/50.Monitoring/docs.md
> +Keep in mind to log-rotate that file as needed.
my thoughts exactly, I think we should actually by default not to write to extra log-files. I will remove it and I created this task: https://tracker.mender.io/browse/MEN-4912

2021-07-23 13:28 UTC, merlin-northern commented on 09.Add-ons/50.Monitoring/docs.md
> +as well as an _OK_ when it is back online. In order to get this
fixed

2021-07-23 13:28 UTC, merlin-northern commented on 09.Add-ons/50.Monitoring/docs.md
> +Let's get the alerts when a `Started Session c244 of user root`-like log
rephrased

2021-07-23 13:28 UTC, merlin-northern commented on 09.Add-ons/50.Monitoring/docs.md
> +is something we do not know a priori.
no, it is a live log line from my rpi :) ok I will change it to a different log line.

2021-07-23 13:41 UTC, estenberg requested changes
If my suggestion is sane, I would change the example like this.
May be more relevant to catch root logins, in most cases it's probably OK to have other users log in.

2021-07-23 13:41 UTC, estenberg commented on 09.Add-ons/50.Monitoring/30.Configuration/docs.md
> +The `mender-monitor` daemon runs has certain
remove runs

2021-07-23 13:41 UTC, estenberg commented on 09.Add-ons/50.Monitoring/docs.md
> +To alert on new user sessions to the device, we can check for the pattern
"new root user sessions"

2021-07-23 13:41 UTC, estenberg commented on 09.Add-ons/50.Monitoring/docs.md
> +Naturally we want to be aware only of new occurrences and the number
Remove this sentence.

2021-07-23 13:41 UTC, estenberg commented on 09.Add-ons/50.Monitoring/docs.md
> + echo -e 'SERVICE_NAME="auth"\nLOG_PATTERN="Started User Manager for UID [0-9]"\nLOG_FILE="/var/log/syslog"' > /etc/mender-monitor/monitor.d/available/log_syslogrootsession.sh
"...for UID 0" (dont make it a pattern)

2021-07-23 13:41 UTC, estenberg commented on 09.Add-ons/50.Monitoring/docs.md
> +#### Has a user started a session?
Has root user started a session?

2021-07-23 13:41 UTC, estenberg commented on 09.Add-ons/50.Monitoring/docs.md
> +
!!! You can also do PCRE pattern matching for the UID to catch users other than root.

2021-07-23 14:32 UTC, merlin-northern commented on 09.Add-ons/50.Monitoring/docs.md
> +
added some beauty at the end of this sentence. fixed.

2021-07-23 14:32 UTC, merlin-northern commented on 09.Add-ons/50.Monitoring/docs.md
> +#### Has a user started a session?
ok

2021-07-23 14:32 UTC, merlin-northern commented on 09.Add-ons/50.Monitoring/docs.md
> + echo -e 'SERVICE_NAME="auth"\nLOG_PATTERN="Started User Manager for UID [0-9]"\nLOG_FILE="/var/log/syslog"' > /etc/mender-monitor/monitor.d/available/log_syslogrootsession.sh
ok but then we loose the whole glory of the regexes.

2021-07-23 14:33 UTC, merlin-northern commented on 09.Add-ons/50.Monitoring/docs.md
> +Naturally we want to be aware only of new occurrences and the number
removed

2021-07-23 14:33 UTC, merlin-northern commented on 09.Add-ons/50.Monitoring/docs.md
> +To alert on new user sessions to the device, we can check for the pattern
changed

2021-07-23 14:33 UTC, merlin-northern commented on 09.Add-ons/50.Monitoring/30.Configuration/docs.md
> +The `mender-monitor` daemon runs has certain
removed

2021-07-23 17:49 UTC, estenberg approved these changes

2021-07-23 17:53 UTC, merged