MEN-4840 Log Monitoring: update on regular expression logic.
mendersoftware/mender-docs pull request #1516
Opened 2021-08-04 10:41 UTC by merlin-northern

MEN-4840 Log Monitoring: update on regular expression logic.

ChangeLog:title
Signed-off-by: Peter Grzybowski <peter@northern.tech>

2021-08-09 06:48 UTC, estenberg requested changes

2021-08-09 06:48 UTC, estenberg commented on 09.Add-ons/50.Monitoring/docs.md
> +Please note, that the log monitoring subsystem uses `grep` command
Don't need comma after "Please note" here.

Otherwise this makes sense, it could have been formatted as a note with a shorter version too, e.g. "!!! Log monitoring relies on `grep -P` support for PCRE. If your device does not support this flag, it falls back to `-E` if available or plain `grep` if not.

2021-08-12 11:41 UTC, merlin-northern commented on 09.Add-ons/50.Monitoring/docs.md
> +Please note, that the log monitoring subsystem uses `grep` command
good idea! what I actually have done now, is I added part of your `!!!` snippet to the existing `!!!` snippet a bit higher. makes sense?

2021-08-12 11:43 UTC, estenberg approved these changes
:egg: sellent

2021-08-12 11:46 UTC, merged