MEN-4839 Monitor: describe the streaming logs pattern search.
mendersoftware/mender-docs pull request #1522
Opened 2021-08-12 13:29 UTC by merlin-northern

ChangeLog:title
Signed-off-by: Peter Grzybowski <peter@northern.tech>

2021-08-13 09:29 UTC, estenberg requested changes
Can we have a better, more realistic use case for stream monitoring using journalctl?
I have a hard time seeing why someone would like an alert once Mender gets accepted - that seems like normal operation.

Some Mender monitoring use cases that I think makes more sense:
* OTA Download "hangs": It has been downloading for more than 1 hour.
* Catch all Error messages from Mender

But there are likely other use cases that may make sense on the system or critical application level, e.g. the "Input device disconnected" use case mentioned a bit earlier. It should be in the journalctl -k output.

2021-08-13 09:29 UTC, estenberg commented on 09.Add-ons/50.Monitoring/docs.md
> +in details, we present three quick-start examples.
in "detail" (not details)

2021-08-13 09:29 UTC, estenberg commented on 09.Add-ons/50.Monitoring/docs.md
> +To this end you can use the log subsystem to look into the output of `journalctl -u mender-client`
"look into" -> "follow"? Or does it check it periodically rather? In either case, clarify (and my hope is we follow :).

2021-08-13 09:29 UTC, estenberg commented on 09.Add-ons/50.Monitoring/docs.md
> +!!! There is a special variant for a value of the `LOG_FILE` variable, if it begins
Would highlight this more, journalctl is widely used.

Add a separate section for this (#####) and call it something like Log stream monitoring, mention that this is the way to monitor output from journalctl.

2021-08-31 09:09 UTC, closed without merging

2021-08-31 09:10 UTC, lluiscampos commented
@merlin-northern After #1527, you need to launch again this PR targetting `master`.

2021-08-31 13:48 UTC, merlin-northern commented
> @merlin-northern After #1527, you need to launch again this PR targetting `master`.

yes, thank you for keeping track. but, you know, by editing the PR we could have just changed the target branch :)

2021-08-31 13:57 UTC, lluiscampos commented
I didn't close it! This was GitHub magic :mage:

2021-08-31 17:24 UTC, merlin-northern commented
> I didn't close it! This was GitHub magic 🧙

oh, sorry for blaming then, it says so above: `lluiscampos closed this 8 hours ago`
so before the target branch is deleted we should edit and re-target, right?

2021-09-01 08:27 UTC, lluiscampos commented
> oh, sorry for blaming then, it says so above: `lluiscampos closed this 8 hours ago`

No problem, I also blamed once a colleague for the very same reason... I think this specific behavior of GitHub is tricky: it closes automatically the PRs targeting branches that are deleted but sets the author of the "close" to whoever deleted the branch :shrug: 

> so before the target branch is deleted we should edit and re-target, right?

Yes. Probably a rebase on master too.