MEN-4948: Document the Mender monitor installation instructions
mendersoftware/mender-docs pull request #1531
Opened 2021-09-07 07:18 UTC by oleorhagen

Changelog: None
Signed-off-by: Ole Petter <ole.orhagen@northern.tech>

2021-09-07 09:22 UTC, lluiscampos commented on 05.System-updates-Yocto-Project/05.Customize-Mender/02.Mender-monitor/docs.md
> +!!! require a hosted-mender user login.
@eysteins Should we document here how to download the files for Mender Enterprise on-prem? In the case of `mender-binary-delta`, we have instructions for both flows in Mender Hub, see [here](https://hub.mender.io/t/robust-delta-update-rootfs/1144).

2021-09-07 09:30 UTC, oleorhagen commented on 05.System-updates-Yocto-Project/05.Customize-Mender/02.Mender-monitor/docs.md
> +    curl --fail -u $HOSTED_MENDER_EMAIL -O https://download.mender.io/content/hosted/mender-monitor/yocto/master/mender-monitor_1.0.0.tar.gz
Note: not the right link (untested)

2021-09-07 09:30 UTC, oleorhagen commented on 09.Downloads/docs.md
> +    curl --fail -u "$HOSTED_MENDER_EMAIL" -O https://download.mender.io/content/hosted/mender-monitor/debian/master/mender-monitor_master-1_all.deb
Note: Not the right link (untested)

2021-09-07 16:41 UTC, merlin-northern commented
@eysteins perhaps you should review -- as you usually do with the docs PRs

2021-09-07 16:42 UTC, merlin-northern commented on 05.System-updates-Yocto-Project/05.Customize-Mender/02.Mender-monitor/docs.md
> +title: Install the Mender monitor add-on
suggested change: "Mender monitor" -> "Mender _M_onitor"

2021-09-07 16:43 UTC, merlin-northern commented on 05.System-updates-Yocto-Project/05.Customize-Mender/02.Mender-monitor/docs.md
> +!!! Note: Mender monitor is a paid add-on of the Mender project, and does
suggested change: "paid" -> "_commercial_"

2021-09-07 16:44 UTC, merlin-northern commented on 05.System-updates-Yocto-Project/05.Customize-Mender/02.Mender-monitor/docs.md
> +!!! require a hosted-mender user login.
I am not sure, do we refer to hosted Mender as "hosted-mender"? (I have not checked, but I think I see it for the first time)

2021-09-07 16:44 UTC, merlin-northern commented on 05.System-updates-Yocto-Project/05.Customize-Mender/02.Mender-monitor/docs.md
> +Mender username and password:
see above, "hosted Mender" looks better.

2021-09-07 16:45 UTC, merlin-northern commented on 05.System-updates-Yocto-Project/05.Customize-Mender/02.Mender-monitor/docs.md
> +Mender username and password:
to "save the tarball using [..] username and password" sounds strange

2021-09-07 16:46 UTC, merlin-northern commented on 05.System-updates-Yocto-Project/05.Customize-Mender/02.Mender-monitor/docs.md
> +
do we need this empty line?

2021-09-07 16:49 UTC, merlin-northern commented on 09.Add-ons/50.Monitor/10.Installation/docs.md
> +* [With a Debian package](../../../09.Downloads/docs.md#remote-terminal-add-on) for the installation from the Debian package
both ending clauses "for the installation [..]" play nice with the "please consult" but at the top we have "There are multiple ways you can install [..] into your image:"

2021-09-07 16:51 UTC, merlin-northern commented on 09.Downloads/docs.md
> +devices for events and anomalies. configuration. See the [add-on page for Mender
" configuration." left over?

2021-09-07 16:51 UTC, merlin-northern commented on 09.Downloads/docs.md
> +Mender APT repository, alternate installation methods are found on the [add-on page for Mender
"are found" -- passive

2021-09-07 18:29 UTC, estenberg commented on 05.System-updates-Yocto-Project/05.Customize-Mender/02.Mender-monitor/docs.md
> +!!! require a hosted-mender user login.
Yes, I think on-premise needs to be documented as well, it's part of our offering after all. :)

2021-09-07 18:30 UTC, estenberg commented on 05.System-updates-Yocto-Project/05.Customize-Mender/02.Mender-monitor/docs.md
> +!!! require a hosted-mender user login.
It's "hosted Mender".

2021-09-07 18:31 UTC, estenberg commented on 05.System-updates-Yocto-Project/05.Customize-Mender/02.Mender-monitor/docs.md
> +title: Install the Mender monitor add-on
Indeed, capital M - it's a name.

2021-09-07 18:48 UTC, estenberg requested changes
Please relocate the Yocto part, it's currently under: 

*  05.System-updates-Yocto-Project/05.Customize-Mender/02.Mender-monitor

but the parent page already contains an add-on section you can add it to: https://docs.mender.io/system-updates-yocto-project/customize-mender#add-ons

Otherwise some minor suggestions.

2021-09-07 18:48 UTC, estenberg commented on 05.System-updates-Yocto-Project/05.Customize-Mender/02.Mender-monitor/docs.md
> +!!! Note: Mender monitor is a paid add-on of the Mender project, and does
Agree use, "commercial" and "Monitor"
"does require" -> "requires"

2021-09-07 18:48 UTC, estenberg commented on 05.System-updates-Yocto-Project/05.Customize-Mender/02.Mender-monitor/docs.md
> +Accept the Mender commercial license by adding to your `local.conf`:
Minor legal note, but I don't think you can say "Accept the license", this is their choice. Would rephrase a bit.

"To use Mender Monitor, you need to accept its license. If you decide to accept it, add the following to your `local.conf`:

2021-09-07 18:48 UTC, estenberg commented on 05.System-updates-Yocto-Project/05.Customize-Mender/02.Mender-monitor/docs.md
> +[snip]
I would skip the snippets above, just show this one and explain quickly each below. That is just one copy-paste and faster.

2021-09-07 18:48 UTC, estenberg commented on 09.Add-ons/50.Monitor/10.Installation/docs.md
> +Mender monitor is a closed source add-on for the Mender project. There are
Monitor, "commercial"

2021-09-07 18:48 UTC, estenberg commented on 09.Add-ons/50.Monitor/10.Installation/docs.md
> +* [With a Debian package](../../../09.Downloads/docs.md#remote-terminal-add-on) for the installation from the Debian package
Wrong URL, it's for remote terminal.

2021-09-07 18:48 UTC, estenberg commented on 09.Downloads/docs.md
> +## Mender monitor
Monitor

2021-09-07 18:48 UTC, estenberg commented on 09.Downloads/docs.md
> +Mender APT repository, alternate installation methods are found on the [add-on page for Mender
Configure -> Monitor

2021-09-08 07:27 UTC, merlin-northern commented on 05.System-updates-Yocto-Project/05.Customize-Mender/02.Mender-monitor/docs.md
> +Mender username and password:
ok I do not know what my comment was stranger than the fragment it refers to. maybe just a nitpick: maybe starting with "Using your hosted Mender username and password download .." ? up to you.

2021-09-10 07:48 UTC, lluiscampos commented on 05.System-updates-Yocto-Project/05.Customize-Mender/docs.md
> +    curl --fail -u $HOSTED_MENDER_EMAIL -O https://download.mender.io/content/hosted/mender-monitor/yocto/master/mender-monitor_1.0.0.tar.gz
We do not have access to the `mender-monitor` binaries using Hosted Mender user and password, we authentication methods available for `mender-monitor` are:
* JWT for Hosted Mender. The JWT is only available from the GUI, so no direct downloads are possible
* user/password for Mender Enterprise on-prem

Maybe it wasn't obvious for everyone during my rant during SU yesterday (it wasn't my clearer speech and I apologize for that), but this won't work. So we need to re-think what are we going to document.

ping @eysteins

2021-09-10 11:30 UTC, lluiscampos commented on 05.System-updates-Yocto-Project/05.Customize-Mender/docs.md
> +    curl --fail -u $HOSTED_MENDER_EMAIL -O https://download.mender.io/content/hosted/mender-monitor/yocto/master/mender-monitor_1.0.0.tar.gz
Update,

We had a call today on the topic and concluded that we must fix before release. Being tracked at [MEN-5042](https://tracker.mender.io/browse/MEN-5042).

2021-09-13 06:11 UTC, oleorhagen commented on 05.System-updates-Yocto-Project/05.Customize-Mender/docs.md
> +    curl --fail -u $HOSTED_MENDER_EMAIL -O https://download.mender.io/content/hosted/mender-monitor/yocto/master/mender-monitor_1.0.0.tar.gz
@lluiscampos from what I could gather, this can now be done with password everywhere?

2021-09-13 09:05 UTC, lluiscampos commented on 05.System-updates-Yocto-Project/05.Customize-Mender/docs.md
> +    curl --fail -u $HOSTED_MENDER_EMAIL -O https://download.mender.io/content/hosted/mender-monitor/yocto/master/mender-monitor_1.0.0.tar.gz
@oleorhagen Correct! Now it should work the same way as `mender-binary-delta`: user and pass both for hosted Mender and on-prem Enterprise. Not yet in production, though, so the links can't be tested.

2021-09-13 16:33 UTC, estenberg requested changes
Overall looks good, just standardize the disclaimers. Good idea to try to follow the structure of other add-ons to save time and avoid confusion for users.

2021-09-13 16:33 UTC, estenberg commented on 05.System-updates-Yocto-Project/05.Customize-Mender/docs.md
> +!!! requires a hosted Mender user login.
"hosted"? It can be used by Enterprise on-premise as well..

I would just make this a standard disclaimer like we have for the other add-on packages:

"The Mender Monitor add-on package is required. See the [Mender features page](https://mender.io/plans/features?target=_blank) for an overview of all Mender plans and features."

2021-09-13 16:33 UTC, estenberg commented on 09.Downloads/docs.md
> +!!! Note: Mender Monitor is a commercial add-on of the Mender project, and does
Same here, use a standardized disclaimer. :)

2021-09-14 12:58 UTC, lluiscampos commented on 05.System-updates-Yocto-Project/05.Customize-Mender/docs.md
> +https://download.mender.io/content/hosted/mender-monitor/yocto/master/mender-monitor_1.0.0.tar.gz
Discussed in person (sorry I didn't review in detail this PR): all these versions need to be `master`, it will be later with the autoversion tool that we will mark 1.0.0

2021-09-14 13:56 UTC, merged