MEN-4978: monitor add-on docs
mendersoftware/mender-docs pull request #1542
Opened 2021-09-17 08:07 UTC by tranchitella

2021-09-17 13:15 UTC, TheMeaningfulEngineer commented on 09.Add-ons/20.Monitor/docs.md
> +state changes per one FLAPPING_INTERVAL goes below FLAPPING_COUNT_THRESHOLD.
Would be great to have links to variable descriptions.

2021-09-17 13:15 UTC, TheMeaningfulEngineer commented on 09.Add-ons/20.Monitor/docs.md
> +when certain parts of your infrastructure malfunction or need your attention.
Doesn't seem to render correctly. Misses the frame ans stuff.
![Screenshot from 2021-09-17 15-13-55](https://user-images.githubusercontent.com/1640260/133788515-6491a4c4-2fbe-48df-a526-24104fdbe370.png)

2021-09-17 13:21 UTC, TheMeaningfulEngineer commented
@lluiscampos 

Comment on the monitor installation.
https://docs.mender.io/development/system-updates-yocto-project/customize-mender#monitor

(still ongoing with the actual testing)

---

> There is a split between hosted/enterprise pointing to the same links.

```
curl --fail -u $MENDER_ENTERPRISE_EMAIL -O https://downloads.customer.mender.io/content/hosted/mender-monitor/yocto/master/mender-monitor-master.tar.gz
curl --fail -u $HOSTED_MENDER_EMAIL     -O https://downloads.customer.mender.io/content/hosted/mender-monitor/yocto/master/mender-monitor-master.tar.gz
```

Found this confusing. 
Would just leave enterprise.
This could be internal terminology hosted/enterprise but to the outside enterprise is a payed plan which is either hosted of on premise, but enterprise all the time.


---

> system-updates-yocto-project/customize-mender#monitor 

The comands are indented making it weird to copy-paste

---


> /<path/downloaded/to/previously>/

Assuming a sane default would make a friendlier user experience.
We assume ~ for binary delta, let's do it here also.
Those who don't want it just need to do the same steps as described here.

2021-09-17 21:00 UTC, estenberg requested changes
Overall looks good, except the "Quickstart" part for Monitor. We don't have this concept yet (we call the general Mender onboarding "Get started"). 

It may be better suited under "Get started/Monitor an application" I think (https://docs.mender.io/get-started), since the users following it already has Monitor installed. We'd need to disclaimer that the Monitor add-on package is required though.

2021-09-20 04:12 UTC, tranchitella commented
@TheMeaningfulEngineer I addressed your comments

2021-09-20 05:22 UTC, tranchitella commented on 09.Add-ons/20.Monitor/docs.md
> +when certain parts of your infrastructure malfunction or need your attention.
Renders correctly here:

<img width="1009" alt="Screenshot 2021-09-20 at 07 22 36" src="https://user-images.githubusercontent.com/1295287/133959859-187cda63-e53e-4760-abc5-e4e3add9df30.png">

2021-09-21 11:36 UTC, TheMeaningfulEngineer commented on 09.Add-ons/20.Monitor/30.Advanced-configuration/docs.md
> +|`DEFAULT_LOG_LINES_AFTER`|integer|default number of lines sent after a line that contained a string that matched a given pattern|
The configuration options for monitoring are listed as a table as opposed to the [header based configuration documentation](https://docs.mender.io/client-installation/configuration-file/configuration-options#artifactverifykey) used for the client.

This format does makes a documentation reference.
At the same time it prevents linking to conf variables.
No linking means variables get divorced from their description when referenced in the text. 

I am biased here with the way how yocto does docs (where every variable is always a link to its description) and would argue that this is a superior way of doing the docs.
The format doesn't matter that much, it can remain a table, as long as the configuration options are linkable.

2021-09-21 11:46 UTC, kacf commented on 09.Add-ons/20.Monitor/30.Advanced-configuration/docs.md
> +|`DEFAULT_LOG_LINES_AFTER`|integer|default number of lines sent after a line that contained a string that matched a given pattern|
+1

2021-09-22 03:41 UTC, tranchitella commented on 09.Add-ons/20.Monitor/30.Advanced-configuration/docs.md
> +|`DEFAULT_LOG_LINES_AFTER`|integer|default number of lines sent after a line that contained a string that matched a given pattern|
Ack: https://github.com/mendersoftware/mender-docs/pull/1542/commits/8ccd6cf5b7461363a31dd38008c7ab5f55df9ff0

2021-09-22 04:34 UTC, merlin-northern commented
@tranchitella do you mind picking this one: https://github.com/mendersoftware/mender-docs/pull/1547 here? it is a missing double quote fix for what Manuel discovered in MEN-5090 I do not want to cause extra conflicts with merging this one, so maybe it is best if you could modify those two characters here.

2021-09-22 08:20 UTC, tranchitella commented
@merlin-northern we don't have that line anymore, we rely on the `mender-monitorctl` command.

2021-09-22 08:22 UTC, merlin-northern commented
> @merlin-northern we don't have that line anymore, we rely on the `mender-monitorctl` command.

thank you for the update. good.

2021-09-22 10:22 UTC, merged