3.0.1 Mender release version updates
mendersoftware/mender-docs pull request #1563
Opened 2021-09-29 12:59 UTC by oleorhagen

Changelog: None
Signed-off-by: Ole Petter <ole.orhagen@northern.tech>

2021-09-29 13:01 UTC, oleorhagen commented
Note: Links are still untested (in fact the binaries are not even there yet), so don't merge

2021-09-29 13:21 UTC, lluiscampos requested changes
See comment below wrt mender-binary-delta.

Also, what about mender-convert images? We can sync on this on Slack but we need to publish and update the links.

2021-09-29 13:21 UTC, lluiscampos commented on 05.System-updates-Yocto-Project/05.Customize-Mender/01.Delta-update-support/docs.md
> +curl -u $HOSTED_MENDER_EMAIL -O https://downloads.customer.mender.io/hosted/content/mender-binary-delta/1.3.0/mender-binary-delta-1.3.0.tar.xz
We shouldn't change the minor version of mender-binary-delta on a bugfix release.

2021-09-30 07:50 UTC, oleorhagen commented on 05.System-updates-Yocto-Project/05.Customize-Mender/01.Delta-update-support/docs.md
> +curl -u $HOSTED_MENDER_EMAIL -O https://downloads.customer.mender.io/hosted/content/mender-binary-delta/1.3.0/mender-binary-delta-1.3.0.tar.xz
Roger, slight misunderstanding between me and Kristian yesterday

2021-09-30 07:55 UTC, oleorhagen commented
> See comment below wrt mender-binary-delta.
> 
> Also, what about mender-convert images? We can sync on this on Slack but we need to publish and update the links.

I'm doing convert separately, if that is okay?

2021-09-30 08:20 UTC, lluiscampos approved these changes

2021-09-30 10:40 UTC, merged