Add Azure IoT Hub integration docs
mendersoftware/mender-docs pull request #1590
Opened 2021-12-09 10:16 UTC by MaciejTe

Add Azure IoT Hub integration docs

Signed-off-by: Maciej Tomczuk <maciej.tomczuk@northern.tech>

2021-12-10 22:27 UTC, estenberg requested changes
Overall good, it's in the right place. Mostly nitpicks on language to make it super-clear.

2021-12-10 22:27 UTC, estenberg commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +In order to connect your devices to Azure IoT Hub, you need to enter connection string. This can be set up in `Settings` - `Integrations`:
Open the Mender UI and navigate to `Settings` -> `Integrations`.

2021-12-10 22:27 UTC, estenberg commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +After choosing Azure IoT Hub integration, enter connection string:
Choose the Azure IoT Hub integration and enter your IoT Hub connection string:

2021-12-10 22:27 UTC, estenberg commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +Connection string can be taken from `Shared access policies` menu in your IoT Hub after selecting desired access policy:
You can find your connection string under the `Shared access policies` menu in your IoT Hub after selecting desired access policy:

2021-12-10 22:27 UTC, estenberg commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +!!! Mender needs Shared access policy with `Registry Read`, `Registry Write` and `Service Connect` permissions
policy with *the* ...
Add punctuation to end of sentence.

2021-12-10 22:27 UTC, estenberg commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +Next, go to `Devices` menu and accept your device - after it gets authorized in Mender, it will also show up in Azure IoT Hub:
Go to the `Devices` tab in Mender and *accept* a device. After it gets authorized in Mender, it will also show up in your Azure IoT Hub:

2021-12-10 22:27 UTC, estenberg commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +## Disabling device in Azure IoT Hub
Would collect these two under common heading, e.g. "Mender manages device life-cycle".
If the device is rejected in Mender, Mender will Disable it in your Azure IoT Hub. ...

2021-12-10 22:27 UTC, estenberg commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +1. At first, device gets accepted - various flows can be used to achieve this state. More about device authentication [here](../../02.Overview/13.Device-authentication/docs.md)
the device

2021-12-10 22:27 UTC, estenberg commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +1. At first, device gets accepted - various flows can be used to achieve this state. More about device authentication [here](../../02.Overview/13.Device-authentication/docs.md)
instead of "here" say See [device authentication]() for more information.

2021-12-10 22:27 UTC, estenberg commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +2. Mender provisions device in Azure IoT Hub - as a result of this operation, Azure device connection string is stored in Mender.
provisions the device

2021-12-10 22:27 UTC, estenberg commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +3. Next step is Mender Configure add-on, which sends device connection string to file (`/var/lib/mender-configure/device-config.json`) on the device.
The Mender Configure add-on sets the device connection string in `....`

2021-12-10 22:27 UTC, estenberg commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +4. From now on, device can send or get any data to/from Azure IoT Hub.
the device.

Perhaps say device applications can read the connection string from the file and communicate with Azure IoT Hub.

2021-12-10 22:27 UTC, estenberg commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +5. If device gets rejected in Mender, it's automatically set to `Disabled` state in Azure IoT Hub.
'it's" -> "it is" (we usually do not use abbreviations)

2021-12-10 22:27 UTC, estenberg commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +6. If device gets decommissioned, it's automatically `deleted` from Azure IoT Hub.
same here "it is"
Deleted (capitalize)

2021-12-13 22:08 UTC, estenberg requested changes
A few more things I thought about after the first review:)

2021-12-13 22:08 UTC, estenberg commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +## Device lifecycle
This would fit better at the top I think.
Also we have a diagram already that you could use instead / in addition: https://drive.google.com/file/d/1n9HVqE00kPcM8EYLvT74Dryo8eTzNpRh/view

2021-12-13 22:08 UTC, estenberg commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +## Disabling device in Azure IoT Hub
Also, you don't mention Mender Configuer here and how it will work end-to end. I would rethink the structure here a bit. E.g. use the diagram, explain the workflow at a high level first, then explain each in detail.

2021-12-13 22:08 UTC, estenberg commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +## Connecting devices to Azure IoT Hub
This is more about setting up the system, would adjust the header accordingly.

2021-12-14 18:22 UTC, MaciejTe commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +Mender supports preparing devices to use Azure IoT Hub. Assuming you already have Mender in place on the device, it is automatically created in Azure IoT Hub and applications running on the device ge
Fixed, thanks!

2021-12-14 18:22 UTC, MaciejTe commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +!!! Currently it's possible to have one cloud provider connection per tenant.
Fixed, thanks!

2021-12-14 18:23 UTC, MaciejTe commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +!!! Currently only new devices can integrate with Azure IoT Hub.
Fixed, thanks!

2021-12-14 18:23 UTC, MaciejTe commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +Azure account with Azure IoT Hub needs to be set up. More information [here](https://azure.microsoft.com/en-us/services/iot-hub/#overview). In order to integrate Mender with Azure IoT Hub you need to
Fixed, thanks!

2021-12-14 18:23 UTC, MaciejTe commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +In order to connect your devices to Azure IoT Hub, you need to enter connection string. This can be set up in `Settings` - `Integrations`:
Fixed, thanks!

2021-12-14 18:23 UTC, MaciejTe commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +After choosing Azure IoT Hub integration, enter connection string:
Fixed, thanks!

2021-12-14 18:23 UTC, MaciejTe commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +Connection string can be taken from `Shared access policies` menu in your IoT Hub after selecting desired access policy:
Fixed, thanks!

2021-12-14 18:23 UTC, MaciejTe commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +!!! Mender needs Shared access policy with `Registry Read`, `Registry Write` and `Service Connect` permissions
Fixed, thanks!

2021-12-14 18:23 UTC, MaciejTe commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +Next, go to `Devices` menu and accept your device - after it gets authorized in Mender, it will also show up in Azure IoT Hub:
Fixed, thanks!

2021-12-14 18:24 UTC, MaciejTe commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +1. At first, device gets accepted - various flows can be used to achieve this state. More about device authentication [here](../../02.Overview/13.Device-authentication/docs.md)
Fixed, thanks!

2021-12-14 18:24 UTC, MaciejTe commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +3. Next step is Mender Configure add-on, which sends device connection string to file (`/var/lib/mender-configure/device-config.json`) on the device.
Fixed, thanks!

2021-12-14 18:24 UTC, MaciejTe commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +4. From now on, device can send or get any data to/from Azure IoT Hub.
Fixed, thanks!

2021-12-14 18:24 UTC, MaciejTe commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +5. If device gets rejected in Mender, it's automatically set to `Disabled` state in Azure IoT Hub.
Fixed, thanks!

2021-12-14 18:24 UTC, MaciejTe commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +6. If device gets decommissioned, it's automatically `deleted` from Azure IoT Hub.
Fixed, thanks!

2021-12-14 18:24 UTC, MaciejTe commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +## Connecting devices to Azure IoT Hub
Fixed, thanks!

2021-12-14 20:29 UTC, estenberg requested changes
This looks clear now; just a few more nitpicks. :)

2021-12-14 20:29 UTC, estenberg commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +!!! [Mender Configure](../../09.Add-ons/10.Configure/docs.md) is required to properly integrate devices with Azure IoT Hub.
"properly integrate devices with Azure IoT Hub" -> "distribute the Azure IoT connection string to the device".

2021-12-14 20:29 UTC, estenberg commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +An Azure account with Azure IoT Hub needs to be set up. More information [here](https://azure.microsoft.com/en-us/services/iot-hub/#overview). In order to integrate Mender with Azure IoT Hub you need
"More information [here](https://azure.microsoft.com/en-us/services/iot-hub/#overview)"

->
"See the [Azure IoT Hub documentation](https://azure.microsoft.com/en-us/services/iot-hub/?target=_blank#overview) for more information.

NOTE: Please use ?target=_blank when referring to external sites (not docs.mender.io links)

2021-12-14 20:29 UTC, estenberg commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +An Azure account with Azure IoT Hub needs to be set up. More information [here](https://azure.microsoft.com/en-us/services/iot-hub/#overview). In order to integrate Mender with Azure IoT Hub you need
This also applies to your second link here.

2021-12-14 20:29 UTC, estenberg commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +!!! Mender needs the `Shared access policy` with `Registry Read`, `Registry Write` and `Service Connect` permissions.
The `iothubowner` user has the required permissions, but you can also use a more limited account if desired. Mender needs the `Shared access policy` with `Registry Read`, `Registry Write` and `Service Connect` permissions.

2021-12-14 20:29 UTC, estenberg commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +2. Mender provisions the device in Azure IoT Hub - as a result of this operation, Azure device connection string is stored in Mender.
"stored in Mender" -> "retrieved by the Mender server".

2021-12-14 20:29 UTC, estenberg commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +## Connecting devices to Azure IoT Hub
Mender provisions devices to the Azure IoT Hub

2021-12-14 20:29 UTC, estenberg commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +## Device lifecycle in detail
Device lifecycle overview

2021-12-14 20:29 UTC, estenberg commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +3. The Mender [Configure add-on](../../09.Add-ons/10.Configure/docs.md) sets the device connection string in file (`/var/lib/mender-configure/device-config.json`) on the device.
It is recommended to create a [Mender configuration script](../../add-ons/configure/device-integration) to reconfigure the Azure IoT application and restart it with its new connection string.

2021-12-14 23:54 UTC, estenberg requested changes
A few notes on Device ID.

2021-12-14 23:54 UTC, estenberg commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +
Notice that the same Device ID used in Mender is provisioned to the Azure IoT Hub. This makes it easy to cross-reference your devices between Mender and Azure IoT Hub.

2021-12-14 23:54 UTC, estenberg commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +![Accept device](image_3.png)
Suggest pointing out Device ID, sent you image update

2021-12-14 23:54 UTC, estenberg commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +![Azure devices](image_4.png)
Suggest pointing out Device ID, sent you image update

2021-12-15 08:56 UTC, MaciejTe commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +![Accept device](image_3.png)
done, thanks!

2021-12-15 08:56 UTC, MaciejTe commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +![Azure devices](image_4.png)
done, thanks!

2021-12-15 09:05 UTC, alfrunes commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +3. The Mender [Configure add-on](../../09.Add-ons/10.Configure/docs.md) sets the device connection string in file (`/var/lib/mender-configure/device-config.json`) on the device.
The idea, as @estenberg says, is to use configuration update modules to bootstrap the iot application. A practical example on Mender Hub would also be great to reference here.
```suggestion
3. The connection string is made available to the device by a configuration deployment. To bootstrap your Azure IoT application you need to create a [Mender configuration module](../../add-ons/configure/device-integration).
```

2021-12-15 09:20 UTC, MaciejTe commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +## Connecting devices to Azure IoT Hub
Are you sure this sounds better?

2021-12-15 09:48 UTC, MaciejTe commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +!!! [Mender Configure](../../09.Add-ons/10.Configure/docs.md) is required to properly integrate devices with Azure IoT Hub.
done!

2021-12-15 09:48 UTC, MaciejTe commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +An Azure account with Azure IoT Hub needs to be set up. More information [here](https://azure.microsoft.com/en-us/services/iot-hub/#overview). In order to integrate Mender with Azure IoT Hub you need
done!

2021-12-15 09:48 UTC, MaciejTe commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +!!! Mender needs the `Shared access policy` with `Registry Read`, `Registry Write` and `Service Connect` permissions.
done!

2021-12-15 09:48 UTC, MaciejTe commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +2. Mender provisions the device in Azure IoT Hub - as a result of this operation, Azure device connection string is stored in Mender.
done!

2021-12-15 09:48 UTC, MaciejTe commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +## Device lifecycle in detail
done!

2021-12-15 09:48 UTC, MaciejTe commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +
done!

2021-12-15 23:15 UTC, estenberg requested changes
Nitpicks on nitpicks I guess at this stage. :)

It is just about trying to link to the right places, looking very good overall :+1:

2021-12-15 23:15 UTC, estenberg commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +!!!!! It is currently possible to have one Azure IoT Hub integration configured per Mender Organization (aka. tenant).
Would move this below the description "Mender supports..."

2021-12-15 23:15 UTC, estenberg commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +!!!!! After you enable the integration, only newly accepted devices in Mender will be created in Azure IoT Hub. Existing devices (in both systems) are left unchanged.
Would move this below the description "Mender supports..."

2021-12-15 23:15 UTC, estenberg commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +You need a physical board that has already been integrated with Mender. For example, you may use one of the reference boards BeagleBone Black, Raspberry Pi 3 or Raspberry Pi 4.
Remove BeagleBone Black. It's not a reference, it used to be (only RPi is).

2021-12-15 23:15 UTC, estenberg commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +- [Client installation](../../03.Client-installation/chapter.md)
Link to Get started instead of these 3.

visit [Get started]()...

2021-12-15 23:15 UTC, estenberg commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +### A board integrated with Mender
A Mender server and device

2021-12-15 23:15 UTC, estenberg commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +You need a physical board that has already been integrated with Mender. For example, you may use one of the reference boards BeagleBone Black, Raspberry Pi 3 or Raspberry Pi 4.
Maybe even generalize this. Just say you need a Mender server set up and a device running the Mender client. Then link to get started.

2021-12-15 23:15 UTC, estenberg commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +## Connecting devices to Azure IoT Hub
No strong opinion, but "connecting devices to Azure IoT Hub" sounded what you would normally do with out Mender. Take your pick. :)

2021-12-16 13:09 UTC, MaciejTe commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +You need a physical board that has already been integrated with Mender. For example, you may use one of the reference boards BeagleBone Black, Raspberry Pi 3 or Raspberry Pi 4.
done!

2021-12-16 13:09 UTC, MaciejTe commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +!!!!! After you enable the integration, only newly accepted devices in Mender will be created in Azure IoT Hub. Existing devices (in both systems) are left unchanged.
done!

2021-12-16 13:10 UTC, MaciejTe commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +![connection string](image_1.png)
done!

2021-12-16 13:11 UTC, MaciejTe commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +## Connecting devices to Azure IoT Hub
I changed it to `Connect your devices to Azure IoT Hub automatically using Mender`, please let me know what do you think :smiley:

2021-12-17 19:07 UTC, estenberg approved these changes
Excellent result. :+1:

2021-12-20 16:32 UTC, MaciejTe commented on 08.Server-integration/04.Azure-IoT-Hub/docs.md
> +3. The Mender [Configure add-on](../../09.Add-ons/10.Configure/docs.md) sets the device connection string in file (`/var/lib/mender-configure/device-config.json`) on the device.
As agreed during standup, I'll prepare an article after we finish working on renaming microservices and potentially preparing abstraction layer for cloud vendors we'll provide integrations with. Task: https://tracker.mender.io/browse/MEN-5337

2021-12-21 08:57 UTC, alfrunes approved these changes

2021-12-21 08:58 UTC, merged