MEN-5137: Document the demo monitors.
mendersoftware/mender-docs pull request #1603
Opened 2021-12-30 13:30 UTC by oleorhagen

Changelog: None
Signed-off-by: Ole Petter <ole.orhagen@northern.tech>

2022-01-03 18:25 UTC, estenberg requested changes
A few things:
* Taxonomy: Use Alert to describe what you enable on the device. I know the tool uses "Check" for this in some places, but at least don't introduce another one (monitor).
* Justify / motivate each demo Alert. I added some suggested sentences.
* For this section (Get started) you can assume that the user is doing a Free trial. Simply add this (Get started/prepartions) as prerequisites, with a link to any extra steps if *not* Free trial.

2022-01-03 18:25 UTC, estenberg commented on 01.Get-started/05.Monitor/docs.md
> +Add-on](../../09.Add-ons/20.Monitor/10.Installation/docs.md) on your device.
Append something like: "If you have followed [get-started/preparation] to prepare your device, the Monitor Add-on should already be installed."

2022-01-03 18:25 UTC, estenberg commented on 01.Get-started/05.Monitor/docs.md
> +!!! NOTE: To follow this tutorial, you will need to install the [Monitor demo
Is this installed by default with the get-started/preparation? If so, I would add a similar note as I suggested above. If not, I would make this into steps rather than a note/warning.

2022-01-03 18:25 UTC, estenberg commented on 01.Get-started/05.Monitor/docs.md
> +Click on either monitor you want to try out.
Taxonomy: "monitor" is not used like this. This should be "Alert".

E.g. "Choose below which demo Alert you want to enable:"

2022-01-03 18:25 UTC, estenberg commented on 01.Get-started/05.Monitor/docs.md
> +First enable the monitor through running:
Alert

2022-01-03 18:25 UTC, estenberg commented on 01.Get-started/05.Monitor/docs.md
> +First enable the diskusage monitor for the root space partition.
Alert

2022-01-03 18:25 UTC, estenberg commented on 01.Get-started/05.Monitor/docs.md
> +Click on either monitor you want to try out.
On a second look, this looks a bit too long to make it into tabs (at least so far we've used them for minor differences between OSes (e.g. Mac vs. Linux). Also not sure how it affects SEO..

Would recommend to simply make these headers in the doc, not tabs.

2022-01-03 18:25 UTC, estenberg commented on 01.Get-started/05.Monitor/docs.md
> +And an alarm shows up in the UI.
alert

2022-01-03 18:25 UTC, estenberg commented on 01.Get-started/05.Monitor/docs.md
> +Let us trigger the alarm through stopping the traffic to `example.com` through
alert

2022-01-03 18:25 UTC, estenberg commented on 01.Get-started/05.Monitor/docs.md
> +Which then triggers the alarm:
alert

2022-01-03 18:25 UTC, estenberg commented on 01.Get-started/05.Monitor/docs.md
> +And soon the alarm will show up as fixed in the UI:
alert

2022-01-03 18:25 UTC, estenberg commented on 01.Get-started/05.Monitor/docs.md
> +!!! NOTE: Docker needs to be installed on the device
Provide link or sample command for Raspberry Pi OS

2022-01-03 18:25 UTC, estenberg commented on 01.Get-started/05.Monitor/docs.md
> +Enable the monitor:
Alert

2022-01-03 18:25 UTC, estenberg commented on 01.Get-started/05.Monitor/docs.md
> +[ui-tab title="Docker container events"]
Docker container restart

2022-01-03 18:25 UTC, estenberg commented on 01.Get-started/05.Monitor/docs.md
> +!!! NOTE: To follow this tutorial, you will need to install the [Monitor demo
In fact, moving up to prerequisites may be better.

2022-01-03 18:25 UTC, estenberg commented on 01.Get-started/05.Monitor/docs.md
> +### Demo monitors
Demo Alerts

2022-01-03 18:25 UTC, estenberg commented on 01.Get-started/05.Monitor/docs.md
> +
"Peripherals such as keypads and displays are in many cases required to be connected in order for an IoT product to function properly. This demo Alert shows how to detect that a USB-connected peripheral gets disconnected."

2022-01-03 18:25 UTC, estenberg commented on 01.Get-started/05.Monitor/docs.md
> +
"If key device resources such as disk space runs out, e.g. due to ever-growing log files, the product will typically stop functioning properly. It is therefore a good practice to enable a disk space Alert to detect high disk space usage and remediate it before it causes any downtime."

2022-01-03 18:25 UTC, estenberg commented on 01.Get-started/05.Monitor/docs.md
> +
"Ongoing connectivity issues may cause the device application to hang or malfunction, disrupting the user experience or function of the product. This Alert is one example how to detect connectivity issues. Note that Mender stores triggered Alerts on the device, so even if Mender cannot send the Alerts to the server immediately, you will get notified about triggered Alerts, even during offline periods, once connectivity is restored."

2022-01-03 18:25 UTC, estenberg commented on 01.Get-started/05.Monitor/docs.md
> +
"Applications may restart sporadically when they encounter new situations like intermittent connectivity. As they are often automatically started again the root cause of this condition may be difficult to detect, and even harder to diagnose solely based on customer reports. Still, this situation and even what led to it can be fairly easy to discover if you look at the log or output from the application itself. This Alert detects restart from Docker logs and notifies the event has happened."

2022-01-04 08:51 UTC, oleorhagen commented on 01.Get-started/05.Monitor/docs.md
> +Click on either monitor you want to try out.
I kinda liked to look of it, as it made it easy to navigate, in the case you do not want to try them all (which I'm guessing most people wont), but either way is fine with me.

2022-01-04 17:14 UTC, estenberg requested changes
This is good, a few more nitpicks. :)

2022-01-04 17:14 UTC, estenberg commented on 01.Get-started/05.Monitor/docs.md
> +you have followed [get-started/preparation](../01.Preparation/docs.md) to
Would not use section "path" in the link, sorry I may have confused you with earlier comment.

Suggesting: If you have followed the [get started tutorial to prepare your device](../01.Preparation/docs.md), the Monitor Add-on should already be installed.

2022-01-04 17:14 UTC, estenberg commented on 01.Get-started/05.Monitor/docs.md
> +> Peripherals such as keypads and displays are in many cases required to be
We don't use quotes other places, would remove this formatting.

2022-01-04 17:14 UTC, estenberg commented on 01.Get-started/05.Monitor/docs.md
> +
"A set of Alerts to demo key use cases is provided out of the box with the Mender Monitor Add-on. This is meant as a starting point to try it out, and you can always [customize and define your own alerts](../../add-ons/monitor/monitoring-subsystems) once you are ready."

2022-01-04 17:14 UTC, estenberg commented on 01.Get-started/05.Monitor/docs.md
> +> Peripherals such as keypads and displays are in many cases required to be
This also applies later in the doc.

2022-01-04 17:14 UTC, estenberg commented on 01.Get-started/05.Monitor/docs.md
> +> server immediately, you will get notified about triggered Alerts, even during
My bad: should not be comma after "immediately".

2022-01-04 17:14 UTC, estenberg commented on 01.Get-started/05.Monitor/docs.md
> +> server immediately, you will get notified about triggered Alerts, even during
It's a long sentence too, maybe consider breaking it into two..

2022-01-05 17:40 UTC, estenberg requested changes
Sorry, one thing I didn't catch earlier is that email notifications are not covered. This is a very important feature and I think we should cover this. I added some suggested paragraph.

2022-01-05 17:40 UTC, estenberg commented on 01.Get-started/05.Monitor/docs.md
> +mender-monitorctl enable log usb
Should be called "usb-disconnect"?

2022-01-05 17:40 UTC, estenberg commented on 01.Get-started/05.Monitor/docs.md
> +Now you can trigger an alert in the Mender UI through inserting and removing a
This is a bit passive sentence. Also not quite clear "inserting" is triggering the alert, or is this relevant?

Suggesting: Now remove a USB device from the device (you can insert it first, e.g. a thumbdrive or mouse, if you don't have any USB devices inserted). The Alert will trigger in the Mender UI once you remove the USB device:

2022-01-05 17:40 UTC, estenberg commented on 01.Get-started/05.Monitor/docs.md
> +
Email notifications are automatically generated in addition to UI notifications shown in the screenshots below. While going through the examples in this tutorial, watch the email inbox of your Mender user to see you get notified about Alerts being triggered and cleared on the device.

2022-01-07 17:09 UTC, estenberg approved these changes
Excellent :+1:

2022-01-10 09:31 UTC, merged