MEN-5223 Monitor: streamline logs and fixes
mendersoftware/mender-docs pull request #1607
Opened 2022-01-10 12:58 UTC by merlin-northern

ChangeLog:title
Signed-off-by: Peter Grzybowski <peter@northern.tech>

2022-01-11 07:46 UTC, lluiscampos requested changes

2022-01-11 07:46 UTC, lluiscampos commented on 01.Get-started/05.Monitor/docs.md
> +Which will trigger a critical alert everytime _Exited with code n_ (where n is any decimal number) shows up
```suggestion
Which will trigger a critical alert every time _Exited with code n_ (where n is any decimal number) shows up
```

2022-01-11 07:46 UTC, lluiscampos commented on 09.Add-ons/20.Monitor/20.Monitoring-subsystems/docs.md
> +command.
Missing new line here

2022-01-11 07:46 UTC, lluiscampos commented on 09.Add-ons/20.Monitor/20.Monitoring-subsystems/docs.md
> +command.
It says "either" this or that, but both cases are the same.
```suggestion
the _"OK"_ alert after a period of time, defined by `LOG_PATTERN_EXPIRATION` in the check. This variable is set via
the last argument to the `mender-monitorctl create log name pattern file expiration`
command.
```

Something like that...

2022-01-11 07:46 UTC, lluiscampos commented on 01.Get-started/05.Monitor/docs.md
> +
At the end here I would add a reference for more information to go to `09.Add-ons/20.Monitor/20.Monitoring-subsystems/docs.md`

2022-01-12 07:48 UTC, merlin-northern commented on 01.Get-started/05.Monitor/docs.md
> +
added:
```md
For more information please refer
to the [Monitoring subsystems](../../09.Add-ons/20.Monitor/20.Monitoring-subsystems/docs.md) section.
```

2022-01-12 07:48 UTC, merlin-northern commented on 09.Add-ons/20.Monitor/20.Monitoring-subsystems/docs.md
> +command.
makes sense. fixed

2022-01-12 07:49 UTC, merlin-northern commented on 09.Add-ons/20.Monitor/20.Monitoring-subsystems/docs.md
> +command.
fixed

2022-01-12 07:49 UTC, merlin-northern commented on 09.Add-ons/20.Monitor/20.Monitoring-subsystems/docs.md
> +cases you can provide wrapper scripts around some of more complicated commands.
fixed. I dropped "some" from the "You can also provide wrapper scripts for some more advance commands" and changed advance -> advanced

2022-01-12 07:49 UTC, merlin-northern commented on 09.Add-ons/20.Monitor/20.Monitoring-subsystems/docs.md
> +#### docker logs
fixed. it was meant more as command `docker logs` but capital letter is better here.

2022-01-12 07:49 UTC, merlin-northern commented on 09.Add-ons/20.Monitor/20.Monitoring-subsystems/docs.md
> +the standard output.
fixed.

2022-01-12 07:49 UTC, merlin-northern commented on 01.Get-started/05.Monitor/docs.md
> +in the logs for `my-service` systemd service. In the above example there is going to be an automatical cancelation of the critical
fixed.

2022-01-12 07:49 UTC, merlin-northern commented on 01.Get-started/05.Monitor/docs.md
> +Which will trigger a critical alert everytime _Exited with code n_ (where n is any decimal number) shows up
fixed.

2022-01-12 07:53 UTC, lluiscampos approved these changes
Looks good. Only one sentence that does not fully make sense now.

2022-01-12 07:53 UTC, lluiscampos commented on 09.Add-ons/20.Monitor/20.Monitoring-subsystems/docs.md
> +command.
Something estrange here now. Maybe:
```suggestion
in the "critical" state forever. Monitor add-on provides a way to send
the _"OK"_ alert after a period of time defined by `LOG_PATTERN_EXPIRATION`
in the check. This variable is defined either directly on the check
or by the last argument to the `mender-monitorctl create log name pattern file expiration`
command.
```

2022-01-12 08:10 UTC, merlin-northern commented on 09.Add-ons/20.Monitor/20.Monitoring-subsystems/docs.md
> +command.
ho crap! sorry! old misplaced line, forgot to delete. shame on me.

2022-01-12 08:12 UTC, lluiscampos commented on 09.Add-ons/20.Monitor/20.Monitoring-subsystems/docs.md
> +command.
No problem. That is the purpose of reviews ;)

2022-01-12 08:13 UTC, merlin-northern commented on 09.Add-ons/20.Monitor/20.Monitoring-subsystems/docs.md
> +command.
thank you Sir!

2022-01-12 08:16 UTC, lluiscampos approved these changes

2022-01-12 08:17 UTC, merged