bump mender-convert and raspios image
mendersoftware/mender-docs pull request #1620
Opened 2022-01-20 15:25 UTC by oleorhagen

Note: Not checked for the img availability yet, but should be good.

Will test before merging.

2022-01-21 09:12 UTC, kacf approved these changes
Be sure to test this. We've had some reports on Mender Hub about non-working conversions.

2022-01-24 09:40 UTC, lluiscampos requested changes

2022-01-24 09:40 UTC, lluiscampos commented on 01.Get-started/01.Preparation/01.Prepare-a-Raspberry-Pi-device/docs.md
> +[raspios-bullseye-armhf-lite-raspberrypi3-mender.img.xz]: https://d4o6e0uccgv40.cloudfront.net/2021-10-30-raspios-bullseye-armhf-lite/arm/2021-10-30-raspios-bullseye-armhf-lite-raspberrypi3-mender-co
This is not correct, the reference above is not updated so the link won't be rendered correctly. Line 33 still reads `raspios-buster-lite-raspberrypi3-mender.img.xz`.

Also, although harmless, we don't need to add the suffix `-armhf`.

2022-01-24 09:49 UTC, oleorhagen commented on 01.Get-started/01.Preparation/01.Prepare-a-Raspberry-Pi-device/docs.md
> +[raspios-bullseye-armhf-lite-raspberrypi3-mender.img.xz]: https://d4o6e0uccgv40.cloudfront.net/2021-10-30-raspios-bullseye-armhf-lite/arm/2021-10-30-raspios-bullseye-armhf-lite-raspberrypi3-mender-co
https://github.com/mendersoftware/mender-docs/pull/1626

fixed here for 3.2.x. Needs cherry for master

2022-01-24 09:55 UTC, lluiscampos commented on 01.Get-started/01.Preparation/01.Prepare-a-Raspberry-Pi-device/docs.md
> +[raspios-bullseye-armhf-lite-raspberrypi3-mender.img.xz]: https://d4o6e0uccgv40.cloudfront.net/2021-10-30-raspios-bullseye-armhf-lite/arm/2021-10-30-raspios-bullseye-armhf-lite-raspberrypi3-mender-co
> Needs cherry for master

This PR goes to master so we are good.

2022-01-24 09:55 UTC, lluiscampos approved these changes

2022-01-24 18:12 UTC, merged