MEN-5301: Documenation: intro, feature desc and config fields
mendersoftware/mender-docs pull request #1667
Opened 2022-02-11 13:44 UTC by alfrunes

2022-02-11 19:00 UTC, estenberg requested changes
Some nitpicks, mainly for consistency.

2022-02-11 19:00 UTC, estenberg commented on 08.Server-integration/04.Mender-Gateway/docs.md
> +![Mender gateway](mender-gateway-schema.png)
The diagram is clear, just the icons are a bit new I think.
Especially the ones for devices and the Mender server. Perhaps copy the icons from other diagrams you find or ask marketing to take a look at it.

2022-02-14 09:36 UTC, lluiscampos commented on 08.Server-integration/04.Mender-Gateway/99.Configuration-reference/docs.md
> +        }
I would put this part first - it really doesn't matter for the json parsing and this is the flag ship feature.

2022-02-14 09:39 UTC, lluiscampos commented on 08.Server-integration/04.Mender-Gateway/99.Configuration-reference/docs.md
> +<!-- Can't this be infered from ServerCertificate CommonName field? -->
It could. But the idea of having this explicit config field is that it will match also the `ServerUrl` in the client. This will make it easy to troubleshoot as there is no "deduced" information about the topology of the network.

Please remove this comment ;)

2022-02-14 09:39 UTC, lluiscampos commented on 08.Server-integration/04.Mender-Gateway/99.Configuration-reference/docs.md
> +<dt>DomainWhitelist</dt> <dd>List of whitelisted domains for proxying artifacts.</dd>
Maybe:
```suggestion
<dt>DomainWhitelist</dt> <dd>List of whitelisted domains to proxy artifacts from.</dd>
```

2022-02-14 09:41 UTC, lluiscampos commented on 08.Server-integration/04.Mender-Gateway/99.Configuration-reference/docs.md
> +<dt>URL</dt> <dd>The upstream server URL for proxying device requests.</dd>
I suggest to be more explicit here:
```suggestion
<dt>URL</dt> <dd>The upstream server URL for proxying device HTTP requests.</dd>
```

2022-02-14 09:42 UTC, lluiscampos commented on 08.Server-integration/04.Mender-Gateway/docs.md
> +storage server to the devices.
```suggestion
upstream Mender server and is capable of proxying artifacts from an upstream s3-compatible object
storage server to the devices and providing mutual TLS authentication on
behalf of devices .
```

2022-02-14 09:43 UTC, lluiscampos commented on 08.Server-integration/04.Mender-Gateway/docs.md
> +assigned by a deployment. See the [Artifact Proxy User Guide](FIXME/MEN-5302)
Please add a comment to this in MEN-5302

2022-02-14 09:43 UTC, lluiscampos commented on 08.Server-integration/04.Mender-Gateway/docs.md
> +Mender server. See the [mTLS user guide](FIXME/MEN-5302) for a reference mutual
Same here

2022-02-14 14:33 UTC, alfrunes commented on 08.Server-integration/04.Mender-Gateway/99.Configuration-reference/docs.md
> +Show debugging logs.
To be honest, I'm not sure why this option lives in the configuration file. Wouldn't it make more sense to have this as a CLI flag? Maybe even allow filtering by log levels other than debug as well.

> Perhaps mention the default file (systemd would put it in)?

I'm not sure what file you refer to, @lluiscampos could you help me? :)

2022-02-14 14:38 UTC, lluiscampos commented on 08.Server-integration/04.Mender-Gateway/99.Configuration-reference/docs.md
> +Show debugging logs.
Thanks @alfrunes for raising this question.

I think we should remove it from the config file - we don't have such an configuration option in other components, have we? (at least on the client side of things I am confident we don't do this).

So I agree with you it should be a CLI flag. Can you remove it now from here and create a follow-up task for it?

2022-02-14 14:40 UTC, alfrunes commented on 08.Server-integration/04.Mender-Gateway/99.Configuration-reference/docs.md
> +<!-- Can't this be infered from ServerCertificate CommonName field? -->
Thanks, will do :)

2022-02-14 14:50 UTC, alfrunes commented on 08.Server-integration/04.Mender-Gateway/99.Configuration-reference/docs.md
> +title: Configuration reference
Well, to be precise it's "Configuration options" within "Configuration file" section. I'm renaming this to "Configuration file", but maybe we should tweak the other section titles as well?

2022-02-14 14:54 UTC, alfrunes commented on 08.Server-integration/04.Mender-Gateway/docs.md
> +![Mender gateway](mender-gateway-schema.png)
I asked @Valeria710 to have a look at it.

2022-02-15 07:56 UTC, lluiscampos commented on 08.Server-integration/04.Mender-Gateway/99.Configuration-reference/docs.md
> +Show debugging logs.
@alfrunes Yes! Let's do that

2022-02-15 07:59 UTC, lluiscampos approved these changes
All good from my side :green_circle: 

Except the CI failures, of course :wink: 

Wrt the links failure, either we rephrase it or we merge into a feature branch and let it fail there. I vote for the former.

2022-02-15 18:43 UTC, estenberg requested changes
What you have is nice, but a few things I did not catch in the previous round:

* Need note that this is Enterprise only. Should be simple, added suggestion.
* Nitpick: File path 04.Mender-Gateway/99.Configuration-reference should probably end with "Configuration-file" now that you change the title.
* This is such a major component that I think it needs to be covered here: https://docs.mender.io/overview/introduction. Would add a small section above "Client modes of operation" called e.g. "Mender Gateway" and have 2-3 sentences about why it exists, your diagram, and a link to your new section in "Server integration".

2022-02-15 18:43 UTC, estenberg commented on 08.Server-integration/04.Mender-Gateway/docs.md
> +
Please add:

!!!!! Mender Gateway is only available in the Mender Enterprise plan.
!!!!! See [the Mender features page](https://mender.io/plans/features?target=_blank)
!!!!! for an overview of all Mender plans and features.

2022-02-17 18:58 UTC, estenberg approved these changes
This is excellent.

Thanks for persisting all the nitpicks. :+1:

2022-02-18 08:51 UTC, alfrunes commented
@estenberg Sorry to bother you one more time. I had to rephrase the first paragraph to pass the passive check here:
https://github.com/alfrunes/mender-docs/blob/9543e8884c6dab950a6faffb9491edc8a56b59ef/08.Server-integration/04.Mender-Gateway/docs.md?plain=1#L11
Would you mind taking a quick look?

2022-02-18 18:18 UTC, estenberg commented
Wordsmithing is a bit tricky. I would suggest adjusting a bit:

In segregated networks, most devices may operate without
direct access to the Internet. In such networks, typically a only a gateway
has Internet access and offers a limited set of services to
devices in the local network.
_Mender Gateway_ is such an application service that runs on the gateway
and enables managing and deploying OTA updates to devices on the local network.
The gateway acts as a proxy with the ability to understand and serve client
requests locally.

2022-02-21 09:38 UTC, alfrunes commented
@estenberg Thanks for the precise feedback. I applied your suggestion - merging.

2022-02-21 09:38 UTC, merged

2022-02-21 17:56 UTC, estenberg commented
:tada: