feat: update the RBAC documentation to match the new implementation
mendersoftware/mender-docs pull request #1728
Opened 2022-03-30 19:26 UTC by tranchitella

Ticket: MEN-5499
Changelog: title

Signed-off-by: Fabio Tranchitella <fabio.tranchitella@northern.tech>

2022-03-31 11:44 UTC, mzedel requested changes
LGTM overall 👍. Only the "artifacts logs" would be better to have fixed before merging - the rest is subjective I think.

2022-03-31 11:44 UTC, mzedel commented on 02.Overview/12.Role.Based.Access.Control/docs.md
> +  * **Manage**: full write access to the releases and artifacts logs sections, requires **Read** and **Upload**.
```suggestion
  * **Upload**: upload-only access to the releases and artifacts sections.
  * **Manage**: full write access to the releases and artifacts sections, requires **Read** and **Upload**.
```

2022-03-31 11:44 UTC, mzedel commented on 02.Overview/12.Role.Based.Access.Control/docs.md
> +releases and User accounts, as well provide information about deployments.
```suggestion
releases and User accounts, as well as providing information about deployments.
```

2022-03-31 11:44 UTC, mzedel commented on 02.Overview/12.Role.Based.Access.Control/docs.md
> +  * **Read**: read access to the audit logs sections.
```suggestion
  * **Read**: read access to the audit log section.
```
This is probably rather subjective, as we have only one auditlog so far, but the details etc. should allow talking about _sections_ - so 🤷‍♂️ whatever you prefer.

2022-03-31 11:44 UTC, mzedel commented on 02.Overview/12.Role.Based.Access.Control/docs.md
> +* **Connect**: troubleshooting access to the devices, requires **Read**.
Here I'm not sure if the implications are clear enough... In the GUI I didn't want to mark the **Manage** right as required, since this is still a bit broader, but connecting to the device does also give write access, although "only" limited to what you can do on the live device, so likely not a full system update in the way **Manage** allows (unless the configured user is able to download & stand-alone install an update)...
Maybe:
_troubleshooting access to the device, also allows write access to the devices, requires **Read**_
but I'm not sure how detailed we should be here...

2022-03-31 12:52 UTC, tranchitella commented on 02.Overview/12.Role.Based.Access.Control/docs.md
> +* **Connect**: troubleshooting access to the devices, requires **Read**.
I added this sentence:

```
!!! Please note that the **Connect** permission gives users access to the Remote Terminal,
!!! File Transfer, and Port-forwarding features. Through these, it is possible to alter
!!! the devices locally, for example, changing the Mender Client configuration.
!!! Therefore, you can consider it a form of write access to the devices.
```

2022-03-31 14:13 UTC, mzedel approved these changes

2022-04-01 07:50 UTC, kjaskiewiczz approved these changes
looks good

2022-04-01 08:08 UTC, merged