feat: 2FA is now available in all plans
mendersoftware/mender-docs pull request #1806
Opened 2022-07-16 16:27 UTC by tranchitella

Changelog: Title
Ticket: MEN-5677

Signed-off-by: Fabio Tranchitella <fabio.tranchitella@northern.tech>

2022-07-18 06:43 UTC, merlin-northern requested changes

2022-07-18 06:43 UTC, merlin-northern commented on 02.Overview/11.Security/docs.md
>  Mender server, or via the web UI. In both cases, the connection is HTTPS
suggested change: "Mender server" -> "Mender _Server_" I think we address it with capital letters everywhere.

2022-07-18 06:43 UTC, merlin-northern commented on 02.Overview/11.Security/docs.md
> +by presenting a valid email address, password, and a Two Factor authentication
suggested change: "Two Factor authentication" -> "_two-factor_ authentication" no reason for the capital letters here?

2022-07-18 06:43 UTC, merlin-northern commented on 02.Overview/11.Security/docs.md
> +code if enabled. The client (e.g., web UI) used to log in then receives a JWT token
suggested change: "code" -> "_token_"

2022-07-18 06:43 UTC, merlin-northern commented on 02.Overview/11.Security/docs.md
> +code if enabled. The client (e.g., web UI) used to log in then receives a JWT token
this sentence "The client used to log in then receives a JWT token with a ..." does not make sense to me.

2022-07-18 08:26 UTC, kjaskiewiczz approved these changes

2022-07-18 09:32 UTC, 0lmi approved these changes
LGTM

2022-07-19 04:14 UTC, tranchitella commented
@merlin-northern ping

2022-07-19 05:55 UTC, merlin-northern commented
> @merlin-northern ping

PONG
yes I am here. sorry for the delay. on it.

2022-07-19 05:58 UTC, merlin-northern approved these changes
pre-approving not to block, one byte change requested. sorry for being picky.

2022-07-19 05:58 UTC, merlin-northern commented on 02.Overview/11.Security/docs.md
> +encrypted with TLS. A user must log in to authenticate with the Mender server
let's try to be consistent with the 'Mender Server' and 'Mender server' at least in those two lines.

2022-07-19 06:19 UTC, merlin-northern approved these changes

2022-07-19 06:36 UTC, merged