chore(pkcs#11): Add PKCS#11 documentation
mendersoftware/mender-docs pull request #1824
Opened 2022-08-24 14:35 UTC by MaciejTe

chore(pkcs#11): Add PKCS#11 documentation

Changelog: None
Ticket: MEN-5760
Signed-off-by: Maciej Tomczuk <maciej.tomczuk@northern.tech>

# External Contributor Checklist

🚨 Please review the [guidelines for contributing](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md) to this repository.

- [ ] Make sure that all commits follow the conventional commit [specification](https://www.github.com/mendersoftware/mendertesting/commitlint/grammar.md) for the Mender project.

The majority of our contributions are fixes, which means your commit should have
the form below:

```
fix: <SHORT DESCRIPTION OF FIX>

<OPTIONAL LONGER DESCRIPTION>

Changelog: <USER-FRIENDLY-CHANGE-DESCRIPTION> or <None>
Ticket: <TICKET NUMBER> or <None>
```

- [ ] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.

### Description

Please describe your pull request.

Thank you!

2022-08-25 07:40 UTC, lluiscampos commented on 06.Artifact-creation/07.Sign-and-verify/docs.md
> +dynamic_path = "/usr/lib/x86_64-linux-gnu/engines-1.1/pkcs11.so"
On latest Ubuntu, OpenSSL is on 3.0 version. For me the path is:
```suggestion
dynamic_path = "/usr/lib/x86_64-linux-gnu/engines-3/pkcs11.so"
```

So I this also deserves a note. Saying something like adjust `dynamic_path` according to your system. An easy way to find this file is to inspect the installed deb package with `dpkg -L libengine-pkcs11-openssl | grep /pkcs11.so`

2022-08-29 14:35 UTC, kjaskiewiczz commented on 06.Artifact-creation/07.Sign-and-verify/docs.md
> +dynamic_path = "/usr/lib/x86_64-linux-gnu/engines-1.1/pkcs11.so"
something like [this](https://github.com/kjaskiewiczz/mender-docs/commit/42ab8aa0890f52d88e1991fa45169742b340bd56)?

2022-08-30 05:39 UTC, tranchitella requested changes

2022-08-30 05:39 UTC, tranchitella commented on 06.Artifact-creation/07.Sign-and-verify/docs.md
> +MODULE_PATH = "~/smtools-linux-x64/smpkcs11.so"
This is a custom set up; smpkcs11 is a library provided by Digicert as part of the smtools package.
I don't think we should document it here.

2022-08-30 05:39 UTC, tranchitella commented on 06.Artifact-creation/07.Sign-and-verify/docs.md
> +!!! Engine shared object needs to be copied to proper location (in this case, SoftHSMv2 `~/smtools-linux-x64/smpkcs11.so` was used)
This is not true, look at what we do to set up softHSM in our tests:
https://github.com/mendersoftware/integration/blob/master/tests/tests/test_mtls.py#L130

2022-08-30 05:39 UTC, tranchitella commented on 06.Artifact-creation/07.Sign-and-verify/docs.md
> +## Supported cryptography standards
I would move this section to the bottom of the document.
Using PKCS#11 is a somewhat more advanced use cases than using file-based keys.

2022-08-30 07:10 UTC, lluiscampos commented on 06.Artifact-creation/07.Sign-and-verify/docs.md
> +dynamic_path = "/usr/lib/x86_64-linux-gnu/engines-1.1/pkcs11.so"
Yes :+1:

2022-08-31 11:02 UTC, tranchitella commented on 06.Artifact-creation/07.Sign-and-verify/docs.md
> +To make sure PKCS#11 engine is available for OpenSSL, issue following command:
```suggestion
To make sure PKCS#11 engine is available for OpenSSL, issue the following command:
```

2022-08-31 11:02 UTC, tranchitella commented on 06.Artifact-creation/07.Sign-and-verify/docs.md
> +After PKCS#11 engine is set up, artifact can be successfully signed with use of PKCS#11 URI:
```suggestion
Once the engine is set up, you can sign the Mender Artifact using a PKCS#11 URI:
```

2022-08-31 11:02 UTC, tranchitella commented on 06.Artifact-creation/07.Sign-and-verify/docs.md
> +PKCS#11 URI can also be used to verify signed artifacts:
```suggestion
You can also verify signed artifacts using the PKCS#11 interface:
```

2022-08-31 11:02 UTC, tranchitella commented on 06.Artifact-creation/07.Sign-and-verify/docs.md
> +You need to adjust MODULE_PATH according to your system.
```suggestion
You need to adjust MODULE_PATH according to your system and PKCS#11 interface.
```

2022-08-31 11:13 UTC, MaciejTe commented on 06.Artifact-creation/07.Sign-and-verify/docs.md
> +## Supported cryptography standards
Done!

2022-08-31 11:14 UTC, MaciejTe commented on 06.Artifact-creation/07.Sign-and-verify/docs.md
> +MODULE_PATH = "~/smtools-linux-x64/smpkcs11.so"
Done!

2022-08-31 11:16 UTC, MaciejTe commented on 06.Artifact-creation/07.Sign-and-verify/docs.md
> +Next, proceed to OpenSSL configuration file:
Done!

2022-08-31 11:16 UTC, MaciejTe commented on 06.Artifact-creation/07.Sign-and-verify/docs.md
> +To make sure PKCS#11 engine is available for OpenSSL, issue following command:
Done!

2022-08-31 11:17 UTC, MaciejTe commented on 06.Artifact-creation/07.Sign-and-verify/docs.md
> +After PKCS#11 engine is set up, artifact can be successfully signed with use of PKCS#11 URI:
Done!

2022-08-31 11:17 UTC, MaciejTe commented on 06.Artifact-creation/07.Sign-and-verify/docs.md
> +PKCS#11 URI can also be used to verify signed artifacts:
Done!

2022-08-31 11:17 UTC, MaciejTe commented on 06.Artifact-creation/07.Sign-and-verify/docs.md
> +You need to adjust MODULE_PATH according to your system.
Done!

2022-08-31 11:17 UTC, MaciejTe commented on 06.Artifact-creation/07.Sign-and-verify/docs.md
> +In order to sign an artifact using PKCS#11 interface, either hardware security modules (HSM), smart cards or Key Storage Provider (KSP) can be used.
Done!

2022-08-31 11:17 UTC, MaciejTe commented on 06.Artifact-creation/07.Sign-and-verify/docs.md
> +Mender supports following standards to interact with cryptographic tokens:
Done!

2022-08-31 11:17 UTC, MaciejTe commented on 06.Artifact-creation/07.Sign-and-verify/docs.md
> +!!! Engine shared object needs to be copied to proper location (in this case, SoftHSMv2 `~/smtools-linux-x64/smpkcs11.so` was used)
Done!

2022-08-31 11:26 UTC, tranchitella approved these changes
It looks good, I'd add two articles but I'm pre-approving.

2022-08-31 11:26 UTC, tranchitella commented on 06.Artifact-creation/07.Sign-and-verify/docs.md
> +You can use hardware security modules (HSMs), smart cards or Key Storage Provider (KSP) to sign an artifact using PKCS#11 interface.
```suggestion
You can use hardware security modules (HSMs), smart cards or Key Storage Provider (KSP) to sign an artifact using the PKCS#11 interface.
```

2022-08-31 11:26 UTC, tranchitella commented on 06.Artifact-creation/07.Sign-and-verify/docs.md
> +First, check if openssl and necessary libraries are installed:
```suggestion
First, check if openssl and the necessary libraries are installed:
```

2022-08-31 11:37 UTC, MaciejTe commented on 06.Artifact-creation/07.Sign-and-verify/docs.md
> +You can use hardware security modules (HSMs), smart cards or Key Storage Provider (KSP) to sign an artifact using PKCS#11 interface.
Done!

2022-08-31 11:37 UTC, MaciejTe commented on 06.Artifact-creation/07.Sign-and-verify/docs.md
> +First, check if openssl and necessary libraries are installed:
Done!

2022-08-31 11:51 UTC, merged