chore: Migration guide for users moving from HM to EU hosted MEnder
mendersoftware/mender-docs pull request #1888
Opened 2022-10-07 12:16 UTC by lluiscampos

2022-10-12 06:41 UTC, kacf requested changes

2022-10-12 06:41 UTC, kacf commented on 301.Troubleshoot/10.Hosted-Mender-migration/docs.md
> +Mender plans and features.
I think your editor's line breaker messed this up.

2022-10-12 06:41 UTC, kacf commented on 301.Troubleshoot/10.Hosted-Mender-migration/docs.md
> +The migration from one server to the other consists in three steps:
"consists **of** three"

2022-10-12 06:41 UTC, kacf commented on 301.Troubleshoot/10.Hosted-Mender-migration/docs.md
> +* From hosted Mender, deploy a software update to the your devices which contains an updated
"to ~the~ your devices"

2022-10-12 06:41 UTC, kacf commented on 301.Troubleshoot/10.Hosted-Mender-migration/docs.md
> +users performing the migration.
Same here, messed up `!!!`.

2022-10-12 06:41 UTC, kacf commented on 301.Troubleshoot/10.Hosted-Mender-migration/docs.md
> +!!! Note that this method will not work on generic instances of Mender server. It is only possible
"of **the** Mender server"

2022-10-12 06:41 UTC, kacf commented on 301.Troubleshoot/10.Hosted-Mender-migration/docs.md
> +!!!!! Migration to EU hosted Mender is only available in the Mender Enterprise plan. !!!!! See [the
Throughout: Should "hosted" be capitalized?

2022-10-12 06:41 UTC, kacf commented on 301.Troubleshoot/10.Hosted-Mender-migration/docs.md
> +### Preparing the configuration file
Use active voice: "Prepare"

2022-10-12 06:41 UTC, kacf commented on 301.Troubleshoot/10.Hosted-Mender-migration/docs.md
> +```
I'm wondering if simple edit instructions are better here. `jq` is not installed by default on Linux, and Mac probably doesn't have it at all. And it also risks being more confusing than manual edit steps.

2022-10-12 06:41 UTC, kacf commented on 301.Troubleshoot/10.Hosted-Mender-migration/docs.md
> +field of the configuration file.
Maybe specify "hosted Mender USA" or "old", just to be crystal clear.

2022-10-12 06:41 UTC, kacf commented on 301.Troubleshoot/10.Hosted-Mender-migration/docs.md
> +or via API. See [API
"or **the** API" ("via" doesn't fit the rest of the sentence above).

2022-10-12 06:41 UTC, kacf commented on 301.Troubleshoot/10.Hosted-Mender-migration/docs.md
> +To reject devices either use GUI
"use **the** GUI"

2022-10-12 06:42 UTC, kacf requested changes
Oops, forgot one.

2022-10-12 06:42 UTC, kacf commented on 301.Troubleshoot/10.Hosted-Mender-migration/docs.md
> +### Deploying the update
Active voice: Deploy

2022-10-19 17:53 UTC, lluiscampos commented on 301.Troubleshoot/10.Hosted-Mender-migration/docs.md
> +!!!!! Migration to EU hosted Mender is only available in the Mender Enterprise plan. !!!!! See [the
No. Although not everywhere, we refer to it as `hosted Mender` in most of the places in the docs.

2022-10-19 17:53 UTC, lluiscampos commented on 301.Troubleshoot/10.Hosted-Mender-migration/docs.md
> +!!!!! Migration to EU hosted Mender is only available in the Mender Enterprise plan. !!!!! See [the
(I'll add a new commit making it consistent everywhere)

2022-10-19 18:01 UTC, lluiscampos commented on 301.Troubleshoot/10.Hosted-Mender-migration/docs.md
> +```
I will verbosely explain what needs to be changed and add this block as something optional :+1:

2022-10-19 18:05 UTC, lluiscampos commented on 301.Troubleshoot/10.Hosted-Mender-migration/docs.md
> +field of the configuration file.
You are right, I am adding a new subsection so that it will look like:
* Prepare the configuration file
* Create the Mender Artifact
* Deploy the update

2022-10-20 08:20 UTC, kacf approved these changes

2022-10-20 08:20 UTC, kacf commented on 301.Troubleshoot/10.Hosted-Mender-migration/docs.md
> +`Servers` field of the configuration file.
"...found **in the** `Servers` field..."

2022-10-20 09:38 UTC, TheMeaningfulEngineer commented
Hey, please don't merge this just yet and thanks for inviting us for the review.
I want to go through the docs review process with @MuchoLucho and @estape11 (will try this evening).
This is a good concrete case for us to get started with the stronger involvement with the docs reviews.

2022-10-20 11:54 UTC, alfrunes commented on 301.Troubleshoot/10.Hosted-Mender-migration/docs.md
> +!!!!! overview of all Mender plans and features.
Should probably include in the notice that this has to go through a support request. We will need to replicate their data in Europe before they can start on this migration procedure.

2022-10-20 17:53 UTC, lluiscampos commented on 301.Troubleshoot/10.Hosted-Mender-migration/docs.md
> +!!!!! overview of all Mender plans and features.
Okey.

2022-10-21 11:02 UTC, alfrunes approved these changes

2022-10-24 12:34 UTC, merged