chore: improve mender convert docs
mendersoftware/mender-docs pull request #1901
Opened 2022-10-18 13:05 UTC by snusifer

See commit messages for each item improved

2022-10-19 07:45 UTC, oleorhagen approved these changes
Good job!

2022-10-19 13:17 UTC, snusifer commented
@lluiscampos might I get a second opinion/review on this, just in case?

2022-10-21 12:43 UTC, lluiscampos requested changes
See some comments below

> (...)There is also a point to make regarding [this pull](https://github.com/mendersoftware/mender-convert/pull/482). Perhaps we need some documentation regarding the bootstrap scripts themselves, and that one would need to pass it as an overlay to mender-convert?

As a follow-up, we could add such chapter, yes. I suggest we discuss it in Slack (mender-docs-team channel) and get the input from Customer Engineers.

2022-10-21 12:43 UTC, lluiscampos commented on 04.System-updates-Debian-family/02.Convert-a-Mender-Debian-image/docs.md
> +$MENDER_CONVERT_LOCATION/scripts/bootstrap-rootfs-overlay-hosted-server.sh \
You need to drop the first commit - it has been fixed (almost at the same time!) by Lucho at #1898

2022-10-21 12:43 UTC, lluiscampos commented on 04.System-updates-Debian-family/02.Convert-a-Mender-Debian-image/docs.md
> +
This part we should drop. Before we had to build the image but now we are publishing it so the recommended flow is just to pull it. See https://github.com/mendersoftware/mender-docs/commit/ddafd0a373b7499d2fac96a581a67069a31ec98d

2022-10-21 12:43 UTC, lluiscampos commented on 04.System-updates-Debian-family/02.Convert-a-Mender-Debian-image/01.Customization/docs.md
> +When passing multiple overlays mender-convert applies each overlay in the order
```suggestion
When passing multiple overlays `mender-convert` applies each overlay in the order
```

2022-10-26 08:50 UTC, lluiscampos approved these changes

2022-11-12 21:26 UTC, merged