chore: added required firewall URLs
mendersoftware/mender-docs pull request #1902
Opened 2022-10-18 16:03 UTC by oldgiova

Signed-off-by: Roberto Giovanardi <roberto.giovanardi@northern.tech>

# External Contributor Checklist

🚨 Please review the [guidelines for contributing](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md) to this repository.

- [x] Make sure that all commits follow the conventional commit [specification](https://www.github.com/mendersoftware/mendertesting/commitlint/grammar.md) for the Mender project.

The majority of our contributions are fixes, which means your commit should have
the form below:

```
fix: Adedd required firewall URLs

Changelog: Added required firewall URLs
Ticket: None
```

- [x] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.

### Description

Added required firewall URLs

2022-10-20 13:42 UTC, oleorhagen reviewed
We sure this should go in the `get started` section?

2022-10-20 13:47 UTC, oldgiova commented
> We sure this should go in the `get started` section?

No, [I'm not](https://northern-tech.slack.com/archives/C0XM0KX9C/p1666013833479779?thread_ts=1666000653.280789&cid=C0XM0KX9C) but it's the best way I found. Of course I'm open to suggestions

2022-10-20 14:15 UTC, TheMeaningfulEngineer requested changes
I agree with Ole about it not living in getting started.
2. Overview is a better candidate

2022-10-20 19:33 UTC, oldgiova commented on 01.Get-started/07.Server-requirements/docs.md
> +title: Requirements
This would limit the requirement page to just `Firewall requirements`. It's ok for me but in this case I have to add at least two different pages for my modification: Network requirements and Security requirements (S3 policies)

2022-10-24 17:36 UTC, oldgiova commented
Superseded by https://github.com/mendersoftware/mender-docs/pull/1914 and https://github.com/mendersoftware/mender-docs/pull/1913

2022-10-24 17:36 UTC, closed without merging