chore: added general requirements for 3.4
mendersoftware/mender-docs pull request #1913
Opened 2022-10-24 13:23 UTC by oldgiova

Signed-off-by: Roberto Giovanardi <roberto.giovanardi@northern.tech>

# External Contributor Checklist

🚨 Please review the [guidelines for contributing](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md) to this repository.

- [x] Make sure that all commits follow the conventional commit [specification](https://www.github.com/mendersoftware/mendertesting/commitlint/grammar.md) for the Mender project.

The majority of our contributions are fixes, which means your commit should have
the form below:

```
fix: added general requirements page

Changelog: Added general requirements page
Ticket: ME-7
```

- [x] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.

### Description

Added general requirements page with AWS S3 policy and with URL allowlist

Thank you!

2022-10-25 07:26 UTC, oleorhagen approved these changes

2022-10-25 07:26 UTC, oleorhagen commented on 02.Overview/16.Requirements/docs.md
> +Corporate Firewalls must permit the following URLs to the devices and for letting Mender works correctly:
```suggestion
Corporate Firewalls must permit the following URLs to the devices in order for Mender to work correctly:
```

2022-10-25 08:33 UTC, alfrunes approved these changes

2022-10-25 13:57 UTC, TheYoctoJester commented on 02.Overview/16.Requirements/docs.md
> +* `https://mender.example.com` - It's the same address you specify it in the [Server Installation Section](../../07.Server-installation/)
```suggestion
* `https://mender.example.com` - Use the same address you specify it in the [Server Installation Section](../../07.Server-installation/)
```

2022-10-25 13:58 UTC, TheYoctoJester commented on 02.Overview/16.Requirements/docs.md
> +If you use Amazon S3 for storing artifacts, you have to permit access to the following URLs:
```suggestion
Permit access to the following URLs:
```

2022-10-25 15:04 UTC, oldgiova commented on 02.Overview/16.Requirements/docs.md
> +If you use Amazon S3 for storing artifacts, you have to permit access to the following URLs:
Done

2022-10-25 15:27 UTC, TheYoctoJester requested changes

2022-10-25 15:27 UTC, TheYoctoJester commented on 02.Overview/16.Requirements/docs.md
> +If you are using Amazon S3 bucket for storing Mender Artifacts, you can use the following minimum policy set:
```suggestion
A minimum policy set to use an Amazon S3 bucket to store Mender Artifacts is:
```

2022-10-27 08:31 UTC, lluiscampos commented
@oldgiova Could you please sqash all changes into a single commit?

2022-10-27 08:35 UTC, TheYoctoJester commented on 02.Overview/16.Requirements/docs.md
> +Corporate Firewalls must permit the following URLs to the devices in order for Mender to work correctly:
```suggestion
The following URLs and access types need outgoing permissions in firewalls in order for Hosted Mender to work correctly:
```

(copied over from #1913 review)

2022-10-27 08:36 UTC, TheYoctoJester requested changes
Please use the sentence on firewalls in the suggestion, then I'm good with it.

2022-10-27 08:50 UTC, oldgiova commented on 02.Overview/16.Requirements/docs.md
> +Corporate Firewalls must permit the following URLs to the devices in order for Mender to work correctly:
Done

2022-10-27 08:54 UTC, TheYoctoJester approved these changes

2022-10-27 11:08 UTC, merged

2022-10-28 09:22 UTC, oldgiova commented
@mender-test-bot cherry-pick to:
3.4.x
3.3.x

2022-10-28 09:24 UTC, oldgiova commented
@mender-test-bot cherry-pick to:
* 3.4.x
* 3.3.x