chore(storage): Add information about all storage types and Azure Blob Storage
mendersoftware/mender-docs pull request #1917
Opened 2022-10-25 10:07 UTC by MaciejTe

chore(storage): Add information about all storage types and Azure Blob Storage

Changelog: Title
Ticket: MEN-5962
Signed-off-by: Maciej Tomczuk <maciej.tomczuk@northern.tech>

# External Contributor Checklist

🚨 Please review the [guidelines for contributing](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md) to this repository.

- [ ] Make sure that all commits follow the conventional commit [specification](https://www.github.com/mendersoftware/mendertesting/commitlint/grammar.md) for the Mender project.

The majority of our contributions are fixes, which means your commit should have
the form below:

```
fix: <SHORT DESCRIPTION OF FIX>

<OPTIONAL LONGER DESCRIPTION>

Changelog: <USER-FRIENDLY-CHANGE-DESCRIPTION> or <None>
Ticket: <TICKET NUMBER> or <None>
```

- [ ] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.

### Description

Please describe your pull request.

Thank you!

2022-10-26 11:01 UTC, alfrunes approved these changes

2022-10-26 11:01 UTC, alfrunes commented on 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
> +* Azure Blob Storage
It would nice to use the `ui-tabs` to have a tabulated view of the different configuration options.

2022-10-26 11:01 UTC, alfrunes commented on 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
> +>     AZURE_AUTH_SHARED_KEY_URI: "<shared-key-uri>"
The URI parameter is optional. If left unspecified, the URI is specified by the account and container name.

2022-10-26 11:02 UTC, alfrunes requested changes
Sorry, I approved by mistake above

2022-10-27 07:06 UTC, tranchitella requested changes

2022-10-27 07:06 UTC, tranchitella commented on 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
> +* Azure Blob Storage
```suggestion
* AWS S3 (or AWS S3 API-compatible storage layers, e.g., MinIO)
* Azure Blob Storage
```

2022-10-27 07:06 UTC, tranchitella commented on 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
> +> To store the Mender artifacts in an *AWS S3 bucket* instead of relying on a Minio service, update
```suggestion
> To store the Mender Artifacts in an *AWS S3 bucket* instead of relying on a Minio service, update
```

2022-10-27 07:06 UTC, tranchitella commented on 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
> +> To store the Mender artifacts in an *Azure Blob Storage* container using *connection string*:
```suggestion
> To store the Mender Artifacts in an *Azure Blob Storage* container using a *connection string*:
```

2022-10-27 07:06 UTC, tranchitella commented on 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
> +>     AZURE_AUTH_CONNECTION_STRING: "BlobEndpoint=https://<name-of-your-storage>.blob.core.windows.net;SharedAccessSignature=sv=2023-04-05&amp;sr=b&amp;si=tutorial-policy-635959936145100803&amp;sig=9
```suggestion
>     AUTH_CONNECTION_STRING: "BlobEndpoint=https://<name-of-your-storage>.blob.core.windows.net;SharedAccessSignature=..."
```

2022-10-27 07:06 UTC, tranchitella commented on 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
> +>     AZURE_AUTH_SHARED_KEY_URI: "<shared-key-uri>"
```suggestion
>     AUTH_SHARED_KEY_ACCOUNT_NAME: "<account-name>"
>     AUTH_SHARED_KEY_ACCOUNT_KEY: "<account-key>"
>     AUTH_SHARED_KEY_URI: "<shared-key-uri>"
```

2022-10-27 08:35 UTC, MaciejTe commented on 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
> +* Azure Blob Storage
Done!

2022-10-27 08:35 UTC, MaciejTe commented on 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
> +>     AZURE_AUTH_SHARED_KEY_URI: "<shared-key-uri>"
Done!

2022-10-27 08:36 UTC, MaciejTe commented on 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
> +* Azure Blob Storage
Done!

2022-10-27 08:36 UTC, MaciejTe commented on 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
> +> To store the Mender artifacts in an *AWS S3 bucket* instead of relying on a Minio service, update
Done!

2022-10-27 08:36 UTC, MaciejTe commented on 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
> +> To store the Mender artifacts in an *Azure Blob Storage* container using *connection string*:
Done!

2022-10-27 08:36 UTC, MaciejTe commented on 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
> +>     AZURE_AUTH_CONNECTION_STRING: "BlobEndpoint=https://<name-of-your-storage>.blob.core.windows.net;SharedAccessSignature=sv=2023-04-05&amp;sr=b&amp;si=tutorial-policy-635959936145100803&amp;sig=9
Done!

2022-10-27 08:36 UTC, MaciejTe commented on 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
> +>     AZURE_AUTH_SHARED_KEY_URI: "<shared-key-uri>"
Done!

2022-10-27 08:36 UTC, MaciejTe commented on 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
> +>   azure:
Done!

2022-10-27 08:36 UTC, MaciejTe commented on 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
> +>   azure:
Done!

2022-10-30 15:00 UTC, tranchitella requested changes
Sorry for being so picky, but I still think the text needs a bit of adjustements.

2022-10-30 15:00 UTC, tranchitella commented on 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
> +[ui-tab title="AWS"]
```suggestion
[ui-tab title="AWS S3"]
```

2022-10-30 15:00 UTC, tranchitella commented on 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
> +[ui-tab title="Azure"]
```suggestion
[ui-tab title="Azure Blob Storage"]
```

2022-10-30 15:00 UTC, tranchitella commented on 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
> +> To store the Mender Artifacts in an *Azure Blob Storage* container using *connection string*:
```suggestion
> To store the Mender Artifacts in an *Azure Blob Storage* container using a *connection string*, update the values file as follows:
```

2022-10-30 15:00 UTC, tranchitella commented on 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
> +>     AZURE_AUTH_CONNECTION_STRING: "BlobEndpoint=https://<name-of-your-storage>.blob.core.windows.net;SharedAccessSignature=..."
```suggestion
>     AUTH_CONNECTION_STRING: "BlobEndpoint=https://<name-of-your-storage>.blob.core.windows.net;SharedAccessSignature=..."
```

2022-10-30 15:00 UTC, tranchitella commented on 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
> +> Instead of connection string you can also use a connection of these parameters:
```suggestion
> Instead of a connection string, you can also specify the following parameters:
```

2022-10-30 15:00 UTC, tranchitella commented on 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
> +Mender supports following artifact storages:
```suggestion
Mender supports the following Artifact storage types:
```

2022-10-31 11:01 UTC, MaciejTe commented on 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
> +[ui-tab title="AWS"]
Done!

2022-10-31 11:02 UTC, MaciejTe commented on 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
> +[ui-tab title="Azure"]
Done!

2022-10-31 11:02 UTC, MaciejTe commented on 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
> +> To store the Mender Artifacts in an *Azure Blob Storage* container using *connection string*:
Done!

2022-10-31 11:02 UTC, MaciejTe commented on 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
> +>     AZURE_AUTH_CONNECTION_STRING: "BlobEndpoint=https://<name-of-your-storage>.blob.core.windows.net;SharedAccessSignature=..."
Done!

2022-10-31 11:02 UTC, MaciejTe commented on 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
> +> Instead of connection string you can also use a connection of these parameters:
Done!

2022-10-31 11:02 UTC, MaciejTe commented on 07.Server-installation/04.Production-installation-with-kubernetes/05.Mender-server/docs.md
> +Mender supports following artifact storages:
Done!

2022-11-04 11:16 UTC, tranchitella approved these changes

2022-11-04 11:45 UTC, alfrunes approved these changes

2022-11-04 13:29 UTC, merged