feat(CI/CD): Add CI/CD documentation
mendersoftware/mender-docs pull request #1922
Opened 2022-10-28 10:43 UTC by MaciejTe

feat(CI/CD): Add CI/CD documentation

Changelog: Title
Ticket: MEN-5893
Signed-off-by: Maciej Tomczuk <maciej.tomczuk@northern.tech>

# External Contributor Checklist

🚨 Please review the [guidelines for contributing](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md) to this repository.

- [ ] Make sure that all commits follow the conventional commit [specification](https://www.github.com/mendersoftware/mendertesting/commitlint/grammar.md) for the Mender project.

The majority of our contributions are fixes, which means your commit should have
the form below:

```
fix: <SHORT DESCRIPTION OF FIX>

<OPTIONAL LONGER DESCRIPTION>

Changelog: <USER-FRIENDLY-CHANGE-DESCRIPTION> or <None>
Ticket: <TICKET NUMBER> or <None>
```

- [ ] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.

### Description

Please describe your pull request.

Thank you!

2022-10-31 08:47 UTC, lluiscampos reviewed
The direction looks good, this is more or less the idea I had. See comments.

Also, let's create a feature branch and target this PR there. I'll update the acceptance criteria of the task with this.

2022-10-31 08:47 UTC, lluiscampos commented on 06.Artifact-creation/10.CI-CD/docs.md
> +To help you in creating CI/CD pipelines, we created Github repository containing ready to use, battle-tested CI/CD pipeline templates that can be used your workflows. Additionally, we provide docker
Docker

2022-10-31 08:47 UTC, lluiscampos commented on 06.Artifact-creation/10.CI-CD/docs.md
> +To help you in creating CI/CD pipelines, we created Github repository containing ready to use, battle-tested CI/CD pipeline templates that can be used your workflows. Additionally, we provide docker
What is the name of the Docker image? We should have it (with a link to Docker Hub)

2022-10-31 08:47 UTC, lluiscampos commented on 06.Artifact-creation/10.CI-CD/docs.md
> +To help you in creating CI/CD pipelines, we created Github repository containing ready to use, battle-tested CI/CD pipeline templates that can be used your workflows. Additionally, we provide docker
We should also add a note in the Downloads sections of `mender-artifact` and `mender-cli` to inform about this new Docker image

2022-10-31 08:47 UTC, lluiscampos commented on 06.Artifact-creation/10.CI-CD/docs.md
> +Location: https://github.com/mendersoftware/mender-ci-workflows
Looks a bit cryptic. What about something like "The CI/CD templates can be found at mender-ci-workflows repository" (with a link to the GitHub repo)

2022-10-31 08:47 UTC, lluiscampos commented on 06.Artifact-creation/10.CI-CD/docs.md
> +* Circle CI
Let's write for now only the three major ones that we are committed to support
```suggestion
* GitHub Actions
* Gitlab
* Azure DevOps
```

and we can add more as we go

2022-10-31 08:47 UTC, lluiscampos commented on 06.Artifact-creation/10.CI-CD/docs.md
> +* Gitlab
`GitLab` or `GitLab CI/CD`

2022-10-31 08:47 UTC, lluiscampos commented on 06.Artifact-creation/10.CI-CD/docs.md
> +More details about signing Mender Artifacts: https://docs.mender.io/artifact-creation/sign-and-verify
These links need to be proper markdown syntax.

2022-10-31 08:47 UTC, lluiscampos commented on 06.Artifact-creation/10.CI-CD/docs.md
> +### Signing an Mender Artefact
Here and below
```suggestion
### Signing an Mender Artifact
```

2022-10-31 08:47 UTC, lluiscampos commented on 06.Artifact-creation/10.CI-CD/docs.md
> +* Circle CI
Let's also create the subpages for these three (empty content for now) so that we can link them from here.

2022-10-31 08:47 UTC, lluiscampos commented on 06.Artifact-creation/10.CI-CD/docs.md
> +
The direction is good. The use cases need to be well described not assuming much knowledge of Mender ecosystem.

2022-11-03 10:56 UTC, MaciejTe commented on 06.Artifact-creation/10.CI-CD/docs.md
> +To help you in creating CI/CD pipelines, we created Github repository containing ready to use, battle-tested CI/CD pipeline templates that can be used your workflows. Additionally, we provide docker
Done!

2022-11-03 10:56 UTC, MaciejTe commented on 06.Artifact-creation/10.CI-CD/docs.md
> +To help you in creating CI/CD pipelines, we created Github repository containing ready to use, battle-tested CI/CD pipeline templates that can be used your workflows. Additionally, we provide docker
Done, thanks!

2022-11-03 10:56 UTC, MaciejTe commented on 06.Artifact-creation/10.CI-CD/docs.md
> +To help you in creating CI/CD pipelines, we created Github repository containing ready to use, battle-tested CI/CD pipeline templates that can be used your workflows. Additionally, we provide docker
Done, thanks!

2022-11-03 10:56 UTC, MaciejTe commented on 06.Artifact-creation/10.CI-CD/docs.md
> +* Circle CI
Done, thanks!

2022-11-03 10:56 UTC, MaciejTe commented on 06.Artifact-creation/10.CI-CD/docs.md
> +### Signing an Mender Artefact
Done!

2022-11-03 10:56 UTC, MaciejTe commented on 06.Artifact-creation/10.CI-CD/docs.md
> +More details about signing Mender Artifacts: https://docs.mender.io/artifact-creation/sign-and-verify
Done!

2022-11-03 10:57 UTC, MaciejTe commented on 06.Artifact-creation/10.CI-CD/docs.md
> +* Gitlab
Done!

2022-11-03 13:14 UTC, MaciejTe commented on 06.Artifact-creation/10.CI-CD/docs.md
> +
Thanks! Please let me know if the current docs are satisfying for you, then I'll create feature branch.

2022-11-07 13:23 UTC, lluiscampos requested changes
Please rebase your patch on top of latest master and set as target branch `feature-cicd-pipelines`.

See comments for suggested improvements

2022-11-07 13:23 UTC, lluiscampos commented on 01.Get-started/03.Deploy-a-system-update/docs.md
> +!!! `mender-artifact` binary is shipped also in [Docker image](https://hub.docker.com/r/mendersoftware/mender-ci-tools). More information [here](../../06.Artifact-creation/10.CI-CD/docs.md#mender-ci-
This one here I would remove. This tutorial is meant to use the binary directly, so having this info here is not giving a real alternative.

2022-11-07 13:23 UTC, lluiscampos commented on 06.Artifact-creation/10.CI-CD/docs.md
> +    label: tutorial
This is not really a tutorial. Remove this line.

2022-11-07 13:23 UTC, lluiscampos commented on 06.Artifact-creation/10.CI-CD/docs.md
> +To help you in creating CI/CD pipelines, we created Github repository containing ready to use, battle-tested CI/CD pipeline templates that can be used your workflows. Additionally, we provide [Docker
Missing a link to the repository.

"... we created **a** [Github repository](https://github.com/mendersoftware/mender-ci-workflows/) containing..."

Also, let's be more generic with:

"battle-tested CI/CD pipeline code snippets that can be used your workflows"

(let's avoid "actions" or "templates" keywords here)

2022-11-07 13:23 UTC, lluiscampos commented on 09.Downloads/docs.md
> +!!! `mender-artifact` binary is shipped also in [Docker image](https://hub.docker.com/r/mendersoftware/mender-ci-tools). More information [here](../06.Artifact-creation/10.CI-CD/docs.md#mender-ci-wor
```suggestion
!!! `mender-artifact` binary is shipped also in [mender-ci-tools Docker image](https://hub.docker.com/r/mendersoftware/mender-ci-tools). More information [here](../06.Artifact-creation/10.CI-CD/docs.md#mender-ci-workflows-docker-image).
```

(same below)

2022-11-07 13:23 UTC, lluiscampos commented on 06.Artifact-creation/10.CI-CD/docs.md
> +
No, sorry. We need a bit more of an introduction to each scenario.. See comment for `Creating and Signing an Mender Artifact` and let's do something similar to the rest.

2022-11-07 13:23 UTC, lluiscampos commented on 06.Artifact-creation/10.CI-CD/docs.md
> +More details about signing Mender Artifacts [here](https://docs.mender.io/artifact-creation/sign-and-verify).
```suggestion
This scenario uses `mender-artifact` tool to package your software as a Mender Artifact. A Mender Artifact can optionally be signed, so the examples provided allow for signing the Artifact too.

The input for the scenario is the software being packaged and the output is a Mender Artifact.

You can read about artifact creation details [here](../01.Create-an-Artifact/docs.md#create-a-full-filesystem-update-artifact).

More details about signing Mender Artifacts [here](https://docs.mender.io/artifact-creation/sign-and-verify).
```

2022-11-07 13:23 UTC, lluiscampos commented on 06.Artifact-creation/10.CI-CD/docs.md
> +More details about signing Mender Artifacts [here](https://docs.mender.io/artifact-creation/sign-and-verify).
Please add something similar in the other scenarios, mentioning what is the expected input and output.

2022-11-07 13:23 UTC, lluiscampos commented on 06.Artifact-creation/10.CI-CD/docs.md
> +To help you in creating CI/CD pipelines, we created Github repository containing ready to use, battle-tested CI/CD pipeline templates that can be used your workflows. Additionally, we provide [Docker
"We provide mender-ci-tools Docker image based on Alpine Linux and providing command-line utilities...."

2022-11-07 13:23 UTC, lluiscampos commented on 06.Artifact-creation/10.CI-CD/docs.md
> +In order to pull the image, you need to issue following command:
```suggestion
To locally inspect the Docker image, pull it with the following command:
```

2022-11-07 13:47 UTC, MaciejTe commented on 06.Artifact-creation/10.CI-CD/docs.md
> +In order to pull the image, you need to issue following command:
Done!

2022-11-07 13:47 UTC, MaciejTe commented on 09.Downloads/docs.md
> +!!! `mender-artifact` binary is shipped also in [Docker image](https://hub.docker.com/r/mendersoftware/mender-ci-tools). More information [here](../06.Artifact-creation/10.CI-CD/docs.md#mender-ci-wor
Done!

2022-11-07 13:47 UTC, MaciejTe commented on 06.Artifact-creation/10.CI-CD/docs.md
> +To help you in creating CI/CD pipelines, we created Github repository containing ready to use, battle-tested CI/CD pipeline templates that can be used your workflows. Additionally, we provide [Docker
Done!

2022-11-07 13:47 UTC, MaciejTe commented on 06.Artifact-creation/10.CI-CD/docs.md
> +    label: tutorial
Done!

2022-11-07 13:47 UTC, MaciejTe commented on 01.Get-started/03.Deploy-a-system-update/docs.md
> +!!! `mender-artifact` binary is shipped also in [Docker image](https://hub.docker.com/r/mendersoftware/mender-ci-tools). More information [here](../../06.Artifact-creation/10.CI-CD/docs.md#mender-ci-
Done!

2022-11-07 13:48 UTC, MaciejTe commented on 06.Artifact-creation/10.CI-CD/docs.md
> +More details about signing Mender Artifacts [here](https://docs.mender.io/artifact-creation/sign-and-verify).
Done plase let me know how `Deploying an Artifact to the fleet of devices` section should look like: given various CI/CD providers, there's no single solution here.

2022-11-07 14:18 UTC, MaciejTe commented on 06.Artifact-creation/10.CI-CD/docs.md
> +More details about signing Mender Artifacts [here](https://docs.mender.io/artifact-creation/sign-and-verify).
Pushed changes after chat discussion, thanks!

2022-11-07 14:21 UTC, lluiscampos approved these changes

2022-11-07 14:24 UTC, merged