Add section on phased rollouts for dynamic groups
mendersoftware/mender-docs pull request #1955
Opened 2022-12-01 14:04 UTC by TheMeaningfulEngineer

Changelog: Title

Ticket: None
Signed-off-by: Alan Martinovic <alan.martinovic@northern.tech>

2022-12-01 18:59 UTC, lluiscampos commented
> @lluiscampos Added you with hopes you can help me understand whats causing the test to fail.

You are submitting this PR from a branch that it is many months old :sweat_smile: 

![image](https://user-images.githubusercontent.com/3168644/205136924-61baafc3-9081-48eb-8ca1-39ad539d7bf4.png)

If you rebase on top of `mendersoftware/master` the failing tests should pass.

Note that your commit is not following the [modern commit syntax](https://github.com/mendersoftware/mendertesting/blob/master/commitlint/grammar.md) so _that_ CI check will fail after the rebase.

2022-12-02 09:29 UTC, TheMeaningfulEngineer commented
@lluiscampos Thanks, my bad :)

2022-12-03 14:21 UTC, kjaskiewiczz approved these changes

2022-12-05 10:12 UTC, TheYoctoJester requested changes

2022-12-05 10:12 UTC, TheYoctoJester commented on 02.Overview/05.Deployment/docs.md
> +The calculation for the number of devices in a phases uses the total number of devices in the dynamic group during deployment creation.
```suggestion
The calculation for the number of devices in a phases uses the total number of devices in the dynamic group at the moment of deployment creation.
```

2022-12-05 10:12 UTC, TheYoctoJester commented on 02.Overview/05.Deployment/docs.md
> +The nature of deployments to a dynamic group is that the total number of devices receiving the update can change during the lifetime of the update.
```suggestion
The nature of deployments to a dynamic group is that the total number of devices receiving the update can change during the lifetime of the deployment.
```

2022-12-05 10:12 UTC, TheYoctoJester commented on 02.Overview/05.Deployment/docs.md
> +Instead the last phase will be expanded to contain all remaining device.
What happens if the number goes down? Maybe even to an extend that would run the last group into negative?

2022-12-05 10:12 UTC, TheYoctoJester commented on 02.Overview/05.Deployment/docs.md
> +!! The time when each device receives an update depends only on the time it contacts the server.
```suggestion
!! The exact time a specific device receives a deployed artifact is not determined by the server, but the concrete moment the device contacts the server following its polling cycle.
```

2022-12-05 10:12 UTC, TheYoctoJester commented on 02.Overview/05.Deployment/docs.md
> +!! This means that it's possible that devices which joined the group after the deployment started, get updated as part of the first phase.
```suggestion
!! This means it is possible that devices which joined the group after the deployment started, get updated as part of the first phase.
```

2022-12-05 10:12 UTC, TheYoctoJester commented on 02.Overview/05.Deployment/docs.md
> +Dynamic group has 100 devices during the creation of the deployment.
```suggestion
A dynamic group has 100 devices during the creation of the deployment.
```

2022-12-05 10:53 UTC, TheMeaningfulEngineer commented on 02.Overview/05.Deployment/docs.md
> +Instead the last phase will be expanded to contain all remaining device.
> Maybe even to an extend that would run the last ~group~ phase into negative?

I assume you mean "phase" instead of group.
Distinction important for this conversation as there are:
* devices being a part of a dynamic group
* phase - which has a number of deployments that need to happen within it (unrelated to the exact devices which ask for as long as they originate from the dynamic group)

A follow up here though at least to my understanding.
There isn't such a thing as a negative number for the phases.
It is calculated at start and remains unchanged.

---

Good catch!
If it goes down I guess it would then all devices will be covered in a single phase and nothing will happen in the later phases.

@kjaskiewiczz 
Can you please confirm and I'll follow up with an update the docs.

2022-12-12 16:26 UTC, TheMeaningfulEngineer commented on 02.Overview/05.Deployment/docs.md
> +Instead the last phase will be expanded to contain all remaining device.
Updated

2022-12-13 08:23 UTC, kjaskiewiczz approved these changes

2022-12-13 08:27 UTC, merged