feat: document the server-side generation of Delta Artifacts
mendersoftware/mender-docs pull request #1967
Opened 2022-12-10 14:36 UTC by tranchitella

Changelog: Title
Ticket: MEN-5807

Signed-off-by: Fabio Tranchitella <fabio.tranchitella@northern.tech>

2022-12-12 10:34 UTC, kjaskiewiczz approved these changes
looks good

2022-12-12 10:34 UTC, kjaskiewiczz commented on 06.Artifact-creation/05.Server-Side-Generation-of-Delta-Artifacts/docs.md
> +You can specify a timeout for the generation job; the Mender Server will abort it if it takes more than the given amount of seconds.
not entirely true, because currently it's not possible to abort the job, but at least we can serve full image after timeout

2022-12-12 11:00 UTC, lluiscampos requested changes

2022-12-12 11:00 UTC, lluiscampos commented on 06.Artifact-creation/05.Server-Side-Generation-of-Delta-Artifacts/docs.md
> +* `rootfs-image.update-module.mender-binary-delta.version: <version>`
Inventory keys won't be sufficient, these need to be in the `mender show-provides` (no inventory is sent to `deployments/next` endpoint, only the provides).

The alternative should be building and installing a empty artifact, with something like:
```suggestion
Otherwise, create and install your own bootstrap Artifact to provide these keys:

\```
mender-artifact write bootstrap-artifact \
        --artifact-name mender-binary-delta-provide-keys \
        --device-type <dev-type> \
        --provides "rootfs-image.update-module.mender-binary-delta.mender_update_module:mender-binary-delta" \
        --provides "rootfs-image.update-module.mender-binary-delta.version:<version>" \
        --output-path mender-binary-delta-provide-keys.mender

The Artifact can be installed either in standalone mode or deployed remotely with the Mender server.
\```
```

2022-12-12 11:00 UTC, lluiscampos commented on 06.Artifact-creation/05.Server-Side-Generation-of-Delta-Artifacts/docs.md
> +Additionally, to make the Server-Side Generation of Delta Artifacts possible, both the Mender Artifacts of the current version of the firmware (`rootfs`) running on your device and the updated one mu
The delta Artifact (as per today) is done from only one Artifact:
```suggestion
Additionally, to make the Server-Side Generation of Delta Artifacts possible, both the Mender Artifact of the current version of the firmware (`rootfs`) running on your device and the updated one must be available as Artifacts on the Mender Server.
```

2022-12-12 11:00 UTC, lluiscampos commented on 06.Artifact-creation/05.Server-Side-Generation-of-Delta-Artifacts/docs.md
> +Additionally, to make the Server-Side Generation of Delta Artifacts possible, both the Mender Artifacts of the current version of the firmware (`rootfs`) running on your device and the updated one mu
Also "of the current version of the firmware ...", rephrase to "of the current firmware version"

2022-12-12 11:00 UTC, lluiscampos commented on 06.Artifact-creation/05.Server-Side-Generation-of-Delta-Artifacts/docs.md
> +Please note that if the Server cannot generate the Delta Artifact, it will automatically fall back to the non-Delta Artifact. This can happen, for example, because the Device is not reporting the ava
```suggestion
Please note that if the Server cannot generate the Delta Artifact, it will automatically fall back to the non-Delta Artifact. This can happen, for example, because the Device is not reporting the availability of the Binary Delta Update Module through the `provides` database keys, or if the Mender Artifact containing the firmware (`rootfs`) version the Device is currently running on is not available in the Mender Server.
```

2022-12-12 15:20 UTC, kjaskiewiczz commented on 06.Artifact-creation/05.Server-Side-Generation-of-Delta-Artifacts/docs.md
> +Additionally, to make the Server-Side Generation of Delta Artifacts possible, both the Mender Artifacts of the current version of the firmware (`rootfs`) running on your device and the updated one mu
> The delta Artifact (as per today) is done from only one Artifact

not sure I understand; you need two artifacts to generate delta

2022-12-12 17:54 UTC, tranchitella commented on 06.Artifact-creation/05.Server-Side-Generation-of-Delta-Artifacts/docs.md
> +Additionally, to make the Server-Side Generation of Delta Artifacts possible, both the Mender Artifacts of the current version of the firmware (`rootfs`) running on your device and the updated one mu
I agree, we need both; it's plural because you need both the current version AND the updated one.

2022-12-12 17:55 UTC, tranchitella commented
@lluiscampos ready for a second round of reviews

2022-12-13 09:26 UTC, TheYoctoJester reviewed
Some remarks

2022-12-13 09:26 UTC, TheYoctoJester commented on 06.Artifact-creation/05.Server-Side-Generation-of-Delta-Artifacts/docs.md
> +To support the Server-Side Generation of Delta Artifacts, your device must report to the server the availability of the `mender-binary-delta` Update Module.
Why is "Server-Side Generation" always capitalized? To me this is neither a term that refers to our brand, nor is it mentioned in the [taxonomy](https://docs.mender.io/overview/taxonomy), so my feeling is that is should be common casing in the English language.

2022-12-13 09:26 UTC, TheYoctoJester commented on 06.Artifact-creation/05.Server-Side-Generation-of-Delta-Artifacts/docs.md
> +This will happen automatically if you are building your firmware using Yocto and the latest version of the `meta-mender` layer.
Not only on the latest, that might be confusing.

2022-12-13 09:26 UTC, TheYoctoJester commented on 06.Artifact-creation/05.Server-Side-Generation-of-Delta-Artifacts/docs.md
> +If the Delta Artifact already exists, the Mender Server selects it and sends the corresponding deployment instructions to the Device. However, if the Delta Artifact does not exist, it will start a De
```suggestion
If the Delta Artifact already exists, the Mender Server selects it and sends the corresponding deployment instructions to the Device. However, if the Delta Artifact does not exist, it will start a Delta Artifact generation job in the background to create it. In this case, the Device will temporarily receive a `No updates` response for the Server. In the next update polling cycle after the Delta Artifact generation has finished, the resulting Delta artifact will be served to the Device.
```

2022-12-13 09:26 UTC, TheYoctoJester commented on 06.Artifact-creation/05.Server-Side-Generation-of-Delta-Artifacts/docs.md
> +Please note that if the Server cannot generate the Delta Artifact, it will automatically fall back to the non-Delta Artifact. This can happen, for example, because the Device is not reporting the ava
```suggestion
Please note that if the Server cannot generate the Delta Artifact, it will automatically fall back to the non-Delta Artifact. Possible reasons are:
- the Device is not reporting the availability of the Binary Delta Update Module through the `provides` database keys
- the Mender Artifact containing the firmware (`rootfs`) version the Device is currently running on is not available in the Mender Server.
```

2022-12-13 09:26 UTC, TheYoctoJester commented on 06.Artifact-creation/05.Server-Side-Generation-of-Delta-Artifacts/docs.md
> +The settings apply to the newly generated Delta Artifacts only. Existing Delta Artifacts previously updated to the Mender Server won't be affected by the changes to these values.
```suggestion
The settings apply to the newly generated Delta Artifacts only. Existing Delta Artifacts previously uploaded to the Mender Server won't be affected by the changes to these values.
```

2022-12-13 13:47 UTC, TheYoctoJester reviewed
Two minor remarks, but I am also okay to merge as is.

2022-12-13 13:47 UTC, TheYoctoJester commented on 06.Artifact-creation/05.Server-side-generation-of-Delta-Artifacts/docs.md
> +To support the server-side generation of Delta Artifacts, your device must report to the server the availability of the `mender-binary-delta` Update Module.
```suggestion
To support the server-side generation of Delta Artifacts, your device must report the availability of the `mender-binary-delta` Update Module to the server.
```

2022-12-13 13:47 UTC, TheYoctoJester commented on 06.Artifact-creation/05.Server-side-generation-of-Delta-Artifacts/docs.md
> +Additionally, to make the server-side generation of Delta Artifacts possible, both the Mender Artifacts of the current version of the firmware (`rootfs`) running on your device and the updated one mu
```suggestion
Additionally, to make the server-side generation of Delta Artifacts possible, both the Mender Artifact of the current version of the [`rootfs-image`](https://github.com/mendersoftware/mender-artifact/blob/3.9.0/Documentation/artifact-format-v3.md#header-info) running on your device and the updated one must be available as Artifact on the Mender Server.
```

The expression "firmware" occurs a few more times. Not sure how to word this in a nice way. I'd like to have the link to the artifact format, as this specifically applies to the `rootfs-image` kind. Maybe a short line that explains the term firmware as referring to only this, and then sticking to "firmware" without the (`rootfs`) appendix

2022-12-13 20:11 UTC, TheYoctoJester approved these changes

2022-12-14 07:18 UTC, lluiscampos commented on 06.Artifact-creation/05.Server-Side-Generation-of-Delta-Artifacts/docs.md
> +Additionally, to make the Server-Side Generation of Delta Artifacts possible, both the Mender Artifacts of the current version of the firmware (`rootfs`) running on your device and the updated one mu
It might be my grammar miss-understanding. But let me retry,

To me in reads like "both _the_ Mender Artifacts ... running on your device (meaning: all the Artifacts running there) and _the_ updated one...".

"I like both _the_ cake and _the_ ice cream" is not the same as "I like both _the_ cakes and _the_ ice cream"

2022-12-14 07:26 UTC, tranchitella commented on 06.Artifact-creation/05.Server-Side-Generation-of-Delta-Artifacts/docs.md
> +Additionally, to make the Server-Side Generation of Delta Artifacts possible, both the Mender Artifacts of the current version of the firmware (`rootfs`) running on your device and the updated one mu
I reworded it, and I dropped "both" and made Mender Artifact singular.

2022-12-14 07:36 UTC, merged