docs: adds troubleshoot guidance for delta issues
mendersoftware/mender-docs pull request #1974
Opened 2022-12-23 15:39 UTC by MuchoLucho

Includes several places where you can take a look if there is any issue with the delta updates feature

Changelog: None
Ticket: None

Signed-off-by: Luis Ramirez Vargas <luis.ramirez@northern.tech>

# External Contributor Checklist

🚨 Please review the [guidelines for contributing](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md) to this repository.

- [ ] Make sure that all commits follow the conventional commit [specification](https://www.github.com/mendersoftware/mendertesting/commitlint/grammar.md) for the Mender project.

The majority of our contributions are fixes, which means your commit should have
the form below:

```
fix: <SHORT DESCRIPTION OF FIX>

<OPTIONAL LONGER DESCRIPTION>

Changelog: <USER-FRIENDLY-CHANGE-DESCRIPTION> or <None>
Ticket: <TICKET NUMBER> or <None>
```

- [ ] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.

### Description

Please describe your pull request.

Thank you!

2022-12-23 15:49 UTC, TheMeaningfulEngineer commented
@MuchoLucho  Seems like you made a branch directly in the repo instead of your fork. Not much difference practically but was sure this wasn't allowed.

@lluiscampos Don't have much opinion on this, do comment if this needs to come from a fork instead.

2022-12-23 15:57 UTC, TheMeaningfulEngineer reviewed
LGTM

Optional - make the example more code based on a concrete example instead of trying to be general.
However even in this shape much better then the previous version.

2022-12-23 15:57 UTC, TheMeaningfulEngineer approved these changes

2022-12-23 20:26 UTC, TheYoctoJester requested changes
Especially the first comment needs to be sorted out. When reading it, I am uncertain if the `dd` implementation I have is ok (`busybox`, `coreutils`,...)

2022-12-23 20:26 UTC, TheYoctoJester commented on 301.Troubleshoot/03.Mender-Client/docs.md
> +A general command should be something like the below, but it depends on your device's type of dd.
"type of dd" sounds like we have seen problems with different implementations of `dd`. Is this accurate? Or did you mean to refer the input file?

2022-12-23 20:26 UTC, TheYoctoJester commented on 301.Troubleshoot/03.Mender-Client/docs.md
> +You can check what is your active root file system (`$ACTIVE_PARTITION` in the following `dd`) with a command like `lsblk`, `fdisk -l`, or similar.
```suggestion
You can identify your active root file system (`$ACTIVE_PARTITION` in the following `dd`) with a command like `lsblk`, `fdisk -l`, `mount` or similar.
```

2022-12-23 20:26 UTC, TheYoctoJester commented on 301.Troubleshoot/03.Mender-Client/docs.md
> +The payload size of the version running on the device can be fetched from `mender-artifact read delta.mender`, check for the variable `rootfs_file_size` and use it as `$PAYLOAD_SIZE` in the following
```suggestion
The payload size of the version running on the device can be obtained from `mender-artifact read delta.mender`, check for the variable `rootfs_file_size` and use it as `$PAYLOAD_SIZE` in the following `dd`.
```

2023-01-02 14:09 UTC, TheMeaningfulEngineer commented on 301.Troubleshoot/03.Mender-Client/docs.md
> +A general command should be something like the below, but it depends on your device's type of dd.
This originates from me, it was a cheap way to say "It wasn't working with my busybox `dd` but don't know what I did!".
Don't know what the solution was of if there was a workaround or I just installed the correct one.
Voting that we just remove that part and assume real dd.

2023-01-03 14:47 UTC, lluiscampos commented on 301.Troubleshoot/03.Mender-Client/docs.md
> +For example, if you remount the partition `rw`, change something and remount it `ro`, the checksum in the `mender provides` won't change, while the checksum of the running partition changes.
For consistency,

```suggestion
For example, if you remount the partition `rw`, change something and remount it `ro`, the checksum in the `mender show-provides` won't change, while the checksum of the running partition changes.
```

2023-05-10 15:01 UTC, TheYoctoJester commented
Merged the new information as well as old comments in. Thoughts @TheMeaningfulEngineer @MuchoLucho ?

2023-05-12 11:31 UTC, TheMeaningfulEngineer approved these changes
Rendered and went through the structure.
Looks good

2023-05-15 08:45 UTC, merged