feat: Document how to integrate Mender with Okta
mendersoftware/mender-docs pull request #1976
Opened 2022-12-30 17:19 UTC by TheMeaningfulEngineer

Extend the documentation with an example on setting Okta as a SAML Identity Provider (IdP) for Hosted Mender.

Changelog: Title
Ticket: None

Signed-off-by: Alan <alan.martinovic@northern.tech>

2022-12-31 06:59 UTC, tranchitella approved these changes
A bunch of suggestions, but the general feedback is super positive.
Well done, nice tutorial!

2022-12-31 06:59 UTC, tranchitella commented on 08.Server-integration/08.SAML-Federated-Authentication/01.OKTA/docs.md
> +In the `General Settings` name the app `Hosted Mender` and proceed.
```suggestion
In the `General Settings`, set the app's name to `Hosted Mender` and proceed.
```

2022-12-31 06:59 UTC, tranchitella commented on 08.Server-integration/08.SAML-Federated-Authentication/01.OKTA/docs.md
> +Set the following in the  `SAML Settings`, section `General`:
```suggestion
Set the following values in the `SAML Settings`, section `General`:
```

2022-12-31 06:59 UTC, tranchitella commented on 08.Server-integration/08.SAML-Federated-Authentication/01.OKTA/docs.md
> +The `http://tmp.url` are temporary values we'll later replace with correct ones.
```suggestion
The `http://tmp.url` are temporary values we'll later replace with the correct ones. 
```

2022-12-31 06:59 UTC, tranchitella commented on 08.Server-integration/08.SAML-Federated-Authentication/01.OKTA/docs.md
> +Once the content of that XML file is added to Hosted Mender, it will generate the correct URLs.
```suggestion
Once you add the content of that XML to Hosted Mender, it will generate the correct URLs you will replace in Okta.
```

2022-12-31 06:59 UTC, tranchitella commented on 08.Server-integration/08.SAML-Federated-Authentication/01.OKTA/docs.md
> +Set the following in the  `SAML Settings`, section `General`:
```suggestion
Set the following values in the `SAML Settings`, section `General`:
```

2022-12-31 06:59 UTC, tranchitella commented on 08.Server-integration/08.SAML-Federated-Authentication/01.OKTA/docs.md
> +Under the `Optional` there will be an XML containing the IdP metadata.
```suggestion
Under the `Optional` section there will be an XML containing the IdP metadata.
```

2022-12-31 06:59 UTC, tranchitella commented on 08.Server-integration/08.SAML-Federated-Authentication/01.OKTA/docs.md
> +That contend needs to be copied to Hosted Mender.
```suggestion
You need to copy that content to Hosted Mender.
```

2022-12-31 06:59 UTC, tranchitella commented on 08.Server-integration/08.SAML-Federated-Authentication/01.OKTA/docs.md
> +Once the XML content has been copied, Mender will generate the required links.
```suggestion
Once you copy the XML to it, Hosted Mender will generate the required links.
```

2022-12-31 06:59 UTC, tranchitella commented on 08.Server-integration/08.SAML-Federated-Authentication/01.OKTA/docs.md
> +The `Start URL` is the URL to share with the user to log in once the setup is completed.
```suggestion
The `Start URL` is the URL to share with the user to log in once you complete the setup. 
```

2022-12-31 06:59 UTC, tranchitella commented on 08.Server-integration/08.SAML-Federated-Authentication/01.OKTA/docs.md
> +Give it the same email, assign it a role but **leave the password blank**.
```suggestion
Before concluding the Okta setup with the correct values,
in Hosted Mender, from the upper left dropdown, select `User management` and click `Create new user`.
Then, give it the same email, and assign it a role, but **leave the password blank**.
```

2022-12-31 06:59 UTC, tranchitella commented on 08.Server-integration/08.SAML-Federated-Authentication/01.OKTA/docs.md
> +Now its time to get back to Okta and replace the temporary urls with real ones.
```suggestion
Now it's time to return to Okta and replace the temporary URLs with the real ones.
```

2022-12-31 06:59 UTC, tranchitella commented on 08.Server-integration/08.SAML-Federated-Authentication/01.OKTA/docs.md
> +This concludes the setup on the Okta side.
```suggestion
Don't change any other values and conclude the editing of the application.
This ends the setup on the Okta side.
```

2022-12-31 06:59 UTC, tranchitella commented on 08.Server-integration/08.SAML-Federated-Authentication/01.OKTA/docs.md
> +Once complete the Okta authentication (you will have to install 'Okta Verify', the mobile app for Okta mfa) you will be redirected to Hosted Mender.
```suggestion
Copy the `Start URL` (the third URL provided by Hosted Mender) into the browser, and an Okta login will pop up.
Once complete the Okta authentication (you will have to install 'Okta Verify', the mobile app for Okta MFA), you will be redirected to Hosted Mender.
```

2023-01-02 10:09 UTC, tranchitella approved these changes
Thanks for accepting my suggestions. Please be sure to squash the commits before merging (and maybe waiting for an extra pair of eyes to review the content).

2023-01-02 16:28 UTC, TheYoctoJester requested changes
Especially textual descriptions of the screenshots are missing.

2023-01-02 16:28 UTC, TheYoctoJester commented on 08.Server-integration/08.SAML-Federated-Authentication/01.OKTA/docs.md
> +This example will show you how to set Okta as an IdP (Identity Provider) for Hosted Mender.
```suggestion
This example will show you how to set Okta as an Identity Provider (IdP) for Hosted Mender.
```

2023-01-02 16:28 UTC, TheYoctoJester commented on 08.Server-integration/08.SAML-Federated-Authentication/01.OKTA/docs.md
> +`Directory` -> `People` -> `Add Person` ([Okta - add users](https://help.okta.com/en-us/Content/Topics/users-groups-profiles/usgp-add-users.htm)).
I think this needs a little textual explanation too. Just the screenshot makes context hard to skim read and impossible to index. Plus, if one of the fields has a special meaning it needs to be noted.

2023-01-02 16:28 UTC, TheYoctoJester commented on 08.Server-integration/08.SAML-Federated-Authentication/01.OKTA/docs.md
> +In the `General Settings`, set the app's name to `Hosted Mender` and proceed.
Is "Hosted Mender" mandatory, or can the name be chosen by the user?

2023-01-02 16:28 UTC, TheYoctoJester commented on 08.Server-integration/08.SAML-Federated-Authentication/01.OKTA/docs.md
> +[Assign mender to user](https://help.okta.com/en-us/Content/Topics/Provisioning/lcm/lcm-assign-app-user.htm)
Again, needs text.

2023-01-02 16:28 UTC, TheYoctoJester commented on 08.Server-integration/08.SAML-Federated-Authentication/01.OKTA/docs.md
> +Once you complete with the Okta authentication (you will have to install 'Okta Verify', the mobile app for Okta MFA), you will be redirected to Hosted Mender.
Maybe a short additional section here how the login/authentication flow will work from now on in the standard case?

2023-01-02 16:47 UTC, TheYoctoJester approved these changes

2023-01-03 12:27 UTC, TheMeaningfulEngineer commented on 08.Server-integration/08.SAML-Federated-Authentication/01.OKTA/docs.md
> +`Directory` -> `People` -> `Add Person` ([Okta - add users](https://help.okta.com/en-us/Content/Topics/users-groups-profiles/usgp-add-users.htm)).
You're right.
This is a deliberate decision.
I don't want to be better than documenting OKTA than [OKTA themselves](https://help.okta.com/en-us/Content/Topics/users-groups-profiles/usgp-add-users.htm) as it's expensive to get these images right (even for these simple ones I had to go back and forth multiple times). 

Not sure what you mean by `impossible to index`.

2023-01-04 03:25 UTC, MuchoLucho approved these changes
Generally speaking it looks good. I would go straight to publish it and then improve it by PRs

2023-01-04 16:39 UTC, TheYoctoJester commented on 08.Server-integration/08.SAML-Federated-Authentication/01.OKTA/docs.md
> +`Directory` -> `People` -> `Add Person` ([Okta - add users](https://help.okta.com/en-us/Content/Topics/users-groups-profiles/usgp-add-users.htm)).
Impossible to index means that search engines can't look into it. So the decision is effectively hindering discoverability of the documentation. Please revisit.

2023-01-19 15:25 UTC, TheMeaningfulEngineer commented on 08.Server-integration/08.SAML-Federated-Authentication/01.OKTA/docs.md
> +`Directory` -> `People` -> `Add Person` ([Okta - add users](https://help.okta.com/en-us/Content/Topics/users-groups-profiles/usgp-add-users.htm)).
I appreciate your comments, but this is slowly turning into bit rot and I'm not finding the time to improve it.

Going with what @MuchoLucho and @lluiscampos suggested - we'll be merging as in a 'better then nothing' form

2023-01-19 15:26 UTC, merged