feat: add zstd documentation
mendersoftware/mender-docs pull request #1991
Opened 2023-01-16 18:16 UTC by Michaelhobo

Changelog: Add zstd documentation
Ticket: None

Signed-off-by: Michael Ho <callmemikeh@gmail.com>

2023-01-17 04:18 UTC, kacf requested changes
Thanks @Michaelhobo

2023-01-17 04:18 UTC, kacf commented on .ispell_english
> +Your�
Looks like the editor messed up some unrelated words here. It has replaced some accented letters with the 0xFFFD "unknown" UTF code sequence. TBH I don't know what those accents are doing here in the first place, but 0xFFFD is definitely even more incorrect, so best to remove those.

2023-01-17 04:18 UTC, kacf commented on 04.System-updates-Debian-family/99.Variables/docs.md
> +See https://engineering.fb.com/2018/12/19/core-data/zstandard for details.
Can you perhaps mention which of the three variants above is the default if you just pick the short one?

2023-01-19 20:09 UTC, Michaelhobo commented on .ispell_english
> +Your�
Fixed. That was weird, my editor didn't even show these changes

2023-01-19 20:09 UTC, Michaelhobo commented on 04.System-updates-Debian-family/99.Variables/docs.md
> +See https://engineering.fb.com/2018/12/19/core-data/zstandard for details.
There's no longer a short one, it's been renamed to `zstd_fast`

2023-01-20 08:06 UTC, kacf approved these changes
Thanks! I will merge this once the code PRs are merged.

2023-01-27 09:46 UTC, merged