feat: upgrading to 3.5
mendersoftware/mender-docs pull request #2020
Opened 2023-02-20 17:56 UTC by merlin-northern

Changelog: Title
Ticket: MEN-6219

2023-02-24 13:08 UTC, TheMeaningfulEngineer commented
Did you manage to render the chapter?
Can't seem to get it locally...

![Screenshot from 2023-02-24 14-07-56](https://user-images.githubusercontent.com/1640260/221186376-e5799d2c-6b3a-4e72-b279-ee4c3da3bdc1.png)

2023-02-26 12:37 UTC, merlin-northern commented
> Did you manage to render the chapter? Can't seem to get it locally...
> 
> Checking... DOn't know if it's me or not yet

yes, of course, I checked the rendering before I asked for review. we can have a call on how I build the docs.

2023-02-27 15:16 UTC, TheMeaningfulEngineer requested changes
I'd like to restructure these docs quite a bit.
I'll make a PR on the structure change, make a PR to your branch and we can review it live.

2023-02-27 15:16 UTC, TheMeaningfulEngineer commented on 07.Server-installation/02.Upgrading-from-previous-versions/docs.md
> +* in particular that it starts up correctly
```suggestion
We only test and support the upgrade path between LTS releases.
This will occasionally be provided by a required middle step through a non LTS versions.

_For example._  A upgrade path between two LTS versions, `3.3 -> 3.5`, needs to happen with an update to `3.4` as the middle step (`3.3->3.4->3.5`). This doesn't guarantee the non LTS upgrade path will be tested for cases where technical boundaries allow for a direct LTS->LTS upgrade.  
```

Not sure what is happening in the bullet points.
Will try to put them under the prerequisites section instead.

2023-02-27 15:16 UTC, TheMeaningfulEngineer commented on 07.Server-installation/02.Upgrading-from-previous-versions/docs.md
> +
```suggestion
Upgrading the production Mender Server installations can be a complex task.
Please note that we won't be able to assist you if your production data gets corrupted in the upgrade process.
That is why we recommend following the preparations listed below to minimize the risk of errors.
```

2023-03-02 12:44 UTC, merlin-northern commented
this one is going with:
[eat: upgrading Mender Server: upgrading to 3.5 by merlin-northern · Pull Request #2041 · mendersoftware/mender-docs](https://github.com/mendersoftware/mender-docs/pull/2041) 

[feat: upgrading Mender Server: upgrading to 3.4 by merlin-northern · Pull Request #2040 · mendersoftware/mender-docs](https://github.com/mendersoftware/mender-docs/pull/2040) 

[feat: upgrading Mender Server: general gudelines. by merlin-northern · Pull Request #2036 · mendersoftware/mender-docs](https://github.com/mendersoftware/mender-docs/pull/2036)

2023-03-02 12:44 UTC, closed without merging