QA-348: ci: adjust test to run on relevant integration branch
mendersoftware/mender-docs pull request #2026
Opened 2023-02-21 19:14 UTC by 0lmi

Changelog: None
Ticket: QA-348

# External Contributor Checklist

🚨 Please review the [guidelines for contributing](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md) to this repository.

- [ ] Make sure that all commits follow the conventional commit [specification](https://www.github.com/mendersoftware/mendertesting/commitlint/grammar.md) for the Mender project.

The majority of our contributions are fixes, which means your commit should have
the form below:

```
fix: <SHORT DESCRIPTION OF FIX>

<OPTIONAL LONGER DESCRIPTION>

Changelog: <USER-FRIENDLY-CHANGE-DESCRIPTION> or <None>
Ticket: <TICKET NUMBER> or <None>
```

- [ ] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.

### Description

Please describe your pull request.

Thank you!

2023-02-22 09:21 UTC, lluiscampos requested changes
I see it is an smart hack to modify only the `git clone` commands, but there are some caveats that will make this not working. See comments below.

Also, please find a way to test this in CI. For example you can launch some debug PRs in `integration` that have a hardcoded version (one containing the changes of this PR) for `mender-docs` branch to use. And you should also test it with `mender-docs` branches based on `hosted` and one release branch.

2023-02-22 09:21 UTC, lluiscampos commented on test_docs.py
> +            integration_branch = os.environ.get(int_branch_env_var_name)
If it is only used here, there is much value on having it as a variable.
```suggestion
            integration_branch = os.environ.get("INTEGRATION_BRANCH")
```

2023-02-22 09:21 UTC, lluiscampos commented on test_docs.py
> +        if line.startswith("git clone"):
This will not really work. The instructions in the docs are `git clone -b ... github...` while on our pull requests `INTEGRATION_BRANCH` will only exist in GitLab (remember that we run the pipelines from these `pr_...` branches.

2023-02-22 09:21 UTC, lluiscampos commented on test_docs.py
> +                default_int_branch = "master"
This will only work on mender-docs/master, but not in hosted or any of the release branches

2023-02-22 09:40 UTC, 0lmi commented on test_docs.py
> +        if line.startswith("git clone"):
It checks if a line starts from `git clone` substring, I tested it and pretty sure it works.

2023-02-22 09:41 UTC, 0lmi commented on test_docs.py
> +            integration_branch = os.environ.get(int_branch_env_var_name)
That is how it was originally done, but it doesn't pass python formatting check.

2023-02-22 09:41 UTC, 0lmi commented on test_docs.py
> +                default_int_branch = "master"
Good point 👍

2023-02-22 10:07 UTC, 0lmi commented on test_docs.py
> +        if line.startswith("git clone"):
Ok, now I got what you mean here. The comment is actually not about the check, but about the logic behind.

2023-02-22 11:52 UTC, 0lmi commented on test_docs.py
> +        if line.startswith("git clone"):
Good point 👍. Added the logic for GitHub URL replacement to GitLab.

2023-02-22 12:28 UTC, 0lmi commented
CI part is improved to be able to run pipelines for any combination of integration<->mender-docs branches.

There is job's [example](https://gitlab.com/Northern.tech/Mender/integration/-/jobs/3813863713#L1150) of running the pipeline from [pr_2339](https://gitlab.com/Northern.tech/Mender/integration/-/commits/pr_2339) branch in GitLab (which corresponds to integration/2339 PR) with [pr_2026](https://gitlab.com/Northern.tech/Mender/mender-docs/-/tree/pr_2026) branch (which corresponds to mender-docs/2026 PR).

2023-02-23 14:15 UTC, lluiscampos approved these changes

2023-02-23 14:15 UTC, lluiscampos commented on test_docs.py
> +                default_int_branch = words[3]
This is quite weak. Using a regex you can make it more robust and fail explicitly when the expression does not match.

2023-02-27 13:23 UTC, merged