feat: upgrading Mender Server: upgrading to 3.5
mendersoftware/mender-docs pull request #2041
Opened 2023-03-01 14:10 UTC by merlin-northern

feat: upgrading Mender Server: upgrading to 3.5

Changelog: Title
Ticket: MEN-6219
Signed-off-by: Peter Grzybowski <peter@northern.tech>

2023-03-01 14:11 UTC, merlin-northern commented
@TheMeaningfulEngineer could you give me review only on the 3.5 chapter here? (the rest will disappear from there when we merge https://github.com/mendersoftware/mender-docs/pull/2036)

2023-03-02 10:25 UTC, TheMeaningfulEngineer commented on 07.Server-installation/02.Upgrading-from-previous-versions/100.Upgrading-to-3.5/docs.md
> +### Database backup
We cover this already in the general section.
Thought the idea was to not have to repeat it every time.

2023-03-02 10:27 UTC, TheMeaningfulEngineer commented on 07.Server-installation/02.Upgrading-from-previous-versions/100.Upgrading-to-3.5/docs.md
> +Be sure that you have access to them.
What does this mean?
The images of the new container components?

2023-03-02 10:32 UTC, TheMeaningfulEngineer requested changes
I think there are chapters in both 3.4 and 3.5 that can be moved to 'generic'

Same structure comment as for 3.4: 
https://github.com/mendersoftware/mender-docs/pull/2040#discussion_r1122873930

2023-03-02 11:07 UTC, merlin-northern commented on 07.Server-installation/02.Upgrading-from-previous-versions/100.Upgrading-to-3.5/docs.md
> +Be sure that you have access to them.
yes, kind of obvious. I removed it.

2023-03-02 11:07 UTC, merlin-northern commented on 07.Server-installation/02.Upgrading-from-previous-versions/100.Upgrading-to-3.5/docs.md
> +### Database backup
removed. (left orver)

2023-03-02 11:37 UTC, TheMeaningfulEngineer commented on 07.Server-installation/02.Upgrading-from-previous-versions/100.Upgrading-to-3.5/docs.md
> +
```suggestion

Besides the version specific guidelines below, please make sure you're following the [suggested upgrade best practices](../docs.md) to reduce the risk of unpredictable downtime and data loss.
```

2023-03-02 12:01 UTC, merlin-northern commented on 07.Server-installation/02.Upgrading-from-previous-versions/100.Upgrading-to-3.5/docs.md
> +
sure.

2023-03-02 12:47 UTC, TheMeaningfulEngineer approved these changes

2023-03-02 14:27 UTC, merged