docs: Improve description how to use of artifact state scripts
mendersoftware/mender-docs pull request #2086
Opened 2023-04-21 10:01 UTC by orzechow

# External Contributor Checklist

🚨 Please review the [guidelines for contributing](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md) to this repository.

- [x] Make sure that all commits follow the conventional commit [specification](https://www.github.com/mendersoftware/mendertesting/commitlint/grammar.md) for the Mender project.
→ btw. this is a deadlink

The majority of our contributions are fixes, which means your commit should have
the form below:

```
fix: <SHORT DESCRIPTION OF FIX>

<OPTIONAL LONGER DESCRIPTION>

Changelog: <USER-FRIENDLY-CHANGE-DESCRIPTION> or <None>
Ticket: <TICKET NUMBER> or <None>
```

- [x] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.

### Description

docs: Improve description how to use of artifact state scripts in contrast to root filesystem state scripts

2023-04-25 07:13 UTC, kacf requested changes
Looks good to me. However, the signoff needs to match the author name and address (check with `git show -s`). Can you please fix it? That should make gitlab green. 🙂

2023-04-25 12:54 UTC, orzechow commented
Thanks for the feedback!
I mixed up my private and company mail address in the commit. Now, it should work :)

2023-04-26 06:01 UTC, kacf approved these changes

2023-04-26 06:02 UTC, kacf commented
Thanks!

2023-04-26 06:02 UTC, merged