Documentation for the Docker Compose Application Update Module
mendersoftware/mender-docs pull request #2134
Opened 2023-06-13 14:18 UTC by alfrunes

2023-06-14 15:35 UTC, alfrunes commented
Requires mendersoftware/app-update-module#31 (app-gen fix) and mendersoftware/app-update-module#30 (update module fixes) to work.

2023-06-16 15:47 UTC, TheMeaningfulEngineer requested changes
@alfrunes 
This and all the comments are happening as part of a CE review - all 3 of as are reading it for the first time and than aligning.
Think about it as a WIP util we reach a conclusion on the change or even suggest a PR so don't freak out by the number of comments :)

**Comments on docs structure**

If we are introducing a section on supported update modules the docs should be restructured.
Instead of listing update modules under artifact creation I'd have a whole section on "Update modules"

```
Update modules
  Create a Delta update Artifact
  Server-side generation of Delta Artifacts
  Create a custom Update Module
  Application Update module
    Docker Compose
  Community update modules
```

2023-06-16 15:47 UTC, TheMeaningfulEngineer commented on 01.Get-started/04.Deploy-a-container-update/docs.md
> +* *[Kubernetes Update Module](https://hub.mender.io/t/kubernetes/1939?target=_blank)* allows you to deploy Kubernetes manifests to a local kubernetes cluster.
I would scrap this example completely.
If we now have a supported version on how to do a container update, let's not have a getting started as a community based one.

2023-06-16 15:47 UTC, TheMeaningfulEngineer commented on 06.Artifact-creation/03.Containerized-application-updates/docs.md
> +[ui-accordion independent=true open=none]
This looks nice, but not obvious from the rendering it was a button.
Would just keep it expanded.

Vefify -> Verify

2023-06-16 15:47 UTC, TheMeaningfulEngineer commented on 06.Artifact-creation/03.Containerized-application-updates/docs.md
> +[ui-accordion independent=true open=none]
This looks nice, but not obvious from the rendering it was a button.
Would just keep it expanded.

Vefify -> Verify

2023-06-16 15:47 UTC, TheMeaningfulEngineer commented on 06.Artifact-creation/03.Containerized-application-updates/docs.md
> +on the edge devices. The Application Update Module extends the update module API
What's an Application Update Module?
The fact that Docker compose is based on it doesn't tell me much about the Application Update module.

2023-06-16 15:47 UTC, TheMeaningfulEngineer commented on 06.Artifact-creation/03.Containerized-application-updates/docs.md
> +!!! Inspect the configuration files on your device `/etc/mender/mender-app.conf` and
Based on what do I know how to configure it?

2023-06-16 15:47 UTC, TheMeaningfulEngineer commented on 06.Artifact-creation/03.Containerized-application-updates/docs.md
> +deploying to is `linux/arm/v7`.
Why do we need to know that?
How do I figure out what mine is if I don't know?

2023-06-16 15:47 UTC, TheMeaningfulEngineer commented on 06.Artifact-creation/03.Containerized-application-updates/docs.md
> +app-gen --artifact-name "$ARTIFACT_NAME" \
Gave me an error:
```
/home/alan-nt/bin/app-gen: line 78: $1: unbound variable
```

2023-06-16 15:56 UTC, estape11 reviewed
CE Docs Review

2023-06-16 15:56 UTC, estape11 commented on 06.Artifact-creation/03.Containerized-application-updates/docs.md
> +#### Prepare the device
### WIP - CE Docs review

We could be more verbose regarding which device, from instructions I got 2 devices involved, the actual remote device and another one for the artifact generation. This is important as the requirements for each are different, i.e the one in charge for artifact generation is not required to have mender installed.

2023-06-16 15:56 UTC, estape11 commented on 06.Artifact-creation/03.Containerized-application-updates/docs.md
> +Application Update Artifact Generator:
### WIP - CE Docs review
Maybe not strictly limited to this doc entry but `app-gen `seems to fail in my environment (tried bash & zsh), apparently the line 78 needs a change:
```bash
...
while [ $# -ge 1 ] && [ -n "$1" ]; do
...
```
After that, I was able to use the script. ([ref](https://unix.stackexchange.com/a/463038))

2023-06-16 15:56 UTC, MuchoLucho reviewed
Just a first review

2023-06-16 15:56 UTC, MuchoLucho commented on 06.Artifact-creation/03.Containerized-application-updates/docs.md
> + * [xdelta3](https://github.com/jmacd/xdelta)
A little bit curious on how the following commands are going to work if we have a read only rootfs. Should we state you must have a RW rootfs before proceeding if you made it "delta ready" in the past?

2023-06-16 15:56 UTC, MuchoLucho commented on 06.Artifact-creation/03.Containerized-application-updates/docs.md
> +[ui-accordion-item title="Vefify device dependencies"]
Small typo in Verify

2023-06-16 15:56 UTC, MuchoLucho commented on 06.Artifact-creation/03.Containerized-application-updates/docs.md
> +To install the Docker Compose update module, run the following commands on your
`Update Module` in uppercase for consistency

2023-06-16 15:56 UTC, MuchoLucho commented on 06.Artifact-creation/03.Containerized-application-updates/docs.md
> +wget https://raw.githubusercontent.com/mendersoftware/app-update-module/master/gen/app-gen \
This script contains hashes like: 

docker.io/library/debian:11,docker.io/library/debian:latest@sha256:a94cd7c7d58f483affd5937853ad4d24caa18cd7c2ec9ef65a9e528dfbc5eb07

Should we worry about it?

2023-06-16 15:56 UTC, MuchoLucho commented on 06.Artifact-creation/03.Containerized-application-updates/docs.md
> +mender-cli port-forward 1bfcf943-4378-4a4f-bc88-0b4c86cdcc74 8080:8080
We should not assume the customer knows that the `id` here means the `device id`. To make sure that visit the reference to https://docs.mender.io/add-ons/port-forward#port-forwarding would be a must and state the following line is an example. Or just change it for `mender-cli port-forward device_id 8080:8080`

2023-06-16 16:02 UTC, TheMeaningfulEngineer commented on 06.Artifact-creation/03.Containerized-application-updates/docs.md
> + * [xdelta3](https://github.com/jmacd/xdelta)
Doesn't sound actionable - pls think in terms of making a PR with improvements you have to suggest instead of open question.

So instead of `Should we state you must have a RW rootfs before proceeding if you made it "delta ready" in the past?` more like `I tested the on a RW file system - didn't work - here is a suggestion for how the docs should address this`.

2023-06-16 16:03 UTC, TheMeaningfulEngineer commented on 06.Artifact-creation/03.Containerized-application-updates/docs.md
> +on the edge devices. The Application Update Module extends the update module API
Needs a chapter with a definition of an Application Update module.

2023-06-16 16:04 UTC, MuchoLucho commented on 06.Artifact-creation/03.Containerized-application-updates/docs.md
> +deploying to is `linux/arm/v7`.
I would assume a person who follows this know about the platform, my concern is the expected format `x/x/x`. Are we documenting it somewhere else?

2023-06-16 16:04 UTC, TheMeaningfulEngineer commented on 06.Artifact-creation/03.Containerized-application-updates/docs.md
> +[ui-accordion independent=true open=none]
Deleting, Lucho commented as well.

2023-06-16 16:05 UTC, TheMeaningfulEngineer commented on 06.Artifact-creation/03.Containerized-application-updates/docs.md
> +!!! Inspect the configuration files on your device `/etc/mender/mender-app.conf` and
Section on configuration of the both the Application Update and Container Update Module needed

2023-06-16 16:09 UTC, TheMeaningfulEngineer commented on 06.Artifact-creation/03.Containerized-application-updates/docs.md
> +The `--deep-delta` flag enables the delta feature which creates a binary delta
Missing documentation about Application Update Module.
Mentioned that already in anohter commetn.
Resolving.

2023-06-16 16:09 UTC, TheMeaningfulEngineer commented on 06.Artifact-creation/03.Containerized-application-updates/docs.md
> +mender-cli port-forward 1bfcf943-4378-4a4f-bc88-0b4c86cdcc74 8080:8080
Pls translate into real change suggestion.

2023-06-16 16:10 UTC, TheMeaningfulEngineer commented on 06.Artifact-creation/03.Containerized-application-updates/docs.md
> +deploying to is `linux/arm/v7`.
Not actionable, open ended question.

Add part explaining how to get the value for the platform (`linux/arm/v7`).

2023-06-16 16:12 UTC, TheMeaningfulEngineer commented on 06.Artifact-creation/03.Containerized-application-updates/docs.md
> +Application Update Artifact Generator:
This snippet is just downloading the app?
Did you mean: https://github.com/mendersoftware/mender-docs/pull/2134/files#r1232398222

2023-06-16 16:12 UTC, TheMeaningfulEngineer commented on 06.Artifact-creation/03.Containerized-application-updates/docs.md
> +To install the Docker Compose update module, run the following commands on your
Let's do a check for that on the whole document.

2023-06-16 16:14 UTC, TheMeaningfulEngineer commented on 01.Get-started/04.Deploy-a-container-update/docs.md
> +* *[Kubernetes Update Module](https://hub.mender.io/t/kubernetes/1939?target=_blank)* allows you to deploy Kubernetes manifests to a local kubernetes cluster.
Two actions in one comment, reducing to only one.

Community update modules shouldn't listed in the same was as supported ones.

2023-06-16 16:17 UTC, TheMeaningfulEngineer commented on 01.Get-started/04.Deploy-a-container-update/docs.md
> +* *[Kubernetes Update Module](https://hub.mender.io/t/kubernetes/1939?target=_blank)* allows you to deploy Kubernetes manifests to a local kubernetes cluster.
Let's just remove Kuberenetes

2023-06-16 16:17 UTC, MuchoLucho commented on 06.Artifact-creation/03.Containerized-application-updates/docs.md
> +Application Update Artifact Generator:
Then I would create the PR for https://github.com/mendersoftware/app-update-module/blob/ee12ba4c869f733af86b74469ead20edaa605866/gen/app-gen#L78 instead

2023-06-16 16:28 UTC, TheMeaningfulEngineer commented on 06.Artifact-creation/03.Containerized-application-updates/docs.md
> +app-gen --artifact-name "$ARTIFACT_NAME" \
Ref to closed conversation: https://github.com/mendersoftware/mender-docs/pull/2134/files#r1232426335

2023-06-16 16:28 UTC, TheMeaningfulEngineer commented on 06.Artifact-creation/03.Containerized-application-updates/docs.md
> +Application Update Artifact Generator:
Closing this as Lucho confirmed this is the error I reported and will continue there as it points to the snippet where the error gets triggered.

2023-06-16 16:30 UTC, TheMeaningfulEngineer commented on 06.Artifact-creation/03.Containerized-application-updates/docs.md
> +app-gen --artifact-name "$ARTIFACT_NAME" \
Seems like there are [code dependencies](https://github.com/mendersoftware/mender-docs/pull/2134#issuecomment-1591491346) to be able to verify these docs.
The docs can't be merged until we can successfully execute the snippets.

2023-06-16 16:31 UTC, MuchoLucho commented on 06.Artifact-creation/03.Containerized-application-updates/docs.md
> +mender-cli port-forward 1bfcf943-4378-4a4f-bc88-0b4c86cdcc74 8080:8080
Change for `mender-cli port-forward device_id 8080:8080`  or state the id above must be replaced with your actual id

2023-06-19 11:46 UTC, alfrunes commented on 06.Artifact-creation/03.Containerized-application-updates/docs.md
> +Application Update Artifact Generator:
https://github.com/mendersoftware/app-update-module/pull/32

2023-06-19 11:46 UTC, alfrunes commented on 06.Artifact-creation/03.Containerized-application-updates/docs.md
> +!!! Inspect the configuration files on your device `/etc/mender/mender-app.conf` and
This was a bit confusing to me too. It should work out of the box, so I'm considering to remove this tip.

2023-06-19 11:47 UTC, alfrunes commented on 06.Artifact-creation/03.Containerized-application-updates/docs.md
> +app-gen --artifact-name "$ARTIFACT_NAME" \
https://github.com/mendersoftware/app-update-module/pull/32

2023-06-20 09:02 UTC, alfrunes commented
Any hints on why the internal link checker cannot resolve the header fragments is appreciated :)

2023-06-20 09:08 UTC, TheMeaningfulEngineer commented
Not sure I'll be able to review this until Friday.
My minimal threshold for giving it a green light will be:
* The example can be executed on the RPi demo image
* It replaces the community container update module in the Getting started - I see no reason the official one shouldn't take priority

2023-06-20 09:16 UTC, alfrunes commented
> * The example can be executed on the RPi demo image

The fixes I reported in the initial comment are now merged into master. I was using the RPi 4 demo image to test the snippets.

> * It replaces the community container update module in the Getting started - I see no reason the official one shouldn't take priority

I would like to get @tranchitella input here. There have already been several twists and turns in this ticket, and I'm not too keen on escalating this ticket beyond the requirements without making a follow-up ticket for restructuring the docs.

2023-06-30 09:02 UTC, alfrunes commented
@TheMeaningfulEngineer @estape11 @MuchoLucho Are there any plans for another round of reviews? I'm a bit lost about what to do with this one.

2023-06-30 15:01 UTC, estape11 reviewed
Sorry I missed hit submit for this review

2023-06-30 15:35 UTC, TheMeaningfulEngineer commented on 06.Artifact-creation/03.Containerized-application-updates/docs.md
> +   * *Only required if using binary deltas*
This was in @estape11 PR whihc was merged.

2023-06-30 15:54 UTC, TheMeaningfulEngineer requested changes
Made the suggestions on the Application Update Module.
It looks just like a means to an end "Doing the container update" and not really important.

2023-06-30 15:54 UTC, TheMeaningfulEngineer commented on 06.Artifact-creation/03.Containerized-application-updates/docs.md
> +supports Docker Compose orchestrator.
```suggestion
```

We want to present the docker componse use case.
Don't care about the Application Update Module which is just a means to an end.

2023-06-30 15:54 UTC, TheMeaningfulEngineer commented on 06.Artifact-creation/03.Containerized-application-updates/docs.md
> +## Docker Compose
```suggestion
```

2023-06-30 15:54 UTC, TheMeaningfulEngineer commented on 06.Artifact-creation/03.Containerized-application-updates/docs.md
> +
```suggestion
!!! [Application Update Module](https://github.com/mendersoftware/app-update-module/blob/master/docs/README-submodule-api.md#applications-updates) contains the generalized logic for application updates. It is a dependency for the Docker Compose Application Update Module, that is why it's being installed.
```

2023-07-04 09:09 UTC, alfrunes commented on 06.Artifact-creation/03.Containerized-application-updates/docs.md
> +Once deployed, the device will start serving a simple server on port 8080. You
I'm failing to reproduce these errors that you report. I did, however, encounter an issue with missing `jq`, so I'll add that to the docs. Could you try again? Maybe the `app-update-module` sources was outdated when you last tested it.

2023-07-04 09:52 UTC, alfrunes commented on 06.Artifact-creation/03.Containerized-application-updates/docs.md
> +supports Docker Compose orchestrator.
Removed the first paragraph and the first heading.

2023-07-04 09:53 UTC, alfrunes commented on 06.Artifact-creation/03.Containerized-application-updates/docs.md
> +on the edge devices. *Application Update Module* (App Update Module), being the regular [Mender Update Module](../08.Create-a-custom-Update-Module),
In the first iteration, we want to receive feedback from customers that have shown interest in an Docker Compose update module. I believe once we have more material it makes sense to split this into a top-level chapter. For now, I believe this is too targeted to stay at the the top level.

2023-07-04 17:20 UTC, estape11 commented on 06.Artifact-creation/03.Containerized-application-updates/docs.md
> +Once deployed, the device will start serving a simple server on port 8080. You
Indeed Alf, I retested and now works as expected, thank you very much for your work ⚡

2023-07-04 17:22 UTC, estape11 commented on 06.Artifact-creation/03.Containerized-application-updates/docs.md
> +on the edge devices. *Application Update Module* (App Update Module), being the regular [Mender Update Module](../08.Create-a-custom-Update-Module),
Excellent then, we (CEs) completed the review for this Docs entry, kind regards

2023-07-05 07:58 UTC, TheMeaningfulEngineer commented on 06.Artifact-creation/03.Containerized-application-updates/docs.md
> +deployment. We will start with the devices before returning to the workstation.
```suggestion
To get started using the Docker Compose Update Module, we need to prepare the
target devices for accepting the deployment and the workstation for creating the
deployment.```

2023-07-05 07:58 UTC, TheMeaningfulEngineer approved these changes
Seems like Esteban got it to work.
I found it hard to install the requirements on the demo images (Raspberry reference, or QEMU) but that's out of scope.

I read the text structure and it make sense.
Just some minor rewording, but lgtm

2023-07-07 12:31 UTC, alfrunes commented
@TheMeaningfulEngineer @estape11 @MuchoLucho; I squashed all the commits and fixed the internal links. I also moved the section as a sub-chapter of "Create an artifact"  and renamed the chapter to "Tutorial: Docker Compose update", the rest of the content is the same. Could I get a quick review on the updated docs structure?

2023-07-07 15:40 UTC, TheMeaningfulEngineer requested changes
Looks good.
Curretly reviweing, will sync with other CEs to see if we can just make all these comments into a PR instead of you having to individually adress them.

2023-07-07 15:40 UTC, TheMeaningfulEngineer commented on 06.Artifact-creation/01.Create-an-Artifact/10.Docker-Compose/docs.md
> +data transfer bandwidth for the resulting deployment.
```suggestion
```

[WIP CE review]

This looks like an excellent replacement for the introduction text.
It gives an overview of what will happen if you follow along, and gently introduces the delta.

Will suggest it as a replacement for the intro text, in which case this can only focus on the "get it working without xdelta"

2023-07-07 15:40 UTC, TheMeaningfulEngineer commented on 06.Artifact-creation/01.Create-an-Artifact/10.Docker-Compose/docs.md
> +Begin by creating the manifest and saving it in a separate directory:
```suggestion
Begin by creating the manifest on your workstation and saving it in a separate directory:
```

2023-07-07 15:40 UTC, TheMeaningfulEngineer commented on 06.Artifact-creation/01.Create-an-Artifact/10.Docker-Compose/docs.md
> + * [`xdelta3`](https://github.com/jmacd/xdelta)
WIP CE review
We used to have a mention that this was optional.
A reader can achieve the first part of the update without worrying about xdelta so let's not insist on it up front

2023-07-07 15:52 UTC, estape11 commented on 06.Artifact-creation/01.Create-an-Artifact/10.Docker-Compose/docs.md
> +Update Module for deploying a simple Docker composition on your device.
@TheMeaningfulEngineer it is truncated (..composition with a), and you do you intend to suggest a list for this?

2023-07-07 15:59 UTC, estape11 commented on 06.Artifact-creation/01.Create-an-Artifact/10.Docker-Compose/docs.md
> +data transfer bandwidth for the resulting deployment.
Hey @TheMeaningfulEngineer xdelta is a must (based on our testing)

2023-07-07 16:05 UTC, estape11 commented on 06.Artifact-creation/01.Create-an-Artifact/10.Docker-Compose/docs.md
> + * [`xdelta3`](https://github.com/jmacd/xdelta)
@TheMeaningfulEngineer, from our testing it was required (the update module fails if is not installed)

2023-07-07 16:24 UTC, estape11 requested changes

2023-07-07 16:24 UTC, estape11 commented on 06.Artifact-creation/01.Create-an-Artifact/10.Docker-Compose/docs.md
> +
```suggestion
##### Create the Mender artifact
```

2023-07-07 16:24 UTC, estape11 commented on 06.Artifact-creation/01.Create-an-Artifact/10.Docker-Compose/docs.md
> +### Prepare the deployment
```suggestion
### Creating a deployment
```

2023-07-07 16:24 UTC, estape11 commented on 06.Artifact-creation/01.Create-an-Artifact/10.Docker-Compose/docs.md
> +!!! ```
```suggestion

```bash
mender --version
docker --version
docker compose version
xdelta3 -V
jq --version
```

```

2023-07-07 16:24 UTC, estape11 commented on 06.Artifact-creation/01.Create-an-Artifact/10.Docker-Compose/docs.md
> +!!! ```
This looks nicer

2023-07-07 18:14 UTC, estape11 commented
@alfrunes we added the final minor corrections. We reviewed, re-reviewed and tested and we agreed it is complete.
Thank you for your openness and patience throughout this review.

2023-07-10 08:11 UTC, TheMeaningfulEngineer reviewed
Whatever @estape11 decides.

2023-07-10 08:45 UTC, alfrunes commented on 06.Artifact-creation/01.Create-an-Artifact/10.Docker-Compose/docs.md
> +!!! ```
Removed the colored box, but replaced it with a regular indent (`>`).

2023-07-10 08:46 UTC, alfrunes commented on 06.Artifact-creation/01.Create-an-Artifact/10.Docker-Compose/docs.md
> +data transfer bandwidth for the resulting deployment.
Rewrote this section and moved your modified version to the intro (with slight rewording).

2023-07-10 08:47 UTC, alfrunes commented
I added the changes based on your feedback. I also replaced the paragraph that was moved to the beginning. You can see the diff from the previous version [here](https://github.com/mendersoftware/mender-docs/compare/0843cc79a9748a89f295be1ad60b822b34442eb2..96ea55e6b1897be9dcc94d1863f008ad50e21973).

2023-07-14 00:59 UTC, estape11 approved these changes
We are all set, thanks @alfrunes

2023-07-14 06:57 UTC, alfrunes commented
> We are all set, thanks @alfrunes

Thanks @estape11 and the CE team :smile_cat: 
@TheMeaningfulEngineer I'm still blocked from merging, I need your approval as well.

2023-07-14 12:46 UTC, TheMeaningfulEngineer approved these changes

2023-07-14 13:06 UTC, merged