Mender-monitor docs enhancement
mendersoftware/mender-docs pull request #2163
Opened 2023-07-05 02:49 UTC by MuchoLucho

# External Contributor Checklist

🚨 Please review the [guidelines for contributing](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md) to this repository.

- [ ] Make sure that all commits follow the conventional commit [specification](https://github.com/mendersoftware/mendertesting/blob/master/commitlint/grammar.md) for the Mender project.

The majority of our contributions are fixes, which means your commit should have
the form below:

```
fix: <SHORT DESCRIPTION OF FIX>

<OPTIONAL LONGER DESCRIPTION>

Changelog: <USER-FRIENDLY-CHANGE-DESCRIPTION> or <None>
Ticket: <TICKET NUMBER> or <None>
```

- [ ] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.

### Description

Please describe your pull request.

Thank you!

2023-09-01 16:33 UTC, TheMeaningfulEngineer commented on 01.Get-started/05.Monitor/docs.md
> +>   mender-monitorctl --version
I get some version output which I guess means success, and then docker fails and then below there's a note "Hey docker might fail.

TODO:

- Move docker check to the example where it is used
- Add some kind of definition of what constitutes success

2023-09-01 16:40 UTC, TheMeaningfulEngineer reviewed
Why is `20.Monitoring-subsystems` a directory if it doesn't render as subchapter:
![Screenshot from 2023-09-01 18-40-13](https://github.com/mendersoftware/mender-docs/assets/1640260/28e27571-40dc-4e44-914a-9874773e9c3d)

2023-09-01 16:45 UTC, TheMeaningfulEngineer commented on 09.Add-ons/20.Monitor/docs.md
>  ## Alerts
Why are alerts here?
Are they a concept more more important than all the other concepts introduces in the Architecture?

It reads as if `alert` = `email sent`.

And than below there's a:

> These alerts are also accessible via the Mender UI by clicking DEVICES on the left panel, then choosing a device, and tap the Monitoring tab.

2023-09-01 16:51 UTC, TheMeaningfulEngineer commented on 09.Add-ons/20.Monitor/docs.md
>  ## Architecture
No definition of `Check` nor `Subsystem`.

Whats a 'Check definition`?
A "Check definition" is calling the subsystem name?

Sorry, but I'm lost here

2023-09-01 17:04 UTC, TheMeaningfulEngineer requested changes
Maybe it's late again, and Friday but I can't see the concepts improved. :(
Here is the reasoning on why I think so.

My use case is:

> I want to get an alert when something is wrong on a device
> I want to define the condition what wrong is

What is a:

* Subsystem and why do I need to know about it to achieve the above?
* A check why do I need to know about it to achieve the above?
* What's the relationship between subsystems and checks?

From the picture (If I ignore the mender-monitor to check communication which is confusing) I can get that:

> Subsystems execute checks and that can result in an alert if the conditions are fulfilled.
 
No reference on subsystems in the Architecture at all and there is a whole page about it.

* Do I Check or Subsystems when I want to define a now condition for an alert?
* How do I "easily extend it and implement your own subsystems"?
* Why would I do that, and not make new Checks?

2023-09-02 05:08 UTC, MuchoLucho commented on 01.Get-started/05.Monitor/docs.md
> +>   mender-monitorctl --version
Makes sense to me. I was biased that no exit code different than 0 would mean success

2023-09-02 05:12 UTC, MuchoLucho commented on 09.Add-ons/20.Monitor/docs.md
> +calling them directly from your scripts.
I would just delete the phrase before the ”,” and it should make more sense. Still it assumes some previous concepts. Needs to revisit if they are all defined beforehand

2023-09-02 05:14 UTC, MuchoLucho commented on 09.Add-ons/20.Monitor/docs.md
>  ## Architecture
Right. It assumes the subsystems page was read, need to give at least a simple subtitle and redirect to the whole subchapter for the sake of clarity

2023-09-02 05:15 UTC, MuchoLucho commented on 09.Add-ons/20.Monitor/docs.md
>  ## Alerts
We fixed the terminology in here, but we did not touch the structure itself of the paragraph, I agree it can be improved

2023-09-02 05:16 UTC, MuchoLucho commented
> Why is `20.Monitoring-subsystems` a directory if it doesn't render as subchapter:
> ![Screenshot from 2023-09-01 18-40-13](https://github.com/mendersoftware/mender-docs/assets/1640260/28e27571-40dc-4e44-914a-9874773e9c3d)
> 

Sorry, I don't follow what you mean in here

2023-12-08 16:42 UTC, TheMeaningfulEngineer approved these changes
Got the tests to pass and the content is concluded.
@MuchoLucho please make the video overview and let's get a green light from Fabio and Peter to merge this big change.

2023-12-19 00:19 UTC, MuchoLucho commented
Hello @merlin-northern @tranchitella, I made a quick summary of the video so it would be easier to you to see what changed.  [monitor-add-on-walkthrough.webm](https://github.com/mendersoftware/mender-docs/assets/6395589/06f298ca-624b-4ab7-8960-50f59a175b61)

2023-12-20 19:03 UTC, estape11 approved these changes
I ran the examples and they worked as expected!

2023-12-20 19:08 UTC, merged