CE reviews - mtls
mendersoftware/mender-docs pull request #2165
Opened 2023-07-14 16:57 UTC by TheMeaningfulEngineer

Rewrite of the mtls section to provide a copy pastable working example.

2023-08-18 15:58 UTC, MuchoLucho commented on 08.Server-integration/03.Mutual-TLS-authentication/docs.md
> -!!! Hosted Mender is available in multiple [regions](/11.General/00.Hosted-Mender-regions/docs.md) to connect to. Make sure you select your desired one before proceeding.
We should still keep information about the multiple regions.

2023-08-18 16:00 UTC, MuchoLucho commented on 08.Server-integration/03.Mutual-TLS-authentication/docs.md
>  If you are using hosted Mender, you can host the mTLS ambassador in your infrastructure and point it to the upstream server `https://hosted.mender.io`.
```suggestion
If you are using hosted Mender, you can host the mTLS ambassador in your infrastructure and point it to the upstream server `https://hosted.mender.io` (US) or `https://eu.hosted.mender.io` (EU).
```

2023-11-24 19:32 UTC, MuchoLucho requested changes
I was not able to continue as I can not prove "you can communicate with the server correctly"

2023-11-24 19:32 UTC, MuchoLucho commented on 08.Server-integration/03.Mutual-TLS-authentication/01.Keys-and-certificates/docs.md
> +docker logout $DOCKER_REGISTRY_URL
I don't think handling authentication for the registry makes sense in here as this is necessary also for any kind of non-open-source on prem installation

2023-11-24 19:32 UTC, MuchoLucho commented on 08.Server-integration/03.Mutual-TLS-authentication/01.Keys-and-certificates/docs.md
> +For the production environment it is expected you have means to handle your PKI infrastructure and make security decisions based on how signing and key rotation takes place. You also have means to de
I wouldn't suggest key rotations if not necessary. Not a hard opinion in here

2023-11-24 19:32 UTC, MuchoLucho commented on 08.Server-integration/03.Mutual-TLS-authentication/01.Keys-and-certificates/docs.md
> +sudo chmod 0600 $(pwd)/server.key
Ending ``` missing

2023-11-24 19:32 UTC, MuchoLucho commented on 08.Server-integration/03.Mutual-TLS-authentication/02.Evaluation-with-docker-compose/docs.md
> +```bash
Why not `text` instead of `bash`?

2023-11-24 19:32 UTC, MuchoLucho commented on 08.Server-integration/03.Mutual-TLS-authentication/02.Evaluation-with-docker-compose/docs.md
> +# 2023/08/18 15:51:21 http: TLS handshake error from 192.168.88.249:46612: tls: client didn't provide a certificate
It gives me:

```
Can't use SSL_get_servername
depth=0 CN = local-domain-1993028.com, O = My Organization, OU = My Unit, emailAddress = myusername@example.com, C = NO, L = Oslo, ST = Oslo
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = local-domain-1993028.com, O = My Organization, OU = My Unit, emailAddress = myusername@example.com, C = NO, L = Oslo, ST = Oslo
verify error:num=21:unable to verify the first certificate
verify return:1
depth=0 CN = local-domain-1993028.com, O = My Organization, OU = My Unit, emailAddress = myusername@example.com, C = NO, L = Oslo, ST = Oslo
verify return:1
003E2B7D377F0000:error:0A00045C:SSL routines:ssl3_read_bytes:tlsv13 alert certificate required:ssl/record/rec_layer_s3.c:1586:SSL alert number 116
```

So there is a problem on the certificates generation from the previous copy+paste

2023-11-24 20:06 UTC, TheMeaningfulEngineer commented on 08.Server-integration/03.Mutual-TLS-authentication/01.Keys-and-certificates/docs.md
> +docker logout $DOCKER_REGISTRY_URL
Rejecting ad this won't be moved to on-prem doc with this PR.
It can be removed from here once we redo that.

2023-11-24 20:08 UTC, TheMeaningfulEngineer commented on 08.Server-integration/03.Mutual-TLS-authentication/01.Keys-and-certificates/docs.md
> +For the production environment it is expected you have means to handle your PKI infrastructure and make security decisions based on how signing and key rotation takes place. You also have means to de
Please add more info on what you're objecting to.

2023-11-24 20:08 UTC, TheMeaningfulEngineer commented on 08.Server-integration/03.Mutual-TLS-authentication/01.Keys-and-certificates/docs.md
> +sudo chmod 0600 $(pwd)/server.key
Why not a fix and push?

2023-11-24 20:09 UTC, TheMeaningfulEngineer commented on 08.Server-integration/03.Mutual-TLS-authentication/02.Evaluation-with-docker-compose/docs.md
> +```bash
Fair, will change.

2023-11-24 20:11 UTC, TheMeaningfulEngineer commented on 08.Server-integration/03.Mutual-TLS-authentication/02.Evaluation-with-docker-compose/docs.md
> +# 2023/08/18 15:51:21 http: TLS handshake error from 192.168.88.249:46612: tls: client didn't provide a certificate
No idea, have to debug it.

2023-11-24 20:19 UTC, MuchoLucho commented on 08.Server-integration/03.Mutual-TLS-authentication/01.Keys-and-certificates/docs.md
> +For the production environment it is expected you have means to handle your PKI infrastructure and make security decisions based on how signing and key rotation takes place. You also have means to de
I don't love it because this https://northern-tech.slack.com/archives/C0XM0KX9C/p1692689811985499?thread_ts=1692689174.204229&cid=C0XM0KX9C and this https://northern-tech.slack.com/archives/C02QYVA6NRE/p1662007450027929?thread_ts=1662006909.437769&cid=C02QYVA6NRE

2023-11-24 20:33 UTC, MuchoLucho commented on 08.Server-integration/03.Mutual-TLS-authentication/01.Keys-and-certificates/docs.md
> +sudo chmod 0600 $(pwd)/server.key
Done

2023-11-24 20:33 UTC, MuchoLucho commented on 08.Server-integration/03.Mutual-TLS-authentication/02.Evaluation-with-docker-compose/docs.md
> +```bash
Done

2023-12-08 11:00 UTC, TheMeaningfulEngineer commented
@merlin-northern 
Please take a look if the changes you're doing can be implemented here instead so we don't end up with conflicts.

2023-12-08 11:04 UTC, merlin-northern commented on 08.Server-integration/03.Mutual-TLS-authentication/01.Keys-and-certificates/docs.md
> +export MENDER_PASSWORD=password
ok you fixed in here what I posted in https://github.com/mendersoftware/mender-docs/pull/2272 so it is fine.

2024-01-19 18:30 UTC, TheMeaningfulEngineer commented on 08.Server-integration/03.Mutual-TLS-authentication/docs.md
> -!!! Hosted Mender is available in multiple [regions](/11.General/00.Hosted-Mender-regions/docs.md) to connect to. Make sure you select your desired one before proceeding.
Stale. Marking as resolved

2024-01-19 18:30 UTC, TheMeaningfulEngineer commented on 08.Server-integration/03.Mutual-TLS-authentication/docs.md
>  If you are using hosted Mender, you can host the mTLS ambassador in your infrastructure and point it to the upstream server `https://hosted.mender.io`.
Stale. Marking as resolved

2024-01-19 18:30 UTC, TheMeaningfulEngineer commented on 08.Server-integration/03.Mutual-TLS-authentication/01.Keys-and-certificates/docs.md
> +For the production environment it is expected you have means to handle your PKI infrastructure and make security decisions based on how signing and key rotation takes place. You also have means to de
Stale. Marking as resolved

2024-01-23 07:45 UTC, oldgiova commented on 08.Server-integration/03.Mutual-TLS-authentication/03.Production-installation-with-kubernetes/docs.md
> +You can rely on the `/status` endpoint for checking the ambassador status. You can check it from a device (virtual or physical) with the right certificates.
Edit: the readiness and liveness probes are already in the manifest:
```
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 30
```

So I guess we can just say:
```suggestion
You can rely on the `/status` endpoint for checking the ambassador status. You can check it from a device (virtual or physical) with the right certificates. Anyway, the kubernetes manifest already has a Liveness Probe and a Readiness Probe in place.
```

2024-01-23 09:32 UTC, oldgiova commented on 08.Server-integration/03.Mutual-TLS-authentication/02.Evaluation-with-docker-compose/docs.md
> +docker ps | grep 'mendersoftware/mender-client-qemu' > /dev/null && echo "Virtual client start successfully"  || echo "Container is not running or failed to start"
```suggestion
docker ps | grep 'mendersoftware/mender-client-qemu' > /dev/null && echo "Virtual client started successfully"  || echo "Container is not running or failed to start"
```

2024-01-23 09:39 UTC, oldgiova commented on 08.Server-integration/03.Mutual-TLS-authentication/03.Production-installation-with-kubernetes/docs.md
> +You can rely on the `/status` endpoint for checking the ambassador status. You can check it from a device (virtual or physical) with the right certificates.
Drop it, I understood now that it's not a test of the mtls itself, but it's a communication test between a client and Mender, through the mTLS.

2024-01-23 09:41 UTC, oldgiova approved these changes
Impressive job! Well done!

2024-02-01 21:41 UTC, oldgiova requested changes
Changes related to the `/status` endpoint

2024-02-01 21:41 UTC, oldgiova commented on 08.Server-integration/03.Mutual-TLS-authentication/03.Production-installation-with-kubernetes/docs.md
> +          periodSeconds: 30
```suggestion
        readinessProbe:
          httpGet:
            path: /status
            port: 8081
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /status
            port: 8081
          periodSeconds: 5
        startupProbe:
          httpGet:
            path: /status
            port: 8081
          failureThreshold: 36
          periodSeconds: 5
```

2024-02-01 21:41 UTC, oldgiova commented on 08.Server-integration/03.Mutual-TLS-authentication/03.Production-installation-with-kubernetes/docs.md
> +You can rely on the `/status` endpoint for checking the health of the ambassador service and set it as the endpoint for the kubernetes liveness probe.
```suggestion
```
This is useless now, since we're adding the new K8s probes in the manifest.

2024-02-02 07:34 UTC, kacf commented on 08.Server-integration/03.Mutual-TLS-authentication/01.Keys-and-certificates/docs.md
> +<!--AUTOVERSION: "mtls-ambassador:mender-%"/ignore-->
Maybe use `integration` instead of `ignore`? Then it will be updated to the latest bundle version automatically.

2024-02-28 16:27 UTC, oldgiova approved these changes
Just a nitpick about the replicas (my bad, sorry), and for me we're good!

2024-02-28 16:27 UTC, oldgiova commented on 08.Server-integration/03.Mutual-TLS-authentication/03.Production-installation-with-kubernetes/docs.md
> +  replicas: 1
```suggestion
```
Sorry, my bad: if you specify the HPA, you have to leave out the replica

2024-02-29 07:51 UTC, kacf commented
Mtls ambassador is not really my area of expertise, I think I'll let the other ones on the list review this.

2024-03-01 17:26 UTC, MuchoLucho approved these changes
All looked good last time I ran it by following this guide

2024-03-01 17:27 UTC, merged