Helm with Ingress included
mendersoftware/mender-docs pull request #2173
Opened 2023-07-24 13:03 UTC by oldgiova

# External Contributor Checklist

🚨 Please review the [guidelines for contributing](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md) to this repository.

- [x] Make sure that all commits follow the conventional commit [specification](https://github.com/mendersoftware/mendertesting/blob/master/commitlint/grammar.md) for the Mender project.

The majority of our contributions are fixes, which means your commit should have
the form below:

```
fix: Added documentation for the Ingress included in the Helm Chart

Changelog: Added documentation for the Ingress included in the Helm Chart
Ticket: <TICKET NUMBER> or <None
```

- [ ] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.

### Description

Please describe your pull request.

Thank you!

2023-08-20 04:36 UTC, tranchitella requested changes
Please use the autoversioning.

2023-08-20 04:36 UTC, tranchitella commented on 07.Server-installation/04.Production-installation-with-kubernetes/03.Mender-server/docs.md
> +for your convenience. Some sample Ingress values are detailed on the later section.
```suggestion
for your convenience. Some sample Ingress values are detailed in the later section.
```

2023-08-20 04:36 UTC, tranchitella commented on 07.Server-installation/04.Production-installation-with-kubernetes/03.Mender-server/docs.md
> +* The Mender helm chart is deployed with `api_gateway.env.SSL=false` option:
```suggestion
* The Mender Helm chart is deployed with the `api_gateway.env.SSL=false` option:
```

2023-08-20 04:36 UTC, tranchitella commented on 07.Server-installation/04.Production-installation-with-kubernetes/03.Mender-server/docs.md
> +You can refer to your Infrastructure Provider's documentation for how to create an Ingress resource.
```suggestion
You can refer to your Infrastructure Provider's documentation for creating an Ingress resource.
```

2023-08-20 04:36 UTC, tranchitella commented on 07.Server-installation/04.Production-installation-with-kubernetes/03.Mender-server/docs.md
> +<!--AUTOVERSION: "cat <<-EOF >> mender-%.yml"/ignore -->
```suggestion
<!--AUTOVERSION: "cat <<-EOF >> mender-%.yml"/integration -->
```

2023-08-20 04:36 UTC, tranchitella commented on 07.Server-installation/04.Production-installation-with-kubernetes/03.Mender-server/docs.md
> +cat <<-EOF >> mender-3.6.0-build3.yml
```suggestion
cat <<-EOF >> mender-3.6.1.yml
```

2023-08-20 04:36 UTC, tranchitella commented on 07.Server-installation/04.Production-installation-with-kubernetes/03.Mender-server/docs.md
> +<!--AUTOVERSION: "cat <<-EOF >> mender-%.yml"/ignore -->
```suggestion
<!--AUTOVERSION: "cat <<-EOF >> mender-%.yml"/integration -->
```

2023-08-20 04:36 UTC, tranchitella commented on 07.Server-installation/04.Production-installation-with-kubernetes/03.Mender-server/docs.md
> +cat <<-EOF >> mender-3.6.0-build3.yml
```suggestion
cat <<-EOF >> mender-3.6.1.yml
```

2023-08-20 04:36 UTC, tranchitella commented on 07.Server-installation/04.Production-installation-with-kubernetes/03.Mender-server/docs.md
> +<!--AUTOVERSION: "helm upgrade --install mender mender/mender -f mender-%.yml"/ignore -->
```suggestion
<!--AUTOVERSION: "helm upgrade --install mender mender/mender -f mender-%.yml"/integration -->
```

2023-08-20 04:36 UTC, tranchitella commented on 07.Server-installation/04.Production-installation-with-kubernetes/03.Mender-server/docs.md
> +helm upgrade --install mender mender/mender -f mender-3.6.0-build3.yml
```suggestion
helm upgrade --install mender mender/mender -f mender-3.6.1.yml
```

2023-08-20 20:39 UTC, oldgiova commented on 07.Server-installation/04.Production-installation-with-kubernetes/03.Mender-server/docs.md
> +<!--AUTOVERSION: "cat <<-EOF >> mender-%.yml"/ignore -->
This is an Azure example, won't work on the EKS cluster for the Integration tests.

2023-08-20 20:41 UTC, oldgiova commented
> Please use the autoversioning.

I'm a bit unsure...

My original idea was to provide some examples/guidance for EKS and AKS setups. Some key points are missing (secret, certificate management...) because it could vary depending on the implementation.

Maintaining this in the CI pipeline requires more effort because we have to push our own secrets and ingress conf in the Autoversion, and also actually testing the Ingress (simply applying it is useless: it could fail after creation).

Also considering that the `ingress` is disabled by default.

I'm going to add the autoversion in a separate commit and let's see how it goes on the actual integration tests.

2024-05-20 12:04 UTC, tranchitella reviewed
I don't known own anymore, therefore I'm not the one supposed to review this stuff.

2024-05-20 12:04 UTC, tranchitella approved these changes
Marking "Approved" only to remove the "Request changes" status.

2024-05-28 16:07 UTC, MuchoLucho approved these changes
It does make sense

2024-05-28 17:11 UTC, merlin-northern approved these changes
dropped some comments take them or leave them ;-) but like them!

2024-05-28 17:11 UTC, merlin-northern commented on 07.Server-installation/04.Production-installation-with-kubernetes/03.Mender-server/docs.md
> +**Required configuration**:
I am having doubts about the number of ** second level has two, right?

2024-05-28 17:11 UTC, merlin-northern commented on 07.Server-installation/04.Production-installation-with-kubernetes/03.Mender-server/docs.md
> +* If the health check is required, the internal path is `/ui`
tons of passive voice, the test may stop you.

2024-05-28 17:11 UTC, merlin-northern commented on 07.Server-installation/04.Production-installation-with-kubernetes/03.Mender-server/docs.md
> +cat <<-EOF >> mender-3.6.3.yml
this is `>>` (append) on purpose?

2024-05-29 09:16 UTC, oldgiova commented on 07.Server-installation/04.Production-installation-with-kubernetes/03.Mender-server/docs.md
> +**Required configuration**:
Here it's bold: 

**Required configuration**:
* Redirection from HTTP to HTTPS on the Ingress is required
* If the health check is required, the internal path is `/ui`

2024-05-29 10:43 UTC, oldgiova commented
That version was too outdated: created a new one here: https://github.com/mendersoftware/mender-docs/pull/2173

2024-05-29 10:43 UTC, closed without merging