fix: revamp of the integration checklist
mendersoftware/mender-docs pull request #2175
Opened 2023-07-24 13:57 UTC by TheMeaningfulEngineer

Ticket: CE-128
Changelog: None

2023-07-25 07:29 UTC, kacf reviewed
Nice rewrite! It reads much better than the old guide.

2023-07-25 07:29 UTC, kacf commented on 03.Client-installation/08.Integration-checklist/docs.md
> +! One way to overcome this is to do one regular rootfs update after the initial flashing before proceeding with the verification.
Aren't these instructions a bit circular? We are trying to verify that rootfs updates work, but then we are asking them to use what we are verifying before starting.

Granted, I suppose this issue isn't new. I'm not sure what's the best approach here though... Chicken and egg problem. Any ideas?

2023-07-25 07:29 UTC, kacf commented on 03.Client-installation/08.Integration-checklist/docs.md
> +!!! If you don't need full rootfs updates you only need to verify this step
Slightly conflicting with the above instruction:

> Please note that the full checklist is required only for doing full rootfs updates.

Maybe we can just remove that sentence above altogether and wait until they get down to this step right here to mention it?

2023-07-25 07:29 UTC, kacf commented on 03.Client-installation/08.Integration-checklist/docs.md
> +# "RootfsPartB": "/dev/nvme0n1p3"
Are the `#` characters intentional? They most likely won't be there, right? At least not for a working configuration.

2023-07-25 07:29 UTC, kacf commented on 03.Client-installation/08.Integration-checklist/docs.md
> +#/dev/nvme0n1p3 on / type ext4 ... ...
`#` here also. If you're trying to separate command from output, then perhaps it's better to split the code blocks.

I won't point out more of these.

2023-07-25 07:29 UTC, kacf commented on 03.Client-installation/08.Integration-checklist/docs.md
> +f you have verified all the steps you have confirmed your device has the correct partitioning and bootloader integration to do full rootfs updates.
Repeated line.

2023-07-25 07:39 UTC, TheMeaningfulEngineer commented on 03.Client-installation/08.Integration-checklist/docs.md
> +! One way to overcome this is to do one regular rootfs update after the initial flashing before proceeding with the verification.
Yes!
But that's the best bad way I have to solve it at the moment. :(

2023-07-25 07:42 UTC, TheMeaningfulEngineer commented on 03.Client-installation/08.Integration-checklist/docs.md
> +# "RootfsPartB": "/dev/nvme0n1p3"
Fair, it's an attempt to make it copy pastable and not have the output make the commands break.
Would you find this clearer:

```
#  Output:
# "RootfsPartA": "/dev/nvme0n1p2"
# "RootfsPartB": "/dev/nvme0n1p3"
```

2023-07-25 07:43 UTC, TheMeaningfulEngineer commented on 03.Client-installation/08.Integration-checklist/docs.md
> +#/dev/nvme0n1p3 on / type ext4 ... ...
Concluding, will address them whole in the upper comment.

2023-07-25 07:46 UTC, TheMeaningfulEngineer commented on 03.Client-installation/08.Integration-checklist/docs.md
> +! One way to overcome this is to do one regular rootfs update after the initial flashing before proceeding with the verification.
The solution is to ensure that generated images which are flashed directly to the device have duplicated content on both partitions.
I've experienced:
* the login credentials sometimes not working when manually switching
* the content of the second partition non existing 
    * this happened a while ago not for this test, for a yocto image. Apparently we deliberately removed the duplication of the second partition content. (how I understood Lluis, also quite a while ago)

2023-07-25 08:28 UTC, kacf commented on 03.Client-installation/08.Integration-checklist/docs.md
> +! One way to overcome this is to do one regular rootfs update after the initial flashing before proceeding with the verification.
> the content of the second partition non existing
> 
>     * this happened a while ago not for this test, for a yocto image. Apparently we deliberately removed the duplication of the second partition content. (how I understood Lluis, also quite a while ago)

Yeah, I remember.. I can't recall the exact reason right now, but I remember that it wasn't for nothing, there was some improvement because of it.

I don't really have any better ideas for this section either, so I guess we can just leave it like this for now.

2023-07-25 08:29 UTC, kacf commented on 03.Client-installation/08.Integration-checklist/docs.md
> +# "RootfsPartB": "/dev/nvme0n1p3"
It's clearer, yes! 👍

2023-07-25 08:55 UTC, TheYoctoJester requested changes
Added some polishing thoughts and taxonomy fixes here and there.
All in all a very nice piece!

2023-07-25 08:55 UTC, TheYoctoJester commented on 03.Client-installation/08.Integration-checklist/docs.md
> +To verify it's successfully running run the following commands and confirm the output:
This actually just checks if the process is correctly started by `systemd`

2023-07-25 08:55 UTC, TheYoctoJester commented on 03.Client-installation/08.Integration-checklist/docs.md
> +To verify it's successfully running run the following commands and confirm the output:
```suggestion
To verify the correct installation of the service, run the following commands and confirm the output:
```

2023-07-25 08:55 UTC, TheYoctoJester commented on 03.Client-installation/08.Integration-checklist/docs.md
> +In the remaining verification, we'll manually be executing similar steps to what the mender-client usually does in regular operations to communicate with the bootloader.
Taxonomy and casual language.

2023-07-25 08:55 UTC, TheYoctoJester commented on 03.Client-installation/08.Integration-checklist/docs.md
> +In the remaining verification, we'll manually be executing similar steps to what the mender-client usually does in regular operations to communicate with the bootloader.
```suggestion
In the remaining verification, we will manually be executing similar steps to what the Mender Client usually does in regular operations to communicate with the bootloader.
```

2023-07-25 08:55 UTC, TheYoctoJester commented on 03.Client-installation/08.Integration-checklist/docs.md
> +To not have the mender-client interfere with the manual verification it's best to disconnect the device from the internet to prevent an update happening during verification time.
```suggestion
To avoid the Mender Client interfering with the manual verification it is recommended disconnect the device from the internet.
```

2023-07-25 08:55 UTC, TheYoctoJester commented on 03.Client-installation/08.Integration-checklist/docs.md
> +Verify that the two commands to manipulate the bootloader environment are in the path and are executable. These are used by the mender-client to communicate with the bootloader.
```suggestion
Verify that the two commands to manipulate the bootloader environment are in the path and are executable. These are used by the Mender Client to communicate with the bootloader. 
```

2023-07-25 08:55 UTC, TheYoctoJester commented on 03.Client-installation/08.Integration-checklist/docs.md
> +Depending on the bootloader you're using these might be GRUB or uboot specific.
Casual language, clarification.

2023-07-25 08:55 UTC, TheYoctoJester commented on 03.Client-installation/08.Integration-checklist/docs.md
> +Depending on the bootloader you're using these might be GRUB or uboot specific.
```suggestion
The executables which the Mender Client expects are bootloader specific. By default, `GRUB` and `uboot` implementations are supported.
```

2023-07-25 08:55 UTC, TheYoctoJester commented on 03.Client-installation/08.Integration-checklist/docs.md
> +If you get errors when calling the `set` command without arguments, that's ok.
```suggestion
Errors upon calling the `set` command without arguments are expected and can be ignored, this step only checks the executable form.
```

2023-07-25 08:55 UTC, TheYoctoJester commented on 03.Client-installation/08.Integration-checklist/docs.md
> +These steps will identify the partitions and check if they align with what is in mender-client configuration.
Taxonomy

2023-07-25 08:55 UTC, TheYoctoJester commented on 03.Client-installation/08.Integration-checklist/docs.md
> +These steps will identify the partitions and check if they align with what is in mender-client configuration.
```suggestion
These steps will identify the partitions and check if they align with what is in the Mender Client configuration.
```

2023-07-25 08:55 UTC, TheYoctoJester commented on 03.Client-installation/08.Integration-checklist/docs.md
> +Check the partitions set in mender.conf to identify rootfs partitions:
```suggestion
Check the partitions set in `mender.conf` to identify rootfs partitions:
```

2023-07-25 08:55 UTC, TheYoctoJester commented on 03.Client-installation/08.Integration-checklist/docs.md
> +! By default mender-client look for [configuration at two locations](../07.Configuration-file/docs.md). One of those is `/var/lib/mender/mender.conf` which is - in the default case - a link to `/data
Taxonomy, wording.

2023-07-25 08:55 UTC, TheYoctoJester commented on 03.Client-installation/08.Integration-checklist/docs.md
> +! By default mender-client look for [configuration at two locations](../07.Configuration-file/docs.md). One of those is `/var/lib/mender/mender.conf` which is - in the default case - a link to `/data
```suggestion
! By default the Mender Client looks for [configuration in two locations](../07.Configuration-file/docs.md). One of those is `/var/lib/mender/mender.conf` which is - in the default case - a link to the persistent partition `/data/mender/mender.conf` and doesn't get overwritten during the rootfs update. We recommend keeping the backup of the `RootfsPartA/B` settings in `/var/lib/mender/mender.conf` as it is very rare that you need to change partition names as a result of an update.
```

2023-07-25 08:55 UTC, TheYoctoJester commented on 03.Client-installation/08.Integration-checklist/docs.md
> +If the device listed is an ambiguous device, such as `/dev/root`, you can use an alternative method for verifying it. If you call the following series of commands:
```suggestion
On some devices the rootfs is not listed as a block device but as `/dev/root` or similar. You can use an alternative method for verifying it, by calling the following series of commands:
```

2023-07-25 08:55 UTC, TheYoctoJester commented on 03.Client-installation/08.Integration-checklist/docs.md
> +Let's manually set the bootloader variable so it boots from the inactive partition on the next reboot.
```suggestion
Set the bootloader variables manually so it boots from the currently inactive partition on the next reboot.
```

2023-07-25 08:55 UTC, TheYoctoJester commented on 03.Client-installation/08.Integration-checklist/docs.md
> +grub-mender-grubenv-set mender_boot_part_hex 2
Additionally, why `mender_boot_part` and `mender_boot_part_hex`? Either needs an explanation, or a link to further documentation.

2023-07-25 08:55 UTC, TheYoctoJester commented on 03.Client-installation/08.Integration-checklist/docs.md
> +Once that is complete repeat the step to return to the previously active partition:
Minor language improvement.

2023-07-25 08:55 UTC, TheYoctoJester commented on 03.Client-installation/08.Integration-checklist/docs.md
> +Once that is complete repeat the step to return to the previously active partition:
```suggestion
After completion, return to the previously active partition by adapting the previous steps:
```

2023-07-25 08:55 UTC, TheYoctoJester commented on 03.Client-installation/08.Integration-checklist/docs.md
> +For this verification, this is a period during which the bootloader environmental variables are expected to change - either by mender-client or the bootloader itself - and the bootloader is expected
Taxonomy

2023-07-25 08:55 UTC, TheYoctoJester commented on 03.Client-installation/08.Integration-checklist/docs.md
> +For this verification, this is a period during which the bootloader environmental variables are expected to change - either by mender-client or the bootloader itself - and the bootloader is expected
```suggestion
For this verification, this is a period during which the bootloader environmental variables are expected to change - either by the Mender Client or the bootloader itself - and the bootloader is expected to enact conditional logic. For comparison, in the non-transition state, the bootloader variables are stable. 
```

2023-07-25 08:55 UTC, TheYoctoJester commented on 03.Client-installation/08.Integration-checklist/docs.md
> +* mender-client and the bootloader know there is a partitioning switch taking place
Taxonomy

2023-07-25 08:55 UTC, TheYoctoJester commented on 03.Client-installation/08.Integration-checklist/docs.md
> +* mender-client and the bootloader know there is a partitioning switch taking place
```suggestion
* the Mender Client and the bootloader know there is a partitioning switch taking place
```

2023-07-25 08:55 UTC, TheYoctoJester commented on 03.Client-installation/08.Integration-checklist/docs.md
> +Once you set the variables from above, confirm your current active partition and reboot:
Rewording suggestion.

2023-07-25 08:55 UTC, TheYoctoJester commented on 03.Client-installation/08.Integration-checklist/docs.md
> +Once you set the variables from above, confirm your current active partition and reboot:
```suggestion
As explained on the variables in the previous paragraph, test a full active partition switch including reboot:
```

2023-07-25 08:55 UTC, TheYoctoJester commented on 03.Client-installation/08.Integration-checklist/docs.md
> +The starting steps are similar to the successful case:
Rewording suggestion

2023-07-25 08:55 UTC, TheYoctoJester commented on 03.Client-installation/08.Integration-checklist/docs.md
> +The starting steps are similar to the successful case:
```suggestion
The process initiation is identical to the "success" form.
```

2023-07-25 08:55 UTC, TheYoctoJester commented on 03.Client-installation/08.Integration-checklist/docs.md
> +With the distinction where we're going to mess up the kernel on the inactive partition.
Rewording suggestion.

2023-07-25 08:55 UTC, TheYoctoJester commented on 03.Client-installation/08.Integration-checklist/docs.md
> +With the distinction where we're going to mess up the kernel on the inactive partition.
```suggestion
To trigger the rollback mechanism, rename the kernel on the inactive partition to break the boot process.
```

2023-07-25 08:55 UTC, TheYoctoJester commented on 03.Client-installation/08.Integration-checklist/docs.md
> +f you have verified all the steps you have confirmed your device has the correct partitioning and bootloader integration to do full rootfs updates.
I guess that line was accidentially commited.

2023-07-25 08:55 UTC, TheYoctoJester commented on 03.Client-installation/08.Integration-checklist/docs.md
> +! **Please note** - the trigger for the rollback is the fact that an unplanned second reboot happened during the transition period, not the fact that the bootloader detected a faulty kernel.
Rewording suggestion

2023-07-25 08:55 UTC, TheYoctoJester commented on 03.Client-installation/08.Integration-checklist/docs.md
> +! **Please note** - the trigger for the rollback is the fact that an unplanned second reboot happened during the transition period, not the fact that the bootloader detected a faulty kernel.
```suggestion
! **Please note** - the rollback is triggered by an unplanned second reboot happened during the transition period, not the bootloader somehow detecting a faulty kernel.
```

2023-07-25 11:06 UTC, TheMeaningfulEngineer commented on 03.Client-installation/08.Integration-checklist/docs.md
> +! In Yocto releases prior to 4.0 kirkstone, the names of the GRUB tools were the same as the U-Boot tools. Make sure to take this into account in the remaining examples on this page.
Nope :(
Don't know what this is about, just fixed the formatting.

2023-08-04 16:23 UTC, TheMeaningfulEngineer commented on 03.Client-installation/08.Integration-checklist/docs.md
> +!!! If you don't need full rootfs updates you only need to verify this step
Removing: `Please note that the full checklist is required only for doing full rootfs updates.` from above.

2023-08-09 04:26 UTC, kacf approved these changes
Some minor typos below, looks good to me otherwise!

2023-08-09 04:26 UTC, kacf commented on 03.Client-installation/08.Integration-checklist/docs.md
> +To avoid the Mender Client interfering with the manual verification it is recommended disconnect the device from the internet.
"recommended **to** disconnect"

2023-08-09 04:26 UTC, kacf commented on 03.Client-installation/08.Integration-checklist/docs.md
> +!!! To make the verification steps generally applicable, we change both variables in the steps event though they aren't both used in all cases.
"...**even** though..."

2023-08-17 20:21 UTC, estape11 requested changes

2023-08-17 20:21 UTC, estape11 commented on 03.Client-installation/08.Integration-checklist/docs.md
> +At the end of this step, we should have successfully identified the active partition (`nvme0n1p3` in the example) and the inactive partition (`nvme0n1p2`). We will use this info when proceeding with
```suggestion
At the end of this step, we should have successfully identified the active partition (`nvme0n1p3` in the example) and the inactive partition (`nvme0n1p2`). This information will be used later when we perform the switch test between partitions.
```

2023-08-17 20:21 UTC, estape11 commented on 03.Client-installation/08.Integration-checklist/docs.md
> +* the bootloader will start incrementing `bootcount` for every new boot attempt
```suggestion
* The bootloader will start incrementing by 1 the `bootcount` variable for every new boot attempt
```

2023-08-17 20:21 UTC, estape11 commented on 03.Client-installation/08.Integration-checklist/docs.md
> +* the Mender Client and the bootloader know there is a partitioning switch taking place
```suggestion
* The Mender Client and the bootloader become aware that there is a partitioning switch taking place
```

2023-08-17 20:21 UTC, estape11 commented on 03.Client-installation/08.Integration-checklist/docs.md
> +    * they can make decisions on when to rollback or commit
```suggestion
    * They can make decisions on when to rollback or commit
```

2023-08-17 20:21 UTC, estape11 commented on 03.Client-installation/08.Integration-checklist/docs.md
> +* returning the `upgrade_available` to `0` represents the conclusion of the transition state
```suggestion
* Returning the `upgrade_available` value to `0` implies the conclusion of the transition state
```

2023-08-17 20:21 UTC, estape11 commented on 03.Client-installation/08.Integration-checklist/docs.md
> +! **Please note** - the rollback is triggered by an unplanned second reboot happened during the transition period, not the bootloader somehow detecting a faulty kernel.
```suggestion
! **Please note** - the rollback is triggered by an unplanned second reboot that takes place during the transition period, and it is not a result of the bootloader detecting a faulty kernel in any way.
```

2023-08-17 20:21 UTC, estape11 commented on 03.Client-installation/08.Integration-checklist/docs.md
> +If you have verified all the steps you have confirmed your device has the correct partitioning and bootloader integration to do full rootfs updates.
```suggestion
If you have verified all the steps, then you have confirmed your device has the correct partitioning and bootloader integration to do full rootfs updates using Mender.
```

2023-08-22 13:59 UTC, TheMeaningfulEngineer commented on 03.Client-installation/08.Integration-checklist/docs.md
> +! One way to overcome this is to do one regular rootfs update after the initial flashing before proceeding with the verification.
Will update the wording.
Don't get the `check the specific board integration` part, can't this be a `dd` snippet?

2023-08-22 14:13 UTC, TheMeaningfulEngineer commented on 03.Client-installation/08.Integration-checklist/docs.md
> +Please note that depending on the types of storage the actual device names can vary.
Don't want to link to external docs, looks like an unnecessary dependency.
Risks it becoming stale or link broken.

The device name is whatever the device name is, and if someone want's to know more, they can research on their own.

2023-08-22 14:16 UTC, TheMeaningfulEngineer commented on 03.Client-installation/08.Integration-checklist/docs.md
> +At the end of this step, we should have successfully identified the active partition (`nvme0n1p3` in the example) and the inactive partition (`nvme0n1p2`). We will use this info when proceeding with
Expanded with UUID example.

2023-08-22 14:17 UTC, TheMeaningfulEngineer commented on 03.Client-installation/08.Integration-checklist/docs.md
> +grub-mender-grubenv-set mender_boot_part 2
Expanded with a section on this

2023-08-22 14:17 UTC, TheMeaningfulEngineer commented on 03.Client-installation/08.Integration-checklist/docs.md
> +grub-mender-grubenv-set mender_boot_part_hex 2
Added a section on this as well

2023-09-22 11:38 UTC, TheYoctoJester approved these changes

2023-09-22 11:38 UTC, TheYoctoJester commented on 03.Client-installation/08.Integration-checklist/docs.md
> +!! PARTUUID feature hasn't been tested for u-boot
Maybe "the PARTUUID feature ..."

2023-09-22 11:38 UTC, TheYoctoJester commented on 03.Client-installation/08.Integration-checklist/docs.md
> +Please note that the content can vary depending  storage actual device names or if you're using PARTUUIDs.
double blank between "depending" and "storage"

2023-09-26 04:30 UTC, estape11 requested changes
Small details

2023-09-26 04:30 UTC, estape11 commented on 03.Client-installation/08.Integration-checklist/docs.md
> +For this verification, this is a period during which the bootloader environmental variables are expected to change - either by the Mender Client or the bootloader itself - and the bootloader is expec
```suggestion
During this verification process, it is expected that the bootloader's environment variables will experience changes - either by the Mender Client or the bootloader itself - and the bootloader is expected to enact conditional logic. For comparison, in the non-transition state, the bootloader's variables remain unchanged. 
```

2023-09-26 04:30 UTC, estape11 commented on 03.Client-installation/08.Integration-checklist/docs.md
> +To notify the bootloader about the switch to the transitional state we will set the following variables:
```suggestion
To notify the bootloader about the switch to the transitional state, we will set the following variables:
```

2023-09-26 04:30 UTC, estape11 commented on 03.Client-installation/08.Integration-checklist/docs.md
> +This is as expected, we can conclude the transition state and confirm the variables remain stable:
```suggestion
This is as expected, we can conclude the transition state and confirm the variables remain unchanged:
```

2023-09-26 04:30 UTC, estape11 commented on 03.Client-installation/08.Integration-checklist/docs.md
> +The device will attempt to boot, fail and then roll back to booting from the previously working partition.
```suggestion
The device will attempt to boot; however, it will fail and trigger a rollback to booting from the previously working partition.
```

2023-09-26 04:30 UTC, estape11 commented on 03.Client-installation/08.Integration-checklist/docs.md
> +You can return your kernel back to normal again:
```suggestion
Now, you can proceed and return your kernel back to normal again:
```

2023-09-26 04:30 UTC, estape11 commented on 03.Client-installation/08.Integration-checklist/docs.md
> +If you have verified all the steps you have confirmed that your device has the correct partitioning and bootloader integration to do full rootfs updates using Mender.
```suggestion
If you have successfully followed and verified all the steps, you can confirm that your device has the appropriate partitioning and bootloader integration for complete rootfs updates using Mender.
```

2023-09-27 10:32 UTC, TheMeaningfulEngineer commented on 03.Client-installation/08.Integration-checklist/docs.md
> +You can return your kernel back to normal again:
Verbose, rejecting

2023-09-27 10:40 UTC, TheMeaningfulEngineer commented on 03.Client-installation/08.Integration-checklist/docs.md
> +! One way to overcome this is to do one regular rootfs update after the initial flashing before proceeding with the verification.
No follow up. Mrking as resolved.

2023-09-28 15:37 UTC, estape11 approved these changes
All good

2023-09-29 02:29 UTC, merged