chore: Adjust Application update tutorial to match UI onboarding
mendersoftware/mender-docs pull request #2195
Opened 2023-08-11 14:08 UTC by michaelntech

Ticket: MEN-6681

# External Contributor Checklist

🚨 Please review the [guidelines for contributing](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md) to this repository.

- [ ] Make sure that all commits follow the conventional commit [specification](https://github.com/mendersoftware/mendertesting/blob/master/commitlint/grammar.md) for the Mender project.

The majority of our contributions are fixes, which means your commit should have
the form below:

```
fix: <SHORT DESCRIPTION OF FIX>

<OPTIONAL LONGER DESCRIPTION>

Changelog: <USER-FRIENDLY-CHANGE-DESCRIPTION> or <None>
Ticket: <TICKET NUMBER> or <None>
```

- [ ] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.

### Description

Please describe your pull request.

Thank you!

2023-08-11 14:09 UTC, michaelntech commented
To go with https://github.com/mendersoftware/mender-demo-artifact/pull/268 and https://github.com/mendersoftware/gui/pull/3870

2023-08-17 07:46 UTC, lluiscampos requested changes
Thanks for refreshing this up @michaelntech!

Once we are here, can we tidy up a bit the images? I found several that are not referenced that should be removed.

2023-08-17 07:46 UTC, lluiscampos commented on 01.Get-started/02.Deploy-an-application-update/docs.md
> -![create a deployment](Image_6.png)
`Image_6.png` reference has been removed from the guide, let's remove the image altogether.

2023-08-17 07:46 UTC, lluiscampos commented on 01.Get-started/02.Deploy-an-application-update/docs.md
> +Select the Release with the name beginning *mender-demo-artifact*; this will be deployed to your device.
I think all this is referring to `Image_7`, which is not referenced.

2023-08-17 07:46 UTC, lluiscampos commented on 01.Get-started/02.Deploy-an-application-update/docs.md
> +!!! Leave the demo web page from the previous step open, you'll use it to verify the update at the end of this step.
This is okey to write (and the other comment at the end asking for refresh).

But I think that after the second deployment the GUI still tells you "go to ... and refresh the page to see your update" so the instructions are slightly different.

2023-08-17 07:46 UTC, lluiscampos commented on 01.Get-started/02.Deploy-an-application-update/docs.md
> -![Upload web page](Image_14.png)
Another image de-referenced, please delete it.

2023-08-17 09:44 UTC, michaelntech commented on 01.Get-started/02.Deploy-an-application-update/docs.md
> +!!! Leave the demo web page from the previous step open, you'll use it to verify the update at the end of this step.
In the updated onboarding we now stop the tooltip instructions after the first deployment, and just refer to the docs for this 2nd optional part - that's why I chose to be explicit here.

2023-08-17 10:05 UTC, lluiscampos commented on 01.Get-started/02.Deploy-an-application-update/docs.md
> +!!! Leave the demo web page from the previous step open, you'll use it to verify the update at the end of this step.
Ok. Thanks!

2023-08-17 10:06 UTC, lluiscampos approved these changes
Great!

2023-08-17 10:25 UTC, merged