Docs: Adds local mender-configure artifacts generation
mendersoftware/mender-docs pull request #2219
Opened 2023-08-31 00:39 UTC by MuchoLucho

# External Contributor Checklist

🚨 Please review the [guidelines for contributing](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md) to this repository.

- [x] Make sure that all commits follow the conventional commit [specification](https://github.com/mendersoftware/mendertesting/blob/master/commitlint/grammar.md) for the Mender project.

The majority of our contributions are fixes, which means your commit should have
the form below:

```
fix: <SHORT DESCRIPTION OF FIX>

<OPTIONAL LONGER DESCRIPTION>

Changelog: <USER-FRIENDLY-CHANGE-DESCRIPTION> or <None>
Ticket: <TICKET NUMBER> or <None>
```

- [x] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.

### Description

Please describe your pull request.

Thank you!

2023-08-31 05:44 UTC, kacf approved these changes
Looks good, just a couple of minor corrections from me. I'm approving now so you can merge immediately after fixing.

2023-08-31 05:44 UTC, kacf commented on 09.Add-ons/10.Configure/docs.md
> +The `mender-configure` add-on was designed thinking on being executed from the UI for one device at a time, however, you can generate the artifact manually and then create deployments to groups (stat
Maybe rephrase:

```
The `mender-configure` add-on was designed to be executed from the UI for one device at a time
```

2023-08-31 05:44 UTC, kacf commented on 09.Add-ons/10.Configure/docs.md
> +You will need an script already localted in `/usr/lib/mender-configure/apply-device-config.d` as described in ["How to make an apply-device-config script"](01.Device-integration/docs.md#how-to-write-
"You will need **a** script already **located** in..."

2023-08-31 05:44 UTC, kacf commented on 09.Add-ons/10.Configure/docs.md
> +Then just upload it to the Mender Server and you are ready to create the deployment for groups of devices.
Maybe also mention that you need to deploy from the normal Deployment section of the UI, not from the Configure section. It should be obvious, since Configure is per-device, but just to make it super clear.

2023-08-31 05:54 UTC, kacf commented on 09.Add-ons/10.Configure/docs.md
> +The `mender-configure` add-on was designed thinking on being executed from the UI for one device at a time, however, you can generate the artifact manually and then create deployments to groups (stat
I think this should fix the passive voice checker as well.

2023-08-31 07:17 UTC, TheMeaningfulEngineer commented on 09.Add-ons/10.Configure/docs.md
> +    -T "mender-configure" \
Cool!
So device type `mender-configure` combined with the configuration key value pairs as json in the meta data is the 'configuration format'?

2023-08-31 14:52 UTC, TheMeaningfulEngineer commented on 09.Add-ons/10.Configure/docs.md
> +    -T "mender-configure" \
"T" is the update module name, not device type.

2023-08-31 18:41 UTC, MuchoLucho commented on 09.Add-ons/10.Configure/docs.md
> +The `mender-configure` add-on was designed thinking on being executed from the UI for one device at a time, however, you can generate the artifact manually and then create deployments to groups (stat
Handled in 77fac55c119ebb15acf141faf240312c4e841f2b

2023-08-31 18:41 UTC, MuchoLucho commented on 09.Add-ons/10.Configure/docs.md
> +You will need an script already localted in `/usr/lib/mender-configure/apply-device-config.d` as described in ["How to make an apply-device-config script"](01.Device-integration/docs.md#how-to-write-
Handled in 77fac55c119ebb15acf141faf240312c4e841f2b

2023-08-31 18:41 UTC, MuchoLucho commented on 09.Add-ons/10.Configure/docs.md
> +Then just upload it to the Mender Server and you are ready to create the deployment for groups of devices.
Handled in 77fac55c119ebb15acf141faf240312c4e841f2b

2023-08-31 18:43 UTC, MuchoLucho commented
Hello folks, I added a new part of "signed mender-configure" artifacts. Can any of you give me your blessing?

2023-09-01 07:12 UTC, kacf approved these changes
Looks good!

2023-09-01 07:12 UTC, kacf commented on 09.Add-ons/10.Configure/docs.md
> +You will need a script already localted in `/usr/lib/mender-configure/apply-device-config.d` as described in ["How to make an apply-device-config script"](01.Device-integration/docs.md#how-to-write-a
`localted` -> `located`

2023-09-01 07:12 UTC, kacf commented on 09.Add-ons/10.Configure/docs.md
> +You can take advantage of this approach to handle signed artifacts as you can include signatures from your workstation as opposed by using the Mender Configure UI per device to deploy a configuration
"...generate **the** key..."

2023-11-17 16:31 UTC, TheMeaningfulEngineer requested changes
Nice!
One thing that is missing is how will the UI behave once you deploy the configuration this way.

The reason why this isn't fully equivalent to using the UI is that this way only the `reported` (of the [configuration API](https://docs.mender.io/api/#management-api-device-configure-get-device-configuration) get changed while the `configure` remains the same.
If you use the API the `configured` changes first and that triggers the generation of the new update.

![image](https://github.com/mendersoftware/mender-docs/assets/1640260/93286a43-e548-4547-a712-795f58f2b2ca)

You should confirm that the UI will function normally after using this apprach and document that.

2024-03-04 01:47 UTC, MuchoLucho commented
![image](https://github.com/mendersoftware/mender-docs/assets/6395589/731c4c0f-d697-4373-8c6d-23ee8d88f6c8)
I can confirm after usin this approach the UI reflects the change made by using the Artifact instead of using the UI itself

2025-03-07 08:34 UTC, TheMeaningfulEngineer commented
@lluiscampos @MuchoLucho 
With the latest discussion where we shouldn't add things to the docs that aren't supported, I'd vote for moving this to mender hub instead.
The configure feature has been developed to work with one device only for the moment.
This is a workaround how to make it work with two.
Seems like ti works ok, but no guarantee that this will be the case in the future.

So I vote for mender hub instead the official docs.

2025-03-10 07:45 UTC, lluiscampos commented
FYI @estenberg as docs owner,

> So I vote for mender hub instead the official docs.

Me too :raising_hand_man: 

Closing the PR. @MuchoLucho If capacity permits, follow-up in Mender Hub :innocent:

2025-03-10 07:45 UTC, closed without merging

2025-03-10 17:44 UTC, estenberg commented
This is useful, but agree it's fair to have in MH instead since we don't conveniently support multi-device-updates to configure.

However, @MuchoLucho I think a better approach could be instead of creating the Artifacts you just make a script that calls the deviceconfig API to change a configuration attribute? I can take a list of Device IDs and a JSON (or key values).