Getting started revamp
mendersoftware/mender-docs pull request #2223
Opened 2023-09-22 17:58 UTC by MuchoLucho

# External Contributor Checklist

🚨 Please review the [guidelines for contributing](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md) to this repository.

- [x] Make sure that all commits follow the conventional commit [specification](https://github.com/mendersoftware/mendertesting/blob/master/commitlint/grammar.md) for the Mender project.

The majority of our contributions are fixes, which means your commit should have
the form below:

```
fix: <SHORT DESCRIPTION OF FIX>

<OPTIONAL LONGER DESCRIPTION>

Changelog: <USER-FRIENDLY-CHANGE-DESCRIPTION> or <None>
Ticket: <TICKET NUMBER> or <None>
```

- [x] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.

### Description

Revamp of Get started docs for Virtual devices and "Deploying an application Update" that is related to the "Virtual Device" section

2023-09-27 10:46 UTC, TheMeaningfulEngineer commented
@merlin-northern 
Hey,
you're doing the onboarding test this sprint.
Could you follow the docs from this PR and do the review of these doc as part of it?

2023-09-27 11:22 UTC, merlin-northern commented
> @merlin-northern Hey, you're doing the onboarding test this sprint. Could you follow the docs from this PR and do the review of these doc as part of it?

@TheMeaningfulEngineer any chance it will get merged this week?

2023-10-04 11:32 UTC, michaelntech commented on 01.Get-started/02.Deploy-an-application-update/docs.md
> +[Step 1 - Create a Deployment](#step-1---create-a-deployment); this time, use the *hello-world* Release.
This adjusted link no longer works for me - the original `#step-1-create-a-deployment` works

2023-10-04 12:11 UTC, michaelntech requested changes
All looks good, except for the link I commented on!

2023-10-10 08:43 UTC, TheMeaningfulEngineer approved these changes

2023-10-10 09:33 UTC, michaelntech approved these changes

2023-10-10 09:44 UTC, merged