Docs: First iteration over direct upload section
mendersoftware/mender-docs pull request #2241
Opened 2023-10-20 17:09 UTC by MuchoLucho

# External Contributor Checklist

🚨 Please review the [guidelines for contributing](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md) to this repository.

- [ ] Make sure that all commits follow the conventional commit [specification](https://github.com/mendersoftware/mendertesting/blob/master/commitlint/grammar.md) for the Mender project.

The majority of our contributions are fixes, which means your commit should have the form below:

```
fix: <SHORT DESCRIPTION OF FIX>

<OPTIONAL LONGER DESCRIPTION>

Changelog: <USER-FRIENDLY-CHANGE-DESCRIPTION> or <None>
Ticket: <TICKET NUMBER> or <None>
```

- [x] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.

### Description

Please describe your pull request.

Thank you!

2023-10-20 18:03 UTC, TheMeaningfulEngineer requested changes
Misses a new section in the server installation (the evaluation with docker compose) on how to enable variables for the server to work this way.


UPDATE: Make no sense to complicate docker compose with this + it wont be visible
It should just link to the variable in the helm chart once it's updated.

2023-10-27 11:43 UTC, tranchitella commented on 07.Server-installation/09.Direct-upload/docs.md
> +This feature drastically reduces the time to upload the Mender artifact to the Mender artifact storage, especially when uploading large artifacts (1TB for example), while also reducing the load on th
```suggestion
The Direct Upload feature provides a Mender channel to upload artifacts directly to the Mender artifact storage, processing it and putting it in the correct place and structure, without going through any other Mender component like the API gateway or deployments service.
This is an API/CLI feature only, and you can see the progress in the Mender Web UI only after the process completes successfully.
This feature drastically reduces the time to upload the Mender artifact to the Mender artifact storage, especially when uploading large artifacts (1TB for example), while also reducing the load on the Mender server infrastructure.
```

2023-10-27 11:43 UTC, tranchitella commented on 07.Server-installation/09.Direct-upload/docs.md
> +* To use the direct upload feature, the user needs to have at least the Deployments Manager and Releases Manager roles.
```suggestion
* To use the direct upload feature, the user must have at least the Deployments Manager and Releases Manager roles.
```

2023-10-27 11:43 UTC, tranchitella commented on 07.Server-installation/09.Direct-upload/docs.md
> +For uploading an artifact you will need to have a session token, this could be solved by running the following command:
```suggestion
For uploading a Mender Artifact you will need to have a session token. You can get one by running the following command:
```

2023-10-27 12:49 UTC, TheMeaningfulEngineer commented on 07.Server-installation/09.Direct-upload/docs.md
> +This feature drastically reduces the time to upload the Mender artifact to the Mender artifact storage, especially when uploading large artifacts (1TB for example), while also reducing the load on th
Couldn't commit this one, github prevented saying no change exists

2023-10-27 16:16 UTC, TheMeaningfulEngineer approved these changes

2023-10-27 16:18 UTC, merged