Fix: Warns Mender delta updates not being tested on UBIFS
mendersoftware/mender-docs pull request #2242
Opened 2023-10-26 20:59 UTC by MuchoLucho

Changelog: None
Ticket: None

# External Contributor Checklist

🚨 Please review the [guidelines for contributing](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md) to this repository.

- [X] Make sure that all commits follow the conventional commit [specification](https://github.com/mendersoftware/mendertesting/blob/master/commitlint/grammar.md) for the Mender project.

The majority of our contributions are fixes, which means your commit should have
the form below:

```
fix: <SHORT DESCRIPTION OF FIX>

<OPTIONAL LONGER DESCRIPTION>

Changelog: <USER-FRIENDLY-CHANGE-DESCRIPTION> or <None>
Ticket: <TICKET NUMBER> or <None>
```

- [X] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.

### Description

It warns Mender delta deployments have not been tested over UBIFS

Thank you!

2023-10-27 08:12 UTC, TheMeaningfulEngineer requested changes
The message leaves the reader without action, just waiting until as what can they do, until Northern.tech 'still needs to test it'.
We know it doesn't work technically.
Would change it to:

```
!! Delta aren't supported with devices running UBIFS. If this is your use case please contact us on support@mender.io
```

None of the chapters where you introduced the warning relate to the client integration focus on the artifact generation and the server.

I would mention it only in [here](https://docs.mender.io/overview/delta-update) in the docs.


And in the [hub page](https://hub.mender.io/t/robust-delta-update-rootfs/1144) - but here without the `contact us on support@mender.io` part.

2023-10-28 00:17 UTC, MuchoLucho commented
Hey @TheMeaningfulEngineer, I agree about the message as I tried it was more positive, but disagree with you about the location of the message. I consider that the "Overview section" should be as clean as possible, and this detail level only cares to the person who is going to actually will implement it.

2023-10-28 08:28 UTC, tranchitella approved these changes

2023-11-10 17:24 UTC, TheMeaningfulEngineer approved these changes

2023-11-10 17:51 UTC, merged