fix: misprints in the MTLS env. variables definition
mendersoftware/mender-docs pull request #2272
Opened 2023-12-08 08:02 UTC by merlin-northern

Changelog: Title
Ticket: None

2023-12-08 10:04 UTC, TheMeaningfulEngineer requested changes
We're rewriting this whole section: https://github.com/mendersoftware/mender-docs/pull/2165

2023-12-12 05:25 UTC, merlin-northern commented
> The current docs don't give result in a working example. We're rewriting this whole section: #2165 It is almost done to give a copy-paste way to set up everything.
> 
> I'd reject this and hope to have your review on the other PR soon.

I checked the other one, and you fixed it there, so I think when you merge #2165 you can close this one.

2023-12-14 10:22 UTC, tranchitella approved these changes

2023-12-14 10:30 UTC, TheMeaningfulEngineer approved these changes
Think this is just cosmetics which doesn't improve the mtls docs.
But the mtls rewrite is taking ages so can't push back with that argument.
Approving.

2023-12-14 10:31 UTC, merged