WIP in MEN-6784
mendersoftware/mender-docs pull request #2289
Opened 2023-12-14 09:42 UTC by kacf

Ticket: [MEN-6784](https://northerntech.atlassian.net/browse/MEN-6784)

2024-01-03 09:35 UTC, kacf commented on 03.Client-installation/02.Install-with-Debian-package/docs.md
> +<!--AUTOMATION: execute=bash get-mender.sh -c experimental -->
I will create a ticket to revert the `experimental` flag.

2024-01-03 09:37 UTC, kacf commented
@TheMeaningfulEngineer: There is *a lot* of repetition here, so I don't expect you to look at all of it. But it would be good to have an ack on the general approach.

@lluiscampos: Please check the last commit.

2024-01-05 08:22 UTC, TheMeaningfulEngineer requested changes
If I'm reading this correctly, this now exists as multiple systemd services instead of one `mender-client`.
So for anyone who was depending on `mender-client` or maybe `mender setup` things will break.


Let's have a chat to resolve this as a general topic before going forwards.
Am starting to form the perspective that we're stretching the definition of a "drop in replacement" too thin.

2024-01-05 09:35 UTC, lluiscampos commented
> If I'm reading this correctly, this now exists as multiple systemd services instead of one `mender-client`. So for anyone who was depending on `mender-client` or maybe `mender setup` things will break.
> 
> Let's have a chat to resolve this as a general topic before going forwards. Am starting to form the perspective that we're stretching the definition of a "drop in replacement" too thin.

@TheMeaningfulEngineer For context for the discussion:

* First we tried with having `mender-client` service as an alias to the new ones. See: https://northerntech.atlassian.net/browse/MEN-6812
    * This created technical inconsistencies, because both auth and update conceptually could be aliases to the `mender-client` old service
* We had feedback both internally and externally that this was a bad idea overall. See https://hub.mender.io/t/feedback-on-mender-c/6344
* And finally decided to remove this alias to make it "correct" at the cost of the drop-in replacement goal. See https://northerntech.atlassian.net/browse/MEN-6858

2024-01-05 12:04 UTC, lluiscampos requested changes
I cannot say it was fun reading so much text. Great work.

A lot of comments below. At some point (too late, maybe) I stopped with the only casing comments but as I said there feel free to still replace the rest.

See the comment regarding `mender-client` deb package: it will also install mender-flash, mender-setup and mender-snapshot. That particular thing is the only blocker from my review.

2024-01-05 12:10 UTC, lluiscampos commented on 06.Artifact-creation/03.Combining-system-and-application-updates/docs.md
> +When performing Operating System updates using the A/B partitioning schema, the Mender-update Client writes a new filesystem image directly to the inactive partition, using the rootfs-image update mo
Please note in this one that the second change is not casing, but actually missing the `-update` suffix.

2024-01-18 08:35 UTC, kacf commented on 03.Client-installation/02.Install-with-Debian-package/docs.md
> +<!--AUTOMATION: execute=bash get-mender.sh -c experimental -->
No need to, it has already been merged, so removing `experimental` now.

2024-01-18 08:42 UTC, kacf commented on 02.Overview/15.Taxonomy/docs.md
> +* _Mender-auth_, _Mender-auth Client_ - A user space application running on a
@TheMeaningfulEngineer mentioned capital casing in Slack (5th Jan) when mentioning them together as a name, so I think I'll stick to that.

2024-01-18 08:47 UTC, kacf commented on 02.Overview/11.Security/docs.md
> +A Device, running the mender-auth and mender-update clients, communicates with
I decided to sidestep this casing question by always referring to `mender-auth` and `mender-update` in monospaced code style, in the few places where I have kept them (most are reverted now). This highlights better that it's a very low level thing.

2024-01-18 09:09 UTC, TheMeaningfulEngineer commented on 02.Overview/15.Taxonomy/docs.md
> +* _Mender-auth_, _Mender-auth Client_ - A user space application running on a
@TheYoctoJester 
I'm trying to follow what you were giving me feedback on in reviews.
Though I have no clue if both are capitalized or one. 
Are you calling it "Mender Client" or "Mender client"?

@kacf 
`Mender-auth` looks like a name of the cli application. I wouldn't capitalize that.

My suggestion is to make a distinction between a binary name and a 'use case' name.
This was simpler when binary == use case but as the relations between the binaries get more complicated the "use case name" needs to be the first contact as it's simpler to reason with.

We tried to follow that in the rewrite of the monitoring section.
There is `Mender Monitor` which is the 'use case` name and than if you want to go into the implementation this is what [Mender Monitor actually is](https://docs.mender.io/add-ons/monitor/concepts).

Or here:
![image](https://github.com/mendersoftware/mender-docs/assets/1640260/165fde7a-e9c8-417b-b5cd-77c2e76884fd)

You need to install the Mender Monitor add-on.
Now this is `mender-monitord` and `mender-monitorctl` and you have to have `mender` there as well.
But that's implementation which might change, but use case wise you're installing "Mender Monitor add-on to achieve the monitoring of your device".

2024-01-18 10:23 UTC, kacf commented on 02.Overview/15.Taxonomy/docs.md
> +* _Mender-auth_, _Mender-auth Client_ - A user space application running on a
> `Mender-auth` looks like a name of the cli application. I wouldn't capitalize that.
> 
> My suggestion is to make a distinction between a binary name and a 'use case' name. This was simpler when binary == use case but as the relations between the binaries get more complicated the "use case name" needs to be the first contact as it's simpler to reason with.
> 
> We tried to follow that in the rewrite of the monitoring section. There is `Mender Monitor` which is the 'use case` name and than if you want to go into the implementation this is what [Mender Monitor actually is](https://docs.mender.io/add-ons/monitor/concepts).

Yes, this is what I've also tried to follow. I don't refer to `mender-auth` and `mender-update` as anything other than binary names, always code styled. "Mender Client" however, is plain text, and with capital C (which it already was, I didn't change it).

2024-01-19 08:14 UTC, lluiscampos approved these changes
I haven't read in full this time the big commit. The rest looks good. Good work.

2024-01-19 08:25 UTC, kacf commented
> I haven't read in full this time the big commit.

That's fine. It was (almost) a pure revert, very few things were manually changed. So the chance for mistakes is low.

2024-01-19 14:15 UTC, TheMeaningfulEngineer reviewed
It seems like you still intended that "Mender-auth client" has a meaning.
This is still a bit confusing to me, I'm assuming the mender connect requirement is driving this.

Also found the split into `mender-auth` and `mender-authd` more confusing than not.

Let's go for another round on Monday

2024-01-19 14:15 UTC, TheMeaningfulEngineer commented on 03.Client-installation/02.Install-with-Debian-package/01.Upgrading/docs.md
> +title: Upgrading
My gut feeling is that we should mention and put a link to the new yocto changes here as well.
The recipe name is changing as well, so that looks like it might break things.

2024-01-19 14:15 UTC, TheMeaningfulEngineer commented on 03.Client-installation/02.Install-with-Debian-package/01.Upgrading/docs.md
> +title: Upgrading
Why change the yocto recipe name in the first place?

2024-01-19 14:15 UTC, TheMeaningfulEngineer commented on 06.Artifact-creation/06.Standalone-deployment/docs.md
> +will entail disabling or removing any `systemd` unit that starts the Mender-update client. If you want to check if Mender is running as a daemon, you can try the following command:
```suggestion
must make sure that the `mender-updated` service isn't running. If you want to check if Mender is running as a daemon, you can try the following command:
```

2024-01-19 14:15 UTC, TheMeaningfulEngineer commented on 09.Add-ons/90.Mender-Connect/docs.md
> +Mender Connect is loosely coupled with the Mender Auth Client. The main information passed between
```suggestion
Mender Connect is loosely coupled with the `mender-auth`. The main information passed between
```

2024-01-19 14:15 UTC, TheMeaningfulEngineer commented on 09.Add-ons/90.Mender-Connect/docs.md
> +can interact with the Mender Server, the Mender-auth client passes the authorization token over DBus
```suggestion
can interact with the Mender Server, the `mender-auth` passes the authorization token over DBus
```

2024-01-19 14:15 UTC, TheMeaningfulEngineer commented on 10.Downloads/docs.md
> +After installing the Mender clients with [get.mender.io](https://get.mender.io),
```suggestion
After installing the Mender client with [get.mender.io](https://get.mender.io),
```

2024-01-19 14:15 UTC, TheMeaningfulEngineer commented on 10.Downloads/docs.md
> +To prevent the Mender clients from upgrading when upgrading the rest of the
```suggestion
To prevent the Mender client from upgrading when upgrading the rest of the
```

2024-01-19 14:15 UTC, TheMeaningfulEngineer commented on 10.Downloads/docs.md
> + To prevent the Mender clients from upgrading when upgrading the rest of the
```suggestion
 To prevent the Mender client from upgrading when upgrading the rest of the
```

2024-01-19 14:15 UTC, TheMeaningfulEngineer commented on 10.Downloads/docs.md
> +You need two applications for any add-on to function: the [Mender-auth Client](../02.Overview/15.Taxonomy/docs.md)
```suggestion
You need two applications for any add-on to function: `mender-auth` one of the components of the Mender client, ```

2024-01-19 14:24 UTC, TheYoctoJester reviewed
Probably I missed a lot of places still where the taxonomy is not consistent.

2024-01-19 14:24 UTC, TheYoctoJester commented on 09.Add-ons/90.Mender-Connect/docs.md
> +Mender Connect is loosely coupled with the Mender Auth Client. The main information passed between
```suggestion
Mender Connect is loosely coupled with `mender-auth. The main information passed between
```

2024-01-19 14:24 UTC, TheYoctoJester commented on 09.Add-ons/90.Mender-Connect/docs.md
> +can interact with the Mender Server, the Mender-auth client passes the authorization token over DBus
```suggestion
can interact with the Mender Server, `mender-auth` passes the authorization token over DBus
```

2024-01-19 14:24 UTC, TheYoctoJester commented on 10.Downloads/docs.md
> +After installing the Mender clients with [get.mender.io](https://get.mender.io),
```suggestion
After installing the Mender Client with [get.mender.io](https://get.mender.io),
```

2024-01-19 14:24 UTC, TheYoctoJester commented on 10.Downloads/docs.md
> +To prevent the Mender clients from upgrading when upgrading the rest of the
```suggestion
To prevent the Mender Client from upgrading when upgrading the rest of the
```

2024-01-19 14:24 UTC, TheYoctoJester commented on 10.Downloads/docs.md
> + To prevent the Mender clients from upgrading when upgrading the rest of the
```suggestion
 To prevent the Mender Client from upgrading when upgrading the rest of the
```

2024-01-19 14:24 UTC, TheYoctoJester commented on 10.Downloads/docs.md
> +for [installing Mender clients using the APT
```suggestion
for [installing the Mender Client using the APT
```

2024-01-19 14:24 UTC, TheYoctoJester commented on 10.Downloads/docs.md
> +You need two applications for any add-on to function: the [Mender-auth Client](../02.Overview/15.Taxonomy/docs.md)
```suggestion
You need two applications for any add-on to function: [`mender-auth`](../02.Overview/15.Taxonomy/docs.md)
```

2024-01-19 14:24 UTC, TheYoctoJester commented on 10.Downloads/docs.md
> +The Remote Terminal does not require any items installed other than the Mender-auth Client
```suggestion
The Remote Terminal does not require any items installed other than `mender-auth`
```

2024-01-19 14:24 UTC, TheYoctoJester commented on 10.Downloads/docs.md
> +The File Transfer does not require any items installed other than the Mender-auth Client
```suggestion
The File Transfer does not require any items installed other than `mender-auth`
```

2024-01-19 14:24 UTC, TheYoctoJester commented on 10.Downloads/docs.md
> +Mender offers a configure extension (`mender-configure`) to the Mender-update client
```suggestion
Mender offers a configure extension (`mender-configure`) to the `mender-update` client
```

2024-01-19 14:24 UTC, TheYoctoJester commented on 10.Downloads/docs.md
> +instructions for [installing Mender clients using the APT
```suggestion
instructions for [installing the Mender Client using the APT
```

2024-01-19 14:24 UTC, TheYoctoJester commented on 301.Troubleshoot/01.Yocto-project-build/docs.md
> +Mender clients 4.0.0 and later have been split up into several separate components: `mender-auth` and `mender-update`, plus `mender-snapshot` which is now a separate recipe. This also changes the bin
```suggestion
Mender Client version 4.0.0 and later have been split up into several separate components: `mender-auth` and `mender-update`, plus `mender-snapshot` which is now a separate recipe. This also changes the binary names, and just `mender` by itself is not valid anymore. Because of this it is not completely backwards compatible. On the stable Yocto branches 4.0 (kirkstone) and older, the latest major release is the 3.x series, and therefore 4.0 and later are not built by meta-mender unless requested.
```

2024-01-19 14:24 UTC, TheYoctoJester commented on 301.Troubleshoot/01.Yocto-project-build/docs.md
> +In Yocto branches higher than 4.0 (kirkstone), Mender client 4.0.0 and later will be built by default.
```suggestion
In Yocto branches higher than 4.0 (kirkstone), Mender Client 4.0.0 and later will be built by default.
```

2024-01-19 14:24 UTC, TheYoctoJester commented on 301.Troubleshoot/01.Yocto-project-build/docs.md
> +!!! Do not confuse the usage of "U-Boot as a first stage bootloader" with "U-Boot integration". "GRUB integration" still means that GRUB is used for all integration with the Mender client and the roo
```suggestion
!!! Do not confuse the usage of "U-Boot as a first stage bootloader" with "U-Boot integration". "GRUB integration" still means that GRUB is used for all integration with the Mender Client and the rootfs-image Update Module.
```

2024-01-19 14:24 UTC, TheYoctoJester commented on 301.Troubleshoot/03.Mender-Client/docs.md
> +The Mender client can not connect to the server, typically the first time it tries, and emits messages like the following to the `mender-authd` log or syslog at the device:
```suggestion
The Mender Client can not connect to the server, typically the first time it tries, and emits messages like the following to the `mender-authd` log or syslog at the device:
```

2024-01-19 14:24 UTC, TheYoctoJester commented on 301.Troubleshoot/03.Mender-Client/docs.md
> +!!! Note that in Mender clients older than 4.0.0, the systemd service is called `mender-client`.
```suggestion
!!! Note that in Mender Clients older than 4.0.0, the systemd service is called `mender-client`.
```

2024-01-19 14:24 UTC, TheYoctoJester commented on 301.Troubleshoot/03.Mender-Client/docs.md
> +The Mender client can not connect to the server, typically the first time it tries, and emits messages like the following to the `mender-authd` log or syslog at the device:
```suggestion
The Mender Client can not connect to the server, typically the first time it tries, and emits messages like the following to the `mender-authd` log or syslog at the device:
```

2024-01-22 12:49 UTC, kacf commented on 07.Server-installation/01.Overview/02.Certificates-and-keys/docs.md
> +| Mender-auth Client | Signs requests for JSON Web Tokens sent to the Device Authentication service. A Mender-auth Client will request a new token when it connects to the Mender Server for the first
The "An other" sentence reads weirdly to me. I kept it plural, but instead added mender-connect as another example, both to match plurality, but also to make it clearer that mender-update is just one of several possibilities.

2024-01-22 12:53 UTC, kacf commented on 10.Downloads/docs.md
> +for [installing Mender clients using the APT
No, this one is correct. Note that it's talking about *all* the mender clients, including mender-connect and mender-configure. Potentially we could have a different name for that bundle of applications, but that is a separate discussion (pre-existing).

2024-01-22 13:24 UTC, TheMeaningfulEngineer commented on 02.Overview/15.Taxonomy/docs.md
> +
Fair, if you want to find dedicated sections for the binaries (`mender-update` and `mender-auth`), I don't mind that. I think it's better to have less, but will accept whatever approach you decide.

However `_Mender-update_` , `_Mender-update Client_`, `_Mender-auth_` and `_Mender-auth Client_` shouldn't be referenced anywhere. To me those look like a mix of a binary name and a use case name and mean neither.
If you want to keep those I'd like to discuss the value.

2024-01-22 13:39 UTC, kacf commented on 03.Client-installation/02.Install-with-Debian-package/01.Upgrading/docs.md
> +title: Upgrading
> My gut feeling is that we should mention and put a link to the new yocto changes here as well. The recipe name is changing as well, so that looks like it might break things.

On Yocto I think it won't generally break, because the existing Yocto releases are pinned to the Golang client. But I can add a small note about it regardless.

> Why change the yocto recipe name in the first place?

It was an intentional break to indicate that the recipe does not build "mender-client" anymore, it builds mender-auth and mender-update, and mender-client is no longer a valid name from 4.0.0 onwards.

2024-01-22 13:46 UTC, TheMeaningfulEngineer commented on 03.Client-installation/02.Install-with-Debian-package/01.Upgrading/docs.md
> +title: Upgrading
> But I can add a small note about it regardless.

Thanks!
I'm thinking about this page a goto for peeps when they are ready to go to version 4.
So regardless of what path they took (yocto/debian/cli) this prepares them a bit with "hey don't be scared, this is what changed, now that you get that, lets go to the section relevant to your implementation (yocto/debian)".

> It was an intentional break to indicate that the recipe does not build "mender-client" anymore, it builds mender-auth and mender-update, and mender-client is no longer a valid name from 4.0.0 onwards.

Fair, no probs with that as long as the content gets linked I'm good.

2024-01-22 14:21 UTC, kacf commented on 03.Client-installation/02.Install-with-Debian-package/01.Upgrading/docs.md
> +This page describes how to upgrade one Mender client version to a different Mender client version.
There is a link, just a few lines below this.

2024-01-22 14:24 UTC, kacf commented on 02.Overview/15.Taxonomy/docs.md
> +
Yep, I agree that less-is-more in general. But this is more of an index, so this is the one place I'd make an exception.

The mixed case names have been fixed and are code styled now.

2024-01-22 14:29 UTC, kacf commented
@TheMeaningfulEngineer, @TheYoctoJester: Updated! Everything is in new commits.

As mentioned I started changing casing, but abandoned it, which is why there are some, but not many, of these.

Note that the migration guide to 4.0.0 for Debian currently says "not supported", but I will add that to https://northerntech.atlassian.net/browse/MEN-6966 to add later.

2024-01-22 15:21 UTC, TheMeaningfulEngineer commented on 03.Client-installation/02.Install-with-Debian-package/01.Upgrading/docs.md
> +#### Overview
I'd expand this section with a few more things.
I'm linking it to the 3.7 docs because the links might die out in hosted when the configs are removed.

> The following features and config will not be available in the 4.0.0 client:
> * The  [update control maps as is in the 3.7 version of the docs](https://docs.mender.io/3.7/overview/customize-the-update-process#synchronized-updates)
> * The [connectivity](https://docs.mender.io/3.7/client-installation/configuration-file/configuration-options#connectivity) options in the client setting
>
> The Mender client components in 4.0.0 are rewritten in C++ (`mender-auth` and `mender-update`) while the Add-ons and supported update modules don't change the programming language in this version bump.
> At the time of this writing it is not known how this affects the memory footrping and the file size of the Mender client
>
> In Mender client 4 the rootfs update is no longer embedded in the client codebase but is treated as any other external update module. A binary CLI tool `mender-flash` now gets installed as part of the Mender client to serve the needs of the external rootfs update module.


In my mind these are all the changes that you might encounter when doing the migration.
I guess you might argue that these are not breaking changes and are just something that should live in a changelog...

I'd probably agree, in this case I'm willing to pay the price of some redundancy to the change log content for the gain of a friendlier to read changes introduced for a major bump version.
All with the goal to make the major bump less scary by having everything at one place and simple to read instead of having to discover it in different sections. 

What do you think?

2024-01-23 08:24 UTC, kacf commented on 03.Client-installation/02.Install-with-Debian-package/01.Upgrading/docs.md
> +#### Overview
Updated! I adjusted it slightly:

* Refer to 3.6, not 3.7, since Client is part of the 3.7 bundle, so the mentioned sections might disappear from there. Doesn't really make much difference otherwise, since these docs have not changed recently.
* Use the terms we use in the docs, "Syncronized updates" and "Update Management API".
* I removed the reference to language. IMHO, this is irrelevant, it's not something a user needs to know about unless they're going to contribute. Less is more!
* I also removed the size sentence. Why mention something we don't know?

2024-01-23 08:32 UTC, kacf commented
> @kacf Does the debian package name stay the same `mender-client` or it changes as well?
> 
> (was just reviewing [Luises PR](https://github.com/mendersoftware/mender-docs/pull/2310) and saw another reference to `mender-client` in the form of the apt package name, so wanted to see if this is relevant for this PR as well)

It changes to `mender-auth` and `mender-update`. Technically there might be a `mender-client` package too, but this is a meta package, only intended for automatic upgrades, so I don't think we should document it. IOW we don't want people to use it, unless it's because the system is automatically upgrading.

Do you think there are any additional changes needed then, or is this approaching "approvability"? 🙂

2024-01-23 08:36 UTC, TheMeaningfulEngineer commented
> Do you think there are any additional changes needed then, or is this approaching "approvability"?

I think we'll have to expand the upgrade section with this as well, but given that it says that debian isn't supported yet green light from me.

2024-01-23 08:37 UTC, kacf commented
> I think we'll have to expand the upgrade section with this as well, but given that it says that debian isn't supported yet green light from me.

Yes, I've added this as an item to [MEN-6966](https://northerntech.atlassian.net/browse/MEN-6966), so it won't be forgotten.

2024-01-23 08:38 UTC, merged