chore: Replace mtls-ambassador with mender-gateway and refresh the docs
mendersoftware/mender-docs pull request #2360
Opened 2024-04-12 13:41 UTC by alfrunes

* Replaced references to mtls-ambassador with mender-gateway
* Replaced environment configuration variablese in eval/prod installation guides.
* Updated and simplified the mtls diagram

2024-04-12 13:54 UTC, TheMeaningfulEngineer commented
Thanks!
I have a pairing session with @oldgiova  Monday at 1500 on exactly this.
Will render there docs and use them for the test.

2024-04-12 14:00 UTC, oldgiova reviewed
In my tests, the environment variables are working with the prefix `MENDER_GATEWAY_`, am I right?
Apart from that lgtm

2024-04-12 14:31 UTC, alfrunes commented on 08.Server-integration/03.Mutual-TLS-authentication/03.Production-installation-with-kubernetes/docs.md
> +          value: "${UPSTREAM_SERVER_URL}" \
No, try using this PR instead: https://github.com/mendersoftware/mender-gateway/pull/152.
The environment variables were inconsistent with the names in the config file and some of them are really long so I dropped the `MENDER_GATEWAY_` prefix.

2024-04-12 14:31 UTC, alfrunes commented on 08.Server-integration/03.Mutual-TLS-authentication/03.Production-installation-with-kubernetes/docs.md
> +        - name: HTTPS_ENABLED
https://github.com/mendersoftware/mender-docs/pull/2360#discussion_r1562636461

2024-04-12 14:32 UTC, alfrunes commented on 08.Server-integration/03.Mutual-TLS-authentication/03.Production-installation-with-kubernetes/docs.md
> +kubectl create secret generic mtls-user --from-literal=MTLS_MENDER_USERNAME=${MENDER_USERNAME} --from-literal=MTLS_MENDER_PASSWORD=${MENDER_PASSWORD}
https://github.com/mendersoftware/mender-docs/pull/2360#discussion_r1562636461

2024-04-12 14:32 UTC, alfrunes commented on 08.Server-integration/03.Mutual-TLS-authentication/02.Evaluation-with-docker-compose/docs.md
> +  -e UPSTREAM_SERVER_URL="$UPSTREAM_SERVER_URL" \
https://github.com/mendersoftware/mender-docs/pull/2360#discussion_r1562636461

2024-04-12 14:38 UTC, oldgiova commented on 08.Server-integration/03.Mutual-TLS-authentication/03.Production-installation-with-kubernetes/docs.md
> +          value: "${UPSTREAM_SERVER_URL}" \
That's a great news! Will test on Monday, thanks

2024-04-15 11:27 UTC, alfrunes commented on 08.Server-integration/04.Mender-Gateway/10.Mutual-TLS-authentication/99.MTLS-ambassador-migration/docs.md
The migration guide and the "Production Installation with Kubernetes" is subject to change. This migration does not make any rigid assumptions on the mender-gateway version, but the production installation guide requires at least `1.3.0` (next minor release) to include the environment variable config.
We could instead provide a ConfigMap resource instead of using environment variable to configure the gateway which would make it more portable. Then the migration would simply be a matter of providing a mapping between the (undocumented) mtls configurations and the Mender Gateway configs like I've done here.

2024-04-29 11:00 UTC, alfrunes commented
Can I please get a review here? This PR has been stale for 2 weeks.

2024-05-02 11:56 UTC, lluiscampos approved these changes
Overall great work. Nice cleanups along the way. Some minor comments but I think this should be good to go.

I have not looked in detail on the instructions to actually bring the software up, but I trust you and CI on that.

2024-05-02 11:56 UTC, lluiscampos commented on 08.Server-integration/04.Mender-Gateway/10.Mutual-TLS-authentication/01.Keys-and-certificates/docs.md
> +<!--AUTOVERSION: "mender-gateway:%"/integration-->
Here we want to follow the `mender-gateway` repo version, not the "bundle" represented by the integration repo version. In other words:
```suggestion
<!--AUTOVERSION: "mender-gateway:%"/mender-gateway-->
```

2024-05-02 11:56 UTC, lluiscampos commented on 08.Server-integration/04.Mender-Gateway/10.Mutual-TLS-authentication/01.Keys-and-certificates/docs.md
> +export TENANT_TOKEN="U3VwZXIgTWVuZGVyIG1hbidzIHNlY3JldCB0b2tlbiE"
I would keep the `...` to signal that this is clearly an example token and not to be taken as-is

2024-05-02 11:56 UTC, lluiscampos commented on 08.Server-integration/04.Mender-Gateway/10.Mutual-TLS-authentication/01.Keys-and-certificates/docs.md
> +To set up Mender Gateway in  mtls mode for evaluation, you need the following keys and certificates:
```suggestion
To set up Mender Gateway in Mutual TLS mode for evaluation, you need the following keys and certificates:
```
or
```suggestion
To set up Mender Gateway in mTLS mode for evaluation, you need the following keys and certificates:
```

2024-05-02 11:56 UTC, lluiscampos commented on 08.Server-integration/04.Mender-Gateway/99.Configuration-file/docs.md
> +This feature requires Mender Gateway version <code>1.1.0</code>
Nice addition :+1:

2024-05-02 11:56 UTC, lluiscampos commented on 08.Server-integration/04.Mender-Gateway/99.Configuration-file/docs.md
> +<dt>DefaultInventory</dt>
Pre-existing, but shouldn't this be part of the next sub-section?

2024-05-02 11:56 UTC, lluiscampos commented on 08.Server-integration/04.Mender-Gateway/99.Configuration-file/docs.md
> +Devices connected to the gateway will show a special attribute named `mender_gateway_system_id` in the reported inventory data.
Pre-existing,

For some unknown reason backticks "`" do not render correctly here

2024-05-02 11:56 UTC, lluiscampos commented on 08.Server-integration/04.Mender-Gateway/10.Mutual-TLS-authentication/01.Keys-and-certificates/docs.md
> +export MENDER_GATEWAY_IMAGE=${DOCKER_REGISTRY_URL}/mendersoftware/mender-gateway:1.3.0
We should set this to `master` in the master branch. Then we can set the tag once it is released.

2024-05-02 12:08 UTC, alfrunes commented on 08.Server-integration/04.Mender-Gateway/10.Mutual-TLS-authentication/01.Keys-and-certificates/docs.md
> +export TENANT_TOKEN="U3VwZXIgTWVuZGVyIG1hbidzIHNlY3JldCB0b2tlbiE"
This is a tenant token following the new format (+ there's an easter egg hidden there somewhere :upside_down_face::egg:)

2024-05-02 12:10 UTC, alfrunes commented on 08.Server-integration/04.Mender-Gateway/99.Configuration-file/docs.md
> +Devices connected to the gateway will show a special attribute named `mender_gateway_system_id` in the reported inventory data.
Right! HTML and markdown don't mix together in Grav.

2024-05-02 12:13 UTC, alfrunes commented on 08.Server-integration/04.Mender-Gateway/10.Mutual-TLS-authentication/01.Keys-and-certificates/docs.md
> +export TENANT_TOKEN="U3VwZXIgTWVuZGVyIG1hbidzIHNlY3JldCB0b2tlbiE"
That is, tenant tokens are no longer issued as JWT tokens, but a random string of 43 chars in the base64 char set.

2024-05-02 14:00 UTC, lluiscampos commented on 08.Server-integration/04.Mender-Gateway/10.Mutual-TLS-authentication/01.Keys-and-certificates/docs.md
> +export TENANT_TOKEN="U3VwZXIgTWVuZGVyIG1hbidzIHNlY3JldCB0b2tlbiE"
Ok

2024-05-06 17:16 UTC, TheMeaningfulEngineer requested changes
I tried this today. Evaluation with docker compose.
Ended up in the following state.
mender-authd logs:
```
May 06 17:11:16 qemux86-64 mender-auth[18074]: using interface /sys/class/net/enp0s3
May 06 17:11:16 qemux86-64 mender-auth[17857]: record_id=15 severity=info time="2024-May-06 17:11:16.982158" name="Global" msg="Signing with: /var/lib/mender/mender-agent.pem"
May 06 17:11:17 qemux86-64 mender-auth[17857]: record_id=16 severity=error time="2024-May-06 17:11:17.076235" name="http_client" url="https://local-domain-1993028.com/api/devices/v1/authentication/auth_requests" msg="https: Failed to perform the SSL handshake: certificate verify failed (SSL routines)"
May 06 17:11:17 qemux86-64 mender-auth[17857]: record_id=17 severity=info time="2024-May-06 17:11:17.091748" name="Global" msg="Authentication error trying server 'https://local-domain-1993028.com': certificate verify failed (SSL routines): POST https://local-domain-1993028.com/api/devices/v1/authentication/auth_requests: "
```

gateway logs (master from today)
```
docker run \
  -p 8443:8443 \
  --name mender-gateway \
  -e HTTPS_ENABLED="true" \
  -e HTTPS_LISTEN=":8443" \
  -e HTTPS_SERVER_CERTIFICATE="/etc/mender/certs/server/server.crt" \
  -e HTTPS_SERVER_KEY="/etc/mender/certs/server/server.key" \
  -e MTLS_CA_CERTIFICATE="/etc/mender/certs/tenant-ca/tenant.ca.pem" \
  -e MTLS_ENABLED="true" \
  -e MTLS_MENDER_PASSWORD="$MENDER_PASSWORD" \
  -e MTLS_MENDER_USERNAME="$MENDER_USERNAME" \
  -e UPSTREAM_SERVER_URL="$UPSTREAM_SERVER_URL" \
  -v $(pwd)/server.crt:/etc/mender/certs/server/server.crt \
  -v $(pwd)/server.key:/etc/mender/certs/server/server.key \
  -v $(pwd)/ca.crt:/etc/mender/certs/tenant-ca/tenant.ca.pem \
  $MENDER_GATEWAY_IMAGE --log-level debug
time="2024-05-06T16:46:34Z" level=info msg="starting mender-gateway" file=main.go func=main.doMain line=98
time="2024-05-06T16:46:34Z" level=debug msg="creating proxy with url https://hosted.mender.io, insecure skip verify: false" file=proxy.go func=proxy.NewProxy line=64
time="2024-05-06T16:46:34Z" level=info msg="proxy scheme: https, host: hosted.mender.io" file=proxy.go func=proxy.NewProxy line=74
time="2024-05-06T16:46:34Z" level=info msg="created client with base url https://hosted.mender.io, insecure skip verify: false" file=client.go func=mender.NewClient line=49
time="2024-05-06T16:46:34Z" level=info msg="logging in with user mtls.dude@email.com" file=auth_provider.go func=app.NewAuthProvider line=26
time="2024-05-06T16:46:35Z" level=fatal msg=unauthorized file=main.go func=main.cmdServer line=125
time="2024-05-06T16:46:35Z" level=info msg="creating cert pool with tenant CA cert: /etc/mender/certs/tenant-ca/tenant.ca.pem" file=server.go func=server.certPool line=99
time="2024-05-06T16:46:35Z" level=info msg="creating cert pool: ok" file=server.go func=server.certPool line=111
time="2024-05-06T16:46:35Z" level=info msg="Starting server..." file=server.go func="server.(*Server).Run" line=85
2024/05/06 16:47:37 http: TLS handshake error from 192.168.88.111:59376: tls: client didn't provide a certificate

## This last command was from the test, not from the client
```

It looks like the client isn't trusting the server certificate.
There are a list of steps on the client side that installs the cert and those used to work on in the old docs.
I'd like someone to try the steps as well, this is cheap to do, to confirm this is reproducible (I tried it twice and got the same results).

2024-05-08 13:54 UTC, alfrunes commented
@TheMeaningfulEngineer I found the issues:
 1. The port was missing in the client config, so I exposed it as an env variable in the prerequisite chapter.
 2. The root certificate was setup with incorrect parameters so the mender-gateway refused to use it for certificate validation.
Was this certificate setup working for the mtls-ambassador? I tried to compare the way the certificates are loaded between the two services and they seem to be identical.

2024-05-08 14:01 UTC, TheMeaningfulEngineer commented
@alfrunes 
Thanks I'll give it for anther go.
It did work for the mtls it was originally.
I've used it for a reference to set up a `device - mtls - HM` whenever I needed to reproduce customers issues that had mtls in the setup.

2024-05-14 10:57 UTC, estape11 approved these changes
I tested and it works perfectly.

<img width="1319" alt="Screenshot 2024-05-14 at 12 56 28 PM" src="https://github.com/mendersoftware/mender-docs/assets/5886355/50d1042c-2c0c-4305-af63-6de26f7a3741">
<img width="1249" alt="Screenshot 2024-05-14 at 12 56 49 PM" src="https://github.com/mendersoftware/mender-docs/assets/5886355/d28c8cea-7a9c-4bb1-bc31-c3ed4fbd9329">

2024-05-14 12:36 UTC, TheMeaningfulEngineer approved these changes
I haven't tested it but @estape11 went through the steps and gave a green light so that works for me.

2024-05-14 12:38 UTC, merged