docs(RBAC): Update images and update release management to include scope
mendersoftware/mender-docs pull request #2416
Opened 2024-07-05 12:47 UTC by alfrunes

2024-07-11 16:39 UTC, kjaskiewiczz approved these changes
looks good; maybe @estenberg want to take a look too?

2024-07-15 12:50 UTC, tranchitella approved these changes

2024-07-16 13:44 UTC, estenberg requested changes
Not changed here, but would suggest clarifying the Connect permission.

Otherwise it's nice.

2024-07-16 13:44 UTC, estenberg commented on 02.Overview/12.Role.Based.Access.Control/docs.md
> +  * **Connect**: troubleshooting access to the devices, requires **Read**.
"troubleshooting devices (using [mender-connect](/add-ons/overview)), requires **Read**"

2024-07-18 08:57 UTC, merged