Docker compose revamp
mendersoftware/mender-docs pull request #2439
Opened 2024-08-20 17:09 UTC by TheMeaningfulEngineer

CE-429

Currently blocked by: https://northerntech.atlassian.net/browse/MEN-7477
After that the links need to be updated `master` -> `1.0.1`

2024-08-20 17:52 UTC, estenberg requested changes
Thanks for updating this, it's overdue. :)

Have you seen that we already have a tutorial here: https://docs.mender.io/artifact-creation/create-an-artifact/docker-compose?

I think that one is mis-placed, and we should remove it after you add yours to Get started. 

There is also another one on Kubernetes I think we should remove: https://docs.mender.io/artifact-creation/create-an-artifact/kubernetes. Perhaps you can just add a note that it's possible to use Kubernetes too at the end of your tutorial instead?

2024-08-20 17:52 UTC, estenberg commented on 01.Get-started/04.Deploy-a-docker-compose-update/docs.md
> +In the example, we'll observe Traefik as the primary container in the composition.
we will instead of we'll (I think we spell those out)

2024-08-20 17:52 UTC, estenberg commented on 01.Get-started/04.Deploy-a-docker-compose-update/docs.md
> +Throughout the tutorial you'll be expected to execute commands on the device.
you will

2024-08-20 17:52 UTC, estenberg commented on 01.Get-started/04.Deploy-a-docker-compose-update/docs.md
> +Throughout the tutorial you'll be expected to execute commands on the device.
you will be expected is a bit long-weinded

maybe something like "you will execute"

2024-08-20 17:52 UTC, estenberg commented on 01.Get-started/04.Deploy-a-docker-compose-update/docs.md
> +Before installing the Update Module on the device, you need to ensure that the following
remove "you need to"

2024-08-20 17:52 UTC, estenberg commented on 01.Get-started/04.Deploy-a-docker-compose-update/docs.md
> +To generate the update artifacts we'll need to install the `Application Update Artifact Generator`.
To generate Mender Artifacts supporting docker-compose, we install the ...

2024-08-20 17:52 UTC, estenberg commented on 01.Get-started/04.Deploy-a-docker-compose-update/docs.md
> +
Make it even more explicit that we are changing place here, e.g.:

Now open a terminal on your **workstation**, which will be used to package the software for your device.

2024-08-20 17:52 UTC, estenberg commented on 01.Get-started/04.Deploy-a-docker-compose-update/docs.md
> +##### Workstation variables
Change this to a note, not a separate header, as it doesn't have any actionable steps. E.g. with !!!

2024-08-20 17:52 UTC, estenberg commented on 01.Get-started/04.Deploy-a-docker-compose-update/docs.md
> +#### Create the Mender artifact
Artifact

2024-08-20 17:52 UTC, estenberg commented on 01.Get-started/04.Deploy-a-docker-compose-update/docs.md
> +Run the command below to generate the update artifact:
update artifact -> Artifact

2024-08-20 17:52 UTC, estenberg commented on 01.Get-started/04.Deploy-a-docker-compose-update/docs.md
> +The generated artifact (`.mender` extension) is now ready to be deployed on the device.
Artifact

2024-08-20 17:52 UTC, estenberg commented on 01.Get-started/04.Deploy-a-docker-compose-update/docs.md
> +Open the Remote terminal from the Hosted Mender UI and run the following:
Where is Remote terminal? I would have one sentence where to find it, e.g. In hosted Mender, under UI, open the Devices tab and click on your device. Then click "Remote terminal" and run the following commands:

2024-08-20 17:52 UTC, estenberg commented on 01.Get-started/04.Deploy-a-docker-compose-update/docs.md
> +Open the Remote terminal from the Hosted Mender UI and run the following:
Just as we're assuming that the reader is completely new to Mender if they're following Get started.

2024-08-20 17:52 UTC, estenberg commented on 01.Get-started/04.Deploy-a-docker-compose-update/docs.md
> +Command below will test for functionality:
Run the following command to verify it works:

2024-08-20 17:52 UTC, estenberg commented on 01.Get-started/04.Deploy-a-docker-compose-update/docs.md
> +bump gateway service to `traefik:v2.10`:
bump -> update the

2024-08-20 17:52 UTC, estenberg commented on 01.Get-started/04.Deploy-a-docker-compose-update/docs.md
> +Proceed with creating the artifact:
Artifact

2024-08-20 17:52 UTC, estenberg commented on 01.Get-started/04.Deploy-a-docker-compose-update/docs.md
> +So in this case we're seeing a ~28% decrease in size.
size, though the size savings of deltas vary depending on the changes between Artifact as well as parameters used and can go up to 90% in some cases.

2024-08-20 17:52 UTC, estenberg commented on 01.Get-started/04.Deploy-a-docker-compose-update/docs.md
> +The motivation for using the delta updates is to have a smaller artifact for the same effect.
Artifact

2024-08-20 17:52 UTC, estenberg commented on 01.Get-started/04.Deploy-a-docker-compose-update/docs.md
> +### Extra: what are the delta benefits?
Benefits of Delta Updates

2024-08-20 17:52 UTC, estenberg commented on 01.Get-started/04.Deploy-a-docker-compose-update/docs.md
> +!!! For Raspberry pi 3 use  `DEVICE_TYPE="raspberrypi3"`
It's possible to supply --device-type twice to avoid this issue, it seems: https://github.com/mendersoftware/app-update-module/blob/master/gen/app-gen#L33. Mender Artifacts support a list of device types compatible.

So if --device-type raspberrypi3 --device-type raspberrypi4 is supplied this should work in both cases.

In this tutorial we can remove the DEVICE_TYPE and PLATFORM variables and have them inline in the command because we are explicitly targetting Raspberry Pi only here (otherwise supplying device-type multiple times may become difficult?).

2024-08-20 17:55 UTC, estenberg commented
Sorry to expand the scope here so much, but we should also consider the Mender Hub Update Module section:
* https://hub.mender.io/c/update-modules/13?ascending=false&order=views

In particular there is a "competing" Kubernetes implementation that we made: https://hub.mender.io/t/kubernetes/1939

The problem is that it will confuse customers if we provide multiple Update Modules for the same update type.

2024-08-20 18:13 UTC, estenberg commented
@kjaskiewiczz FYI, ref the QA discussion.

My opinion is that we need to move the app-update module to https://github.com/mendersoftware/mender-update-modules, add a Mender Hub Update Module tutorial (maybe one for Docker-Compose and another for Kubernetes).

I don't understand why the app-update module was done separate? Was this a more "strategic" decision to split out the update modules we support or was it just done oneoff?

2024-08-21 08:25 UTC, kjaskiewiczz commented
Thanks for the info.

> I don't understand why the app-update module was done separate? Was this a more "strategic" decision to split out the update modules we support or was it just done oneoff?

I don't know, but maybe @merlin-northern knows something about it?

2024-08-21 09:50 UTC, merlin-northern commented
> Thanks for the info.
> 
> > I don't understand why the app-update module was done separate? Was this a more "strategic" decision to split out the update modules we support or was it just done oneoff?
> 
> I don't know, but maybe @merlin-northern knows something about it?

who me? let's face it my knowledge is a bit on a low level.
so it was a decision that was made, to keep it separate:
1. app-update-module is really an answer to the Mender for Applications, implemented as an update module, true, but we had in mind the release and it had been decided to release from a separate repo
2. it goes a bit beyond the update modules as it introduces so-called submodules
3. the mender-update-modules has or had slightly different idea

I can dig further. if you want to move it to the other repo we can discuss.

2024-08-21 13:31 UTC, TheMeaningfulEngineer commented
@estenberg 

Thanks for the review, will go through it.

> Have you seen that we already have a tutorial here: https://docs.mender.io/artifact-creation/create-an-artifact/docker-compose?
> I think that one is mis-placed, and we should remove it after you add yours to Get started.


I've used that one as the base and describe the high level changes in the commit messages.
The current PR changes are doing the move.

2024-08-21 13:43 UTC, TheMeaningfulEngineer commented on 01.Get-started/04.Deploy-a-docker-compose-update/docs.md
> +The motivation for using the delta updates is to have a smaller artifact for the same effect.
Adjusted the case for all occurrences of lower case.

2024-08-21 13:44 UTC, TheMeaningfulEngineer commented on 01.Get-started/04.Deploy-a-docker-compose-update/docs.md
> +##### Workstation variables
This was an approach I dropped and didn't delete it.
I removed it completly.

2024-08-21 13:47 UTC, TheMeaningfulEngineer commented on 01.Get-started/04.Deploy-a-docker-compose-update/docs.md
> +!!! For Raspberry pi 3 use  `DEVICE_TYPE="raspberrypi3"`
Good call.
If QEMU ever becomes Debian based we can revisit.
Will change and retest.

2024-08-21 13:50 UTC, TheMeaningfulEngineer commented on 01.Get-started/04.Deploy-a-docker-compose-update/docs.md
> +So in this case we're seeing a ~28% decrease in size.
Will expand the text but want do go with:

```
So in this case we are seeing a ~28% decrease in size, though the size savings of deltas vary depending on the changes between Artifacts and can go up to 90% in some cases.
```

Not clear what parameters are you referring to.
If it's the [delta parameters](https://docs.mender.io/artifact-creation/create-a-delta-update-artifact#generating-the-delta-custom-compression-values-special-use-case) I don't know a way to customize these for this update type.

2024-08-21 14:43 UTC, TheMeaningfulEngineer commented on 01.Get-started/04.Deploy-a-docker-compose-update/docs.md
> +Open the Remote terminal from the Hosted Mender UI and run the following:
I've added that to the beginning of the document with the link to the Remote terminal section where all the parameters are.
I've expanded the link to every mention of the remote terminal.
Would prefer this approach than to start superficially explaining the Remote terminal here. Fair? :)

2024-08-30 20:59 UTC, estenberg approved these changes

2024-09-19 07:52 UTC, oldgiova commented
The app-update-module `1.1.0` has been released. The links has been updated already

2025-04-15 12:12 UTC, closed without merging