MEN-7508: Add a troubleshoot entry for the `fsck` error
mendersoftware/mender-docs pull request #2460
Opened 2024-09-18 11:15 UTC by lluiscampos

2024-09-19 08:33 UTC, estenberg approved these changes
Nice and clear!

2024-09-19 12:30 UTC, TheMeaningfulEngineer commented on 301.Troubleshoot/03.Mender-Client/docs.md
> +
I cant make a suggestion with code blocks.
Here is it in raw form:

---

You can workaround the issue by executing a few extra steps:

On the shell **of the device** execute:

```
mkfifo /data/mender/dump
mender-snapshot dump > /data/mender/dump
```

Open another shell, **on the host**, where you have the variables form the getting started and run:

```
ssh -p 8822 root@${IP_ADDRESS} cat /data/mender/dump > rootfs.ext4
mender-artifact write rootfs-image \
    -f ssh://"${USER}@${IP_ADDRESS}" \
    -t "${DEVICE_TYPE}" \
    -n system-v1 \
    -o system-v1.mender \
    -f rootfs.ext4
```

You can upload the `system-v1.mender` and continue with the evaluation.

2024-09-19 12:31 UTC, TheMeaningfulEngineer requested changes
Made the suggestions for a workaround

2024-09-20 08:47 UTC, TheMeaningfulEngineer approved these changes

2024-09-20 08:51 UTC, merged

2024-09-20 08:56 UTC, TheMeaningfulEngineer commented
Forgot to add.
I rendered this and executed the steps from the rendered docs.
The system-v1.mender was created correctly and I did an update with it.

2024-09-20 08:58 UTC, lluiscampos commented
> Forgot to add. I rendered this and executed the steps from the rendered docs. The system-v1.mender was created correctly and I did an update with it.

Thank you very much! I was waiting for the dev branch to be updated before asking for merges. But once a human has checked it, I can do:

@mender-test-bot cherry-pick to:
* hosted
* 3.7.x