feat: add documentation for Multi Tenancy and Service Provider Tenants
mendersoftware/mender-docs pull request #2480
Opened 2024-10-24 07:44 UTC by tranchitella

Changelog: None
Ticket: MEN-7407

2024-10-24 08:25 UTC, TheMeaningfulEngineer requested changes
This looks like a focused "Multi Tenancy and Service Provider Tenants" overview page but doesn't document how to use the feature as that seems to be blocked by the UI.

I'd rather see this presented in that manner being explicit that the other part is still to follow, would gladly approve it in that case.


I've commented it from that perspective.
The Introduction and Use cases is an amazing section for the overview, full support on that.

The other parts seemed an overly verbose way to say "a child tenant behaves like a regular tenant in isolation". 
Won't have a hard opinion on this one as it depends who the reader is and I took a perspective of a customer who is already using Hosted Mender in a single tenant setup.

2024-10-24 08:25 UTC, TheMeaningfulEngineer commented on 02.Overview/13.Multi-Tenancy/docs.md
> +customer.
The document is already text only which make it kind of boring and dry.
There is a brief Introduction and then a great "Use case" section below on the why.
I'd remove this completely.

2024-10-24 08:25 UTC, TheMeaningfulEngineer commented on 02.Overview/13.Multi-Tenancy/docs.md
> +## How to Use Multi Tenancy in Mender Enterprise
This isn't really an explanation on how to use the feature.
It's more of a list of features.

I say this because I ask myself "Do I know how to hands on use multi tenancy after reading this" the answer is no.

2024-10-24 08:25 UTC, TheMeaningfulEngineer commented on 02.Overview/13.Multi-Tenancy/docs.md
> +  audit logs without visibility into other tenants' environments.
Mentioning Logging is misleading.
Perhaps we provide individual logging per tenant, logging itself isn't an end user mender feature.

2024-10-24 08:25 UTC, TheMeaningfulEngineer commented on 02.Overview/13.Multi-Tenancy/docs.md
> +Server, please [contact us](https://mender.io/contact-us).
It doesn't seem this feature exists yet the backend might, but the e2e feature is missing.
I'd be more honest here and say "This feature is currently under development. If you want to know more please [contact us](https://mender.io/contact-us).

2024-10-24 10:07 UTC, kjaskiewiczz commented on 02.Overview/13.Multi-Tenancy/docs.md
> +Server, please [contact us](https://mender.io/contact-us).
> It doesn't seem this feature exists yet the backend might, but the e2e feature is missing. I'd be more honest here and say "This feature is currently under development. If you want to know more please [contact us](https://mender.io/contact-us).

@TheMeaningfulEngineer We will publish the docs together with the feature, so I don't really understand why we should say it's under development.

2024-10-24 10:16 UTC, TheMeaningfulEngineer commented on 02.Overview/13.Multi-Tenancy/docs.md
> +Server, please [contact us](https://mender.io/contact-us).
> We will publish the docs together with the feature, so I don't really understand why we should say it's under development.

Where's the UI and what steps does a person who just registered for a free trial follow to actually use it?
Without that, it sounds like there does need to be another iteration of the docs once the feature is ready to use because there is a big chunk missing which is the UI.

2024-10-24 10:18 UTC, TheMeaningfulEngineer commented on 02.Overview/13.Multi-Tenancy/docs.md
> +Server, please [contact us](https://mender.io/contact-us).
I get the point where it doesn't make sense to put it as `under development` just to remove it with the next iteration or release it like that.
But in this state it doesn't look like it's ready, so merging it in this form (missing the UI and documenting the way to actually use it) and claiming its ready is what doesn't make sense to me.

2024-10-25 00:01 UTC, estenberg requested changes
Good direction, adding some more "meat" would make it great. I added some suggestions.

2024-10-25 00:01 UTC, estenberg commented on 02.Overview/13.Multi-Tenancy/docs.md
> +- User Management: Admins can assign different roles and permissions within
Also, add a sentance that SSO or no SSO can be used?

2024-10-25 00:01 UTC, estenberg commented on 02.Overview/13.Multi-Tenancy/docs.md
> +2. *Large Enterprises with Multiple Divisions*: Organizations that have several
Add that there is support for enforcing a single SSO configuration for all Tenants in this case. This is to ensure that no users outside the SSO (external users) can be added to any Mender Tenant.

2024-10-25 17:59 UTC, estenberg requested changes
Some minor adjustments only in wording. Overall looks good.

2024-10-25 17:59 UTC, estenberg commented on 02.Overview/13.Multi-Tenancy/docs.md
> +Unit and their product lines isolated
Missing .

2024-10-25 17:59 UTC, estenberg commented on 02.Overview/13.Multi-Tenancy/docs.md
> +environment by adding a user into their tenant, or they can let a customer
Tenant

2024-10-25 17:59 UTC, estenberg commented on 02.Overview/13.Multi-Tenancy/docs.md
> +2. *OEMs (Original Equipment Manufacturers)*: OEMs can manage device deployments
Should this be removed? It's duplicate of the next?

2024-10-25 17:59 UTC, estenberg commented on 02.Overview/13.Multi-Tenancy/docs.md
> +- User Management: Admins can create an initial admin for a children Tenant
child Tenant

2024-10-25 17:59 UTC, estenberg commented on 02.Overview/13.Multi-Tenancy/docs.md
> +  the children Tenant intself, ensuring proper access control. Each children
child Tenant itself

2024-10-25 17:59 UTC, estenberg commented on 02.Overview/13.Multi-Tenancy/docs.md
> +  the children Tenant intself, ensuring proper access control. Each children
Each child

2024-10-25 17:59 UTC, estenberg commented on 02.Overview/13.Multi-Tenancy/docs.md
> +  tenants; this way, users from the organization's Identity Provider can log
only users from the...

2024-10-29 17:22 UTC, TheMeaningfulEngineer approved these changes
Like the graph!

Would like to have a graph that also shows the creation of the Child, making it more explicit that the SP admin creates a token and the admin instead of just mentioning it in text.
But couldn't get that as a mermaid suggestion so optional.

2024-10-29 17:22 UTC, TheMeaningfulEngineer commented on 02.Overview/13.Multi-Tenancy/service-provider.md
> +flowchart TD
```
flowchart TD
    %% Main node with boxed global settings
    A(["**Service Provider**<br><div style='border: 1px solid #000; padding: 5px; margin-top: 5px;'>***Device limit: 100***</div><div style='border: 1px solid #000; padding: 5px; margin-top: 5px;'>***Global security policy***</div><br>👤 SP Admin"])

    %% Child nodes with boxed device limits and user sections
    A --> B(["**Child 1**<br><div style='border: 1px solid #000; padding: 5px; margin-top: 5px;'>***Device limit: 20***</div><div style='border: 1px solid #000; padding: 5px; margin-top: 5px; text-align: left;'>👤 Admin 1<br>👤 User A<br>👤 User B</div>"])
    A --> C(["**Child 2**<br><div style='border: 1px solid #000; padding: 5px; margin-top: 5px;'>***Device limit: 40***</div><div style='border: 1px solid #000; padding: 5px; margin-top: 5px; text-align: left;'>👤 Admin 2<br>👤 User A</div>"])
    A --> D(["**Child 3**<br><div style='border: 1px solid #000; padding: 5px; margin-top: 5px;'>***Device limit: 40***</div><div style='border: 1px solid #000; padding: 5px; margin-top: 5px; text-align: left;'>👤 Admin 3<br>👤 User B</div>"])
```

Played a bit here (https://www.mermaidchart.com/play), had something like this in mind.
Should be mermaid code.

![image](https://github.com/user-attachments/assets/a9c6887f-4d46-4518-bc37-e6c1549a92ea)

2024-10-29 17:22 UTC, TheMeaningfulEngineer commented on 02.Overview/13.Multi-Tenancy/service-provider.md
> +flowchart TD
Don't have a strong opinion on the naming of the SP Admin vs Admin.
Whatever @estenberg things works.

2024-10-30 01:25 UTC, estenberg requested changes
Just some final tweaks, feel free to merge after changing these few things, I don't have to review it again. It's good!

2024-10-30 01:25 UTC, estenberg commented on 02.Overview/13.Multi-Tenancy/docs.md
> +called Service Provider Tenant (or SP Tenant). SP Tenant can:
The SP Tenant can:

2024-10-30 01:25 UTC, estenberg commented on 02.Overview/13.Multi-Tenancy/docs.md
> +prefixed by the Tenant ID. However, it is possible to configure a Tenant specific
However, it is possible -> It is also possible

2024-10-30 01:25 UTC, estenberg commented on 02.Overview/13.Multi-Tenancy/docs.md
> +  Tenant ID and Token and set of users, which can be managed independently from
Tenant ID, Tenant Token and and initial administrative account.

2024-10-30 01:25 UTC, estenberg commented on 02.Overview/13.Multi-Tenancy/docs.md
> +- User Management: Admins can create an initial admin for a child Tenant
SP Tenant administrators

2024-10-30 01:25 UTC, estenberg commented on 02.Overview/13.Multi-Tenancy/docs.md
> +- Device limit: Set and change device limit of all children Tenants. Allocates
Would move this before Billing, as it's logically related to adding/managing individual tenants, same as user management.

2024-10-30 01:25 UTC, estenberg commented on 02.Overview/13.Multi-Tenancy/service-provider.md
> +flowchart TD
Nice and clean. I think it's good to name it SP Admin to distinguish.

2024-10-30 08:43 UTC, TheMeaningfulEngineer reviewed
Thanks for the second iteration.
I did a bunch of suggestions
They were driven by trying to figure out "What precisely can the SP admin do"?

For me that is the info about that was mixed together with the topic of "tenant isolation". 
My suggestion is to separate those things and for the "Service Provider Tenant" cover the capabilities from the perspective of the SP Admin.
 
 This is what I got on the capabilities of the SP Admin:
 * It can distribute its device limits to child tenants
 * It can set SSO config which child tenant admins can't override
 * It can create new child tenants that will have a single admin in them
 
Things that weren't clear:
* can the SP admin choose to enforce policy on individual tenants and let others be independent (SSO for some, full freedom for others)
* can the SP admin trigger password resets for the child admins?
* is the SP admin by definition a username/password account?
* can there be more SP admins?

2024-10-30 08:43 UTC, TheMeaningfulEngineer commented on 02.Overview/13.Multi-Tenancy/docs.md
> +  and audit logs without visibility into other Tenants' environments.
This mixes describing the SP tenant together with capabilities of the child tenants.

"The SP Tenant can: .... ... Billing and Resource usage"
"The SP Tenant can: .... ... Monitoring and Audit Logs"

Those two sections also aren't focusing on the SP tenant but are describing the isolation of the tenants.

Is the goal to explain what the SP tenant is doing or describe the tenant isolation, currently both are mixed together?

My impression is to go for the SP tenant for this section.
Optionally, everything related to tenant isolation can live under it's own section "Tenant isolation".

Let me see if I can put that as a suggestion instead of like this.

2024-10-30 08:43 UTC, TheMeaningfulEngineer commented on 02.Overview/13.Multi-Tenancy/docs.md
> +object store for the artifacts if needed.
```suggestion
## High-Level Overview

Mender's Multi Tenancy feature ensures that different tenants, all within a context of a single organisation, have completely separate environments, meaning that each tenant has their own set of users, devices, and device groups, and only the users associated with a tenant can access its data. 

At the same time the Service Provider Tenant acts as a central point of control for all the child tenants allowing for organisation wide definition of policies applicable to all child tenants (i.e. SSO and features available to child tenants). 
```

There was no SP tenant present here, to me it read as primarily focusing on tenant separation.
The suggestion expands on the full feature "tenants are isolated" + "you still have some global management".

Removed the technical part, will add that in the "Tenant isolation" section.

2024-10-30 08:43 UTC, TheMeaningfulEngineer commented on 02.Overview/13.Multi-Tenancy/docs.md
> +
```suggestion

## Tenant isolation
Mender achieves multi tenancy by logically partitioning the platform's resources so
that multiple tenants can use the same underlying infrastructure without interfering
with one another. This setup helps organizations reduce overhead and operational costs,
as they don't need to set up and maintain separate servers for each department or
customer.

Every microservice stores the information about all the Tenants in a single database,
and every record includes the Tenant ID. When retrieving information from the database,
the server filters the records by Tenant ID and returns the data belonging to the
specific Tenant the user or the device belongs to. Similarly, the Mender artifacts
are stored in a common storage account (Azure Blob Storage or AWS S3 bucket) and
prefixed by the Tenant ID. It is also possible to configure a Tenant specific
object store for the artifacts if needed.

Individual billing may be addressed on the Tenant level. 
Mender Server tracks resource usage (such as device  limits and consumption) per Tenant, 
enabling cost management across different clients or teams.

The Mender Server provides monitoring and audit logs capabilities at the Tenant level, 
allowing each Tenant to monitor its own devices and audit logs without visibility 
into other Tenants' environments.
```

New section on Tenant isolation.
Introducing this to separate the "tenants are isolated" message from the "how SP tenant works"

2024-10-30 08:43 UTC, TheMeaningfulEngineer commented on 02.Overview/13.Multi-Tenancy/docs.md
> +  and audit logs without visibility into other Tenants' environments.
```suggestion
```

Moved that to the "Tenant isolation" section

2024-10-30 08:43 UTC, TheMeaningfulEngineer commented on 02.Overview/13.Multi-Tenancy/docs.md
> +  in to the Mender Server accessing the correct Tenant based on their needs.
From what I understood what the SP tenant can do, this sounds a bit misleading.
This is the model I built for how this works:


The SP tenant can only ever create a single admin on the child tenant as part of the child tenant creation.
What options does an SP tenant admin have with regards to resetting passwords for the child tenant admins?


The SP admin can create set the SSO as an organisational policy, these settings are applied to all child tenants and can't be overridden.
Is this correct?

2024-10-31 11:41 UTC, TheMeaningfulEngineer approved these changes
Thanks!
Looks great

2024-11-05 16:35 UTC, estenberg approved these changes

2024-11-05 16:46 UTC, merged