feat: review of the supported cryptographic keys
mendersoftware/mender-docs pull request #2483
Opened 2024-10-29 12:19 UTC by tranchitella

Changelog: None
Ticket: MEN-7535

2024-10-30 01:49 UTC, estenberg requested changes
Small tweaks.

2024-10-30 01:49 UTC, estenberg commented on 02.Overview/11.Security/docs.md
> +Each Device has a unique public and private RSA, ECDSA with curve P-256 or ED25519
Strictly speaking, ED25519 is not ECDSA, and ECDSA is a signature algorithm (not a key type). So this was wrong to start off with.

Each Device has a unique RSA or Elliptic Curve (P-256 or Ed25519) keypair (public and private key). 

Strictly-strictly speaking it is a Curve25519 keypair, but I see it's often referred to as Ed25519 keypair, so we should be fine with that.

2024-10-30 01:49 UTC, estenberg commented on 02.Overview/11.Security/docs.md
Suggesting to add a note here:
(with right amount of exlamation marks for versioning / introuction compatibility note, don't quite recall :)

!! Mender Client version 4.1.0 and later generates an Ed25519 keypair by default, while prior versions generated a 3072 bit RSA key by default. These have the same security level (128 bit), but the Ed25519 keys are smaller and more efficient.

2024-10-30 01:49 UTC, estenberg commented on 06.Artifact-creation/07.Sign-and-verify/docs.md
> +* Ed25519, only when used in combination with KeyFactor
Don't think this relates to KeyFactor?

Or I am not aware of that.. why can't we sign Artifacts using Ed25519 without KeyFactor?

2024-10-30 08:51 UTC, vpodzime commented on 06.Artifact-creation/07.Sign-and-verify/docs.md
> +* Ed25519, only when used in combination with KeyFactor
Are you talking about Mender Artifact sources? I have no idea what `KeyFactor` is, but I see no mention of it in the Client 4 sources (or the MCU client's sources, FWIW)

2024-10-30 20:47 UTC, estenberg commented on 06.Artifact-creation/07.Sign-and-verify/docs.md
> +* Ed25519, only when used in combination with KeyFactor
Ah, okey.

Then for this task I would remove that line (* Ed25519, only when used in combination with KeyFactor) as this is a bit different (it doesn't use a Ed25519 key, but a partner REST API).

Rather, add KeyFactor here: https://docs.mender.io/artifact-creation/sign-and-verify#cloud-key-management

Sorry to scope-creep, but this section should be renamed from "Supported cryptography standards" to "Hardware security" https://docs.mender.io/artifact-creation/sign-and-verify#cloud-key-management ?

2024-10-31 07:52 UTC, lluiscampos commented on 06.Artifact-creation/07.Sign-and-verify/docs.md
> +* Ed25519, only when used in combination with KeyFactor
There actually might be something to this. As for the client,

We have unit tests with Ed25519 keys only for _signing_ things, which means signatures used for auth requests. I quickly wrote a unit test for _verifying_ a signature, and it fails in the OpenSSL initialization (iow when reading a Ed25519 public key).

Then we have acceptance tests for the verification of signed Artifacts, using RSA and ECDSA P-256 keys. This matches Fabio's findings, as we don't test KeyFactor integration with the actual client.

However... How can KeyFactor integration work if the client does not accept the Ed25519 public key? This sounds to me like a bug in the client (a possible regression from 3.x series).

I am creating a task for it.

2024-10-31 14:40 UTC, vpodzime approved these changes
Looks good to me either way.

2024-10-31 14:40 UTC, vpodzime commented on 06.Artifact-creation/07.Sign-and-verify/docs.md
> +On Linux, both `mender-artifact` and the Mender Client support the PKCS#11 programming interface to manipulate cryptographic tokens using `openssl`.
Is the mention of `openssl` important here? PKCS#11 is an interface, it's not important by which means we use it, right?

2024-10-31 14:40 UTC, vpodzime commented on 06.Artifact-creation/07.Sign-and-verify/docs.md
> +## Hardware security
:+1:

2024-10-31 14:55 UTC, vpodzime commented on 06.Artifact-creation/07.Sign-and-verify/docs.md
> +On Linux, both `mender-artifact` and the Mender Client support the PKCS#11 programming interface to manipulate cryptographic tokens using `openssl`.
I thought "supporting/having PKCS#11 interface" was equal to "compatible with `openssl`", but I don't know if that's 100% the case.

2024-11-02 09:10 UTC, lluiscampos approved these changes
Looks good to me. Thank you!

2024-11-04 18:41 UTC, estenberg requested changes
Just a few word changes. Feel free to merge after those.

2024-11-04 18:41 UTC, estenberg commented on 02.Overview/11.Security/docs.md
> +Each Device has a unique RSA or Elliptic Curve (P-256 or Ed25519) keypair (public
key pair

2024-11-04 18:41 UTC, estenberg commented on 02.Overview/11.Security/docs.md
> +!!!!! Mender Client version 4.1.0 and later generates an Ed25519 keypair by
key pair

2024-11-04 18:41 UTC, estenberg commented on 02.Overview/11.Security/docs.md
> +Device, it will require going through the authorization process again. The client
Client

2024-11-04 18:41 UTC, estenberg commented on 02.Overview/11.Security/docs.md
> +!!!!! default, while prior versions generated a 3072 bit RSA key by default.
key -> key pair

2024-11-04 19:22 UTC, estenberg approved these changes

2024-11-04 21:27 UTC, merged