"docs: added comment to run script as root"
mendersoftware/mender-docs pull request #2494
Opened 2024-11-25 16:45 UTC by victormlg

- **docs: updated command from mender to mender-update**
- **docs: added comment to run script as root**

# External Contributor Checklist

🚨 Please review the [guidelines for contributing](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md) to this repository.

- [x] Make sure that all commits follow the conventional commit [specification](https://github.com/mendersoftware/mendertesting/blob/master/commitlint/grammar.md) for the Mender project.

The majority of our contributions are fixes, which means your commit should have
the form below:

```
fix: <SHORT DESCRIPTION OF FIX>

<OPTIONAL LONGER DESCRIPTION>

Changelog: <USER-FRIENDLY-CHANGE-DESCRIPTION> or <None>
Ticket: <TICKET NUMBER> or <None>
```

- [x] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.

### Description

Please describe your pull request.

Thank you!

2024-11-26 07:37 UTC, lluiscampos requested changes
Thanks Victor for taking initiatives in improving the docs :rocket: 

As a general remark, it is a good idea to request for reviews after you create a PR and are happy to present it. This can be done in the top right corner where it says "Reviewers" - in this case I would have pinged your favorite buddy.

When it comes to this PR, please read up our style guide. One thing that we want to avoid as much as possible in Mender Docs is the use of passive voice. Read more [here](https://github.com/mendersoftware/mender-docs/blob/master/README-styleguide.markdown#active-voice-is-preferred-over-passive-voice).

2024-11-26 07:38 UTC, lluiscampos commented on 01.Get-started/05.Monitor/docs.md
> +You can for example put the above code in a file called `setup-countdown.sh` and run that with sudo:
Please rewrite to not use passive voice :+1:

2024-12-02 13:52 UTC, olehermanse commented on 01.Get-started/05.Monitor/docs.md
> +You can for example put the above code in a file called `setup-countdown.sh` and run that with sudo:
@lluiscampos What do you mean? This is not passive voice.

2024-12-03 08:13 UTC, lluiscampos approved these changes
I won't block it further, if you both think that this is not passive voice I accept I am wrong :smiley:

2024-12-03 08:13 UTC, lluiscampos commented on 01.Get-started/05.Monitor/docs.md
> +You can for example put the above code in a file with the name `setup-countdown.sh` and run it with sudo:
@olehermanse What I meant is something like
```suggestion
In order to run the script privileged, put the above code in a file with the name `setup-countdown.sh` and run it with sudo:
```

So that we avoid the "you can do this", "you may do that".

Our docs owner @estenberg has been vocal about not using these constructions of passive voice.

2024-12-03 09:56 UTC, merged

2024-12-03 14:51 UTC, olehermanse commented on 01.Get-started/05.Monitor/docs.md
> +You can for example put the above code in a file with the name `setup-countdown.sh` and run it with sudo:
> So that we avoid the "you can do this", "you may do that".

@lluiscampos Ah, I see. As far as I know, this is not passive voice. Passive voice would be like this:

```
The script below may be run as root (by you).
```

Passive voice means the sentence is turned around so the object comes first and subject comes later ("you can do this" vs "this can be done by you").

Avoiding "you can do", "you may do", is about using shorter, more direct language, in this case with imperative tense (commands - do this, put that, run that).

Nothing wrong with your suggested wording. I think I suggested the wording Victor wrote, because as far as I know, most of our users reading this will know how to run a command / script as root. If not, here is an example of one way it could be done.