feat: adjust the docs to the current Orchestrator functionality
mendersoftware/mender-docs pull request #2499
Opened 2024-11-27 17:24 UTC by TheMeaningfulEngineer

Tickets: MEN-6996 MEN-7016 CE-447

2024-11-27 20:03 UTC, estenberg requested changes
First off, do you know how docs gets merged to stable these days? This is great to have in master for now and iterate over, but we should not merge it into the stable / default docs site.

A few nitpicks here, overall:

* Names are Capital Case. For example, Mender Client, Orchestrator, Manifest, Artifact, etc.
* We need to define such new concepts clearly (one sentence) and add them to Taxonomy.
* Separate examples from Concepts
* There are some unrelated changes included in the PR

2024-11-28 17:28 UTC, TheMeaningfulEngineer commented on 09.Add-ons/05.Orchestrator/docs.md
> +A system is a combination of interdependent digital components running on multiple hardware boards that together acts like a single product.
Added the digital as it's a CRA buzzword that fits the description.
Still want me to remove it?

2024-11-29 09:26 UTC, michaelntech commented on 09.Add-ons/05.Orchestrator/docs.md
> +For the default case, the Mender client (in daemon mode, communicating with the Mender server) will download the manifest as part of an update and the Orchestrator will pull the artifacts it needs ba
and Mender **S**erver right after it

2024-11-29 09:27 UTC, michaelntech commented on 09.Add-ons/05.Orchestrator/02.Examples/docs.md
> +* you have a Hosted Mender tenant and can get a token
Lowercase for hosted, please!

2024-12-02 17:27 UTC, estenberg commented on 09.Add-ons/05.Orchestrator/docs.md
> +A system is a combination of interdependent digital components running on multiple hardware boards that together acts like a single product.
Yes please remove, let's not try to SEO-optimize / add marketing to the docs. It will get unwieldy and confusing in the end.

2024-12-02 17:28 UTC, estenberg commented on 09.Add-ons/05.Orchestrator/docs.md
> +### Update interface
Right, actually it's not done but tracked here: https://northerntech.atlassian.net/browse/MEN-7505

I guess you can use the old name for now then, until that task is done. Up to you.

2025-06-27 04:34 UTC, closed without merging