MEN-7796: Document the upgrade details for Mender Client 5.x
mendersoftware/mender-docs pull request #2506
Opened 2024-12-04 19:25 UTC by lluiscampos

2024-12-04 23:55 UTC, estenberg requested changes
A few nits.

Also, shouldn't this be moved up one level? It is currently under Installing a Debian package. I think we move it on the same level as Installing, just under it is better?

2024-12-04 23:55 UTC, estenberg commented on 03.Client-installation/02.Install-with-Debian-package/01.Upgrading/docs.md
> +In Mender Client 5.0.0, some update modules have been removed.
Update Module Capital Case everywhere.

2024-12-04 23:55 UTC, estenberg commented on 03.Client-installation/02.Install-with-Debian-package/01.Upgrading/docs.md
> +The missing update modules `deb`, `docker`, `rpm` and `script` have been moved to
Remove "missing"

2024-12-04 23:55 UTC, estenberg commented on 03.Client-installation/02.Install-with-Debian-package/01.Upgrading/docs.md
> +The rest of this section explains how to install any of the missing modules, taking `deb` as an
"missing" -> "moved"

2024-12-04 23:55 UTC, estenberg commented on 03.Client-installation/02.Install-with-Debian-package/01.Upgrading/docs.md
> +
For a list of all community-supported Update Modules, please see the [Update Module category in the Mender Hub community forum](https://hub.mender.io/c/update-modules).

2024-12-04 23:55 UTC, estenberg commented on 03.Client-installation/02.Install-with-Debian-package/01.Upgrading/docs.md
> +In Mender Client 5.0.0, some update modules have been removed.
"some Update Modules have been moved from our officially supported repository to the community repository to clarify their support level.

2024-12-05 07:46 UTC, lluiscampos commented
> A few nits.

Thanks, I'll fix them now.

> 
> Also, shouldn't this be moved up one level? It is currently under Installing a Debian package. I think we move it on the same level as Installing, just under it is better?

Coincidentally, I was just about to comment on that when I prepared this PR (iow it was pre-existing and I was about to suggest to move it) but the thing is that although the mender-docs directory and the url have the "debian-package" on it the actual content does not :point_down: 

![image](https://github.com/user-attachments/assets/66ba9361-ad99-4572-b2f0-21605cc7d6fc)

We could rename it regardless, but because we also would need to add redirects from the old urls I personally think it is not worth it. If you consider otherwise I'll follow-up in a separate PR :ok_hand:

2024-12-05 09:08 UTC, lluiscampos commented on 03.Client-installation/02.Install-with-Debian-package/01.Upgrading/docs.md
> +
This line I put it above (and the end of the intro subsection) as it is not mender-convert specific.

2024-12-05 10:02 UTC, TheMeaningfulEngineer requested changes

2024-12-05 10:02 UTC, TheMeaningfulEngineer commented on 03.Client-installation/02.Install-with-Debian-package/01.Upgrading/docs.md
> +to the community repository to clarify their support level.
```suggestion
If you update from Mender Client 4 to Mender Client 5, you will lose the community Update Modules that were previously installed by default. This will happen regardless of the way you're installing the Mender Client.

Below you'll find the steps describing how to modify your settings to get the same behavior on Mender Client 5.
```

2024-12-05 10:02 UTC, TheMeaningfulEngineer commented on 03.Client-installation/02.Install-with-Debian-package/01.Upgrading/docs.md
> +to the community repository to clarify their support level.
The motivation on this rephrasing is to make it explicit whether you'll them if they are already installed, or the just won't be present on new installations.

This is clear for mender-convert and yocto if you're doing an OS image.
But for me it's not clear for the golden image case if someone updates with `apt-get`.

I've rephrased it to assume you'll always lose it, please sanity check that claim.

2024-12-05 10:05 UTC, TheMeaningfulEngineer commented on 03.Client-installation/02.Install-with-Debian-package/01.Upgrading/docs.md
> +OVERLAY_MODIFY_HOOKS+=(install_update_module_deb)
All of this should be steps on how to get the 4.0 behavior on 5.0 instead of "here is a way to update one update module".

Misses the example when you do the installation as apt-get.

2024-12-05 11:46 UTC, lluiscampos commented on 03.Client-installation/02.Install-with-Debian-package/01.Upgrading/docs.md
> +OVERLAY_MODIFY_HOOKS+=(install_update_module_deb)
> All of this should be steps on how to get the 4.0 behavior on 5.0 instead of "here is a way to update one update module".

I don't understand. What exactly are you suggesting in this point? Isn't that covered with the rephrasing that you have suggested above?

> Misses the example when you do the installation as apt-get.

I will add this.

2024-12-05 11:47 UTC, lluiscampos commented on 03.Client-installation/02.Install-with-Debian-package/01.Upgrading/docs.md
> +to the community repository to clarify their support level.
> But for me it's not clear for the golden image case if someone updates with apt-get.

I will add this (it is the same as you commented below, or?)

2024-12-05 12:03 UTC, TheMeaningfulEngineer commented on 03.Client-installation/02.Install-with-Debian-package/01.Upgrading/docs.md
> +OVERLAY_MODIFY_HOOKS+=(install_update_module_deb)
Sorry, I crammed two topics into one comment.
1 topic is adding the `apt-get` part. This seems that we're on the same page and is concluded.

2nd topic was to not give an example for a single update module but a snippet to get you to the previous default state that was available in Mender Clitent 4.

I want to first see how the `apt-get` part will work.
I'm imagining that's a separate package so all community modules will be installed at the same time.
So for apt-get case you the steps to install all the community modules while for yocto and mender-convert you on only get one.

2024-12-05 12:05 UTC, TheMeaningfulEngineer commented on 03.Client-installation/02.Install-with-Debian-package/01.Upgrading/docs.md
> +OVERLAY_MODIFY_HOOKS+=(install_update_module_deb)
A ok...
Got it.
Didn't know this was the way to install them:

```
mkdir -p work/rootfs/usr/share/mender/modules/v3
wget -P work/rootfs/usr/share/mender/modules/v3 https://raw.githubusercontent.com/mendersoftware/mender-update-modules/master/deb/module/deb
chmod 0755 work/rootfs/usr/share/mender/modules/v3/deb
```

2024-12-05 12:07 UTC, TheMeaningfulEngineer commented on 03.Client-installation/02.Install-with-Debian-package/01.Upgrading/docs.md
> +do_install:append:qemux86-64 () {
```suggestion
do_install:append () {
```

This would make it less platform specific?

2024-12-05 13:37 UTC, lluiscampos commented on 03.Client-installation/02.Install-with-Debian-package/01.Upgrading/docs.md
> +do_install:append:qemux86-64 () {
Yes, of course. Thank you.

2024-12-05 13:38 UTC, lluiscampos commented on 03.Client-installation/02.Install-with-Debian-package/01.Upgrading/docs.md
> +
Good call, thanks.

2024-12-05 13:39 UTC, lluiscampos commented on 03.Client-installation/02.Install-with-Debian-package/01.Upgrading/docs.md
> +OVERLAY_MODIFY_HOOKS+=(install_update_module_deb)
That is the process according to the `mender-update-module` READMEs and Mender Hub tutorials. Doing a new deb package for the modules goes against marking them as community maintained :sweat_smile:

2024-12-05 22:18 UTC, estenberg requested changes
Sorry just tiny nitpicks but hopefully quick.

2024-12-05 22:18 UTC, estenberg commented on 03.Client-installation/02.Install-with-Debian-package/01.Upgrading/docs.md
> +Mender Hub community forum](https://hub.mender.io/c/update-modules/13).
Maybe remove the /13 at the end? I don't know what it does.

2024-12-05 22:18 UTC, estenberg commented on 03.Client-installation/02.Install-with-Debian-package/01.Upgrading/docs.md
> +Below you'll find the steps describing how to modify your settings to get the same behavior on
Move this right before the next header.

2024-12-06 07:44 UTC, lluiscampos commented on 03.Client-installation/02.Install-with-Debian-package/01.Upgrading/docs.md
> +Mender Hub community forum](https://hub.mender.io/c/update-modules/13).
It is part of the URL, `https://hub.mender.io/c/update-modules` redirects to `https://hub.mender.io/c/update-modules/13`.

I think it is the category number. Every category URL in MH has a trailing number.

2024-12-06 10:45 UTC, TheMeaningfulEngineer commented on 03.Client-installation/02.Install-with-Debian-package/01.Upgrading/docs.md
> +In Mender Client 5.0.0, some Update Modules have been moved from our officially supported repository
```suggestion
In Mender Client 5.0.0, community Update Modules have been moved from our officially supported repository
```

2024-12-06 10:47 UTC, TheMeaningfulEngineer commented on 03.Client-installation/02.Install-with-Debian-package/01.Upgrading/docs.md
> +Mender Client 5.x series, taking `deb` Update Module as an example.
```suggestion
Below you will find the steps describing how to to get the community Update Modules, installed by default with  Mender Client 4.x, on Mender Client 5.x series.
The example below will show the case for the `deb` Update Module.
```

2024-12-06 10:49 UTC, TheMeaningfulEngineer commented on 03.Client-installation/02.Install-with-Debian-package/01.Upgrading/docs.md
> +On Mender Client 4.x series, the installed Update Modules alongside the client were:
```suggestion
On Mender Client 4.x series, both the community and Norhtern.tech supported Update Modules were installed:
```

2024-12-06 10:49 UTC, TheMeaningfulEngineer commented on 03.Client-installation/02.Install-with-Debian-package/01.Upgrading/docs.md
> +From Mender Client 5.x series onwards, only the following ones are installed alongside the client:
```suggestion
From Mender Client 5.x series onwards, the community Update Models are removed, and only the officially supported ones are installed by default alongside the client:
```

2024-12-06 10:51 UTC, TheMeaningfulEngineer approved these changes
A few minor reqordings to make it explicit on community vs supported.
Other than that good, thatks!
Preapproving

2024-12-06 18:51 UTC, estenberg approved these changes

2024-12-06 19:10 UTC, lluiscampos commented
Thank you both for your reviews. The final text reads much better that my first iteration :smiley:

2024-12-06 19:13 UTC, merged