MEN-7767: Replace libssl1.1 `mender-artifact` with deb packages
mendersoftware/mender-docs pull request #2509
Opened 2024-12-13 14:39 UTC by lluiscampos

OpenSSL 1.1 has been replaced in latest Ubuntu and Debian releases and, most importantly, Ubuntu does not provide an openssl1.1 compatibility package, which runs our pre-compiled binary unusable there.

Instead of having two binaries, one per each OpenSSL version, we link now directly into the deb packages as the preferred method to install the tool on Linux.

On Mac the support has not changed, but we add the architecture to make it explicit where the binary is expected to work.

As a side effect of using deb packages, we cannot offer anymore a reliable link to the pre-release version, so we remove these from the table. The master versions are still accessible via APT experimental repositories for the advance users.

2024-12-13 14:39 UTC, lluiscampos commented
@bahaa-ghazal or @victormlg, can you please test the commands on your machines?

2024-12-13 17:46 UTC, estenberg requested changes
Some nitpicks.

This will be a nice improvement, thank you.

2024-12-13 17:46 UTC, estenberg commented on 01.Get-started/03.Deploy-an-operating-system-update/docs.md
>  !!! If you already installed `mender-artifact` on your system, you can skip this step.
Would append to this: "The simplest installation instructions for `mender-artifact` are covered below, see [Downloads](../../10.Downloads/docs.md#mender-artifact) for installation alternatives such as setting up package repositories."

2024-12-13 17:46 UTC, estenberg commented on 01.Get-started/03.Deploy-an-operating-system-update/docs.md
> +See [Downloads chapter](../../10.Downloads/docs.md#mender-artifact) for more options to install
I suggested moving this to the top, as it's too late for the user to change the installation method here.

2024-12-13 17:46 UTC, estenberg commented on 01.Get-started/04.Deploy-a-container-update/docs.md
>  !!! If you already installed `mender-artifact` on your system, you can skip this step.
Same comment as OS update page:

Would append to this: "The simplest installation instructions for mender-artifact are covered below, see Downloads for installation alternatives such as setting up package repositories."

2024-12-13 17:46 UTC, estenberg commented on 01.Get-started/04.Deploy-a-container-update/docs.md
> +See [Downloads chapter](../../10.Downloads/docs.md#mender-artifact) for more options to install
Same comment as OS update page: 

I suggested moving this to the top, as it's too late for the user to change the installation method here.

2024-12-15 15:31 UTC, bahaa-ghazal commented on 01.Get-started/03.Deploy-an-operating-system-update/docs.md
> +sudo dpkg --install mender-artifact_3.11.3-1%2B$(. /etc/os-release; echo $ID)%2B$(. /etc/os-release; echo $VERSION_CODENAME)_amd64.deb
The artifact installed  is called `mender-artifact_3.11.3-1+ubuntu+noble_amd64.deb`, but it's trying to unpack `mender-artifact_3.11.3-1%2Bubuntu%2Bnoble_amd64.deb`
Getting this error:
```bash
dpkg: error: cannot access archive 'mender-artifact_3.11.3-1%2Bubuntu%2Bnoble_amd64.deb': No such file or directory
```

2024-12-15 17:30 UTC, lluiscampos commented on 01.Get-started/03.Deploy-an-operating-system-update/docs.md
> +sudo dpkg --install mender-artifact_3.11.3-1%2B$(. /etc/os-release; echo $ID)%2B$(. /etc/os-release; echo $VERSION_CODENAME)_amd64.deb
Thank you for testing! That was an stupid mistake from my side :sweat_smile:

2024-12-15 17:34 UTC, lluiscampos commented on 01.Get-started/03.Deploy-an-operating-system-update/docs.md
>  !!! If you already installed `mender-artifact` on your system, you can skip this step.
Thanks for the suggestion.

2024-12-16 11:49 UTC, bahaa-ghazal approved these changes
The artifact is getting installed and unpacked as intended  :+1:

2024-12-16 17:37 UTC, estenberg requested changes
Sorry, one last nitpick.

2024-12-16 17:37 UTC, estenberg commented on 01.Get-started/03.Deploy-an-operating-system-update/docs.md
> +!!! chapter](../../10.Downloads/docs.md#mender-artifact) for installation alternatives such as
"see Downloads chapter" is not correct English somehow.

Would recommend removing "chapter" (as nobody except those working with our docs infra knows what a "Chapter" means I suppose).

see [Downloads](..) for installation alternatives...

2024-12-16 17:37 UTC, estenberg commented on 01.Get-started/04.Deploy-a-container-update/docs.md
> +!!! The simplest installation instructions for `mender-artifact` are covered below, see [Downloads
Same here..

2024-12-17 06:50 UTC, lluiscampos commented on 01.Get-started/03.Deploy-an-operating-system-update/docs.md
> +!!! chapter](../../10.Downloads/docs.md#mender-artifact) for installation alternatives such as
Okey. Done.

I found 50 existing references to "chapter" in our docs text, though :sweat_smile:

2024-12-17 06:53 UTC, lluiscampos commented
> Sorry, one last nitpick.

No problem, thanks for taking the time.

For next time, if you believe the "last nitpick" is clear and you trust enough the author, consider pre-aproving the PR so that due to our time delay we don't need to wait a full day for this :innocent:

2024-12-17 13:51 UTC, estenberg approved these changes

2024-12-17 13:52 UTC, estenberg commented
Approved now, just in time for sprint review :grin:

2024-12-17 14:53 UTC, merged